### ISSUE TITLE
ZLIB_VERSION

### ISSUE THREAD

**Issue by olneykimberly** [ANGSD/angsd#10]
I downloaded the sample set and have angsd installed on my computer but I keep getting this error:
	-> Problem with difference in zlib version used for compiling and linking
	-> ZLIB_VERSION: 1.2.8 zlibversion: 1.2.5 

I have Zlibversion 1.2.5 installed on my computer but it doesn't seem to recognize it. I have included the zlib version 1.2.5 into my path but that didn't fix the issue. I even deleted the newer version of zlib and I still get the same error. Please how do I tell it to use the zlib 1.2.5 which is installed on my computer. 

Thank you!

**Comment by ANGSD** [comment]
If you have the maked (./configure;make) zlib-a.b.c.d in /path/to/zlib-a.b.c.d/. Then you should be able to make main angsd like

make clean
make FLAGS="-I/path/to/zlib-a.b.c.d/"
But redo the linking
g++ -O3 -D__WITH_POOL__  -o angsd *.o -lpthread /path/to/zlib-a.b.c.d/libz.a

You might also need to do this for some of the programs in the misc folder if these depend on zlib.

That should fix the problem. But the best would of course be to make a proper systemwide installtion of the latest zlib.

Best

**Comment by noahrose** [comment]
Hi There,

I'm having the same problem, and when I try to redo the linking I get several errors related to undefined references, like:

abcFreq.cpp:(.text+0x1a29): undefined reference to `bgzf_close'

Any advice on how to successfully fix the linking would be much appreciated! Thanks

Noah

**Comment by noahrose** [comment]
Hmm...sort of oddly after a couple times doing the same thing, it worked perfectly. Is it possible that I was supposed to do the g++ command before compiling rather than after, and that's why it worked ultimately? Sorry for any confusion.
