### ISSUE TITLE
dadi-SNP format

### ISSUE THREAD

**Issue by z0on** [ANGSD/angsd#101]
Hello - I am delighted to see that realSFS now generates file with counts that can be used (after reformatting) for dadi or moments; would it be too much to ask to output it in the right format so no additional reformatting would be necessary?   Here is the dadi-SNP format example, for two populations labeled K and W (the format is described here: https://bitbucket.org/gutenkunstlab/dadi/wiki/DataFormats ):
NAME	OUT	Allele1	K	W	Allele2	K	W	Gene	Position
AGA	AGA	G	31	33	A	9	3	gi|344217551|dbj|DF095586.1|	19651
ATA	ATA	T	40	35	C	0	1	gi|344217550|dbj|DF095585.1|	15174
ATA	ATA	T	40	35	A	0	1	gi|344217550|dbj|DF095585.1|	25922
ATA	ATA	T	39	36	C	1	0	gi|344217548|dbj|DF095583.1|	30766
many thanks in advance
Misha

**Comment by claudiuskerth** [comment]
Hey Misha,

that would require _calling_ allele frequencies for each position. Instead angsd produces distributions of allele frequency likelihoods (SAF's) for each position, thus feeding uncertainty in the true allele frequencies into realSFS. What you are asking for defeats the whole purpose of angsd/realSFS, IMHO. 

claudius

**Comment by z0on** [comment]
Hi Claudius - 
Many thanks for quick response - I totally see your point. But would it not be reasonable to generate a _sample_ of allele counts based on uncertainties of their frequencies? (maybe make several replicate datasets like that?) 

You might be wondering why this is would be even useful for anyone. Honestly the only reason is that _moments_ (a new _dadi_-like SFS analysis package, [https://bitbucket.org/simongravel/moments](url) ) has a very handy/quick built-in bootstrap function, which requires dadi-SNP (counts) input. 

Misha

**Comment by z0on** [comment]
The new option "dadi" in realSFS now works great and allows for build-in bootstrap in Moments (https://bitbucket.org/simongravel/moments) -  Thanks a lot!

Example:
realSFS dadi pop1.saf.idx pop2.saf.idx -sfs pop1.sfs -sfs pop2.sfs -ref reference.fasta -anc ancestral.fasta >dadiout

Here is an accessory script that reformats the output into something that is understood by dadi or Moments: https://github.com/z0on/2bRAD_denovo/blob/master/realsfs2dadi.pl 

The AFS out of ANGSD still appears "mottled" to my liking - highly uneven despite thousands of sites used (see my other issue in this forum) - but this can be glossed over by projecting the AFS in dadi or moments down to 90% of all individuals.

Misha Matz
