### ISSUE TITLE
-doSaf and -snpstat filters

### ISSUE THREAD

**Issue by z0on** [ANGSD/angsd#102]
Hello folks - 
I noticed that doSaf now responds to -snpstats filters, which it did not before. This is awesome but there seems to be a glitch: apparently SNPs that are filtered out in one pop _but not another_ are still scored in 2d SFS, or something else is going on but the result is a lot of private alleles throughout the whole range of frequencies in both pops.  
Without -snpstat filters, 2dSFS looks like this: 
[2dAFS_ok.nosnp.sfs.pdf](https://github.com/ANGSD/angsd/files/1256843/2dAFS_ok.nosnp.sfs.pdf)
And with filters, like this:
[2dAFS_ok.allfilters.sfs.pdf](https://github.com/ANGSD/angsd/files/1256849/2dAFS_ok.allfilters.sfs.pdf)

cheers

Misha

**Comment by ANGSD** [comment]
Hello Misha, if the filtering is based on data for both populations then it won't be filtered out when generating the per pop saf files. Im closing this issue, but feel free to reopen if needed or if im misunderstanding.

Best

**Comment by z0on** [comment]
I think it is worth reopening this, since generating 2d SFS while filtering sites is still a major hassle. The process still requires a "filtering run" on a dataset containing both populations, extracting the list of sites passing filters, and then re-running doSaf for each population separately with this list specified through -sites. For larger datasets this takes approximately forever . 

This could have been solved if realSFS did not score sites that were not overlapping between two populations (i.e., have been genotyped in one population but not another) as private alleles but simply discarded them when building 2dSFS.

does it make sense?..

Misha
