### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by anubhabkhan** [ANGSD/angsd#105]
Hi, I face a segemntation fault issue. I am trying to execute the following:
/extstor/softwares/angsd/angsd -minQ 30 -C 50 -ref /extstor/anubhab/GCA_000181335.3_Felis_catus_8.0/GCA_000181335_3_Felis_catus_8_genomic.fasta -GL 1 -out /path/angsd_genolike -P 80 -doGlf 2 -doMajorMinor 1 -SNP_pval 1e-6 -doMaf 1 -bam /path/angsd_bams.filelist

and I get the following:
-> angsd version: 0.918-35-gc9988b5 (htslib: 1.5-14-ge1380c8) build(Aug 18 2017 12:54:19)
        -> Reading fasta: /extstor/anubhab/GCA_000181335.3_Felis_catus_8.0/GCA_000181335_3_Felis_catus_8_genomic.fasta
        -> SNP-filter using a pvalue: 1.000000e-06 correspond to 23.928127 likelihood units
        -> Parsing 17 number of samples 
        -> Printing at chr: CM001378.2 pos:25752 chunknumber 100 contains 251 sites
        -> Printing at chr: CM001378.2 pos:50951 chunknumber 200 contains 252 sites
        -> Printing at chr: CM001378.2 pos:76267 chunknumber 300 contains 251 sites
        -> Printing at chr: CM001378.2 pos:101502 chunknumber 400 contains 251 sites
        -> Printing at chr: CM001378.2 pos:126908 chunknumber 500 contains 251 sites
        .
        .
        .
        .
-> Allocated ~ 30 million nodes to the nodepool, this is not an estimate of the memory usage
/var/spool/torque/mom_priv/jobs/12339.tiramisu.ncbs.res.in.SC: line 1: 345350 Segmentation fault

can someone please help. I have checked the BAM headers for all the files, they are the same. I don't know what to do.

**Comment by ANGSD** [comment]
You are using 80 threads which might might exceed your stack. The bottleneck is normally the diskio, so i dont think you will be able to utilize more than 7-8. Could you try changing -P 80 to -P 5 and see if that helps.

Best

**Comment by anubhabkhan** [comment]
Hi,

I tried it with fewer threads from 3-5 and it still gives the fault. However when I set -GL to 2 instead of 1 it worked. What might be the issue??

**Comment by ANGSD** [comment]
Hello sorry for the long delay.

It looks like there might be single site that is causing the problem. Without having access to the data it will be difficult to solve. 
Could you check to see if it is a specific site that is causing the problem?

Add -P 1 and -howOften 1.
Then it will printout the position for each chunk. And when it segfaults we know the approximate location. Then it will be easier to figure out what is happening.

Thanks

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed.
