### ISSUE TITLE
SAF file is out of sync contact developer

### ISSUE THREAD

**Issue by SIlviaHinojosa** [ANGSD/angsd#107]
Hello

I've been using ANGSD for a short time and still getting used to the program. So far so good until I try to use the realSFS option and this error keeps appearing 

./realSFS out_dtil.saf.idx out_dban.saf.idx > dtil.dban.saf.idx.ml

	-> Version of fname:out_dtil.saf.idx is:2
	-> Assuming .saf.gz file: out_dtil.saf.gz
	-> Assuming .saf.pos.gz: out_dtil.saf.pos.gz
	-> Version of fname:out_dban.saf.idx is:2
	-> Assuming .saf.gz file: out_dban.saf.gz
	-> Assuming .saf.pos.gz: out_dban.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:out_dban.saf.idx fstout:(null) oldout:0 seed:1506608854 bootstrap:0 whichFst:0
	-> Multi SFS is 'still' under development. Please report strange behaviour
	-> nSites: 1671
	-> The choice of -nSites will require atleast: 0.344215 megabyte memory, that is at least: 0.00% of total memory
	-> dim(out_dtil.saf.idx):33
	-> dim(out_dban.saf.idx):17
	-> Dimension of parameter space: 561
	-> Done reading data from chromosome will prepare next chromosome
	-> Is in multi sfs, will now read data from chr:comp0_seq0
	-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
	-> Chromosome: 'comp0_seq0' does not exists in population: out_dban.saf.idx will skip it
	-> Done reading data from chromosome will prepare next chromosome
	-> [readdata] lastread:1671 posi:67
	-> Comparing positions: 1 with 0 has:1671
SAF file is out of sync contact developer
Mismatch at s:1 which is i=0 vs i=1 with pos1:67 pos2:0

So far I have been able to produce all the files required to realSFS and they seem to be ok. Hope you can help me .

Best
Silvia

**Comment by ANGSD** [comment]
Hello Silvia sorry for the long delay.

Can you tell me how the saf files was generated?

**Comment by SIlviaHinojosa** [comment]
Hello

Here is what I did:

./angsd -checkBamHeaders 0  -bam bam.filelist -doSaf 1 -anc ancestral.fa
-GL 1 -P 24 -out out -minMapQ 20


I am also getting this error while using ./thetastat

./thetaStat print program
Assuming binfile:program.bin and indexfile:program.idx
Problem opening file: program.idx


./thetaStat do_stat /home/silvia/out_trans.2.thetas.gz
    Assuming binfile:/home/silvia/out_trans.2.thetas.gz.bin and
indexfile:/home/silvia/out_trans.2.thetas.gz.idx
Problem opening file: /home/silvia/out_trans.2.thetas.gz.idx


I used this command to create the thetas file:


./misc/realSFS out.saf.idx -P 24 > out.sfs

./angsd -bam bam.filelist -out out -doThetas 1 -doSaf 1 -pest out.sfs -anc
ancestral.fa -GL 1

Cheers,
Silvia

2017-10-11 19:34 GMT+02:00 ANGSD <notifications@github.com>:

**Comment by ANGSD** [comment]
the theta stuff assumes you could generate a prior with realSFS. So if that
part fails, the theta part won't work either.

It looks like the files are very small is that correct?

Could you try printing each of your saf files to check they can be parsed
correctly?

realSFS print out_dtil.saf.idx
and
realSFS print out_dban.saf.idx

Thanks

**Comment by SIlviaHinojosa** [comment]
Hello

Sorry for the delay I did print the out_dtil.saf.idx file here it is

2017-10-18 13:20 GMT+02:00 ANGSD <notifications@github.com>:

**Comment by ANGSD** [comment]
Dear Silvia I can see that this issue got lost somewhere so im closing the issue. Feel free to reopen if needed.

Best
