### ISSUE TITLE
Outdated Beagle GL output format

### ISSUE THREAD

**Issue by mbrieuc** [ANGSD/angsd#108]
I just ran ANGSD to get the genotype likelihood and selected the Beagle output format. Unfortunately, this format is no longer recognized as an input file for Beagle. Beagle now only takes vcf files as input files. Any chance this could be updated or is there a script out there that can convert a Beagle-format file from ANGSD to a VCF file? Thanks!

**Comment by ANGSD** [comment]
Hello, angsd can output vcf files.
See here:
http://www.popgen.dk/angsd/index.php/Vcf

It is not something I've used a lot, but it seemed to work on the scenarios
i played with. Let me know if things doesn't work.

**Comment by mbrieuc** [comment]
Thanks - I just started a job with that option - I'll let you know how it goes.

**Comment by mbrieuc** [comment]
Hi - I ran it with the -dovcf option, but the GL appear to be different between the Beagle and vcf output files (with all other options kept the same).

**Comment by ANGSD** [comment]
Im not sure I understand. Does your vcf not work as input for the newest
version of beagle. Or is there a difference in the calculated gl?

**Comment by mbrieuc** [comment]
There is a difference in the calculated gl...

**Comment by ANGSD** [comment]
Dear @mbrieuc sorry for the delayed response, ive had an updated vcffilereader and vcffiledumper on my to do list for long time, this should be implemented now. Please try the newer version and see if this helps, if it is still relevant. Im closing this issue, feel free to reopen or start a new issue.

Best
