### ISSUE TITLE
Failed to open .bam file error

### ISSUE THREAD

**Issue by lmcg1158** [ANGSD/angsd#111]
Hi. I'm trying to run ANGSD to perform abbababa (multipop) test with four different populations, each one with three individuals.

When i run this command line:
angsd/./angsd -doAbbababa2 1 -bam abbababa.bamlist -sizeFile sizeFile.size -doCounts 1 -out bam.Angsd -useLast 0 -minQ 20 -minMapQ 30 -p 1

it returns the same error everytime I try:
[E::hts_open_format] Failed to open file INDIVIDUAL_NAME_sorted_merged.bam
angsd: multiReader.cpp:333: multiReader::multiReader(int, char**): Assertion `in' failed.
Aborted (core dumped)

I run the command with the terminal rooted in the same folder where .bam files, bam list and sizeFile.size are. I've tried to change the bamlist adding the exact path, but it returns exactly the same error everytime.

**Comment by SamueleSoraggi** [comment]
Hi

you use the option -useLast 0 but do not define a fasta outgroup by the
option -anc , I think that might be the mistake. If your outgroup is inside
the abbababa.bamlist, then you need -useLast 1




2017-10-08 23:36 GMT+02:00 lmcg1158 <notifications@github.com>:

**Comment by lmcg1158** [comment]
I've tried that, but it returned exactly the same error

**Comment by SamueleSoraggi** [comment]
Ok I see,

could you send the files you use for the input -bam and -sizeFile ?



2017-10-09 11:48 GMT+02:00 lmcg1158 <notifications@github.com>:

**Comment by SamueleSoraggi** [comment]
Also, could you double check if all the bam files you have listed in your
file exist? It seems there is a problem specifically with the file

INDIVIDUAL_NAME_sorted_merged.bam

2017-10-09 12:59 GMT+02:00 Samuele Soraggi <samuelson1990@gmail.com>:

**Comment by lmcg1158** [comment]
abbababa.bamlist has all the twelve bam file names separated by enters, as following

a1_sorted_merged.bam
a2_sorted_merged.bam
...
a12_sorted_merged.bam

All bam files exist. I've already tried to add the complete path to the bam files, with no success. sizeFile.size is exactly as following:

3
3
3
3
1

I've tried with and without 1 and it returned the same error.

**Comment by SamueleSoraggi** [comment]
The size file should be without that final 1, and you should have the
option -useLast 1 so the last 3 individuals will be the outgroup.

But I think the problem might be actually related to the files, because I
just used angsd today and it worked totally fine on the abbababa2 function.

Have you downloaded the latest version of angsd?

2017-10-09 13:58 GMT+02:00 lmcg1158 <notifications@github.com>:

**Comment by ANGSD** [comment]
Hello, could you try the most simple analysis.

something lke

./angsd -bam abbababa.bamlist -domaf  1 -gl 1 -domajorminor.

That command should always work.

**Comment by ANGSD** [comment]
Hello, Im assuming this got resolved. Im closing this issue, feel free to reopen if needed.
