### ISSUE TITLE
Error reading a vcf file

### ISSUE THREAD

**Issue by mbrieuc** [ANGSD/angsd#117]
Hi,
I have a vcf file with GP field and I'm getting an error while trying to use it:
The command I use is
$angsd -vcf-gl All.GP.vcf.gz -nind 851 -fai cod.fasta.fai -domaf 1 -doMajorMinor 1 -out angsd_GP_output

And here is the error message:
#vcfReader.cpp:147: int vcfReader::parseline(double**, double**, char&, char&): Assertion `pp==3' failed.

Missing values are coded as ".", otherwise there are 3 values for each individual, adding up to 1.

Thanks for your help

**Comment by ANGSD** [comment]
Hello. There are 3 unrelated issues concerning vcf files. So im quite interested in resolving these vcf issues.

Could I see your vcf file? Apart from that not all analysis in ANGSD will work with genotype post probs. 

Best

**Comment by mbrieuc** [comment]
Here is an example of my file.
Thanks!

[sample.vcf.gz](https://github.com/ANGSD/angsd/files/1468224/sample.vcf.gz)

**Comment by ANGSD** [comment]
Since the vcf file does not contain raw genotype likelihoods(gl) or
phredscaled genotype likelihoods (pl), you won't be able to use the
genotype likelihood based analysis. Run like this instead:

./angsd -vcf-gp sample.vcf -fai fai.fai -nind 851 -domaf 4

The program should of course had output a better warning message, and I've
created an issue on GitHub about this.

Best

**Comment by mbrieuc** [comment]
Thanks for your reply. I just tried to run it and here is the error message that I got:
$angsd -vcf-gp /sample.vcf.gz -fai ref.fasta.fai -nInd 851 -domaf 4
        -> angsd version: 0.918 (htslib: 1.5) build(Sep 21 2017 09:29:35)
        -> BETA when using vcf-gl make sure that you use -doMajorMinor 1angsd: vcfReader.cpp:147: int vcfReader::parseline(double**, double**, char&, char&): Assertion `pp==3' failed.
Aborted (core dumped)

Marine

>-----Original Message-----
>From: ANGSD [mailto:notifications@github.com]
>Sent: Tuesday, November 14, 2017 2:20 PM
>To: ANGSD/angsd
>Cc: Marine Servane Brieuc; Author
>Subject: Re: [ANGSD/angsd] Error reading a vcf file (#117)
>
>Since the vcf file does not contain raw genotype likelihoods(gl) or phredscaled
>genotype likelihoods (pl), you won't be able to use the genotype likelihood
>based analysis. Run like this instead:
>
>./angsd -vcf-gp sample.vcf -fai fai.fai -nind 851 -domaf 4
>
>The program should of course had output a better warning message, and I've
>created an issue on GitHub about this.
>
>Best
>

**Comment by ANGSD** [comment]
Ok, it looks like there is a problem with a specific site. But annoyingly angsd does not show which position. I've just pushed a new version to GitHub, which will tell you which position that causes the problem. https://github.com/ANGSD/angsd/commit/a4de7623587d03a36c963175601fcb256ec80e57

Could you try pulling that, do a make clean and then recompile.
The program should then tell us which position in the vcf that causes the problem, and you can grep that out with:
gunzip -c  All.GP.vcf.gz |grep reported_position.

Thanks for your help with this.

Best

**Comment by mbrieuc** [comment]
I reran it. The first site on my vcf file is where the (first!) problem is. How can I tell what the problem actually is?

These GP values have actually been manually recoded from PL values - which might not actually be the best thing to do, but I couldn't figure out how to convert PL (output from GATK) to GL. Do you have any suggestions as to how to do it instead of coding them as GP?

Thanks

**Comment by mbrieuc** [comment]
Hi -
I tried to run the same command with a different file (not one that I made manually), and I also get a problem with the very first position.
Thanks for your help
Marine

**Comment by ANGSD** [comment]
Dear Marine sorry for the much extended delay, I've just finialized a new vcf-gl filereader. Please try to use this one, given that this issue reported was started so long ago i'm assuming you found a workaround so im closing this issue. Fell free to open af new issue if needed.
