### ISSUE TITLE
noisy 2dSFS

### ISSUE THREAD

**Issue by z0on** [ANGSD/angsd#119]
Hello -
My 2dSFS spectra generated with realSFS look weird - with a lot of empty cells giving them a "mottled", noisy appearance (see the first attached). 
The same saf data converted into likely allele counts (sampling alleles based on saf probabilities) produces SFS that looks more or less normal (the second attachment).
One of these must be wrong? 
(Chances are my sfs2dadi conversion is not ideal but the spectrum looks much more normal that the one generated by realSFS...)
cheers
Misha
[2dAFSf_KieRau.pdf](https://github.com/ANGSD/angsd/files/1444421/2dAFSf_KieRau.pdf)
[2dAFSf_3pops_dadi.data_kie_rau_40_42.pdf](https://github.com/ANGSD/angsd/files/1444427/2dAFSf_3pops_dadi.data_kie_rau_40_42.pdf)

**Comment by ANGSD** [comment]
Hello, how many sites do you include in the analysis?

 It is an ML estimator and with 2dsfs you are optimizing 43*41 parameters jointly. If you dont have many sites then the optimisation might bin categories together.

Best

**Comment by z0on** [comment]
Hey! 
I have >30k sites, folded. I understand that sites may become scarce in a 2d plot, but what looked strange to me is that count sampling from the same saf produces normal-looking spectrum...

iPhone. Autocorrections galore.

**Comment by ANGSD** [comment]
Hi
realSFS can now do proper folding of the 2dsfs based on the unfolded saf.idx. This should help stabilize the 2dsfs. This code should have been written a long time ago.

Best
