### ISSUE TITLE
Install Error 1 (it can't find libhts.a)

### ISSUE THREAD

**Issue by eyesmo** [ANGSD/angsd#120]
I've got htslib v1.6.1 installed via Homebrew in /usr/local/Cellar/htslib.

I cloned angsd into the Cellar folder with:
>git clone git clone https://github.com/angsd/angsd.git

Then tried to install it with:
>cd angsd
>make HTSSRC=../htslib

I get 
>HTSSRC defined
>make -C misc/ HTSSRC=/usr/local/Cellar/htslib
>HTSSRC defined
>/usr/local/Cellar/htslib/libhts.a
>make -C ../ prep_sites.o HTSSRC=/usr/local/Cellar/htslib
>HTSSRC defined
>make[2]: `prep_sites.o' is up to date.
>g++ -O3 -c realSFS_args.cpp -I /usr/local/Cellar/htslib
>make -C ../ analysisFunction.o HTSSRC=/usr/local/Cellar/htslib
>HTSSRC defined
>make[2]: `analysisFunction.o' is up to date.
>g++ -O3 realSFS.cpp -o realSFS  safreader.o realSFS_args.o safstat.o fstreader.o header.o >safcat.o realSFS_optim.o realSFS_dadi.o realSFS_shared.o ../prep_sites.o ../analysisFunction.o -I >/usr/local/Cellar/htslib /usr/local/Cellar/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread
>clang: error: no such file or directory: '/usr/local/Cellar/htslib/libhts.a'
>make[1]: *** [realSFS] Error 1
>make: *** [misc] Error 2

Okay, so the program can't find libhts.a
I have found libhts.a, its path is 
>/usr/local/Cellar/htslib/1.6_1/lib/libhts.a

However, if I try 
>make HTSSRC=../htslib/1.6_1/lib

I get 
>HTSSRC defined
>make -C misc/ HTSSRC=/usr/local/Cellar/htslib/1.6_1/lib
>HTSSRC defined
>/usr/local/Cellar/htslib/1.6_1/lib/libhts.a
>make -C ../ prep_sites.o HTSSRC=/usr/local/Cellar/htslib/1.6_1/lib
>HTSSRC defined
>make[2]: `prep_sites.o' is up to date.
>g++ -O3 -c realSFS_args.cpp -I /usr/local/Cellar/htslib/1.6_1/lib
>make -C ../ analysisFunction.o HTSSRC=/usr/local/Cellar/htslib/1.6_1/lib
>HTSSRC defined
>make[2]: `analysisFunction.o' is up to date.
>g++ -O3 realSFS.cpp -o realSFS  safreader.o realSFS_args.o safstat.o fstreader.o header.o >safcat.o realSFS_optim.o realSFS_dadi.o realSFS_shared.o ../prep_sites.o ../analysisFunction.o -I >/usr/local/Cellar/htslib/1.6_1/lib /usr/local/Cellar/htslib/1.6_1/lib/libhts.a -lz -lm -lbz2 -llzma ->lpthread
>Undefined symbols for architecture x86_64:
>  "_curl_easy_cleanup", referenced from:
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>      _libcurl_seek in libhts.a(hfile_libcurl.o)
>      _libcurl_close in libhts.a(hfile_libcurl.o)
>  "_curl_easy_duphandle", referenced from:
>      _libcurl_seek in libhts.a(hfile_libcurl.o)
>  "_curl_easy_getinfo", referenced from:
>      _easy_errno in libhts.a(hfile_libcurl.o)
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>  "_curl_easy_init", referenced from:
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>  "_curl_easy_pause", referenced from:
>      _libcurl_read in libhts.a(hfile_libcurl.o)
>      _libcurl_write in libhts.a(hfile_libcurl.o)
>      _libcurl_seek in libhts.a(hfile_libcurl.o)
>      _libcurl_close in libhts.a(hfile_libcurl.o)
>  "_curl_easy_reset", referenced from:
>      _libcurl_seek in libhts.a(hfile_libcurl.o)
>  "_curl_easy_setopt", referenced from:
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>      _libcurl_seek in libhts.a(hfile_libcurl.o)
>  "_curl_global_cleanup", referenced from:
>      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
>      _libcurl_exit in libhts.a(hfile_libcurl.o)
>  "_curl_global_init", referenced from:
>      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
>  "_curl_multi_add_handle", referenced from:
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>      _libcurl_seek in libhts.a(hfile_libcurl.o)
>  "_curl_multi_cleanup", referenced from:
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>      _libcurl_close in libhts.a(hfile_libcurl.o)
>  "_curl_multi_fdset", referenced from:
>      _wait_perform in libhts.a(hfile_libcurl.o)
>  "_curl_multi_info_read", referenced from:
>      _wait_perform in libhts.a(hfile_libcurl.o)
>  "_curl_multi_init", referenced from:
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>  "_curl_multi_perform", referenced from:
>      _wait_perform in libhts.a(hfile_libcurl.o)
>  "_curl_multi_remove_handle", referenced from:
>      _libcurl_open in libhts.a(hfile_libcurl.o)
>      _libcurl_seek in libhts.a(hfile_libcurl.o)
>      _libcurl_close in libhts.a(hfile_libcurl.o)
>  "_curl_multi_timeout", referenced from:
>      _wait_perform in libhts.a(hfile_libcurl.o)
>  "_curl_share_cleanup", referenced from:
>      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
>      _libcurl_exit in libhts.a(hfile_libcurl.o)
>  "_curl_share_init", referenced from:
>      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
>  "_curl_share_setopt", referenced from:
>      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
>  "_curl_version_info", referenced from:
>      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
>ld: symbol(s) not found for architecture x86_64
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>make[1]: *** [realSFS] Error 1
>make: *** [misc] Error 2

Is there something obvious I'm doing wrong?

**Comment by ANGSD** [comment]
Could you try to step into the htslib folder and do a
make clean
make

And then retry the angsd part

**Comment by eyesmo** [comment]
I got 
>make: *** No rule to make target `clean'.  Stop.

and
>make: *** No targets specified and no makefile found.  Stop.

Then when I try the angsd lines again I get the same error message.

To give you some idea of how  Homebrew has set up the directory, this is what's in htslib (each dash is another folder down):
-1.6_1
--INSTALL_RECEIPT.json
--README
--LICENSE
--NEWS
--lib
---libhts.1.6.dylib
---libhts.a
---pkgconfig
---libhts.2.dylib
---libhts.dylib
--bin
--share
--include

**Comment by ANGSD** [comment]
Dear Isaac, I also have home-brew on my osx, but i have already installed
htslib from github source, so that overrides my home-brew,  I think the
easiest solution is just to clone the htslib from GitHub, and link angsd
with that.

Best

**Comment by eyesmo** [comment]
Thanks! That got it to work.
