### ISSUE TITLE
Does angsd recognize the "SM" read group (@RG)

### ISSUE THREAD

**Issue by schimar** [ANGSD/angsd#121]
Hey, 

here's a quick question. 
I have a set of bam files, with each sample consisting of multiple *.bams, and I want to calculate sfs, D stats, etc. Does angsd recognize the 'SM' read group or do I have to merge the bam files before running? 

Thanks a lot, 
martin

**Comment by ANGSD** [comment]
Angsd does not recognize the sm tag. For angsd one bam is one sample

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed.
