### ISSUE TITLE
more -doThetas seg faults

### ISSUE THREAD

**Issue by devonorourke** [ANGSD/angsd#122]
Hi, 

After reading though a couple of posts about different folks receiving segmentation fault errors [beyond](https://github.com/ANGSD/angsd/issues/105) and [specifically using](https://github.com/ANGSD/angsd/issues/88) the `-doThetas` function, I was hoping to add my problems to the mix, but with a twist. For what it's worth, I've been running v.0.918 (build Oct. 6, 2017).  

I've been able to run the following command without any issue - the output contains the expected suite of files (the .glf's, the .depths, the .saf's, the .maf, etc.)
```
angsd -P 24 \
-nInd 25 \
-b pop1_bamlist.txt \
-ref myref.fa \
-anc myref.fa \
-out pop1out \
-uniqueOnly 0 -remove_bads 1 -only_proper_pairs 0 -trim 0 -C 50 -baq 1 \
-minMapQ 20 -minInd 8 -setMinDepthInd 3 -SNP_pval 1e-3 -minMaf 0.05 \
-doDepth 1 -doCounts 1 \
-domajorminor 1 -domaf 1 \
-gl 1 -doGlf 3 \
-doSaf 2 -fold 1 -indF pop1.indF
```
I then separately ran a very short command to calculate the RealSFS:
```
realSFS pop1.saf.idx -P 24 > pop1.sfs
```

Everything appeared in order. Finally, I wanted to incorporate those values to calculate thetas. So ultimately all I changed from that initial block of code to what follows below was the inclusion of the `.sfs` file:

```
angsd -P 24 \
-nInd 25 \
-b pop1_bamlist.txt \
-ref myref.fa \
-anc myref.fa \
-out pop1out \
-uniqueOnly 0 -remove_bads 1 -only_proper_pairs 0 -trim 0 -C 50 -baq 1 \
-minMapQ 20 -minInd 8 -setMinDepthInd 3 -SNP_pval 1e-3 -minMaf 0.05 \
-doDepth 1 -doCounts 1 \
-domajorminor 1 -domaf 1 \
-gl 1 -doGlf 3 \
-doSaf 2 -fold 1 -indF pop1.indF \
-pest pop1.sfs \
-doThetas 1
```

- I've added the `-howOften 1` argument and varied the number of threads (I've tried 24, 10, and 8) within the _angsd_ script. It seg faults at different locations but always seg faults.
- I've upped the ram on our compute cluster from the default of 2, to 32, to 120, to 510 MB and it seg faults. It actually seg faults _faster_ with more memory, which is a bit suspicious...

Finally, I tried doing another thing recommended on this forum - specifying just a single thread (`-P 1`) along with the chunk size information printing out every iteration (`howOften -1`) and it appears to be _almost_ working - the .glf, .maf, and .depth files are all created and contain the expected information. What's curious: the `.thetas.idx` and `thetas.gz` file are created, but there is no `thetas.gz.bin` file. Which really stinks, as I can't run subsequent `thetaStat` commands without it, as far as I can tell.

So in summary two strange things to consider:
- similar to what Elias reported in his issue, I have run a nearly identical script in which one worked without any issue, and then by only adding the `-doThetas` and `-pest` arguments, the seg fault message pops up, provided the number of threads specified is greater than 1.
- even if I get around that problem by specifying just one thread, I still miss the binary `.thetas.gz.bin` file and have no idea how to generate it

Provided the program continue to operates, perhaps the only advice/observation I have at this point is to ensure that folks use `-P 1` and `-howOften 1` if their `-doThetas` program is segfaulting and the previously advised memory allocation tricks don't work.  But then again, you won't have your .bin file, so I don't know what that'll ultimately amount to.

I'm curious if anyone else has this issue.

**Comment by devonorourke** [comment]
One update: It turns out that if you use the [angsd-wrapper](https://github.com/mojaveazure/angsd-wrapper) package *and* specify a single thread, you can get the .bin file to be properly produced. This runs a different angsd version (angsd version: 0.911-44-g1c0ebb6 (htslib: 1.3.1-30-gbb03b02)), so perhaps this might help for comparisons sake (given that my problems are stemming from angsd version 0.918).

Thanks!

**Comment by ANGSD** [comment]
Im abut puzzled by this segfault. Does the program generate a core dump? If so, could you try loading it in gdb and see which file and line that is causing it?

Best

**Comment by rmarquezp** [comment]
I ran into the same issue. I've analyzed my dataset extensively in ANGSD, and it only segfaults when I use -doThetas and -pest. -P1 and -howOften 1 did not solve the issue. I down-graded to version 0.9.17 and this solved the problem.

**Comment by shannonekj** [comment]
Has any progress been made on this front? I'm wondering if v0.920 has addressed this issue and allows for multiple threads while still generating the .bin file? Thanks!

**Comment by ANGSD** [comment]
I just pushed an update which should fix the thetas issues that would occur if you had specified -fold 1. See if that helps

**Comment by ANGSD** [comment]
Dear user Im assuming this got resolved im therefore closing this issue feel free to reopen if needed.

Best
