### ISSUE TITLE
Issue calculating Fst on scaffolds 

### ISSUE THREAD

**Issue by erikenbody** [ANGSD/angsd#126]
Hello,
I am using ANGSD (0.918) to calculate the SFS and population statistics, such as Fst, on a species with few existing genomic resources. I have encountered what might be a bug, but I equally assume could be user error. My reference is composed of ~5000 scaffolds that vary in length. When I calculate Fst using realSFS, a random selection of very short scaffolds (e.g. <5kb) have values that were apparently calculated from other longer scaffolds. These are also indexed to positions that do not occur on the short scaffold, but are present on the long. 

Here are two examples to visualize this (scaffold_2414 is 4kb long, scaffold_1 is 11mbp):
```
realSFS fst print aida_naimii.pbs.fst.idx -r scaffold_2414
>scaffold_2414    101    0.000011    0.000209
>scaffold_2414    102    0.000011    0.000206
>scaffold_2414    103    0.000011    0.000203
>scaffold_2414    104    0.000011    0.000206
```
```
realSFS fst print aida_naimii.pbs.fst.idx -r scaffold_1
>scaffold_1    101    0.000011    0.000209
>scaffold_1    102    0.000011    0.000206
>scaffold_1    103    0.000011    0.000203
>scaffold_1    104    0.000011    0.000206
```

My input .saf files are a bit too large to share with you. When I ran the full analysis using only the above two scaffolds, I was not able to reproduce the problem and scaffold 2414 had the correct Fst calculations. I realize this is very specific and likely something to do with my dataset or commands. However, my input bam files and reference do not have any apparent issues that could cause this and I have failed to discover the root cause. 
I would greatly appreciate it if you have a sense of  where this issue could originate from. Right now, I am able to filter out the short scaffolds in my downstream analysis (e.g. in a sliding window analysis). Thank you for any help!

The full command sequence I am running is below:
```
for POP in aida naimii
do
  echo $POP
  angsd -b $BAMLIST -ref $REFGENOME -anc $REFGENOME -out test/${POP}.${RUN}.ref -rf $REGIONS -P 20\
                -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 0 -trim 0 \
                -minMapQ 20 -minQ 20 -minInd $MININD -doCounts 1 \
                -GL 1 -doSaf 1
done

realSFS -P 20 test/${POP1}.${RUN}.ref.saf.idx test/${POP2}.${RUN}.ref.saf.idx > test/${POP1}_${POP2}.sfs

realSFS fst index test/${POP1}.${RUN}.ref.saf.idx test/${POP2}.${RUN}.ref.saf.idx -sfs test/${POP1}_${POP2}.sfs -fstout test/${POP1}_${POP2}.pbs -whichFST 0

realSFS fst stats2 test/${POP1}_${POP2}.pbs.fst.idx -win 50000 -step 50000 -whichFST 0 > test/${POP1}_${POP2}_${SUBSET}.fst.txt
```

**Comment by ANGSD** [comment]
Dear @erikenbody sorry for the delay, i dont think i understand the problem.
The output prints the persite estimate of the fst, the reason that you observe the same value is most likely due to the site having little information and therefore the prior dominates the estimates.
In both your examples you are printint the sites 101-104 which should exist in both scaffolds.

Best

**Comment by ANGSD** [comment]
There was a problem with the indexing jumping contigs if there was no data, maybe this was what you observed here. It should be resolved in this commit 657fa64d016b46053b11ce48e09121b9d4e0cea3

Feel free to reopen if needed.

Best

**Comment by erikenbody** [comment]
Great - thank you for the followup! Each of those reasons may apply to my dataset and I will investigate further. With the benefit of a year of hindsight, it occurs to me that it is also possible that some of my very small contigs are duplicated regions found on other contigs and could produce identical results. Regardless, for analysis removing the smallest contigs (in my case <50kb) produced sensible and usable results.

**Comment by emilya21** [comment]
Hi, I am having this same issue even after cloning the most recent version of angsd (As of today). I am trying to calculate PBS using sliding windows. I have scaffolds that are smaller than my window length ( around 1000 bps), and these scaffolds are being assigned PBS values of the larger scaffolds (this index jumping described above). Is anyone else still dealing with this issue and is there any way to fix this other than removing the small contigs?

Thanks in advance!

**Comment by nspope** [comment]
The easiest thing to do would be to use './realSFS fst print' to get the
numerator and denominator of Fst per site for each population pair, then
window/sum numerator and denominator/take ratio/transform to PBS, as you
see fit.

Nate

>
