### ISSUE TITLE
Bootstrapping multi-/2D-SFS bug or not yet supported?

### ISSUE THREAD

**Issue by marqueda** [ANGSD/angsd#130]
Dear ANGSD-developers,

I tried to estimate bootstrap replicates for 2D-SFSs using realSFS, with the following command:
realSFS pop1.saf.idx pop2.saf.idx -bootstrap 100 > out.boot.sfs

Now, after seeing the results (see image below), I am unsure whether boostrapping of 2D-SFS is supported at all or whether there might be a bug in the code? It seems that the 2D-SFS is produced from non-identical sites due to randomly picking different sites in the two populations, which could explain all the 0/N and N/0 counts in the bootstrapped SFS.
![obsvsbootsfs](https://user-images.githubusercontent.com/18431521/34726388-26344564-f554-11e7-9e15-b753523276bc.jpg)

Thank you for your input on this and recommendations on how to best proceed to get bootstrapped 2D-/multi-SFS.

Best regards, David

**Comment by ANGSD** [comment]
Hello David sorry for the delay. We are still working on the bootstrapping
part. How did you fold your sfs?

**Comment by marqueda** [comment]
Thank you for your reply - I am looking forward to the bootstrapping capability for <1DSFS. I used a simple R script to fold the SFS, see my [SFS-scripts repository](https://github.com/marqueda/SFS-scripts).

**Comment by claudiuskerth** [comment]
Hi Marqueda,

have you checked your 2D folding against the folding function in dadi?

claudius

**Comment by marqueda** [comment]
Hi Claudius,

No, I have not. Have you found any inconsistencies?

Best,
David

**Comment by ANGSD** [comment]
A kind user fixed a bug in realSFS along with a bootstrapping approach. Im therefore closing this issue, feel free to reopen if needed.

Best
