### ISSUE TITLE
Why not accept vcf without GP or GL flag(sometimes with GT flag only)?

### ISSUE THREAD

**Issue by xiekunwhy** [ANGSD/angsd#131]
Hi
ANGSD, why not accept vcf without GP or GL flag(sometimes with GT flag only) when calculate Fst pi and Tajima's D and some others parameters only use population allele frequencies? 
Hope well,
Xie Kun

**Comment by huangl07** [comment]
I have the same question，Could Someone reply

**Comment by ANGSD** [comment]
Dear all. If you have called genotypes in the vcf/bcf then you dont need the heavy machine in angsd that loops over all the different uncertainties for all samples. I would just write a small script.

**Comment by huangl07** [comment]
well? like GATK/stacks software，there‘re sometimes it will produce only GT flag，is there something to use angsd software to do some population analysis？

**Comment by ANGSD** [comment]
I would recommend to use angsd if you have lowcoverage sequencing data. If
you have high coverage data then it should be possible to call genotypes
without most of the bias that exists with lowcoverage data. angsd is not
meant for analysis based on called genotypes.

Best

**Comment by huangl07** [comment]
well，I have some vcf data by only GT file， How could we analysis it use angsd

**Comment by xiekunwhy** [comment]
PopGenome is a good software for called genotype.

**Comment by ANGSD** [comment]
ok, im closing this issue, feel free to reopen if needed.
