### ISSUE TITLE
Why the angsd must provide the -anc *.fa

### ISSUE THREAD

**Issue by Johnjzy** [ANGSD/angsd#132]
$angsd -bam bam.list -ref ref.fa -doSaf 1 -GL 1 -fold 1 -nThreads 10 -out test
	-> angsd version: 0.921-3-g40ac3d6 (htslib: 1.7-1-gaf40c73) build(Jan 30 2018 15:00:06)
	-> Reading fasta: ref.fa
	-> Must supply -anc for polarizing the spectrum

I haven't ancestry fasta file, I can just provide my ref.fasta, and replace the -ref with -anc option, but whether it's right?
And, I replace the option, but when I do the next:
$ realSFS -P 5 test.saf.idx > test.sfs
The message:
------------
startlik=-3110223756.965082
lik[2]=-82621054.252686 diff=3.027603e+09 alpha:1.000000 sr2:8.631238e-01
lik[5]=-81436878.430502 diff=1.184176e+06 alpha:1.159145 sr2:1.272101e-05
lik[8]=-81407922.834626 diff=2.895560e+04 alpha:2.790631 sr2:1.524823e-08
lik[11]=-81402809.961423 diff=5.112873e+03 alpha:4.000000 sr2:2.966307e-10
lik[14]=-81399760.828021 diff=3.049133e+03 alpha:8.158992 sr2:9.316479e-11
lik[17]=-81399500.852947 diff=2.599751e+02 alpha:1.508842 sr2:1.069123e-10
lik[20]=-81398928.227588 diff=5.726254e+02 alpha:16.000000 sr2:8.917227e-12
lik[23]=-81398902.177842 diff=2.604975e+01 alpha:2.234562 sr2:8.681232e-12
	-> Breaking EM(sr2) at iter:24, sqrt(sr2):7.475298e-07
likelihood: -81398902.177842
------------
	-> Only read nSites: 0 will therefore prepare next chromosome (or exit)

	-> NB NB output is no longer log probs of the frequency spectrum!
	-> Output is now simply the expected values! 
	-> You can convert to the old format simply with log(norm(x))
Then I just get 1Kb file, I want to know how?? and how to deal with it? 
Any advice would be appreciated, Thank you all !

**Comment by ANGSD** [comment]
if you use the reference as your anc then you should also apply -dofold 1.

Best

**Comment by ANGSD** [comment]
im closing this issue, feel free to reopen if needed.
