### ISSUE TITLE
error in realSFS

### ISSUE THREAD

**Issue by krystal915** [ANGSD/angsd#134]
I ran 
$ANGSD/angsd -P 4 -b $POP.bamlist -ref $REF -anc $ANC -out Results/$POP -r 11 \
		-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 \
		-minMapQ 20 -minQ 20 -minInd 10 -setMinDepth 20 -setMaxDepth 200 -doCounts 1 \
		-GL 1 -doSaf 1 &> /dev/null
and got three result files,$POP.saf.gz  $POP.saf.idx  $POP.saf.pos.gz  in a few seconds.
and I used the $POP.saf.idx file to run realSFS,
$ANGSD/misc/realSFS Results/$POP.saf.idx -P 4 2> /dev/null > Results/$POP.sfs
but unfortunately I got a empty output.
I tried to have a look on the saf.result by:
$ANGSD/misc/realSFS print Results/$POP.saf.idx | less -S
but I got some error mesasages like:
-> Only read nSites: 0 will therefore prepare next chromosome (or exit) 
-> Done reading data from chromosome will prepare next chromosome
-> Only read nSites: 0 will therefore prepare next chromosome (or exit) 
-> Done reading data from chromosome will prepare next chromosome

I really wonder what happened to my data.
thanks a lot for your help! :-)

**Comment by ANGSD** [comment]
I looks like your saf files are empty, maybe your filters are too strict.
You can get the output by:

./realSFS print your.saf.idx

Hopefully this helps.

**Comment by ANGSD** [comment]
im closing this issue, feel free to reopen if needed.

**Comment by sagitaninta** [comment]
Hi, I am also having this problem. The other saf outputs are not empty, only the saf.idx is empty. I wonder why.
