### ISSUE TITLE
ANGSD Error

### ISSUE THREAD

**Issue by phermy** [ANGSD/angsd#136]
Hello everyone I tried running angsd on the merge bams file was used to generate my PSMC plot got this errors, what must I do.

-> Printing at chr: ScS9zPn_2515 pos:3776257 chunknumber 212200 Killed

**Comment by ANGSD** [comment]
Can you give the entire command you used.

Best

**Comment by phermy** [comment]
Quality checking
$ANGSDPATH/angsd -doQsDist 1 -doDepth 1 -doCounts 1 -b bamlist.txt -uniqueOnly 1 -remove_bads 1 -minMapQ 25 -minQ 25 -minInd 3  -out Black_Rhino_quality_check  

Also for Phylogenetics
$ANGSDPATH/angsd -doIBS 2 -makeMatrix 1 -doCounts 1 -uniqueOnly 1 -remove_bads 1 -minMapQ 25 -minQ 25 -minInd 3 -b bamlist.txt -ref ref.fa -out Black_Rhino_IBS  

Got same errors when running both commands on my local Linux machine with angsd properly installed and working.

Thanks
Femi

**Comment by ANGSD** [comment]
I dont see anything sinister looking with these commands.

Could you try the most simple command:

$ANGSDPATH/angsd -b bamlist.txt

If that doesn't crash then add the other arguments incrementally.

Thanks for helping me figure this out.

**Comment by phermy** [comment]
Thanks, I did just what you instructed me to do, by running this cammand.
$ANGSDPATH/angsd -b bamlist.txt
job got killed, so what I do please.

-> Problem with difference in zlib version used for compiling and linking
	-> ZLIB_VERSION: 1.2.3 zlibversion: 1.2.11 
	-> angsd version: 0.913 (htslib: 1.3.1) build(Jun 10 2017 12:38:17)
	-> No '-out' argument given, output files will be called 'angsdput'
	-> Parsing 4 number of samples 
	-> Printing at chr: ScS9zPn_185 pos:2327317 chunknumber 8500 
	-> Allocated ~ 10 Megabytes to the nodepool

	-> Allocated ~ 20 Megabytes to the nodepool
	-> Printing at chr: ScS9zPn_751 pos:9280409 chunknumber 123800 Killed

**Comment by ANGSD** [comment]
are the bams sorted?

**Comment by phermy** [comment]
Yes I did

**Comment by ANGSD** [comment]
Ok, im afraid i wont be able to figure out what goes wrong without having
access to the bams. Would it be possible obtain a copy of these? Ill of
course keep them confidential and will delete them as soon as I've solved
the issue.

Thanks

**Comment by phermy** [comment]
[bamlist.txt](https://github.com/ANGSD/angsd/files/1837275/bamlist.txt)

**Comment by phermy** [comment]
[bamlist.txt](https://github.com/ANGSD/angsd/files/1837503/bamlist.txt)

**Comment by ANGSD** [comment]
Dear phermy, I would need a copy of the bamfiles. Not just a file
containing the filenames.

Best

**Comment by ANGSD** [comment]
Dear  phermy, im closing this issue, feel free to reopen if needed

Best

**Comment by xinxin2** [comment]
@phermy Hello, has the angsd error you asked solved? Recently, I have encountered similar problems, such as printing at Chr: scs9zpn_ two thousand five hundred and fifteen pos:3776257 chunknumber  212200 killed, if you have a solution, please let me know. Thank you very much!
