### ISSUE TITLE
Number of sites that passed filters

### ISSUE THREAD

**Issue by lindaboettger** [ANGSD/angsd#138]
Dear ANGSD,
I’m estimating allele frequencies with “-doMaf” and using several filters (MapQ, qscore, read depth, etc). 
I’d like to understand the fraction of bases that are polymorphic. Is there a way to output the number of sites that passed my filtering parameters so that I know how many sites were considered in the analysis? 
Thanks,
Linda

**Comment by mfumagalli** [comment]
I would look at the number of rows in your .mafs file in output, e.g. with `wc -l` in bash and then -1 to account for the header. Hope that's what you were asking.

**Comment by lindaboettger** [comment]
The issue is that the .mafs file only outputs polymorphic sites. I'm hoping to know the total number of sites that passed filters (including those that were not polymorphic).

**Comment by ANGSD** [comment]
Hello Linda this is actually an excellen idea. Ill add this as an issue to
the github so i dont forget.

Best

**Comment by lindaboettger** [comment]
Great, thank you! I don't mean to rush you, but could you give me an idea of about how long this will take? I'm trying to decide if I should find an alternate method or hold out.

**Comment by ANGSD** [comment]
The program now outputs the number of sites in total and the number of sites keept in the output.
 ./angsd -b list -r 1 -domaf 1 -domajorminor 1  -gl 1 -minmaf 0.1	-> angsd version: 0.919-40-g642076d-dirty (htslib: 1.5-10-gcc55632) build(Mar  6 2018 12:41:21)
	-> No '-out' argument given, output files will be called 'angsdput'
	-> Parsing 33 number of samples 
	-> Region lookup 1/1
	-> Printing at chr: 1 pos:14086716 chunknumber 300 contains 251 sites
	-> Done reading data waiting for calculations to finish
	-> Done waiting for threads
	-> Output filenames:
		->"angsdput.arg"
		->"angsdput.mafs.gz"
	-> Wed Mar  7 07:38:36 2018
	-> Arguments and parameters for all analysis are located in .arg file
	-> Total number of sites analyzed: 100197
	-> Number of sites retained after filetering: 124 
	[ALL done] cpu-time used =  4.81 sec
	[ALL done] walltime used =  5.00 sec

I'm closing this issue, feel free to reopen if needed. Thanks for contacting me.

**Comment by lindaboettger** [comment]
Amazing, thanks!

Linda Boettger, Ph.D.
Postdoctoral Researcher, Vertebrate Genome Biology
The Broad Institute
75 Ames Street
Cambridge, MA 01242
Phone: 617-714-8094

**Comment by lindaboettger** [comment]
When compiling this new version, I am getting the following errors:

`make clean; make HTSSRC=../htslib`

Output:
```
...
g++ -c  -O3 -D__WITH_POOL__  prep_sites.cpp -I/seq/vgb/linda/bin/angsd_nsites/htslib 
prep_sites.cpp: In function 'void filt_gen(const char*, int, int)':
prep_sites.cpp:520:24: error: 'unlink' was not declared in this scope
     unlink(outnames_bin);
                        ^
```

...and if I comment out the unlinks and continue...

```
...
g++ -c  -O3 -D__WITH_POOL__  shared.cpp -I/seq/vgb/linda/bin/angsd_nsites/htslib 
shared.cpp: In function 'void init(argStruct*)':
shared.cpp:73:28: error: 'isatty' was not declared in this scope
   if(!isatty(fileno(stderr))){
                            ^
shared.cpp:80:45: error: 'isatty' was not declared in this scope
   if(!isatty(fileno(arguments->argumentFile)))
                                             ^
shared.cpp: In function 'void destroy_shared()':
shared.cpp:111:12: error: 'sleep' was not declared in this scope
     sleep(1);
            ^
shared.cpp: In function 'void waiter(int)':
shared.cpp:318:12: error: 'sleep' was not declared in this scope
     sleep(1);
```

Thanks for your help.

**Comment by aguilar-gomez** [comment]
Do you output somewhere which sites did not pass the filters and why? I ran this command:
`angsd -bam $bamlist -out outname -minInd 250 -setMinDepthInd 1 -minMapQ 25 -minQ 25 -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 -GL 1 -doMaf 1 -doMajorMinor 4 -doGlf 2 -SNP_pval 1e-6 -nThreads 10 -ref $REF -setMaxDepthInd 50 -doCounts 1 -skipTriallelic 1`
And got this:
-> Total number of sites analyzed: 3,306,892,825
-> Number of sites retained after filtering: 15,945,383

I am not sure I understand properly but is 3,306,892,825 sites the sites that passed 
-minInd 250
-setMinDepthInd 1
-minMapQ 25 
-minQ 25 
-remove_bads 1 
-uniqueOnly 1 
-only_proper_pairs 1 
-setMaxDepthInd 50 
-skipTriallelic 1

And 15,945,383 sites the ones that additionally pass:
-SNP_pval 1e-6  

Or what is the total number of sites analyzed? My reference genome is larger than 3,306,892,825

Thank you
