### ISSUE TITLE
New segfault error: angsd sites index

### ISSUE THREAD

**Issue by dmvelasco** [ANGSD/angsd#14]
Happened into a new segfault error while running ANGSD. In this case I am working on setting up a 2dSFS estimation to use as a prior for Fst. The first two lines 
```
gunzip -c PD.saf.pos.gz PP.saf.pos.gz | sort -S 50% | uniq -d | sort -k1,1 -S 50% | gzip > PE.saf.pos.gz
gunzip -c PE.saf.pos.gz PE.2pops.saf.pos.gz | sort -S 50% | uniq -d | sort -k1,1 -S 50% > intersect.txt
```
appear to function properly, producing a 64KB file, but
```
bin/angsd sites index intersect.txt
```
gives the following error
```
indexing intersect.txt and will add '0' to pos column
        -> Filterfile: intersect.txt supplied will generate binary representations... 
/var/spool/slurmd/job3702808/slurm_script: line 100: 21399 Segmentation fault      (core dumped)
```
(line 100 being the angsd line).

Thanks in advance for any help with this situation.

**Comment by ANGSD** [comment]
If you are using the new version of angsd, the ones that generate saf.idx files, then you can simply run realSFS on the saf.idx files without having to rerun angsd to get the intersect.

./realSFS PD.saf.idx PP.saf.idx -P 24 >2dsfs.txt

**Comment by dmvelasco** [comment]
Aha! Must have missed that while trying to figure it out.

Thanks again
