### ISSUE TITLE
New version (See #138) does not compile

### ISSUE THREAD

**Issue by lindaboettger** [ANGSD/angsd#140]
_(Crosspost from #138 - I cannot re-open my issue since I was not the one to close it.)_

When compiling this new version, I am getting the following errors:

`make clean; make HTSSRC=../htslib`

Output:
```
...
g++ -c  -O3 -D__WITH_POOL__  prep_sites.cpp -I/seq/vgb/linda/bin/angsd_nsites/htslib 
prep_sites.cpp: In function 'void filt_gen(const char*, int, int)':
prep_sites.cpp:520:24: error: 'unlink' was not declared in this scope
     unlink(outnames_bin);
                        ^
```

...and if I comment out the unlinks and continue...

```
...
g++ -c  -O3 -D__WITH_POOL__  shared.cpp -I/seq/vgb/linda/bin/angsd_nsites/htslib 
shared.cpp: In function 'void init(argStruct*)':
shared.cpp:73:28: error: 'isatty' was not declared in this scope
   if(!isatty(fileno(stderr))){
                            ^
shared.cpp:80:45: error: 'isatty' was not declared in this scope
   if(!isatty(fileno(arguments->argumentFile)))
                                             ^
shared.cpp: In function 'void destroy_shared()':
shared.cpp:111:12: error: 'sleep' was not declared in this scope
     sleep(1);
            ^
shared.cpp: In function 'void waiter(int)':
shared.cpp:318:12: error: 'sleep' was not declared in this scope
     sleep(1);
```

Thanks for your help.

**Comment by lindaboettger** [comment]
I did another `make clean` and remade, and these errors above seemed to disappear. However, now I am getting another error during make.

For context, after some work I got `htslib` built successfully with no errors when I compiled local versions of missing libraries (llzm, lbz2). `bzip2` needed a dynamically linked version of `libbz2` made with `Makefile-libbz2_so`, in addition to the normal `Makefile`. Finally, to get ANGSD `make HTSSRC=../htslib` to find all of the libs, I also had to add them to the LFLAGS and CPPFLAGS.

My command looks like:
```
env CPPFLAGS="-I/seq/vgb/linda/bin/zlib-1.2.11/include -I/seq/vgb/linda/bin/bzip2-1.0.6 -I/seq/vgb/linda/bin/bzip2-1.0.6 -I/seq/vgb/linda/bin/liblzma/include" LDFLAGS="-L/seq/vgb/linda/bin/bzip2-1.0.6 -L/seq/vgb/linda/bin/zlib-1.2.11/lib -L/seq/vgb/linda/bin/liblzma/lib" make HTSSRC=../htslib
```

These same CPPFLAGS and LDFLAGS allowed `htslib` to compile successfully.

However, this gets pretty far but also fails:

```
...
g++ -O3 -D__WITH_POOL__ -L/seq/vgb/linda/bin/bzip2-1.0.6 -L/seq/vgb/linda/bin/zlib-1.2.11/lib -L/seq/vgb/linda/bin/liblzma/lib  -o angsd *.o /seq/vgb/linda/bin/angsd_nsites/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread -lcurl
/broad/software/free/Linux/redhat_6_x86_64/pkgs/gcc_5.2.0/bin/ld: /seq/vgb/linda/bin/angsd_nsites/htslib/libhts.a(hfile_s3.o): undefined reference to symbol 'HMAC@@libcrypto.so.10'
/usr/lib64/libcrypto.so.10: error adding symbols: DSO missing from command line
```

I am now stuck here. Thanks for your help.

For reference,
```
$ uname -a
Linux vert02 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 12 15:07:59 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ANGSD** [comment]
Dear Linda, could you try to do a make clean and see if that helps.

Best

**Comment by lindaboettger** [comment]
If only it were that simple :)
I did brute force my way to getting it installed though. 

Best wishes,
Linda
