### ISSUE TITLE
No X0 tag available in BAM. Is there a workaround?

### ISSUE THREAD

**Issue by init-js** [ANGSD/angsd#142]
I'm using NGM to align bams, and trying to estimate genetic distances. As part of the process, I'm using angsd to compute genotype posterior probabilities

angsd outputs:
```
        -> Need XO tag to calculate the number of best hits
```
( from https://github.com/ANGSD/angsd/blob/a30d0b4ab89637c3c76dee38d3a20359f49f0aca/pop1_read.cpp#L55)

which I believe is a BWA-specific SAM header. NGM does not output this header. Is there any way to work around this, or calculate this header as a post-processing step?

My angsd flags:
```
    -P 32              #threads                                                                                                                       
    -ref "$REF"                                                                                                                                                
    -out "$OUTDIR/ALL"                                                                                                                                         
    -uniqueOnly 1      #discard reads that don't map uniquely    
    -minMapQ 20        #minimum mapping quality of 20                                                                                                          
    -minQ 20           #minimum base quality of 20                                                                                                             
    -minInd 5          #use only side with data from at least IND individuals                                                                                  
    -doCounts 1        #calculate stats                                                                                                                        
    -GL 1              #estimate genotype likelihoods                                                                                                          
    -doMajorMinor 1    #infer major/minor using different approaches                                                                                           
    -doMaf 1           #estimate allele frequencies                                                                                                            
    -skipTriallelic 1  #                                                                                                                                       
    -SNP_pval 1e-6     #                                                                                                                                       
    -doGeno 8          #call genotypes                                                                                                                         
    -doPost 1
```

**Comment by ANGSD** [comment]
Does your aligner have any other aux tag that compares to the XO? If there is not information on number of best hits then it is not possible to use the -uniqueOnly option and i would disable that.

Best

**Comment by init-js** [comment]
I can't find any equivalent flags (that are documented), but I'll certainly ask the maintainers.

I'm dealing with paired reads. I wonder in general what are the effects of dropping the requirement that X0==1 on the final output? I will certainly be including strictly more information into calculating the genotype likelihood with -uniqueOnly 0.

thank you

**Comment by ANGSD** [comment]
Hello init-js, could you supply me with a bam/cram containing these problematic xo tagged reads.

Best regards

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed.

**Comment by init-js** [comment]
Apologies for the tardy answer. After some debugging, I believe this error was due to a bad build of libhts (I was using a version pulled from conda). I can't reproduce this bug anymore when compiling from source.
