### ISSUE TITLE
Counting number of sites in analysis

### ISSUE THREAD

**Issue by lindaboettger** [ANGSD/angsd#143]
Dear ANGSD, 

I have two questions about the new counts that were added "Total number of sites analyzed" and "Number of sites retained after filetering”.

1. If I use a SNP filter (i.e. -snp_pval 1e-6), it looks like only polymorphic sites are retained in the count of sites that passed filters. I’m hoping to understand the count of all sites that passed filters, even if they are not variable. Is there a way to get this total site count while only retaining the likely polymorphic sites in the output mafs? 

2. When I run a command without anything I perceive as a filter, many sites are still removed. Am I misinterpreting something?

```
$angsd  -r chr22:1-10611527 \
	-bam $bamfilelist \
	-out $maffile$chr \
	-ref $ref \
	-anc $anc \
	-GL 2 \
	-doCounts 1 \
	-domaf 1 \
	-doGeno 2 \
	-doPost 1 \
	-doMajorMinor 5

-> Total number of sites analyzed: 101625
-> Number of sites retained after filetering: 84538 
```

Many thanks,
Linda

**Comment by ANGSD** [comment]
hello linda, i think it is the -domajorminor 5 that causes this. If the
ancestral is N then the site gets discarded. Hopefully this helps.

Best

**Comment by lindaboettger** [comment]
Yes, when I use --doMajorMinor 1 only 99 snps get filtered (see below). Not sure why those 99 are removed, but this is very close to what I expect.

Any thoughts on the first question regarding a count of all passing sites (not just SNPs)? I suppose I could run the command twice - once to get a count of all the sites that passed filters (without using -snp_pval 1e-6), and a second time to make the mafs (using -snp_pval 1e-6), but it would be time consuming since I'm doing a whole genome analysis. 

Best wishes,
Linda

```
$angsd -r chr22:1-10611527 \
	-bam $bamfilelist \
	-out $maffile$chr \
	-ref $ref \
	-anc $anc \
	-GL 2 \
	-doCounts 1 \
	-domaf 1 \
	-doGeno 2 \
	-doPost 1 \
	-doMajorMinor 1

        -> Total number of sites analyzed: 101625
        -> Number of sites retained after filetering: 101526 
```

**Comment by ANGSD** [comment]
The sites that are retained are the intersect of all filters. It is
currently not possible to know how many sites are filtered out from the
different filter parameters. You would have to rerun

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed
