### ISSUE TITLE
unsorted saf when filtering?

### ISSUE THREAD

**Issue by sagw** [ANGSD/angsd#145]
I seem to be having a problem when I filter my saf file using -rf like this:
/local/home/sarahgw/angsd/angsd/angsd -b /local/home/sarahgw/WGS/Sequences/filelists/NJ_U.filelist -anc /local/home/sarahgw/references/Myotis_lucifugus.Myoluc2.0.dna_sm.toplevel.fa -GL 1 -dosaf 1 -minMapQ 30 -minQ 20 -rf /local/home/sarahgw/WGS/QC/All_mylu_Map1.txt -out /local/home/sarahgw/WGS/SNPS/All_mylu/saf/NJ_U_unfilt

the filter file looks like this (and is sorted)
GL429767:1-4318
GL429767:4438
GL429767:4440-4443
GL429767:4447-4459
GL429767:4789-5777
GL429767:5780-6041
GL429767:6058-6079
GL429767:6086-6219
GL429767:6229-6840
GL429767:6915-6922
GL429767:6923
GL429767:6982-6995
GL429767:6998-7010
GL429767:8949
GL429767:9043
GL429767:9048-9145
GL429767:9170-9173

When I then try to create a 2dSFS:
/local/home/sarahgw/angsd/angsd/misc/realSFS /local/home/sarahgw/WGS/SNPS/All_mylu/saf/VT_E_unfilt.saf.idx /local/home/sarahgw/WGS/SNPS/All_mylu/saf/VT_U_unfilt.saf.idx > /local/home/sarahgw/WGS/SNPS/All_mylu/sfs/VT_EU_unfilt.mI 

I get this error: 
      -> Potential big problem, ordering of positions indicates that sites has not been sorted ?
        -> chromoname: 'AAPE02062079' pos[6318]:20402 vs pos[6318-1]:20402
        -> Consider running ./realSFS check your.saf.idx for each pop
        -> Sites to keep[AAPE02062079] from pop0:       93
        -> Sites to keep[AAPE02062079] from pop1:       95
realSFS: realSFS_shared.cpp:131: int set_intersect_pos(std::vector<persaf*>&, char*, int, int, char**, filt*): Assertion `tsk[i]==tsk[i-1]' failed.
Aborted (core dumped)

the saf files apparently are now unsorted: 
~/angsd/angsd/misc/realSFS check ~/WGS/SNPS/All_mylu/saf/VT_U_unfilt.saf.idx
gives me         
-> problems with unsorted saf file chromoname: 'AAPE02064518' pos[4598]:10861 vs posd[4598-1]:10861

This worked before when I wasn't filtering the saf files. Is there a way to sort the saf files? Does anyone know why this is happening? I tried updating ANGSD to 0.9.20 but get the same errors. 

Any help would be very appreciated, thanks!
Sarah

**Comment by z0on** [comment]
Hi Sarah - you seem to have overlapping entries in your -rf file (different lines in that file cannot refer to the same position)
Misha

**Comment by ANGSD** [comment]
Hello I agree with Misha the -rf should be disjoint regions.

Im closing this issue, but feel free to reopen if needed.
