### ISSUE TITLE
thetaStat and nChr for folded data

### ISSUE THREAD

**Issue by alielw** [ANGSD/angsd#146]
Hi ANGSD team,

I had a question about the nChr parameter for thetaStat do_stat on folded data.

For older versions of ANGSD when you had to specify nChr, am I correct in thinking that nChr = number of individuals if the SFS is folded?

How is nChr used in the calculation of Tajima's D in thetaStat do_stat?

For newer versions of ANGSD where you do not specify nChr, will thetaStat do_stat correctly identify nChr for folded data?

I ask because I have folded data with 3 individuals. I am running angsd version: 0.921-3-g40ac3d6. I run thetaStat do_stat input.idx but I get Inf for Tajima's D. I get the same output when I run thetaStat do_stat input.idx -nChr 3. However, interestingly when I run thetaStat do_stat input.idx -nChr 6, I get a value for Tajima's D. Why might this be?

Thanks

**Comment by ANGSD** [comment]
The correct number of chromosomes should be given by the binary saf.idx file. But you can override this if you supply -nChr.

Hope this helps.
