### ISSUE TITLE
Reference ID error 

### ISSUE THREAD

**Issue by liushanlin** [ANGSD/angsd#147]
Dear ANGSD group,

I got the error message as follows when i tried to estimate a bunch of things using ANGSD v0.921
**ReferenceID:(r:0) for read:CL100033396L1C017R046_454501 is not: 254 but is:253**

the parameters are: `-P 1 -b list.bam -trim 3 -out angsd -gl 1 -minQ 20 -minMapQ 30  -uniqueOnly 1 -only_proper_pairs 1 -setMaxDepthInd 100 -doMajorMinor 1 -snp_pval 1e-6 -domaf 1 -minmaf 0.01 -doIBS 1 -doCounts 1 -makeMatrix 1 -doCov 1 -doGlf 2 -doDepth 1 -doGeno 3 -dopost 1
`

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed.

**Comment by nicolas931010** [comment]
Hi,

I am having a similar error message with angsd v0.931. My input is:

`./angsd -b /workdir/sucker/sample_lists/bam_list_realigned.txt -anc /workdir/sucker/genome/final.genome.scf.fasta -out /workdir/sucker/angsd/bam_list_realigned_mindp46_maxdp195_minind46_minq20 -dosaf 1 -GL 1 -doGlf 2 -doMaf 1 -doMajorMinor 1 -doPost 1 -doVcf 1 -doCounts 1 -doDepth 1 -dumpCounts 1 -doIBS 1 -makematrix 1 -doCov 1 -P 32 -SNP_pval 1e-6 -setMinDepth 46 -setMaxDepth 195 -minInd 46 -minQ 20 -minMaf 0.01`

And the last 10 lines of the angsd log are the following:

**Charnge chr:37903
[shared.cpp.changeChr():281] refid:37904
Charnge chr:37904
[shared.cpp.changeChr():281] refid:37905
Charnge chr:37905
[shared.cpp.changeChr():281] refid:37906
Charnge chr:37906
[shared.cpp.changeChr():281] refid:37907
Charnge chr:37907
ReferenceID:(r:0) for read:E00489:449:H2VJ2CCX2:8:2220:21978:50709 is not: 37907 but is:37906**

Thanks!

**Comment by FR193** [comment]
Hi,
I am having a similar error with angsd v.0.933 whenever I try to use bam files as input. The last 10 lines of the log file are the following:

	-> Printing at chr: Contig276 pos:13 chunknumber 7300 contains 137 sites
	-> Printing at chr: Contig280 pos:61870 chunknumber 7400 contains 2210 sites
	-> Printing at chr: Contig285 pos:71698 chunknumber 7500 contains 1301 sites
	-> Printing at chr: Contig289 pos:53384 chunknumber 7600 contains 1723 sites
	-> Printing at chr: Contig294 pos:29675 chunknumber 7700 contains 2903 sites
	-> Printing at chr: Contig296 pos:47609 chunknumber 7800 contains 1435 sites
	-> Printing at chr: Contig301 pos:84996 chunknumber 7900 contains 256 sites
	-> Printing at chr: Contig306 pos:40859 chunknumber 8000 contains 1821 sites
	-> Printing at chr: Contig308 pos:26962 chunknumber 8100 contains 23 sites
ReferenceID:(r:0) for read:K00198:327:HWFYTBBXX:8:2206:24962:48333 is not: 309 but is:146

I checked the bam files and none of them has a read K00198:327:HWFYTBBXX:8:2206:24962:48333 (or any K00198:327:HWFYTBBXX:8 pattern). What is the error? 

Any help would be appreciated. Thanks!
