### ISSUE TITLE
Determinant becomes zero at ... ?

### ISSUE THREAD

**Issue by AlexLemo** [ANGSD/angsd#149]
Dear Angsd group,

I am trying to run an Association analysis on a quantitative phenotype. I have a total of 116 individuals, but since I have population structure, I want to first remove it using Pcangsd, and then perform the analysis. However, when I finally run the -doAsso 2 commande line, I get the message : Determinant becomes zero at 117! The program still runs but all my sites have a LRT of -99.00.

Any idea why this happens?

Here are the lines I am using
1)  to prepare the input for pcangsd:
./angsd -GL 1 -out genolike_PCA  -doGlf 2 -doMajorMinor 1 -SNP_pval 1e-6 -doMaf 1  -bam bam.filelist -minInd 87 -minMaf 0.05 -HWE_pval_F  0.05 -minMapQ 20 -minQ 20

2) In pcangsd:

python pcangsd.py -beagle genolike_PCA.beagle.gz -n 116 -o output_pcangsd

3) the association
./angsd  -doAsso 2 -bam bam.filelist -yQuant phenotypes.txt  -cov output_pcangsd.cov -out outfile_asso_test -GL 1 -doMaf 1 -doMajorMinor 1 -doPost 1 -SNP_pval 1e-6 -minMaf 0.05 -HWE_pval_F  0.05 -minInd 87 -minMapQ 20  -minQ 20

Thanks a lot for your help !

Best,

Alexandre

**Comment by aalbrechtsen** [comment]
Dear Alexandre

including the whole covariance matrix in the associational test. You cannot include that many covariates in the linear model used in the association test. 

Here is What I would do
perform PCA on the covariance matrix from the output from PCAngsd first. 
For example using R:
## read the covariance matrix into R
 cov <- as.matrix(read.table("output_pcangsd.cov"))
## get the Principal components
 e<-eigen(cov)
## plot the first 2 PCs
 plot(e$vectors[,1:2],col=ID$POP)
## write the covariates e.g. the first 3 PCs
write.table(e$vectors[,1:3],file="new.covariats",row=F,qu=F,col=F)

Use the selected  low number of PC to include as covariates in the linear model
./angsd -doAsso 2 -bam bam.filelist -yQuant phenotypes.txt -cov new.covariats -out outfile_asso_test -GL 1 -doMaf 1 -doMajorMinor 1 -doPost 1 -SNP_pval 1e-6 -minMaf 0.05 -HWE_pval_F 0.05 -minInd 87 -minMapQ 20 -minQ 20

-Anders

**Comment by AlexLemo** [comment]
Dear Anders,

That's great, thanks a lot, it worked perfectly! 

One more very trivial question (sorry about it). 
If I understand correctly, the -doAsso function gives individual LRT values for each analysed locus. These values are chi-square distributed with 1 degree of freedom. So, to know if a locus (SNP) presents significant association with the phenotype, the LRT value should be above the chi-square critical value for an alpha level. For example, if I decide to take an alpha of 0.01, then any LRT > 6.635 is significant (https://www.medcalc.org/manual/chi-square-table.php) ?

Thanks again,
Best,
Alexandre
