### ISSUE TITLE
Calculate the thetas for each site

### ISSUE THREAD

**Issue by houzhe1991** [ANGSD/angsd#152]
HI：
    When I Calculate the thetas for each site through the command:

> ./angsd -bam bam.filelist -out out -doThetas 1 -doSaf 1 -pest out.sfs -anc chimpHg19.fa -GL 1

The output from the above command are 1 files out.thetas.gz ,
but have not the file out.thetas.idx .What happened? How can i get the idx file???

**Comment by ANGSD** [comment]
Please double check that this is correct. Supply me with output of 
ls out*
Which version are you using.

Best

**Comment by ANGSD** [comment]
Im closing this one. Feel free to reopen if needed.
