### ISSUE TITLE
Allele count for positions in region file 

### ISSUE THREAD

**Issue by madzayasodara** [ANGSD/angsd#153]
Hi I'm trying to do allele counts for a series of sites listed in .txt file as shown bellow:
1:231293074
1:231293077
1:231293301
1:231293590
1:231300381
and I'm using the following command:
./angsd -out test -bam bam.filelist -rf region.txt -doCounts 1 -dumpCounts 4
But It's not working. 
It does work when I do for only one region. Let's say
./angsd -out test -bam bam.filelist -r 1:231293074 -doCounts 1 -dumpCounts 4

What I could be doing wrong?
Thanks!

**Comment by ANGSD** [comment]
can you show me the full outfrom from when you run it. It seems to work at
my end:

[fvr124@zl08368 angsd]$ cat rf
1:13999902
1:13999911
[fvr124@zl08368 angsd]$ ./angsd -b list -rf rf -show 1|cut -f1-2
    -> angsd version: 0.921-11-g20b0655 (htslib: 1.8-17-g699ed53) build(May
28 2018 10:23:47)
    -> No '-out' argument given, output files will be called 'angsdput'
    -> Parsing 33 number of samples
    -> Region lookup 1/2
    -> Region lookup 2/2
    -> Done reading data waiting for calculations to finish
    -> Done waiting for threads
    -> Output filenames:
        ->"angsdput.arg"
    -> Mon May 28 10:27:14 2018
    -> Arguments and parameters for all analysis are located in .arg file
    -> Total number of sites analyzed: 0
    -> Number of sites retained after filetering: 0
    [ALL done] cpu-time used =  0.06 sec
    [ALL done] walltime used =  1.00 sec
1    13999902

**Comment by madzayasodara** [comment]
Yes this is what I get when I run ./angsd -out test -bam bam.filelist -rf region.txt -doCounts 1 -dumpCounts 4

-> angsd version: 0.921-11-g20b0655 (htslib: 1.8-14-gbceff25) build(May 22 2018 15:27:46)
    -> No '-out' argument given, output files will be called 'angsdput'
    -> Parsing 148 number of samples 
    -> Region lookup 1/1-> Done reading data waiting for calculations to finish
    -> Done waiting for threads
    -> Output filenames:
        ->"angsdput.arg"
    -> Wed May 30 11:02:08 2018
    -> Arguments and parameters for all analysis are located in .arg file
    -> Total number of sites analyzed: 0
    -> Number of sites retained after filetering: 0 
    [ALL done] cpu-time used =  4.87 sec
    [ALL done] walltime used =  17.00 sec
1    231293074

I noticed you actually used the cmd
angsd -b list -rf rf -show 1|cut -f1-2
is this what I should use instead?
this still only outputs the allele count for the 1st line.
Thank you

**Comment by ANGSD** [comment]
Was this issue resolved? 
There is some information about obtaining the simple counts here:
http://www.popgen.dk/angsd/index.php/Allele_Counts

Im closing this issue feel free to reopen if needed.
