### ISSUE TITLE
PCA single read sampling approach

### ISSUE THREAD

**Issue by inndcm** [ANGSD/angsd#154]
Hi!
I'm trying this new function that was added in the latest versions to do PCA only by sampling one single read per site. I was hoping you could clarify this information that is in the wiki:

"For the PCA / MDS methods you should called SNP sites (use PCA if you do not want to call SNPs). SNPs can be called based on genotype likelihoods (see SNP_calling)".

What kind of information exactly is used to produce the covariance matrix? Is it the information about the precise allele inferred in each site (e.g., A, C, T, G information)? SNPs are inferred based on genotype likelihoods, but the likelihood information is not used?
What is the major difference from this method to the NGStools method that you recommend in the wiki? NGStools is based on genotype likelihoods?
I would really appreciate your help because I'm new to this kind of analyses!

**Comment by aalbrechtsen** [comment]
hi

you have the option to use a single sampled read at each site or to use all information using genotype likelihoods

The single read sampling is described here
http://www.popgen.dk/angsd/index.php/PCA_MDS

For the genotype likelihood approach you can use either PCangsd or NGStools. 
1)  NGStools can be used without calling variable sites but it cannot handle large differences in depth between samples
2) PCAngsd handles any depth differences but you need to call variables. PCAngsd is the method I use. 
Both methods have a article that you can read. 


-Anders

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed.
