### ISSUE TITLE
Get sequence from SNP

### ISSUE THREAD

**Issue by AlexLemo** [ANGSD/angsd#158]
Dear Angsd community,

Thanks for this awesome program!

I successfully ran the -doAsso function and obtained several SNPs of interest. My goal would now be to extract the sequences preceding these SNP in order to develop primers.
I was wondering how I could get the reads / sequence from Angsd output. I am using RADseq data on non-human data.

Thanks for the help,

Best,

Alexandre

**Comment by z0on** [comment]
Try ‘samtools faidx’ to extract reference sequence region around your SNP 

iPhone. Autocorrections galore.

**Comment by AlexLemo** [comment]
Hi,

Thanks for the answer. This will however give me the reference sequence. Is there any possible way to get the actual sequence directly from my reads. I am working with a non model organism with no available genome, so I had to align to a closely related species. Thus I'd prefer to have the actual sequence rather than the reference one.

Thanks,

Alexandre

**Comment by z0on** [comment]
Ah, I see.
Try this seat-of-the-pants solution: 
assuming you did '-doMajorMinor 1 -doMaf 1' without filtering by snp_pval or minMaf, and want to extract region contig1:1000-1200 :

zcat angsdput.mafs.gz | awk '$1==“contig1" && $2>=1000 && $2<=1200' | cut -f 3 | perl -pe 's/\n//'

this should print out the sequence of the major allele for the region.

Misha

**Comment by ANGSD** [comment]
Dear Alexandre. You can obtain consensus with angsd -dofasta and extract with samtools faidx afterwards as Misha suggests.

Best
Thorfinn

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed.
