### ISSUE TITLE
SFS counts and nSites input

### ISSUE THREAD

**Issue by twooldridge** [ANGSD/angsd#159]
Hi,

I'm attempting to use ANGSD to get the site frequency spectrum from a vcf file. The vcf file was generated by GATK's GenotypeGVCFs and subsequently hard-filtered for low quality variants. My issue is that I'm having trouble interpreting the estimated counts produced by realSFS.  I'm using angsd  v. 0.921.

First, here's how I generate the SAF file:

```
~/Software/angsd_new/angsd -vcf-pl NUB.chr23.vcf -fai anc.Pman.fasta.fai -nind 15 -doSaf 1 -out results/NUB.chr23 -anc anc.Pman.fasta -fold 0
```

And this seems to complete normally, although emitting lots of messages for skipping indels or multiallelic sites. Then I run realSFS, and get the following output:

```
~/Software/angsd_new/misc/realSFS results/NUB.chr23.saf.idx
	-> Version of fname:results/NUB.chr23.saf.idx is:2
	-> Assuming .saf.gz file: results/NUB.chr23.saf.gz
	-> Assuming .saf.pos.gz: results/NUB.chr23.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fstout:(null) oldout:0 seed:1529621838 bootstrap:0 whichFst:0 fold:0 ref:(null) anc:(null)
	-> You are printing the optimized SFS to the terminal consider dumping into a file
	-> E.g.: './realSFS results/NUB.chr23.saf.idx >sfs.ml.txt'
	-> nSites: 4331436
	-> The choice of -nSites will require atleast: 545.262878 megabyte memory, that is at least: 3.43% of total memory
	-> dim(results/NUB.chr23.saf.idx):31
	-> Dimension of parameter space: 31
	-> Done reading data from chromosome will prepare next chromosome
	-> Is in multi sfs, will now read data from chr:chr23
	-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
	-> Will run optimization on nSites: 4331436
------------
startlik=-19836741.587509
lik[2]=-5662210.264976 diff=1.417453e+07 alpha:1.000000 sr2:4.809535e-01
lik[5]=-5661103.788474 diff=1.106477e+03 alpha:1.265469 sr2:4.321427e-06
lik[8]=-5661103.151803 diff=6.366713e-01 alpha:1.687753 sr2:7.838466e-10
	-> Breaking EM(sr2) at iter:9, sqrt(sr2):7.419701e-08
likelihood: -5661103.151803
------------
3123478.322878 284536.306954 172690.749292 118089.115025 83695.179344 62422.259712 49867.506603 41620.288743 35435.393336 30073.953906 25842.762182 23468.675811 21672.423136 19162.661057 17174.730032 17285.649680 13962.509282 13129.205798 12632.937280 11615.223713 10220.564299 9991.796552 10033.425103 9646.501763 9051.481433 8972.401417 9319.607877 9577.886125 10071.018680 11204.715604 55490.747382
	-> Only read nSites: 0 will therefore prepare next chromosome (or exit)

	-> NB NB output is no longer log probs of the frequency spectrum!
	-> Output is now simply the expected values! 
	-> You can convert to the old format simply with log(norm(x))
```

My confusion stems from the nSites parameter. The output shows that 4,331,436 sites are being considered. How exactly is this number determined? It definitely exceeds the number of variants in the file (2,677,804), even including SNPS and multiallelic sites. The chromosome size is much larger at 47,673,962 bp.  It looks like the SFS output adds up to nSites, which does make sense. So what sites are being considered with "nSites", and should I be concerned about how this affects my output SFS proportions?

Also, I figure that "invariant" sites must be considered/estimated somehow in order to generate the first value in the SFS (where derived allele frequency=0), but how is this done with an input file that is, by definition, only variants?

Thank you for your help

Brock

**Comment by ANGSD** [comment]
Dear Brock, does your vcf contain gl pl or gp?

**Comment by twooldridge** [comment]
It contains PL likelihoods

**Comment by twooldridge** [comment]
Quick follow up: 

The SFS frequencies end up being extremely siilar between runs when I modify the input interval, as long as that interval is not too small. So I'm less concerned about the effects of the "optimization on nSites", but am still curious as to what is going on. Also, the output SFS is very similar to the empirical SFS I get from running SweepFinder2. This is using a sweepfinder-formatted file derived from the same original VCF.

**Comment by ANGSD** [comment]
Dear Brock sorry for loosing track with regards to this issue.

How many lines did you have in the input vcf?

**Comment by twooldridge** [comment]
Hi,

I'm revisiting this issue after some experimentation with fastsimcoal and other demographic inference software is suggesting some problems with my input SFS (derived from ANGSD). In short, the count for monomorphic sites seems very low, and I'm wondering how monomorphic site frequencies are estimated given a VCF as input? I imagine this will also be affected by whether I provide a reference genome or ancestral genome to polarize? 

To answer your question above, I'm not sure how many lines were in that specific VCF, as my filtering strategy has since changed and I'm using a different version (but experiencing the same phenomenon I described in the first post). Right now, I'm using a VCF with 2172888 variants (and lines) in the file.

Thank you for your help,
Brock

**Comment by ANGSD** [comment]
Dear Brock, sorry for the very extending delay, i was working on a new vcf filereading. Please try the latest version which should fix many issues and most likely also the issue you are seeing here.

Im closing this issue but feel free to reopen if needed.

Best
