### ISSUE TITLE
unweighted and weighted Fst

### ISSUE THREAD

**Issue by dmvelasco** [ANGSD/angsd#16]
After much searching, including reading through Fumagalli et al. (2013) and documentation at http://www.popgen.dk/angsd, I have been unsuccessful in finding a clear explanation of the difference between the unweighted and weighted Fst values output by ANGSD realSFS. Are the unweighted values equation 4 while the weighted values equation 12 in Fumagalli et al. (2013)? The motivation for asking is that the unweighted and weighted Fst values for my two study populations are very different, 0.029449 and 0.668699, respectively, and I am trying to understand why there is such a large difference and its meaning. Any clarification is greatly appreciated; thank you.

**Comment by ANGSD** [comment]
We are using the formulas from the [raynolds 1983] paper. You can find some R code that implements the weighted and unweighted model in the R subfolder https://github.com/ANGSD/angsd/blob/master/R/fstFrom2dSFS.R

**Comment by dmvelasco** [comment]
If I understand both the paper and the R code correctly, the difference between unweighted and weighted values is averaging versus ratio of sums method, correct? The weighted value is derived from the ratio of the separate per-locus sums of numerator and denominator values, while the unweighted value is the average of per-locus values. [If that is unclear: weighted is sum(a)/sum(a+b), while unweighted is average(a/(a+b))]. If that is correct, many thanks for the clarification.

**Comment by ANGSD** [comment]
This is correct.

Best

**Comment by dmvelasco** [comment]
Great - thanks!
