### ISSUE TITLE
thetaStat segfault

### ISSUE THREAD

**Issue by fgvieira** [ANGSD/angsd#161]
thetaStat segfaults if option `-outname` is not provided.
Not a major issue, but I think it would be nice to get an error message or so.

cheers,

**Comment by ANGSD** [comment]
Can you give an example of which command that causes the segfault

**Comment by fgvieira** [comment]
for example, running:

    thetaStat do_stat input.thetas.idx

**Comment by ANGSD** [comment]
This does not segfault in the newest version, so im assuming it is fixed. Im closing this issue, feel free to reopen if needed.

Best
