### ISSUE TITLE
Input data for D-stat?

### ISSUE THREAD

**Issue by Ptero64** [ANGSD/angsd#163]
Hello,

Sorry to post this here. It's not an issue with the software, but advises for using D-statistics test. 
I am interested to use to D-stat to test for pattern of introgression or ILS between different species. I would like to use ANGSD (then Dfoil to estimate the direction of gene flow).

I haven't used those tests yet but I am a bit confused on the type of input data needed.

1- I saw several papers using D and Dfoil statistics using whole genome sequence data, but can we also apply this method with targeted sequences data? I have thousand of protein coding sequences, does it make sense to concatenate them and use them for D-stat ( ~ 3 million bp and use windows of 100kb)? 

2- For the input, I mapped reads with BWA to a reference genome which will be the outgroup in my D-stats test. Then I have sorted .bam files. What I am not sure is if I need to make SNP calling (with freebayes or GATK) before to run ANGSD? And/or do I have to code heterozygote sites as IUPAC (with GATK and FastaAlternateReferenceMaker)?

Thanks for the advices.

Nico

**Comment by ANGSD** [comment]
Maybe @aalbrechtsen or @SamueleSoraggi has some input on this.

Best

**Comment by aalbrechtsen** [comment]
I don't know Dfoil. 
If you use GATK for call SNPs and genotypes then you don't need Angsd (but you can use the many software for D-stat). If you don't want to call SNPs and genotypes then you should use angsd
-Anders

**Comment by Jungal10** [comment]
This goes a bit late, but you do not need to call variants to have D-stat on ANGSD. Only the bam files

**Comment by ANGSD** [comment]
I am closing this issue. Feel free to reopen if needed.
