### ISSUE TITLE
support for CRAM

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#164]
Dear @fgvieira 

When I use CRAM file as input, the angsd (0.918, htslib: 1.5) always print following information.

[E::socket_connect] Can't resolve www.ebi.ac.uk:80: System error
Failed to populate reference for id 0
Unable to fetch reference #0 131185..166263
Failure to decode slice
[E::socket_connect] Can't 

I know this information should from samtools. For samtools to open the cram file it must have the reference sequence added with the -T flag. I do not know how angsd can solve this problem, hope your help.

Best
Zhuqing

**Comment by ANGSD** [comment]
Ok this is something that hasn't been tested much. Could you supply me with
a very small subset of the cram. Maybe just a few reads.

Best

2018-07-05 16:12 GMT+02:00 biozzq <notifications@github.com>:

**Comment by biozzq** [comment]
Dear @ANGSD 

Thank you.  I hope the attached file can help you test.
[HX09H.trimmed.zip](https://github.com/ANGSD/angsd/files/2168747/HX09H.trimmed.zip)

Best

**Comment by ANGSD** [comment]
Ok this should be fixed in latest version.

You need to supply the reference with either -ref or -T 

Best
