### ISSUE TITLE
thetaStat do_stat per region

### ISSUE THREAD

**Issue by wenhaotan208** [ANGSD/angsd#166]
Hello, 
I wanted to calculate Tajima’s D and FST per gene. I was able complete the Step 1 and 2 in [the manual](http://www.popgen.dk/angsd/index.php/Thetas,Tajima,Neutrality_tests) to obtain thetas per site; however, for Step 3a I found that the output I got were combined estimates per scaffold rather than individual regions of interest. For example, when I used -rf to input a region file with three regions (genes): 
Scaf1:100-500
Scaf1:1500-2000
Scaf2:500-1000 
The output for Tajima’s D I got only contains two lines, one line per scaffold. I wonder if there is a way to calculate Tajima’s D separately for multiple regions of interest that are on the same scaffold? 
Thank you!

**Comment by ANGSD** [comment]
You can estimate the persite thetas and calculate the statistic directly or you should be able to define the region with -rf

**Comment by wenhaotan208** [comment]
Thanks!

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed.

Best
