### ISSUE TITLE
angsd error for BAM header

### ISSUE THREAD

**Issue by zdz1989** [ANGSD/angsd#167]
Dear all, 

I have met a problem when read BAM files, here is my command:
./angsd -out /Volumes/Cyanoptila_David/Final_Data_July3_2018/dfoil/bamlist_gd -doMaf 2 -bam /Volumes/Cyanoptila_David/Final_Data_July3_2018/dfoil/bam.filelist -doMajorMinor 1 -GL 1 -P 5

the error message:
-> angsd version: 0.920 (htslib: 1.6) build(Jul  2 2018 19:07:15)
	-> We require a proper header starting with @HD for ANGSD
	-> We observed: '@SQ	SN:NC_' will exit
	-> We require a proper header starting with @HD for ANGSD
	-> We observed: '@SQ	SN:NC_' will exit
	-> We require a proper header starting with @HD for ANGSD
	-> We observed: '@SQ	SN:NC_' will exit
	-> We require a proper header starting with @HD for ANGSD
	-> We observed: '@SQ	SN:NC_' will exit
	-> Parsing 4 number of samples 
Segmentation fault: 11

How can this be solved?

Thanks a lot for your time!

Dezhi

**Comment by ANGSD** [comment]
Does the bams work with samtools view?

2018-07-18 4:01 GMT+02:00 zdz1989 <notifications@github.com>:

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed.

**Comment by theshowmustgolangon** [comment]
@ANGSD Yes, I encountered this error now! Any suggestions or solutions?
