### ISSUE TITLE
Question about Only Propper Pairs

### ISSUE THREAD

**Issue by rmarquezp** [ANGSD/angsd#168]
Hello, 

I am working on bam files generated by mapping both PE and SE reads to a reference and was wondering: Will using the -only_proper_pairs 1 flag result in angsd ignoring SE reads, or will this only filter out improperly-paired PE reads?  

Thanks!

Roberto

**Comment by ANGSD** [comment]
That option will only be checked if read is a PE as given by the flag
value, see here:
https://github.com/ANGSD/angsd/blob/master/pop1_read.cpp#L132
Best

2018-07-24 20:02 GMT+02:00 Roberto Márquez <notifications@github.com>:

**Comment by rmarquezp** [comment]
Thanks!
