### ISSUE TITLE
incomplete make install target?

### ISSUE THREAD

**Issue by wookietreiber** [ANGSD/angsd#171]
`make install` installs the **angsd** binary to `$DESTDIR/$prefix/bin/angsd`. All the binaries/scripts that are built in the **misc** directory do not get installed. Should they be?

**Comment by wookietreiber** [comment]
If misc is not necessarily relevant, I would suggest to remove it from the default make target:

- `make` and `make angsd` only builds the **angsd** binary
- `make misc` builds everything in the misc subdirectory
- `make all` both get built

You could then also provide separate install targets:

- `make install` install **angsd**
- `make install-misc` installs the tools from the misc subdirectory
- `make install-all` installs both

**Comment by wookietreiber** [comment]
If you want, I can add this to the pull request I submitted.

**Comment by ANGSD** [comment]
ahh ok, well there are two programs in the misc folder that should be
compiled together with 'angsd' and should be part of the install process.
That is the 'thetastat' and the 'realSFS', the rest in the misc folder
could be part of an optional make misc.

Thanks for these helpfull suggestions.

Best



2018-07-25 17:40 GMT+02:00 ♫ Christian Krause ♫ <notifications@github.com>:
