### ISSUE TITLE
doFasta when the reference fasta missed in the disk

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#172]
Hi @ANGSD 

During running -doFasta 2, I found I have moved my reference to another directory. So, the reference information will miss in the BAM header (ANGSD can not find the reference fasta file). I do not know whether this will affect the results.  Many thanks.

Best
Zhuqing

**Comment by biozzq** [comment]
Hi @fgvieira @ANGSD 

I found the results are ok, that is all the sequences have the same length with the corresponding reference chromosome. I also want to understand how `doFasta` handles the indels? 

Hope for your help.

Best
Zhuqing

**Comment by fgvieira** [comment]
Dear Zhuqing,

Glad to know it worked.
As for indels, ANGSD currently ignores all of them so you will always get a fasta file with the same number of chromosomes and lengths as your reference genome.

cheers,

**Comment by biozzq** [comment]
Dear @fgvieira  @ANGSD 

I found the number of chromosomes is different from the reference genome. The missed are all scaffolds  that cannot be anchored on chromosomes.  When I only try with the missed scaffolds (with -r parameter), the log just tell me no sites are retained.  Is this usual?
	-> Total number of sites analyzed: 0
	-> Number of sites retained after filetering: 0

Best
Zhuqing

**Comment by fgvieira** [comment]
Dear Zhuqing,

By "scaffolds that cannot be anchored on chromosomes", are you referring to small contigs/scaffolds?
If so, can you check if you have any reads mapping to them?

Also, can you send me the full command line you used?

**Comment by biozzq** [comment]
Dear @fgvieira 

Yes, they are small contigs/scaffolds. I have checked with `samtools tview`, and can find mapped reads on them.

the command 
`/bin/angsd-master/angsd -i $bam -only_proper_pairs 1 -uniqueOnly 1 -remove_bads 1 -nThreads 5 -minQ 20 -minMapQ 30 -doFasta 2 -basesPerLine 100 -doCounts 1 -out $out`

Best
Zhuqing

**Comment by fgvieira** [comment]
Hmm the it is weird...
@ANGSD did you change anything on the doFasta recently?

**Comment by ANGSD** [comment]
Was this resolved?
YOu can validate that angsd finds data using -show 1.

**Comment by ANGSD** [comment]
Ok, im assuming this got issue can be solved otherwise feel free to reopen.

Best
