### ISSUE TITLE
fst print output

### ISSUE THREAD

**Issue by NicolaKriefall** [ANGSD/angsd#173]
Hello,

When I execut the following command:
realSFS fst print p01.fst.idx > p01.fst

The output document looks like this:
chr0 8215 0.000000 0.000009
chr0 8216 0.000000 0.000009
chr0 8217 0.000000 0.000009
chr0 8218 0.000000 0.000009
chr0 8219 0.000000 0.000009
chr0 8220 0.000000 0.000009
chr0 8221 0.000000 0.000009
chr0 8222 0.000000 0.000009
chr0 8223 0.000000 0.000009
chr0 8224 0.000000 0.000009

What are the headings exactly?

Best,
Nicola

**Comment by NicolaKriefall** [comment]
More specifically:

I sequenced my data on two different sequencing platforms (HiSeq 2500 & HiSeq 4000). Unfortunately now my data shows SNP variants that are specific to the two sequencers while the data shouldn't, in theory, be structured that way. I defined the two sequencing runs as 2 "populations" and am trying to use ANGSD & RealSFS to find these SNP variant outliers that are sequencer-specific, so that later I can remove them from my analysis. Have you encountered any use of ANGSD for this before? 

So I used the command outlined on this website:

http://www.popgen.dk/angsd/index.php/Fst#realSFS_fst_print

The command I used was (from the above link):
./realSFS fst print pop1.pop2.fst.idx

The output from the command does not have headings at the top of the 4 columns that are generated, but instead look like this: (this is just the beginning of the output):

chr0 8215 0.000000 0.000009
chr0 8216 0.000000 0.000009
chr0 8217 0.000000 0.000009
chr0 8218 0.000000 0.000009
chr0 8219 0.000000 0.000009
chr0 8220 0.000000 0.000009
chr0 8221 0.000000 0.000009
chr0 8222 0.000000 0.000009
chr0 8223 0.000000 0.000009
chr0 8224 0.000000 0.000009

The website also says in explanation for "RealSFS fst print":
"The weighted fst for a region is the ratio between the sum of As and the sum of B. The unweighted is the mean of the persite ratios.
A is the alpha from the reynolds 1983 (or Bhatia) and B is the alpha + beta."

I am looking specifically for the unweighted & weighted Fst values at each SNP variant, so that I can find the SNP variant outliers that are causing my data to identify the two sequencers as two populations, and am unclear how to calculate this from the given output & given explanation.

Thank you,
Nicola

**Comment by ANGSD** [comment]
Sorry for the delay. Are the rest of the output from fst print just a repeat of the first lines?

**Comment by NicolaKriefall** [comment]
That's correct

**Comment by ANGSD** [comment]
Dear Nicola sorry for the delay it got lost in the stack of other projects.
It looks like the prior is dominating the estimates, is this an issue of very little data and coverage?

Best

**Comment by ANGSD** [comment]
Im assuming this got resolved, im closing this issue.

Best
