### ISSUE TITLE
-> Debug message: Problems at position:

### ISSUE THREAD

**Issue by Murukarthick** [ANGSD/angsd#175]
Hi
I have called SNPs using ANGSD with scattered regions and resulted in vcf format. below my command for SNP calling,

find $rfDir | grep 'rf' | parallel --will-cite -j 40 $angsd -bam $cramList \
-dovcf 1 -gl 1 -dopost 1 -postCutOff 0.95 -domajorminor 1 \
-domaf 1 -snp_pval 1e-6 -doGeno 21 -rf '{}' -out '{/.}' \
-remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 -C 50 -baq 1 \
-ref $ref -minMapQ 20 -minQ 20 &> angsd.log

It works. After SNP calling, I used this vcf file for downstream analysis lik SFS,

$angsd -P 30 -vcf-gl 0000-scattered.vcf -fai $fai -nind 3 -anc $ANC -doSaf 1 -doMajorMinor 1 -out test_gl

-> angsd version: 0.921-11-g20b0655 (htslib: 1.8-37-gcaed43e) build(Jul  3 2018 09:43:52)
input_vcf
        -> BETA when using vcf-gl make sure that you use -doMajorMinor 1  -> VCF still beta. Remember that
           1. indels and sites that are non diallelic are discarded
           2. will use chrom, pos, ref, alt columns
           3. GL tags are interpreted as log10 and are scaled to ln
           4. GP tags are interpreted directly as unscaled post probs (spec says phredscaled...)
           5. FILTER column is currently NOT used (not sure what concensus is)
        -> Reading fasta: /data/Pb_angsd_anc.fa
        -> Debug message: Problems at position: 85154

Although the VCF file was produced by ANGSD I still get error.

**Comment by ANGSD** [comment]
Dear Murukarthick. Could I get a copy of the problematic vcf?

Best

**Comment by Murukarthick** [comment]
Hi
thanks for the reply. Here I attached one specific region vcf file.

Regards,

 0000-scattered.vcf.gz
<https://drive.google.com/file/d/1rP2DGoqtQQeCebCVd6lL9HtuAduhmN2v/view?usp=drive_web>

**Comment by huangl07** [comment]
is  this the problem solved？

**Comment by Murukarthick** [comment]
Hi
I have tried different options with different settings. It did not work. If
you have solution please let me know. thank you.

Cheers,

**Comment by ANGSD** [comment]
Dear @Murukarthick Ive just pushed a new commit of angsd that has a new filereading of vcf-gl, hopefully that should fix any filereading issue.
In a more general context there is no need to make a vcf for calculating the sample allele frequencies along wiht the sfs based statistics,  i would recommend to do it from the bam/cram files.

Im closing the issue, feel free to reopen if needed.

Best
