### ISSUE TITLE
Soft-clipped bases and diversity estimates

### ISSUE THREAD

**Issue by mlucenaperez** [ANGSD/angsd#179]
Dear developers,

Are soft-clipped bases considered in ANGSD?

Best,

María.

**Comment by ANGSD** [comment]
the  softclip bases are not used in the analyses.

Den fre. 24. aug. 2018 kl. 14.51 skrev Maria Lucena Perez <
notifications@github.com>:

**Comment by ANGSD** [comment]
Ill close this issue, feel free to reopen if needed.
