### ISSUE TITLE
nSites option and estimating thetas

### ISSUE THREAD

**Issue by josieparis** [ANGSD/angsd#180]
Hi guys, 

I have been generating my sfs using -nSites 150000000, which means I get multiple lines of output.

Can you inform on what is best to do with the multiple-lined sfs output when 

a) estimating thetas and neutrality stats 
b) using the sfs for demographic inference

Do I take the mean of the columns for a) and the sum of the columns for b)?

Thanks for your help,

josie

**Comment by ANGSD** [comment]
Dear Josie, it is better to include as many sites as possible for estimating the global SFS. It depends on the sequencing depth and number of individuals what the exact value should be. I would barplot the different values side by side and visually inspect that they are not too different between the different regions. Internally the sfs is normalized to sum to one.

**Comment by ANGSD** [comment]
Dear Josie, im closing this issue feel free to reopen if needed.

Best
