### ISSUE TITLE
Negative IBS value

### ISSUE THREAD

**Issue by MickWest1** [ANGSD/angsd#182]
Dear ANGSD users.

When running the -doIBS 2 on 2 individuals with the following parameters:
angsd -doIBS 2 -makeMatrix 1 -nThreads 10 -doCounts 1 -uniqueOnly 1 -doMajorMinor 1 -minInd 2 -GL 1 -setMinDepthInd 10 -minmapq 25 -minq 25 -b bamlist.txt -ref ref.fa -out outfile 
I have been getting a negative value. I rerun the same analysis when mapping to a different reference and it was positive. I have also rerun both analyses (1 analysis per reference) in a sliding window fashion and the results were also positive.
All analyses gave a very similar pairwise difference (~0.0056) apart from the one that resulted in a negative (-0.0064). I was hoping to just remove the negative sign but as it is so different I was thinking that there must be something not right.
Any help would be greatly appreciated.
Mick

**Comment by aalbrechtsen** [comment]
Hi Mick

I assume that you are looking at the outfile.ibsMat file?
If this is the case then observing a negative value is indeed odd.  
I cannot replicate the error but I have added an assert statement in the code so that the problem will check for negative counts of similar alleles. If negative values are found in any part of the genome then the program will exit with an error statement. 
If you clone a new version of angst the change is implemented. 

- Anders

**Comment by MickWest1** [comment]
Hi Anders,

Thanks for the reply. Yes indeed odd. I cloned the new version and reran the analysis. The ibsMat still has a negative value. The actual .ibs file also has some -1 values. Is that normal or could that be the problem?

Thanks,
Mick

**Comment by aalbrechtsen** [comment]
If you use the option -output01 1 then, in the .ibs file, -1 means missing data i.e. no unfiltered reads at that position. 
I am unable to re-create your problem. 

Could to try to run it with -doIBS 1 instead of the consensus base so that I can see if the problem lies there?


-Anders

**Comment by MickWest1** [comment]
Hi Anders,

Sorry it took so long, the server has been down. I reran the analysis with doIBS 1 and it still gave a negative result... I don't specify output01 which is guess it means it does -output01 1 by default?

Thanks,
Mick

**Comment by MickWest1** [comment]
Hi Anders,

I was doing the same IBS with some other species/bam files, and ran into the same problem. I then looked into the ibs.gz file and counted the number of lines where species 1 was different from species 2 then divided that by the total number of sites used. The value was 0.0192 as opposed to the -0.0218. The values are very close but I guess there may a bug or be something in the software when producing the ibsMat file? Not sure if that helps at all.

Thanks,
Mick

**Comment by ANGSD** [comment]
Was this resolved?
@aalbrechtsen ?

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed.

Best

**Comment by elishempel** [comment]
Dear ANGSD users,
I ran into the same issue as MickWest1 above. My command was 
`angsd -nThreads 20 -doIBS 2 -doCounts 1 -makeMatrix 1 -minMapQ 20 -minQ 20 -rf list_only_autosomes -b bamlist -out outfile -minInd 2`

I tried also the newest angsd version, but the result is still negative.

Do you know what could be causing this and how this could be solved? 

Thank you!
Elis
