### ISSUE TITLE
Question about scaling of genotype likelihoods

### ISSUE THREAD

**Issue by gwct** [ANGSD/angsd#183]
Hi,
I'm developing a method that requires calculation of likelihoods for all 10 genotypes. I'm grateful to find that your software does this already with several methods and outputs all 10 scores! So thank you for that!

I just had a question about the scaling of the likelihoods in the output file. For -doGlf 1 or -doGlf 4, the wiki page (http://www.popgen.dk/angsd/index.php/Genotype_Likelihoods) says that these are "log genotype likelihoods". Is this just a simple log base 10 transform or natural log? On the same page, under the Binary heading, it also states that, "These are log scaled likelihood ratios to the most likely. " Does this mean you have normalized them somehow? If so, how? I need the raw likelihood calculations for my method, so if I know how you have transformed and scaled these calculations, I should be able to go backwards from there.

Thank you!
-Gregg Thomas

**Comment by ANGSD** [comment]
Dear Greg sorry for the delayed reply. No non of the current gl models use the mapping quality. Im closing this issue, feel free to reopen if needed.
