### ISSUE TITLE
The BAM list includes both SE and PE data

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#186]
Dear @ANGSD ,

All my samples are sequenced using pair-end (PE). I also combined some published data which was generated using single-end (SE). When I call variants on cohorts of samples, if I want to using the reads that are properly mapped in PE samples and uniquely mapped in SE samples, how can I set the parameters to take these into account? If I set "-only_proper_pairs 1 -uniqueOnly 1", the SE samples will all be missing. If I only set "-uniqueOnly 1", I do not know the effect on the PE samples. Many thanks.

Sincerely,
Zhuqing

**Comment by ANGSD** [comment]
Dear biozzq, it only does the -only_proper_pairs if it is a paired in read. Let me know if this is not the observed behavior. 
https://github.com/ANGSD/angsd/blob/master/pop1_read.cpp#L132

Im closing this issue, but feel free to reopen if needed.

Best
