### ISSUE TITLE
More details about the output from -doMisMatch

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#187]
Dear @ANGSD ,

Recently, I want to statistic the landscape of the mismatch from the BAM file. After getting the results, I found it is difficult for me to extract the useful information because of the limited description of the format of the results (http://www.popgen.dk/angsd/index.php/Mismatch), such as, which number (0 or 1) represents the plus strand. Thank you.

Sincerely,
Zhuqing

**Comment by ANGSD** [comment]
Dear @biozzq sorry for the very much delayed reply. I have updated the wiki, and are closing this issue.
