### ISSUE TITLE
multi-SFS problem with realSFS: please discard non-overlapping sites!

### ISSUE THREAD

**Issue by z0on** [ANGSD/angsd#188]
Hi Thorfinn - I am resurrecting this old issue since it seems to be a pervasive realSFS problem, likely to affect everyone who is doing low-coverage sequencing and especially RAD-like stuff. We often have sites that are genotyped in one population, but not in the other. I have a strong impression that realSFS, when calculating multi-sfs, does not simply discard such sites but counts them towards private alleles (in the population in which they are genotyped). I cannot think of a situation where such a behavior would be reasonable - please do tell me what am I missing. This must be a super-easy fix for you! 
cheers
Misha

**Comment by ANGSD** [comment]
Dear z0on realSFS discards sites that doesnt not exists in every population. At least this is what it is supposed to do. If you have some data where this is not the observed behavior please let me know.

Best

**Comment by z0on** [comment]
I am glad that you agree that it should be happening! But I think it does not. Here are two 2dSFS plots, one straight after doing per-population saf and then realSFS, and another using pre-selected sites (using custom script) that are genotyped in both populations. You might not have noticed this behavior since typical WGS data do not often suffer from systematically missing sites in one population compared to another, but RAD has this issue quite often.  
[2dAFS_c24f_dadi.data_pop0_pop1_56_65.pdf] (https://github.com/ANGSD/angsd/files/2589979/2dAFS_c24f_dadi.data_pop0_pop1_56_65.pdf)
[2dAFS_c24_dadi.data_pop0_pop1_56_65.pdf](https://github.com/ANGSD/angsd/files/2589982/2dAFS_c24_dadi.data_pop0_pop1_56_65.pdf)

**Comment by ANGSD** [comment]
Dear z0on, if you do 
realSFS print pop1.saf.idx pop2.saf.idx it printout the sites that exists in both populations, these are the ones that are used for the optimisation. I would not interpret the plots as one of them having an excess of private variation compared to the other plot. It looks more like you are loosing variation that is common to both pops. You can also check the perpopulation safs.
realSFS print pop1.saf.idx
and
realSFS print pop2.saf.idx

**Comment by z0on** [comment]
Maybe it only happens with "realSFS dadi" command?..

**Comment by z0on** [comment]
Actually this is the proper pair of SFS plots to compare. First one is with pre-filtered sites, another generated straight up, using "realSFS dadi" command.
[2dAFS_c24_dadi.data_pop0_pop1_56_65.pdf](https://github.com/ANGSD/angsd/files/2590529/2dAFS_c24_dadi.data_pop0_pop1_56_65.pdf)
[2dAFS_c24s_dadi.data_pop0_pop1_56_65.pdf](https://github.com/ANGSD/angsd/files/2590530/2dAFS_c24s_dadi.data_pop0_pop1_56_65.pdf)

**Comment by z0on** [comment]
...to reiterate why I am such a fan of 'realSFS dadi' option: it allows me to use the super-fast and easy built-in bootstrap function in Simon Gravel's Moments, https://bitbucket.org/simongravel/moments

**Comment by z0on** [comment]
..and this is how it looks using -sites produced with 'realSFS print pop1.saf.idx pop2.saf.idx '. I believe this is how it is *supposed* to look when running 'realSFS dadi' straight up 
(interestingly it is a bit different from mine, has a few more shared allelels):
[2dAFS_c24sc_dadi.data_pop0_pop1_56_65.pdf](https://github.com/ANGSD/angsd/files/2591252/2dAFS_c24sc_dadi.data_pop0_pop1_56_65.pdf)

**Comment by ANGSD** [comment]
Dear z0on I just checked with these commands:
seq 1 3 >rg1
seq 2 4 >rg2
./angsd -b pop1.list -rf rg1 -dosaf 1 -gl 1 -anc ../hs37d5.fa -out pop1
./angsd -b pop2.list -rf rg2 -dosaf 1 -gl 1 -anc ../hs37d5.fa -out pop2
 ./misc/realSFS pop1.saf.idx >pop1.sfs
./misc/realSFS pop2.saf.idx >pop2.sfs
./misc/realSFS dadi pop1.saf.idx pop2.saf.idx  -sfs pop1.sfs -sfs pop2.sfs -ref ../hs37d5.fa -anc ../hs37d5.fa|cut -f3|uniq -c

outputs
    272 2
    214 3

So if there was an issue it should be fixed now. There was a problem with the fst index procedure reusing scaffolds if either population was missing a scaffold but that is also solved.

Im closing this issue, but feel free to reopen if needed.

BEst
