### ISSUE TITLE
Segfault when using doMaf -1

### ISSUE THREAD

**Issue by fgvieira** [ANGSD/angsd#19]
I get a segfault when using -doMaf -1 on:

./angsd -glf testF.glf.gz -fai testAF.ANC.fai -nInd 20 -doMajorMinor 1 -doGlf 2 -doMaf -1 -SNP_pval 1e-4 -out testF

thanks,

**Comment by ANGSD** [comment]
I think I'll remove the option to use negative values for the parameters.
