### ISSUE TITLE
segmentation fault (core dumped) with -dovcf

### ISSUE THREAD

**Issue by kakapocy** [ANGSD/angsd#191]
Hi,

We tried running the following and it worked with a mafs output file:
angsd -domaf 2 -gl 2 -doMajorMinor 1 -bam (input).bam.filelist -out (output) -snp_pval 1e-6 -dopost 1

However, when we ran the same line with -dovcf 1, we got the segmentation fault issue. We are running with angsd version 0.922 (htslib: 1.9).

Hope you can help us with this problem. Or are there other tools to convert mafs file to vcf file type?

**Comment by yzongzjnu** [comment]
I encountered the same problem when -dovcf. All the command was following official instructions but got a  core dump without any error report. Did you fix that? Would you mind sharing how to solve the problem?
