### ISSUE TITLE
Error opening fai FILE handle 

### ISSUE THREAD

**Issue by hans-recknagel** [ANGSD/angsd#193]
Hi,
I am trying to run an association test using a vcf file with genotype likelihoods (see command below). The vcf file was generated using a reference genome. The reference genome was indexed with samtools faidx.

/export/home/2060771r/apps/angsd/angsd -vcf-gl Zootoca_WGS_admixture_GL.vcf.gz -fai JM_LG19_L1_aftersplit.fasta.fai -nInd 65 -yQuant inc_days.txt -doAsso 2 -doPost 1 -out inc_days_association.txt -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 -P 6 -r 1:

However, I get an error message suggesting there is something wrong with my fai file:

-> Error opening FILE handle for file:JM_LG19_L1_aftersplit.fasta.fai exiting

I repeated the indexing step, but still get the same error message. Do you have any suggestion what is causing the problem?

Thanks for your help,
Hans

**Comment by ANGSD** [comment]
Dear Hans, could you doublecheck that the file exists?
ls -lh M_LG19_L1_aftersplit.fasta.fai 

Best

**Comment by hans-recknagel** [comment]
Thanks for your help. The file JM_LG19_L1_aftersplit.fasta.fai does exist (M_LG19_L1_aftersplit.fasta.fai doesn't, but I assume the missing J is a typo?).
-rwxrwx--- 1 aay2c elmer 866K Jan 21 07:55 JM_LG19_L1_aftersplit.fasta.fai
I am trying to set up the analysis on a high-performance computing cluster.
Thanks,
Hans

**Comment by ANGSD** [comment]
Dear Hans, Ive just finalized a new vcf reader in ansd, based on the
excellent htslib. See if that helps otherwise write back.

Best

Den ons. 30. jan. 2019 kl. 05.29 skrev hans-recknagel <
notifications@github.com>:

**Comment by ANGSD** [comment]
Dear Hans I was going over the issues ones more and I can see that you were trying to use the -r 1 iterator in the older version which didnt work. The newer version of angsd reads bcf files and allows for  random lookup with bcf.

Im therefore closing this issue, but feel free to reopen if needed.

**Comment by hans-recknagel** [comment]
Hi,
I downloaded the new version and tried to run the command, but it failed again. I tried both vcf and bcf. The -r option did not work in any of the two cases either. If I do not use -r option I still get an error about the likelihood scores. The errors with bcf and vcf files are the same, I am just posting the bcf error with and without -r option here

1) bcf file with -r 1: option
 /Applications/angsd/angsd -vcf-gl Zootoca_WGS_admixture_GL_sorted.bcf.gz -fai JM_LG19_L1_aftersplit.fasta.fai -nInd 65 -yQuant inc_days.txt -doAsso 2 -GL 2 -doPost 1 -out inc_days_out.txt -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 -P 5 -r 1:
	-> angsd version: 0.929-13-gb5c4df3 (htslib: 1.9-121-g0a2cf81) build(Mar  4 2019 05:16:12)
[parseArgs_bambi.cpp.parse_region():55] (-r) Problems finding chromosome: '1' from header
[setArgsBam] Problems with indexing: 1

2) bcf file without -r option
 /Applications/angsd/angsd -vcf-gl Zootoca_WGS_admixture_GL_sorted.bcf.gz -fai JM_LG19_L1_aftersplit.fasta.fai -nInd 65 -yQuant inc_days.txt -doAsso 2 -GL 2 -doPost 1 -out inc_days_out.txt -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 -P 5
	-> angsd version: 0.929-13-gb5c4df3 (htslib: 1.9-121-g0a2cf81) build(Mar  4 2019 05:16:12)
	-> VCF still beta. Remember that
	   1. indels are are discarded
	   2. will use chrom, pos PL columns
	   3. GL tags are interpreted as log10 and are scaled to ln (NOT USED)
	   4. GP tags are interpreted directly as unscaled post probs (spec says phredscaled...) (NOT USED)
	   5. FILTER column is currently NOT used (not sure what concensus is)
	   6. -sites does NOT work with vcf input but -r does
	   7. vcffilereading is still BETA, please report strange behaviour
Can't calculate genotype likelihoods from -glf/-glf3/VCF files

Thanks for your help and advice,
Hans

**Comment by ANGSD** [comment]
Dear Hans, the output looks like the old version, can you do a make
clean;make and ensure it is the most recent version.

Best

Den man. 4. mar. 2019 kl. 08.04 skrev hans-recknagel <
notifications@github.com>:

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed.

Best

**Comment by hans-recknagel** [comment]
Thanks for your help. I have done a make clean of angsd and htslib, removed both folders and reisntalled angsd and htslib using the suggested
git clone https://github.com/samtools/htslib.git;
git clone https://github.com/angsd/angsd.git;
cd htslib;make;cd ../angsd;make HTSSRC=../htslib

I still get the same error with the following version comment:
angsd version: 0.929-13-gb5c4df3 (htslib: 1.9-123-g21f8c6e) build(Mar 11 2019 11:10:32)

I thought that 0.929 is the latest version?

**Comment by Jungal10** [comment]
Hello. 
I am finding the same issue while trying to run with a list of bam files:
 
Command:
```
~/angsd/angsd -bam /home/jgoncal1/projects/snp_polar/scripts/batch_submissions/bam.filelist \
-dohaplocall 1 -doCounts 1 -r 1: -minMinor 1 \
-out projects/snp_polar/data/output/snp_calling/haploid_angsd_list
```
bam.filelist:
```
/home/jgoncal1/projects/snp_polar/data/output/previous_tests/alignemnts/bv_ah_sorted.bam
/home/jgoncal1/projects/snp_polar/data/output/previous_tests/alignemnts/sorted_spinach.bam
/home/jgoncal1/projects/snp_polar/data/output/previous_tests/alignemnts/sorted_at_ah.bam

```
Output:
```
	-> angsd version: 0.931 (htslib: 1.9-298-ga840aa8) build(Aug 26 2019 22:21:27)
 [parseArgs_bambi.cpp.parse_region():55] (-r) Problems finding chromosome: '1' from header
```

I have installed yesterday, with the corresponding htslib, so it is the most updated version. Any suggestions where the problem might come from?

Thank you
