### ISSUE TITLE
problems with estAvgError.R

### ISSUE THREAD

**Issue by kritikamgarg** [ANGSD/angsd#202]
Hi All,

I am using ANGSD to perform multipop ABBA-BABA test.

I was able to run -doAbbababa2 but have issues when I run estAvgError.R R script.

I get the following error

"Error in file(file, "rt") : cannot open the connection
Calls: unlist -> read.table -> file
Execution halted"

I am not sure how to resolve this issue. 

Thank you very much for your help.
Regards
Kritika

**Comment by SamueleSoraggi** [comment]
Hi,
could you help me and post the command you use to run the script? It seems you use the wrong file name as input

**Comment by kritikamgarg** [comment]
Hi,

Thank you for a quick reply.
So my input file is called "fresh.Angsd.abbababa2", the size file is called "size_file_fresh.size", the population file "popNames.name" and the error file is called "errorList.error"

All files are in the same folder as the R script and command I have run is

Rscript estAvgError.R angsdFile="fresh.Angsd" out="result" sizeFile=sizeFile.size errFile=errorList.error nameFile=popNames.name

Thank you for the help.

Best Regards
Kritika

**Comment by SamueleSoraggi** [comment]
Isn't this file `size_file_fresh.size` named differently from the one you give in input?

**Comment by kritikamgarg** [comment]
Thank you for spotting the error. I was able to run Rscript.

Regards
Kritika

**Comment by ANGSD** [comment]
Thanks Samuele. Much appreciated.
