### ISSUE TITLE
Fst values for Manhattan plot

### ISSUE THREAD

**Issue by qiaole1311** [ANGSD/angsd#204]
Hi, I want to make use of the FST values generated by realSFS to build a manhattan plot. The output file had an idx extention (filename.idx) and other than printing the values into another text file, I have not been able to find another way to open or read it legibly. 

I won't be able to use the text file as it is way too big (approx 20 GB). Is there any way around this? 
In other words making use of the idx file to build a plot in Rstudio. 

Thank you!

**Comment by ANGSD** [comment]
Im not sure I follow you can printout the fst values with realSFS fst print.

That should print out the binary files in a nice textfriendly version.
Feel free to reopen if this doesnt answer your question.

Best

**Comment by qiaole1311** [comment]
Hi, what I'm asking is if I can use the idx file directly for other programs (such as in Rstudio for Manhattan plot)? 

I am able to print the values out into a text file, but the text file size is very big and will take very long to process it.

**Comment by ANGSD** [comment]
The idx file simply contains the binary offset to a location within the compressed files, therefore the idx does not contain any values regarding your fst value. I would suggest you do a window based fst analysis so you dont have to printout the value for every site.

Best

**Comment by ANGSD** [comment]
There is some information about how to do sliding window analysis with regards to the fst stat here:
http://www.popgen.dk/angsd/index.php/Fst#Sliding_Window_output

Im closing this issue, feel free to reopen if needed.

**Comment by yzongzjnu** [comment]
By saying your Fst file up to 20GB, I think what you were trying to use is the binary Fst file. Following the instruction here http://www.popgen.dk/angsd/index.php/Fst#Sliding_Window_output, I suggest you to perform Fst calculation with sliding windows and then draw Fst Manhattan plot using gg.manhattan https://github.com/pcgoddard/Burchardlab_Tutorials/wiki/GGplot2-Manhattan-Plot-Function.
