### ISSUE TITLE
Cannot generate .ml file with same code that has worked succesfully

### ISSUE THREAD

**Issue by aguilar-gomez** [ANGSD/angsd#207]
I have been using this code: 
pop1=$1
pop2=$2
name=$3
realSFS $pop1.saf.idx $pop2.saf.idx -P 6 >$pop1.$pop2.ml
Which has successfully generated the ml file. I have three populations. I made all the possible combinations:
pop1.pop2, pop1.pop3,pop2.pop3 
and they worked out. 
Later I made a new saf file that was successfully created by using the bamfiles of two populations:
pop4=pop1+pop2

Now I am trying to generate an ml file of pop4 and pop3 and I get an error, using the same code. The saf file for pop4 was generated without errors, it is not empty.  This is my error when I try to generate the pop3.pop4.ml :

lik[77]=-16951586.437467 diff=1.290228e+01 alpha:19.694887 sr2:1.208686e-12
lik[80]=-16951585.359974 diff=1.077493e+00 alpha:1.300446 sr2:7.725750e-12
	-> Breaking EM(sr2) at iter:81, sqrt(sr2):9.587326e-07
likelihood: -16951585.359974
------------
	-> Done reading data from chromosome will prepare next chromosome
	-> Only read nSites: 0 will therefore prepare next chromosome (or exit)

I do not understand what is happening or how to solve it.

**Comment by ANGSD** [comment]
The realSFS will only use the sites that are in common between the different saf files. Could you check which sites are in common between the two saf files.

You can extract the positions with realSFS print your.saf.idx

Best

**Comment by aguilar-gomez** [comment]
I cannot even run that:
realSFS print white.saf.idx
	-> Version of fname:white.saf.idx is:2
	-> Assuming .saf.gz file: white.saf.gz
	-> Assuming .saf.pos.gz: white.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fstout:(null) oldout:0 seed:1551761753 bootstrap:0 whichFst:0 fold:0 ref:(null) anc:(null)
	-> Will jump to multisaf printer and will only print intersecting sites between populations
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by aguilar-gomez** [comment]
I ran it and got sites, I still do not get the .ml file
 realSFS print white.saf.idx  HSK.saf.idx |head 
	-> Version of fname:white.saf.idx is:2
	-> Assuming .saf.gz file: white.saf.gz
	-> Assuming .saf.pos.gz: white.saf.pos.gz
	-> Version of fname:HSK.saf.idx is:2
	-> Assuming .saf.gz file: HSK.saf.gz
	-> Assuming .saf.pos.gz: HSK.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fstout:(null) oldout:0 seed:1552021776 bootstrap:0 whichFst:0 fold:0 ref:(null) anc:(null)
	-> Will jump to multisaf printer and will only print intersecting sites between populations
	-> dim(white.saf.idx):69
	-> dim(HSK.saf.idx):95
	-> Dimension of parameter space: 6555
	-> Done reading data from chromosome will prepare next chromosome
	-> Is in multi sfs, will now read data from chr:chr108564
	-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
	-> Sites to keep[chr108564] from pop0:	84
	-> Sites to keep[chr108564] from pop1:	84
	-> [readdata] lastread:84 posi:1528
	-> Comparing positions: 1 with 0 has:84
chr108564	1529	0.000000	-0.533762	-1.076646	-1.628975	-2.191089	-2.763348	-3.346132	-3.939843	-4.544909	-5.161782	-5.790943	-6.432904	-7.088209	-7.757440	-8.441218	-9.140209	-9.855126	-10.586735	-11.335859	-12.103389	-12.890284	-13.697586	-14.526424	-15.378029	-16.253744	-17.155037	-18.083525	-19.040987	-20.029394	-21.050928	-22.108032	-23.203438	-24.340227	-25.521889	-26.752403	-28.036345	-29.379002	-30.786558	-32.266315	-33.826988	-35.479130	-37.235729	-39.113056	-41.131969	-43.319874	-45.713764	-48.364738	-51.342785	-54.729408	-58.545868	-62.795906	-67.491516	-72.656334	-78.318047	-84.461250	-91.033800	-97.990663	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	0.000000	-0.474271	-0.954157	-1.439795	-1.931327	-2.428901	-2.932671	-3.442796	-3.959443	-4.482784	-5.012999	-5.550274	-6.094807	-6.646800	-7.206466	-7.774027	-8.349714	-8.933772	-9.526452	-10.128022	-10.738761	-11.358961	-11.988928	-12.628986	-13.279474	-13.940749	-14.613189	-15.297189	-15.993169	-16.701572	-17.422869	-18.157553	-18.906155	-19.669231	-20.447380	-21.241234	-22.051470	-22.878809	-23.724024	-24.587942	-25.471453	-26.375509	-27.301144	-28.249466	-29.221680	-30.219086	-31.243103	-32.295273	-33.377285	-34.490986	-35.638405	-36.821781	-38.043591	-39.306580	-40.613812	-41.968720	-43.375156	-44.837482	-46.360645	-47.950310	-49.612988	-51.356232	-53.188869	-55.121326	-57.166031	-59.338005	-61.655643	-64.141815	-66.825340	-69.742775	-72.939713	-76.468704	-80.379356	-84.722763	-89.558052	-94.930155	-100.794023	-inf	-inf	-inf-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf
chr108564	1673	-32.498806	-20.161062	-8.083600	-1.732955	-0.789543	-0.323966	-0.090498	0.000000	-0.008938	-0.092611	-0.235657	-0.427916	-0.662372	-0.934034	-1.239283	-1.575469	-1.940649	-2.333420	-2.752799	-3.198140	-3.669082	-4.165507	-4.687511	-5.235388	-5.809621	-6.410872	-7.039991	-7.698013	-8.386177	-9.105935	-9.858978	-10.647265	-11.473054	-12.338954	-13.247978	-14.203624	-15.209962	-16.271761	-17.394651	-18.585337	-19.851883	-21.204123	-22.654221	-24.217520	-25

**Comment by ANGSD** [comment]
How big are the saf* files, maybe it would be easier and faster if I got access to these so I can see invistigate the issue.

Best

**Comment by aguilar-gomez** [comment]
9.5 G for one population and 7.1 G for another. How can I send them to you?

**Comment by ANGSD** [comment]
You can upload the data here:
https://sid.erda.dk/wsgi-bin/ls.py?share_id=PsOCg1AVSY

But everybody with this link will have access to the data, which might not be acceptable for you.

Write me an email on this account tskorneliussen@snm.ku.dk, and I will supply you with a private link.

Best

**Comment by ANGSD** [comment]
Hi I reran the commands and they seem to work, if this is till an issue feel free to reopen.

Best

**Comment by sagitaninta** [comment]
This is also an issue I currently have... my .saf. files are not empty but when i run realSFS, the .ml file is empty.
