### ISSUE TITLE
-doAbbababa error when using -useLast

### ISSUE THREAD

**Issue by albinap** [ANGSD/angsd#211]
I am working with ancient and modern wgs sheep data. As an outgroup I have chosen a published Ovis orientalis genome which I have mapped to the sheep reference genome as there is not a reference genome available for Ovis orientalis.

I am trying to do Abbababa on my dataset see command
 angsd -bam bam.combinedfilelist_n51_outgrouplast -doAbbababa 1 -rmTrans 1 -blockSize 5000000 -doCounts 1 -out sheep -P 40 -printEmpty 0 -remove_bads 1 -useLast 1 -enhance 1

but get the error
Error: -doAbbababa needs an outgroup in fasta format (use -anc fastaFileName )

Since there is not a reference genome for my outgroup species I can't use the -anc flag right? Why is angsd not accepting the -useLast 1 flag? I have put Ovis orientalis last in the bam filelist I am using

**Comment by albinap** [comment]
Realized that I was using a very old version of angsd which was likely causing this issue. The process is working now

**Comment by ANGSD** [comment]
ok super im closing this issue then.

Best

Den ons. 27. mar. 2019 kl. 16.48 skrev Albína Hulda Pálsdóttir <
notifications@github.com>:
