### ISSUE TITLE
Problems compiling 0.929 version

### ISSUE THREAD

**Issue by arturomarin** [ANGSD/angsd#213]
I have the same problem when try compiling ANGSD with a local folder containing HTSlib and with system installation of HTSlib.

when compiling with a local folder containing HTSlib:

> [root@genocloud01 angsd-0.929]# make HTSSRC=/opt/samtools-1.9/htslib-1.9
> HTSSRC defined
> echo '#define ANGSD_VERSION "0.929"' > version.h
> cc -c  -I/opt/samtools-1.9/htslib-1.9 -O3   fet.c
> cc -MM -I/opt/samtools-1.9/htslib-1.9 -O3   fet.c >fet.d
> cc -c  -I/opt/samtools-1.9/htslib-1.9 -O3   pooled_alloc.c
> cc -MM -I/opt/samtools-1.9/htslib-1.9 -O3   pooled_alloc.c >pooled_alloc.d
> cc -c  -I/opt/samtools-1.9/htslib-1.9 -O3   sample.c
> cc -MM -I/opt/samtools-1.9/htslib-1.9 -O3   sample.c >sample.d
> cc -c  -I/opt/samtools-1.9/htslib-1.9 -O3   kprobaln.c
> cc -MM -I/opt/samtools-1.9/htslib-1.9 -O3   kprobaln.c >kprobaln.d
> cc -c  -I/opt/samtools-1.9/htslib-1.9 -O3   from_samtools.c
> cc -MM -I/opt/samtools-1.9/htslib-1.9 -O3   from_samtools.c >from_samtools.d
> cc -c  -I/opt/samtools-1.9/htslib-1.9 -O3   malloc_wrap.c
> cc -MM -I/opt/samtools-1.9/htslib-1.9 -O3   malloc_wrap.c >malloc_wrap.d
> g++ -c  -I/opt/samtools-1.9/htslib-1.9 -O3   makeReadPool.cpp
> g++ -MM -I/opt/samtools-1.9/htslib-1.9 -O3   makeReadPool.cpp >makeReadPool.d
> g++ -c  -I/opt/samtools-1.9/htslib-1.9 -O3   abcCounts.cpp
> g++ -MM -I/opt/samtools-1.9/htslib-1.9 -O3   abcCounts.cpp >abcCounts.d
> g++ -c  -I/opt/samtools-1.9/htslib-1.9 -O3   vcfReader.cpp
> vcfReader.cpp: In function ‘int vcf_format_tsk(const bcf_hdr_t*, const bcf1_t*)’:
> vcfReader.cpp:177:8: error: ‘errno’ was not declared in this scope
>         errno = EINVAL;
>         ^
> vcfReader.cpp:177:16: error: ‘EINVAL’ was not declared in this scope
>         errno = EINVAL;
>                 ^
> vcfReader.cpp: In function ‘int isindel(const bcf_hdr_t*, const bcf1_t*)’:
> vcfReader.cpp:233:2: error: ‘errno’ was not declared in this scope
>   errno = EINVAL;
>   ^
> vcfReader.cpp:233:10: error: ‘EINVAL’ was not declared in this scope
>   errno = EINVAL;
>           ^
> make: *** [vcfReader.o] Error 1
> 

and when compiling with system installation of HTSlib:

> [root@genocloud01 angsd-0.929]# make
> HTSSRC not defined, assuming systemwide installation
> g++ -c   -O3   vcfReader.cpp
> vcfReader.cpp: In function ‘int vcf_format_tsk(const bcf_hdr_t*, const bcf1_t*)’:
> vcfReader.cpp:177:8: error: ‘errno’ was not declared in this scope
>         errno = EINVAL;
>         ^
> vcfReader.cpp:177:16: error: ‘EINVAL’ was not declared in this scope
>         errno = EINVAL;
>                 ^
> vcfReader.cpp: In function ‘int isindel(const bcf_hdr_t*, const bcf1_t*)’:
> vcfReader.cpp:233:2: error: ‘errno’ was not declared in this scope
>   errno = EINVAL;
>   ^
> vcfReader.cpp:233:10: error: ‘EINVAL’ was not declared in this scope
>   errno = EINVAL;
>           ^
> make: *** [vcfReader.o] Error 1
> 
>

**Comment by ANGSD** [comment]
Which version are you using, this block of code should be macroet out in the newer versions.

**Comment by ANGSD** [comment]
Hi im closing this issue, feel free to reopen if needed.

Best
