### ISSUE TITLE
Loss of loci for which there are GLs between angsd versions 9.02 and 9.28

### ISSUE THREAD

**Issue by albinap** [ANGSD/angsd#216]
I realized I had been running an old version of angsd version: 0.902-59-g02028fe so I re-ran my analyses with the same flags but with angsd 0.928. When comparing the number of loci for which there are GLs I saw that I was loosing a lot of loci between versions (hundreds of thousands) when running the same analysis on the same samples. Is this normal? Was there a big change in the options between the versions which might explain this?
Below is my code for a run on 23 individuals with coverage 3-6,5x

angsd -GL 1 -bam $bam -doGlf 2 -doMajorMinor 1 -doMaf 1 -SNP_pval 2e-6 -minInd 11 -remove_bads 1 -uniqueOnly 1 -C 50 -only_proper_pairs 1 -baq 2 -checkBamHeaders 1 -P 40 -ref $REF -out

**Comment by ANGSD** [comment]
Dear albinap the 902 is a very old version and there has been many changes. It is not possible to say which option or commit that caused this. I would look at the sites that are removed in the newer version and see why they have been dropped.

Best

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed.

Best
Thorfinn
