### ISSUE TITLE
-baq definitions and settings

### ISSUE THREAD

**Issue by albinap** [ANGSD/angsd#217]
I have been using the -baq 2 setting for my analysis but after looking into various published papers using angsd and getting conflicting information I wanted to ask about the current definition of the -baq options and what is the current recommendation on its use. The data I have has been realigned around indels.

**Comment by ANGSD** [comment]
Hi @albinap sorry for not getting back to you. If i remember correctly -baq 1 only allows for downgrading the qscores, whereas -baq 2 will also allow them to be upgraded. It is not clear for me which option is the best or if baq should be avoided altogether. I think samtools does baq automaticly if you pass the reference. For some datasets i didnt see much of a difference, but for other datasets where the reference wasnt as curated as the human reference it was impossible to obtain a proper sfs without applying baq.

Hopefully this helps. Im closing this issue, feel free to reopen.
