### ISSUE TITLE
premature (?) exit when calculating 2dsfs

### ISSUE THREAD

**Issue by nerdbrained** [ANGSD/angsd#218]
Hola ANGSD - I have generated safs for 6 populations based on RADseq reads mapped to a draft genome, with a MAF filter of 0.05. I am trying to generate pairwise 2dsfs for each combination of populations using all of the available sites after filtering. This works for some combinations of populations but not for others. 

Here is what I think is happening based on output: many of the draft genome scaffolds are small, and the # of filtered sites for the saf can be in the single digits or zero. If the first scaffold analyzed has one or more sites for a given combination of populations everything works fine. The 2dsfs is calculated for all sites and it will bypass any scaffolds that don't have sites. If the first scaffold has 0 sites for both populations, though, the 2dsfs calculation stops and an empty .ml file is generated. This happens even though many of the other scaffolds have sites. I have confirmed this by running the 2dsfs for a specific large scaffold and all of the combinations of populations seem to work, even those that don't work using all sites.

So it seems like a combination of populations having 0 sites for one specific scaffold is preventing calculating of the 2dsfs - I am not sure though if this is working as intended / a known issue or if this is bad behavior. I can think of workarounds (removing small scaffolds) but wanted to check first to see if there was any other solution. I can provide the commands, logs, and/or input files if needed.

Thanks!

Brendan

**Comment by nerdbrained** [comment]
Update on this - I did use the workaround of filtering out smaller scaffolds in the draft genome and re-running alignments and saf/2dsfs calculations using this, after which every population pair did work... still wondering though if there is a way to use all of the data and whether quitting after first encountering a scaffold with no sites is intended.

**Comment by ANGSD** [comment]
Sorry this issue got to the bottom of the stack. Let me know if this is still relevant otherwise ill close the issue at some point.

Best

**Comment by ANGSD** [comment]
Dear nerdbrained, I am assuming this got resolved, so I am closing this issue, feel free to reopen if needed.

Best
Thorfinn
