### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by tristanpwdennis** [ANGSD/angsd#220]
Hi,

I am trying to install ANGSD on my Ubuntu machine.

Htslib seems to compile ok, but when I make in the angsd directory, I end up with ```Makefile:69: recipe for target 'angsd' failed```

When I clone htslib and angsd to my local machine (Mac OS X Mojave) it seems to compile just fine.

Please could I trouble you guys for some assistance? Thanks!

**Comment by ANGSD** [comment]
Could you supply the list of commands you have been using

**Comment by tristanpwdennis** [comment]
```git clone https://github.com/samtools/htslib.git
git clone https://github.com/ANGSD/angsd.git 
cd htslib;make;cd ../angsd ;make HTSSRC=../htslib```

**Comment by ANGSD** [comment]
Hi tristan, sorry for not getting back to you before. Im assuming that this issue has been resolved, so im closing this issue. If you still have problems compiling it feel free to reopen or start a new issue.

Best
