### ISSUE TITLE
Abbababa2 -sizeFile what should this file look like and how should it be ordered?

### ISSUE THREAD

**Issue by albinap** [ANGSD/angsd#221]
I am running Abbababa2 and have been trying to figure out -sizeFile 
what should this file look like and how should it be ordered?
If I have bam files from 51 samples and the outgroup as the last entry in the bamfilelist how do I structure the sizeFile?
In many cases there is one individual per population but in some cases I have multiple individuals per population but the order in my bamfilelist is not by population. Does that matter?

**Comment by SamueleSoraggi** [comment]
Hi!

The abbababa2 program reads your bamfilelist assuming individuals are
grouped in populations. So for example
sample1_population1.bam
sample2_population1.bam
sample1_population2.bam
sample2_population2.bam
sample3_population2.bam
sample1_population3.bam
...
...

and the corresponding sizeFile should contain the number of samples you
have in each population, e.g. referring to the sequence above:
2
3
1
...
...

meaning that you need first to have your bam files reordered in bamfilelist
:)

Cheers.



Den fre. 3. maj 2019 kl. 21.50 skrev Albína Hulda Pálsdóttir <
notifications@github.com>:
