### ISSUE TITLE
Chunk error 

### ISSUE THREAD

**Issue by ciselkemahli** [ANGSD/angsd#224]
Hello,

I have NGS data from 37 individuals. First, I tried to estimate inbreeding coefficients as suggested in ngsF program. After that, I tried to get SFS using glf files. My code is:

~/bin/angsd/angsd -glf bear.glf -anc $anc -fai $fai -out BTR -nind 37 -doMajorMinor 1 -doMaf 1 -doSaf 1 -P 10 -indF bear.indF
~/bin/angsd/misc/realSFS BTR.saf.idx -maxIter 100 -P 10 > BTR.sfs

At first step, I get the below error (error reading full chunk):

 -> angsd version: 0.929-13-gb5c4df3 (htslib: 1.9-123-g21f8c6e) build(Mar 12 2019 15:34:39)
        -> Reading fasta: 
        -> Printing at chr: scaffold1 pos:4951 chunknumber 100 contains 50 sites
        ................
        -> Printing at chr: scaffold1 pos:54951 chunknumber 1100 contains 50 sites

**[glfReader.cpp:fetch():34] Error reading full chunk: bytesRead:2072 expected:2960 will exit**

I check the glfReader.cpp from the codes, but I couldn't understand what can be the reasons for the error. Do you have any suggestions? I appreciate for any help! Thanks!

**Comment by ANGSD** [comment]
Hi ciselkemahli, it looks like the file is corrupt, i would suggest that you rerun, otherwise we can ask @fgvieira .

Sorry for my delayed response.

Best

**Comment by ANGSD** [comment]
Dear ciselkemahli, I am assuming this got resolved one way or another, so im closing this issue, feel free to reopen if needed.

Best
Thorfinn
