### ISSUE TITLE
sfs and 2dsfs are filled with nan, -dosaf outpu -inf, especially with some populations including many samples

### ISSUE THREAD

**Issue by clairemerot** [ANGSD/angsd#226]
Hello,
I'm sorry I am opening another issue (again!)... angsd is really a great tool and I am sorry to be coming constantly with little questions

I am trying to do saf and then obtain either sfs (for thetas) or 2dsfs. While this is working perfectly fine for some populations, with the two largest populations (>1000 bamfiles), I always run into troubles. 

The saf file (as shown by realSFS print file.saf.idx) include many (or sometimes only -inf values) and then the sfs or 2dsfs made with 
realSFS file.saf.idx output just nan.

Have you ever found this problem? Could it be because I am using the -fold option? or because of too many dimensions?
note that I use this command at teh beginning of the script ulimit -S -n 2048 to allow my serve to open more than 1024 bam files. 

Thanks a lot for your help!
Claire

ps: also I 'd like to point your attention that the problem with fst index going to LG1 when finding scaffold without overlapping snp is still going on (https://github.com/ANGSD/angsd/issues/200) . I solved it post-analysis by checking that fst max was lower than scaffold size - it happened only for a few very small scaffolds - but it might be more problematic for people with fragmented genomes.

**Comment by nspope** [comment]
This could be numeric underflow in the saf calculation, which can happen with large numbers of individuals. If any site has all `-inf` in all saf bins, this will result in division by zero in realSFS (& thus NaNs). Have you tried using the flag `-underFlowProtect 1` when running angsd with `-doSaf`?

Nate

**Comment by clairemerot** [comment]
Thanks a lot for your advice, I'm re-running with that option, we should know if it goes better within a few days!

**Comment by clairemerot** [comment]
So... it did not work better with underFlowProtect... :(
The saf file has not only -Inf on each line but also numbers. Yet, thetas is nan. I am re-running without the -fold option that may be deprecated and also adding the underFlowProtect in the -doThetas. Any suggestions about how to improve the output is more than welcomed!!
Thanks a lot
Claire

**Comment by clairemerot** [comment]
As an update, I finally managed to get actual numbers with the thetas function for many samples (no nan!!) by re-doing the saf without the -fold option and the -underFlowProtect option.
