### ISSUE TITLE
vcfReader error

### ISSUE THREAD

**Issue by Liangyy1902** [ANGSD/angsd#227]
Hi,
I have a vcf file and I'm getting an error while trying to use it in angsd:
The command I use is
angsd -vcf-gl  chr02.recode.vcf

And here is the error message:
#angsd: vcfReader.cpp:233: int isindel(const bcf_hdr_t*, const bcf1_t*): Assertion `hit!=-1' failed.

Thanks for your help

**Comment by ANGSD** [comment]
Which version of angsd are you using? The vcfparsing was updated within the
last few months.

Best

Den man. 27. maj 2019 kl. 06.06 skrev Liangyy1902 <notifications@github.com

**Comment by Liangyy1902** [comment]
Hi! Thanks for the quick response.
the version I use is:
 -> angsd version: 0.929-21-g4c6d001 (htslib: 1.9-159-g5c7ff9c) build(May 16 2019 00:49:59)
Is this version has any question? which version should I use?

Thanks for your help

**Comment by Liangyy1902** [comment]
And what I want to do is to calculate Tajima's D in angsd , but I only have the vcf file , what command should I use?
the command I use:
$ANGsd/angsd \
-vcf-gl chr02.recode.vcf.gz \    # not work as i have described above.
-doSaf 1 \
-anc Qrob_PM1N.fa \
-GL 1 \
-P 24 \
-out outFold
-fold 1

This is very important to me! 
 Thanks for your help

**Comment by ANGSD** [comment]
Dear @Liangyy1902 , sorry for not get back to you sooner. If this is still relevant could you provide me with the vcf and ill see if I can figure out what is wrong.

Best

**Comment by deboraycb** [comment]
Hi! 

I'm getting that same error when reading a vcf with version 0.930 (htslib: 1.9) and I wasn't getting it with version 0.921-8-gc12d2fa (htslib: 1.7-23-g9f9631d).

I'm attaching a subset of my vcf that reproduces this:
[popPEL_sorted_chr21_head.vcf.gz](https://github.com/ANGSD/angsd/files/3791764/popPEL_sorted_chr21_head.vcf.gz)

Thanks!

**Comment by nspope** [comment]
Hi,

If you add the appropriate INDEL definition to the header it should work, e.g.
```
INFO='##INFO=<ID=INDEL,Number=0,Type=Flag,Description=\"\">'

awk -v infohdr=$INFO '/^#CHROM/ {print infohdr"\n"$0} !/^#CHROM/' my.vcf >my.info.vcf

angsd -vcf-pl my.info.vcf ...
```
but note that this will then assume that everything is not an indel, and this could cause issues if there are actually indels (e.g. one of REF/ALT fields have more than one base).

Also, @deboraycb -- in your vcf the PL field is defined as a float, and angsd expects an integer. If angsd gives warnings like "BAD SITE <snip> return code -2 <snip>" then you need to modify your header by changing "Type" in the appropriate "FORMAT" definition. For example change
```
##FORMAT=<ID=PL,Number=3,Type=Float,Description="three Phred-scaled likelihoods for RR,RA,AA genotypes">
```
to
```
##FORMAT=<ID=PL,Number=3,Type=Integer,Description="three Phred-scaled likelihoods for RR,RA,AA genotypes">
```
Nate

**Comment by deboraycb** [comment]
Hi Nate, thank you for your help! I fixed the INDEL in the header and also the PL Type, and now I get this:

```
        -> Reading fasta: human_g1k_v37.fasta
[shared.cpp.changeChr():281] refid:12
Charnge chr:12
        -> Problem with length of fastafile vs length of chr in BAM header
        -> Chromosome name: '21' length from BAM header:2147483647 length from fai file:48129895
```
I have no idea where "'21' length from BAM header:2147483647" comes from

Here's what I ran:
```
angsd -vcf-gl popPEL_sorted_chr21_head.vcf.gz -doMajorMinor 1 -doMaf 1 -fai human_g1k_v37.fasta.bgz.fai -out TEST_popPEL_sorted_chr21_head -nind 50 -dosaf 1 -anc human_g1k_v37.fasta -nThreads 10
```

Here's the fixed vcf, and my fai file (gzipped just for the upload here): 
[popPEL_sorted_chr21_head.vcf.gz](https://github.com/ANGSD/angsd/files/3817661/popPEL_sorted_chr21_head.vcf.gz)
[human_g1k_v37.fasta.bgz.fai.gz](https://github.com/ANGSD/angsd/files/3817680/human_g1k_v37.fasta.bgz.fai.gz)

**Comment by ANGSD** [comment]
Dear All, I finally had time to check up on this. And I have modified the file reading for bcf/vcf. You know have to specify vcf-gl or vcf-pl depending on what you you are using. I am assuming that this resolved all the issues so I am closing this one. Feel free to reopen of submit a new issue.

Best
