### ISSUE TITLE
Individual names in output

### ISSUE THREAD

**Issue by tristanpwdennis** [ANGSD/angsd#228]
Hi,

Really enjoying using ANGSD so far (managed to get everything working). I am using it to generate .beagle files for NGSAdmix with one problem. All of my samples in the .beagle GL file are rendered as Ind01, Ind02, Ind03 etc. Is there any way I can get ANGSD to render my sample names as the names of the .bam files?

What order does the .beagle file end up in? If it is the order of the bams in filelist that I supplied, that would be fine too!

Many thanks for your help

**Comment by ANGSD** [comment]
yes same order as the bam/cram filelist.

Glad to hear you like the program

Best

**Comment by tristanpwdennis** [comment]
Great, thank you!
