### ISSUE TITLE
question on the input file

### ISSUE THREAD

**Issue by cityCoder** [ANGSD/angsd#23]
Hi,
Those days I came across ANGSD, it is a very great tool for population genetics study. I would like to know is it necessary to perform BQSR with the bam files before running ANGSD. 
Thanks very much!

**Comment by ANGSD** [comment]
It depends on the quality of the qscores for your samples. You can try enabling baq to see if that makes a difference.

**Comment by cityCoder** [comment]
Got it, one more question, when perform BQSR with GATK, it will produces indel quality scores in addition to the regular base qualities. They are stored in the BI and BD tags of the read records. I would like to know will ANGSD use such score. Such that I can decide discard this or not.

**Comment by ANGSD** [comment]
angsd does not use the BI and BD tag, currently it only uses the X0 tag in the aux part of the read. Indels are represented internally in the program but currently no analysis is actually utilising this information.

**Comment by cityCoder** [comment]
Great, thanks very much.
