### ISSUE TITLE
how to convert "realSFS print" output into probabilities?

### ISSUE THREAD

**Issue by ariloytynoja** [ANGSD/angsd#230]
Hi,
I'd like to compute SFS for a subset of sites but don't know how to convert the output of "realSFS print" into probabilities. 

I've tried running these commands:
`realSFS data.saf.idx > vec`
`realSFS print data.saf.idx > mat`
and then with R:
`d=read.table("mat")`
`e=apply(exp(d[,c(-1,-2)]),1,function(x){x/sum(x)})`
`write.table(t(colSums(t(e))),"vec2",col.names = F, row.names=F)`
but the files "vec" and "vec2" are not the same. 

Can you please explain how I should do it?
Regards, Ari

**Comment by ANGSD** [comment]
Dear ariloytynoja, the input are sample allele frequency likelihoods. Running realSFS data.saf.idx will read all the data into memory and will perform a maximum likelihood estimate of the sfs.
The R commands you are using calculates the persite estimates which will be very different and more noisy.

Best

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if I should elaborate.

Best
