### ISSUE TITLE
beagle genotype posteriors as input (-doSaf 4 and -beagle)

### ISSUE THREAD

**Issue by shannonekj** [ANGSD/angsd#231]
Hi all,

I would like to use doSaf 4 to generate a SFS, however when I use the following command:

`angsd -beagle file.beagle.gz -doSaf 4 -doGeno 32 -fai file.fai -anc file.fasta -out out -underFlowProtect 1 -fold 0`

I receive an error: **Must supply genotype likelihoods (-GL [INT])**

If I change my command to include -GL 2 I receive the following error: **Likelihoods can only be estimated based on BAM input and uppile input**

Additionally, if I try to include the original set of bam files using -bam I receive the same **Error: Likelihoods can only be estimated based on BAM input and uppile input* error.

"Error: Likelihoods can only be estimated based on BAM input and uppile input"

**Comment by ANGSD** [comment]
Hello Shannonkj, i dont think i have ever tried to use beagle as input for the saf stuff.
The -dosaf 4 assumes that the input files are genotype posteriours, is that what you have in your file.beagle.gz?

Best

**Comment by ANGSD** [comment]
Dear Shannonkj, I am closing this issue. Feel free to reopen or post a new issue.

Best

**Comment by beausoleilmo** [comment]
I have the same here, but in my Beagle file, it's genotype likelihoods. Would using imputation with Beagle 5.4 work to get the correct file format? I only found some information about posterior probabilities with Beagle 3.3 (https://faculty.washington.edu/browning/beagle/beagle_3.3.2_31Oct11.pdf) 

I have multiple populations in the Beagle file, so I'll impute and then separate the beagle file based on the IDs. Would that work?
