### ISSUE TITLE
help with estAvgError.R

### ISSUE THREAD

**Issue by kritikamgarg** [ANGSD/angsd#232]
Hi,
I have previously used estAvgError.R for my work. Now for a bigger data set when I run the Rscript estAvgError.R, I get the following error:

Estimating error matrix from file:
--- Building tree error matrices ---
  |:):):):):):):):):):):):):):):):):):):):)| 100%--- Time Spent  89.343  sec
Read 17784144 rows and 262 (of 262) columns from 39.281 GB file in 00:12:44

Error in FUN(newX[, i], ...) :
  long vectors not supported yet: memory.c:1668
Calls: getJackKnife -> apply -> FUN

Can you please suggest a possible solution.

Thank you

Regards
Kritika

**Comment by aalbrechtsen** [comment]
Hi Kritika

Seems like the input file is very large. 

Can you provide the command your are using and specify you input file ( is it a *.ancError file ? ). 

-Anders

**Comment by kritikamgarg** [comment]
Hi Anders,

Thank you for the followup. I think it was an issue with the version of R. I have upgraded R to 3.4 and it is working as of now. The R script is still running. If I run into new errors, I will post here.

Thank you once again.

Kritika

**Comment by ANGSD** [comment]
Ok sounds good, ill close the issue. Feel free to reopen if needed.
