### ISSUE TITLE
compiling error the latest 0.929 version

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#237]
Dear all,
When i complied the latest angsd with the local directory containing htslib, the following errors occurred. Hope someone can help me.

make HTSSRC=/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9
HTSSRC defined
echo '#define ANGSD_VERSION "0.929"' > version.h
cc -c  -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   fet.c
cc -MM -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   fet.c >fet.d
cc -c  -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   from_samtools.c
cc -MM -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   from_samtools.c >from_samtools.d
cc -c  -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   kprobaln.c
cc -MM -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   kprobaln.c >kprobaln.d
cc -c  -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   malloc_wrap.c
cc -MM -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   malloc_wrap.c >malloc_wrap.d
cc -c  -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   pooled_alloc.c
cc -MM -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   pooled_alloc.c >pooled_alloc.d
cc -c  -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   sample.c
cc -MM -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   sample.c >sample.d
g++ -c  -I/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9 -O3   abcAncError.cpp
In file included from sample.h:24:0,
                 from argStruct.h:8,
                 from shared.h:12,
                 from analysisFunction.h:8,
                 from abcAncError.cpp:14:
/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9/htslib/kstring.h: In function ‘int kputsn(const char*, size_t, kstring_t*)’:
/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9/htslib/kstring.h:147:13: error: ‘SIZE_MAX’ was not declared in this scope
     if (l > SIZE_MAX - 2 - s->l || ks_resize(s, s->l + l + 2) < 0)
             ^
/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9/htslib/kstring.h: In function ‘int kputsn_(const void*, size_t, kstring_t*)’:
/stor9000/apps/users/NWSUAF/2015060152/bin/htslib-1.9/htslib/kstring.h:179:10: error: ‘SIZE_MAX’ was not declared in this scope
  if (l > SIZE_MAX - s->l || ks_resize(s, s->l + l) < 0)
          ^
make: *** [abcAncError.o] Error 1

Best wishes,
Zhuqing

**Comment by biozzq** [comment]
Dear all,

I think the most convenient way is to update the package deposited on conda.

Best wishes,
Zhuqing

**Comment by ANGSD** [comment]
yes, i also think the easiest would be clone the most reason version of htslib and link with that.

Im closing this issue, feel free to reopen if needed.

Best
