### ISSUE TITLE
realSFS dadi Plotting

### ISSUE THREAD

**Issue by madzayasodara** [ANGSD/angsd#240]
I wanna use dadi's `dadi.Plotting.plot_single_2d_sfs` function to plot my 2dsfs out of realSFS.
I'm editing the output of 
`realSFS po1.saf.idx  po2.saf.idx -P 24 > output.sfs`
by adding a header with each's pop number of  chrs and if unfolded or not:

> 22 22 unfolded
> 198448660.905448 341185.271362 263321.171480 163391.017846 115634.487247 79507.149083 55211.959347 38549.027846 26379.244108 18152.854543 13605.965929 9765.553809 6986.959864 4802.821199 3356.183651 2227.537012 1615.298832 1170.610727 773.455394 ...
> 

Then I'm reading and plotting using 
```
data = dadi.Spectrum.from_file('output.sfs')
dadi.Plotting.plot_single_2d_sfs(data, vmin=1)
```
but It's not looking good
![test](https://user-images.githubusercontent.com/22630874/61593749-7874ea80-abb1-11e9-9cb8-8bf2b7a7134d.png)

What could be wrong

**Comment by madzayasodara** [comment]
K I didnt know of realSFS dadi.
The way this seem to go is:
realSFS pop1.saf.idx > pop1.idx.ml 
realSFS pop2.saf.idx > pop2.idx.ml 
realSFS dadi pop1.saf.idx po2.saf.idx -sfs pop1.idx.ml -sfs pop2.idx.ml > output.dadi
Then fix the file to get it as the SNP format dadi needs to build a dict using 
https://github.com/z0on/2bRAD_denovo/blob/master/realsfs2dadi.pl 
then run from the script at dadi/examples/fs_from_data/fs_from_data.py
Simple example of extracting a frequency spectrum from a SNP data file.
"""
import dadi
# Parse the data file to generate the data dictionary
dd = dadi.Misc.make_data_dict('output.dadi2plot')
# Extract the spectrum for ['pop0','pop1'] from that dictionary, with both
# projected down to 11 samples per population.
fs = dadi.Spectrum.from_data_dict(dd, ['pop0', 'pop1'], [11,11])
# Let's plot the fs.
import pylab
pylab.figure(1)
#dadi.Plotting.plot_1d_comp_multinom(model, data)
dadi.Plotting.plot_single_2d_sfs(fs, vmin=1)
# This ensures that the figure pops up. It may be unecessary if you are using
# ipython.ii
from matplotlib import pyplot as plt
plt.savefig('2dsfs.png')
pylab.show()

Is this correct?

**Comment by z0on** [comment]
If you are using moments instead of dadi (same thing but faster and does some extra cool things, https://www.genetics.org/content/206/3/1549)  you can use 1dAFS.py and 2dAFS.py from here
https://github.com/z0on/AFS-analysis-with-moments/tree/master/multimodel_inference
to plot spectra

That repo also has a whole lot of 2d models to try and look for best fit using AIC

iPhone. Apologies for brevity

**Comment by madzayasodara** [comment]
Thank you! I'll def need those as well.
one more...
do I have to do the same to transform my 1dSFS out of realSFS to do parameter optimization and calc best fit model in dadi?
meaning, for example for pop1
```
realSFS pop1.saf.idx > pop1.idx.ml 
realSFS dadi pop1.saf.idx -sfs pop1.idx.ml > output.dadi
```
then do some manipulation to get the file output.dadi  in the format dadi needs to build a dict and so on.
Or I can  add a header (nind Unfolded)  to my .sfs out of
` realSFS pop1.saf.idx > pop1.sfs`
and read it straight into `dadi.Spectrum.from_file`?

**Comment by z0on** [comment]
There is a converter script realsfs2dadi.pl at 2brad_denovo github repo https://github.com/z0on/2bRAD_denovo?files=1

iPhone. Apologies for brevity

**Comment by madzayasodara** [comment]
Thank you!
-madza

**Comment by madzayasodara** [comment]
I guess I'm confused about what exact units are in the 1 pop .sfs and .ml files.
