### ISSUE TITLE
dadi.Spectrum.from_file('angsd.sfs')

### ISSUE THREAD

**Issue by madzayasodara** [ANGSD/angsd#242]
I guess I'm confused about what are the exact units in let's say for a 1 pop unfolded .sfs and .ml files.  
From what I get in the .sfs it would be the probability of sampling zero derived alleles on logscale, and so on. Is this correct? People in the lab are saying it is the counts in each category and that I can input that directly into for example dadi and read it straight into `dadi.Spectrum.from_file('angsd.sfs')` , but this makes no sense bc the numbers are not integers.
for example pop1 unfolded .sfs:
`348398020.670957 616056.539667 434489.161227 304745.964758 242005.838217 199375.157620 167487.991092 143066.809409 125862.137423 109980.958992 99609.061586 90920.572153 83000.454505 77025.261765 74636.908585 69652.208053 68631.425787 66388.365671 66318.632284 74497.831215 107331.610928 160531.323274 11067692.114832`
what 348398020.670957 means?

**Comment by ANGSD** [comment]
Hello Madza, sorry for not paying closer attention to these questions. Are the .sfs and .ml the stdoutput from the realSFS program? If so the output is the expected values of the frequency spectrum. 
In the case of the unfolded, it is a vector with 2n+1 values (n is number of diploid individuals), first values is the expected number of sites where you are monomophic for the ancestral allele, the second value is the expected number of sites where you observe one derived allele. etc.

**Comment by madzayasodara** [comment]
Got it. They are the expected. Makes sense why they are floats. Thanks!
