### ISSUE TITLE
Incorrect initialization for -doSaf 4

### ISSUE THREAD

**Issue by nspope** [ANGSD/angsd#244]
Hi,

I believe the initialization of the dynamic programming algo is incorrect in `abcSaf::algoJointPost`. The current initialization is simply https://github.com/ANGSD/angsd/blob/3efa507e96d0bc781c984e06abe7490cb65cbdba/abcSaf.cpp#L618
However, `hj[1]` (at initialization equal to probability of heterozygote genotype in first individual) should then be multiplied by 2. Omitting the factor of 2 will lead to an incorrect SAF if `hj[1]` is non-zero.

Nate

**Comment by ANGSD** [comment]
Hi Nate, nice getting input from you. I agree this was a bug, ive just pushed a new version.

Best
