### ISSUE TITLE
Incorrect indexing in hard-coded depth filtering for -doCovar

### ISSUE THREAD

**Issue by nspope** [ANGSD/angsd#245]
In `abcCovar::run` there appears to be filtering based on depth against hard-code limits here
https://github.com/ANGSD/angsd/blob/e7739a505abcfd66b3dd6c70ed5ea0e7957c60ba/abcCovar.cpp#L161
and again here
https://github.com/ANGSD/angsd/blob/e7739a505abcfd66b3dd6c70ed5ea0e7957c60ba/abcCovar.cpp#L163
but, unless I am very mistaken about intent, I believe the indexing is wrong -- shouldn't we have `pars->counts[s][4*i]`, `pars->counts[s][4*i+1]`, etc ... else the condition is checked using a mish-mash of counts that may well not belong to the target individual.

Potential bugs aside I am curious to know why it's desirable to filter to this relatively narrow range of depth ...

Nate

**Comment by ANGSD** [comment]
Hi Nate, this part of the code is mostly kept for historical reasons. But I agree completely that this doesnt look right, your suggestion that it should offset by blocks of 4 is correct, and I also agree that these values look somewhat arbitrary. Ill keep this issue open.

**Comment by ANGSD** [comment]
Thanks for the input I removed the offending code. Filtering should be done in the abcCounts class instead.
