### ISSUE TITLE
Sites for Fst

### ISSUE THREAD

**Issue by madzayasodara** [ANGSD/angsd#246]
I'm getting contradictory info on which sites should I be using to calculate Fst. The way I've done was to 
I have done some calcs for my each one of my pops (11 ind each) using:

`angsd -b pop.list -ref .fa -anc .fa -out pop1 -uniqueOnly 1 -only_proper_pairs 1 -minMapQ 20 -minInd 11 -minIndDepth 4 -doSaf 1 -doSnpStat 1 -doCounts 1 -dovcf 1 -gl 1 -doGeno 6 -doPost 1 -doMaf 1 -doMajorMinor 1 -nThreads 24 -sites .pos`

where my -sites are # ~1.229.000.000 sites (just the total genome sites minus the likely paralogous sites)

This gave me: 
.saf pop1 # ~362.000.000 sites and pop1 # ~386.000.000

Used those 2 .saf.idx to calc Fst doing:
```
realSFS pop1.saf.idx  pop2.saf.idx -P 24 > pop1pop2.ml
realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1pop2.ml -fstout pop1pop2 -P 24
```
after realSFS fst print pop1pop2.fst.idx gave me # ~413.000.000 sites
I assume it calc Fst for more sites bc some sites were in pop1.saf but not in pop2.saf and vice versa. 
Then I'm using those sites to do Fst per gene calculations.

Is this correct or I should be calculating for intersecting sites between the 2 pops only? (i noticed the ngsTools tutorial does this, but the instructions in angsd wikipage doesn't have this step).
Or I should call variants in both pop's together and use those sites to calc Fst?

Thanks again!

**Comment by ANGSD** [comment]
Hi the output from realSFS should only be sites that exists in both populations. Could you check with

realSFS print pop1.saf.idx|wc -l
realSFS print pop2.saf.idx|wc -l

and 
realSFS print pop1.saf.idx pop2.saf.idx|wc -l

Thanks for using my program

Best

**Comment by ANGSD** [comment]
Also ive pushed a new version of angsd that can do the analysis based on the proper folding of the 2dsfs. These should be less noisy since there are fewer parameters to optimize. You can also try that out if you want.

Best

**Comment by madzayasodara** [comment]
Got it! Thank YOU for being patient with my almost daily questions! Best

**Comment by ANGSD** [comment]
Let me know if there is still an issue?

**Comment by madzayasodara** [comment]
I have a related question and just decided to reopen this. 
I'm confused about some results when I calculate things selecting for different sites. 
I've calculated the SFS filtering out sites that are fixed ancestral in both pops and the shape changes a lot. I'm curious about what would be the contribution of fixed ancestral states, if this result is sound and if I should just use all sites bc this is what angsd expects.
This is the sfs when I use all sites (I mean I give the Chr pos for all sites just filtered out some likely paralogous sites). From What I understood the program will calculate for all the sites that have data and pass whichever requirements I'm asking for. In my case I'm doing minInd 11 (I have 11 individuals in each pop) and -uniqueOnly 1 -only_proper_pairs 1 -minMapQ 20 -minInd 11 -minIndDepth 4.
![image](https://user-images.githubusercontent.com/22630874/64480032-2bef6980-d175-11e9-88a2-db9ac80b0e6f.png)
This is when I ask to calculate over sites that are NOT fix ancestral in BOTH pops. 
![image](https://user-images.githubusercontent.com/22630874/64480056-8ee10080-d175-11e9-8419-aecf2638c1cc.png)
This is when I ask to calculate over sites that are NOT fix ancestral in EACH pops. 
![image](https://user-images.githubusercontent.com/22630874/64491835-a1187880-d221-11e9-95f5-dbfff0406cab.png)

**Comment by ANGSD** [comment]
Dear @madzayasodara , I would do a run without any filtering. Removing the paralogs could be quite important but I would not use the  -minInd 11 -minIndDepth 4 filters.

Best

**Comment by ANGSD** [comment]
Dear @madzayasodara , Im closing this issue. Feel free to reopen.
