### ISSUE TITLE
doSaf does not produce .idx file

### ISSUE THREAD

**Issue by finchnSNPs** [ANGSD/angsd#249]
doSaf doesn't build a idx file. Is this because of a memory issue? Or another issue? I tried allotting 400G of memory to the job. The error file is attached. I see "Calling destroy" at the end. Is this an error that is supplied when doSaf is finished? Or is this error due to a memory limit. The arg file is also attached.

Thanks.
[20190903_arg.txt](https://github.com/ANGSD/angsd/files/3572834/20190903_arg.txt)
[sfs_3_e.txt](https://github.com/ANGSD/angsd/files/3572825/sfs_3_e.txt)

**Comment by nspope** [comment]
Hi, that's an extremely old version of ANGSD (the build is from 2014), and it is generating the old (v1) SAF format which did not include an idx file. Please clone/compile the latest version of ANGSD (from github) and give that a whirl.

Nate

**Comment by finchnSNPs** [comment]
'Doh!
