### ISSUE TITLE
depthSample info

### ISSUE THREAD

**Issue by nwales** [ANGSD/angsd#251]
Just a minor item... I was using the website to understand the depth files (.depthSample and .depthGlobal), and it looks there is a mistake in the description. By my calculations from a counts.gz file, Column1 of the .depthSample corresponds to a depth of 0 (rather than a depth of 1 as stated on http://www.popgen.dk/angsd/index.php/Allele_Counts). 

Thanks! Nathan

**Comment by ANGSD** [comment]
Thanks you are right, I have updated the wiki. Thanks.
