### ISSUE TITLE
Segmentation fault with doHWE

### ISSUE THREAD

**Issue by clairemerot** [ANGSD/angsd#254]
Hello,
trying to estimate the observed heterozygosity through the HWE deviation estimate, I'd like to run the doHWE option, but whatever way I tried I am getting a segmentation fault (everything else is fine when I do doSaf or doMaf, etc)

This is the version of angsd I was using. 
angsd version: 0.929-11-gb2d6b34-dirty (htslib: 1.8) build(Feb 26 2019 10:34:33).

and the command
 angsd -doHWE 1 -b 02_info/AGbam.filelist -out essaiHW

has anybody encounter that problem?
Thanks a lot
Claire

**Comment by nspope** [comment]
Hi Claire, what is the full command you used? Surely must include -GL <int>, no?

**Comment by clairemerot** [comment]
Thanks, that is working fine now with -GL 2.
