### ISSUE TITLE
The FST scan on windows skips the first window and starts on whatever step size is 

### ISSUE THREAD

**Issue by aguilar-gomez** [ANGSD/angsd#257]
I am running the following command to do Fst scan :     
realSFS fst stats2 $pop1.$pop2.fst.idx -win 50000 -step 10000 >slidingwindow$pop1$pop2

I get a result where the first window in all scaffolds is the second, for example:
 (129,160)(13715,58120)(10000,60000)	chr333	35000	33	0.095373
(141,173)(29433,69651)(20000,70000)	chr333	45000	34	0.115676
(143,181)(30544,79593)(30000,80000)	chr333	55000	40	0.134265
(150,185)(41323,87553)(40000,90000)	chr333	65000	37	0.137762

In this scaffold the first window seems to be form 10kb-60kb, I think it should be from position 1 to position 50kb. I believe the way the code is written, you always miss the first k base pairs where k is the sliding parameter. 
Please correct me if I am not understanding properly or if this is done on purpose for a reason. 
Thank you

**Comment by ryangreenway** [comment]
Has anyone looked into this? I have been having the same issue, for multiple window and step sizes.

**Comment by ANGSD** [comment]
Hi this is described here:
http://www.popgen.dk/angsd/index.php/Fst#Relative_window_positions.3F

You can use 3 different ways of defining the window regions.

Im closing this issue, feel free to reopen if needed.
