### ISSUE TITLE
question about ploidy or pooled samples

### ISSUE THREAD

**Issue by peterdfields** [ANGSD/angsd#26]
I was just wondering if there is a way currently, or possibly a planned extension, to allow for non-diploid samples or pooled samples to be analyzed within the ANGSD framework? Thanks!

**Comment by ANGSD** [comment]
No not in the near future. Not that many have asked for this.
For some analysis the changes required would be very small (like simple maf estimation), but for more complicated models like the sfs it would have to be completely redone.

**Comment by ANGSD** [comment]
I'm closing this issue, feel free to reopen if needed.
