### ISSUE TITLE
Reading bam files from minimap2 

### ISSUE THREAD

**Issue by mstetter** [ANGSD/angsd#260]
Hi,
I'm trying to create a consensus fasta from a whole genome alignment that I did with minimap2. But angsd seems to filter out all sites in the bam file even without supplying any filters. 
It does read the file fine but seems to not keep any sites. 
Do you have any idea why this is the case? any experience with bam files from minimap2?
I would appreciate your help.
Cheers 
Markus

**Comment by ANGSD** [comment]
I have not tried data from minimap.

If possible could you supply me with a subset of the bam? Then i will look
into why it does not retain any sites.

Best

Den tor. 10. okt. 2019 kl. 13.53 skrev Markus Stetter <
notifications@github.com>:

**Comment by mstetter** [comment]
Thanks for the quick response. Here is one chromosome as bam file.
I really appreciate your help.
(the file is a bam, just had to change the extension as github does not want files that end on .bam)
[minimap_example_subset.txt](https://github.com/ANGSD/angsd/files/3712504/minimap_example_subset.txt)

**Comment by alexjvr1** [comment]
Hi, 
Has there been a resolution for this problem? I'm running into a similar issue when reading files merged with bbmerge. The individual seems to be read in properly, but then angsd can't find the data (even though the bam file has data in it). 
Error: 
[bammer_main] 1 samples in 1 input files
	-> Parsing 1 number of samples 
No data for chromoId=0 chromoname=LR761647.1
This could either indicate that there really is no data for this chromosome
Or it could be problem with this program regSize=0 notDone=0

	-> Done reading data waiting for calculations to finish
	-> Done waiting for threads
	-> Output filenames:
		->"angsdput.arg"
	-> Fri Apr 17 16:45:14 2020
	-> Arguments and parameters for all analysis are located in .arg file
	-> Total number of sites analyzed: 0
	-> Number of sites retained after filtering: 0 
	[ALL done] cpu-time used =  4.24 sec
	[ALL done] walltime used =  4.00 sec

Cheers
Alex

**Comment by ANGSD** [comment]
Hi sorry for the delay, i dont have as much time to fix these things. I have modified the code. There were two things. 1) I discarded supplemental reads in the past. 2) sometimes the sequence is * or sometimes the quality scores is *. I had not observed this before. But it  should work now.

Best
