### ISSUE TITLE
DoFasta with Whole Genome Alignemnts

### ISSUE THREAD

**Issue by Jungal10** [ANGSD/angsd#261]
I have been trying to create a Consensus FASTA sequence from different whole-genome alignments `bam` files, but ANGSD ends all by filtering out the results.

I have tried with default settings, with `doFasta` 1 2 and 3,-`doCounts` 0 and 1, but nothuing seems to work. I end always with a full output of _NNNNN_. `-minInd`parameter also experiemnted with 0, 1 and 2.
I have also tried `RemoveBads` options without any luck.

I always end up with a scenario similair to this:

```
	-> Total number of sites analyzed: 64588599
	-> Number of sites retained after filtering: 0
```

Any suggestion of how to work around the issue?

Preferable setup:
` ~/angsd/angsd -out outflie -bam bam.filelist -doFasta 2 -minInd 2 -doCounts 1`

Thank you in advance

**Comment by ANGSD** [comment]
Dear @Jungal10 not sure if this is still relevant but what platform is your data? I recently pushed a commit that includes suppl reads and also solves an issue with missing quality scores or very high quality scores. That could cause the stuff you have been observing. Given that this was posted quite some time ago I am closing this issue. But feel free to reopen or post a new issue. Thanks for using the program.

**Comment by Jungal10** [comment]
I was using minimap2 for it. I saw that you have done some work on this. I will take a look again since it has been a while. Thank you !

**Comment by ANGSD** [comment]
Ok, super. That could indeed explain it. Sorry that it has taken so long. I dont have as much time as i used to for updating the program.
