### ISSUE TITLE
minIndDepth filter "unknown"?

### ISSUE THREAD

**Issue by j-a-thia** [ANGSD/angsd#262]
Hey there.

My lab typically runs ANGSD in custom miniconda environments. 

Since the v0.931 update to ANGSD in miniconda, we have been unable to get the `minIndDepth` filter to work. This problem persists across local installs and on our HPC. Older versions of ANGSD miniconda installs seem to work.

Has anyone else had this problem and is it an easy solution?

See example of a code snippet that works on an older version of ANGSD:

```
# This used to work:
angsd -GL 1 -out Bcoco_HastHeron1617_Angsd2 -nThreads 2 -doGlf 2 -doMajorMinor 1 -minQ 30 -doMaf 2 -minMaf 0.01 -doHWE 1 -SNP_pval 2e-6 -minM30 -minInd 400 -minIndDepth 5 -doCounts 1 -dumpCounts 2 -bam Bcoco_HastHeron1617_Run2.bamlist

-> angsd version: 0.931 (htslib: 1.9) build(Aug 28 2019 05:50:59)
-> SNP-filter using a pvalue: 2.000000e-06 correspond to 22.595043 likelihood units
25 argument  -minIndDepth is unknown will exit
```

Thanks!

~ Josh

**Comment by nspope** [comment]
Hi Josh,

at some point the name of argument changed and it seems the wiki has not been updated. It is always best to check inline help (`angsd -doCounts`). Try

```
angsd ... -doCounts 1 -setMinDepthInd <int> ...
```

**Comment by ANGSD** [comment]
Dear Josh, I agree with @nspope the option should be -setMinDepthInd, the wiki is somewhat out of sync on some of the pages and I have just updated the pages.

Thanks for reporting these things.

I am closing this issue feel free to reopen if needed.

Best

**Comment by j-a-thia** [comment]
(Sorry for late reply)

Thanks for help, it was as per suggestions -- all fixed!

Best,

~ Josh
