### ISSUE TITLE
vcfReader issue

### ISSUE THREAD

**Issue by cursorially** [ANGSD/angsd#264]
Hi there,

I'm using angsd with input `.vcf` files and am coming across the following error:

`Assertion failed: (hit!=-1), function isindel, file vcfReader.cpp, line 233.`

In the `vcfReader.ccp` file I notice that it assumes that the `INFO` filed has `INDEL` somewhere in it. Mine does not. I have a set of called and filtered SNPs already (with GLs), and I effectively just want to use this to rewrite the `.vcf` into the exact `.beagle` format (with normalisation) required for things like NGSadmix and PCangsd (is this even possible with angsd?). There are remarkably few existing tools to do this.

Is this the expected behaviour?

**Comment by nspope** [comment]
Hi, does it work if you add INDEL to the header of the vcf? e.g.

```
INFO='##INFO=<ID=INDEL,Number=0,Type=Flag,Description=\"\">'
awk -v infohdr=$INFO '/^#CHROM/ {print infohdr"\n"$0} !/^#CHROM/' my.vcf >my.info.vcf
```

more generally it should be possible to detect indels by length of REF/ALT fields (as per vcf format standard), not relying on an INDEL flag that may or may not be in the vcf. I will look into it...

Nate

**Comment by ANGSD** [comment]
Could you supply me with the file that causes this problem?

**Comment by cursorially** [comment]
[File attached.](https://github.com/ANGSD/angsd/files/3823200/test.vcf.gz)

**Comment by ANGSD** [comment]
Hi Sorry about this delay. I updated the bcf/vcf and gl/pl file reading in the most recent version. It should work much better now. Sorry for the delay, i dont have so much time to code as I used to have.
This is the commit 940463de2b1c9d3a016ad1b733cb5a6311a992bb for the fix. I am closing this issue. Thanks for reporting it.
