### ISSUE TITLE
Bus error when running 2DSFS

### ISSUE THREAD

**Issue by cdomsar** [ANGSD/angsd#267]
Hi, 

I am trying to run 2DSFS in order to extract information from Fst as in Fumagalli's tutorial (https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md#population-genetic-differentiation-fstpbs), but I got the following issue:

rsfs gen1.autosomes.saf.idx gen2.autosomes.saf.idx > sfs/gen1.gen2.sfs
	-> Version of fname: gen1.autosomes.saf.idx is:2
	-> Assuming .saf.gz file: gen1.autosomes.saf.gz
	-> Assuming .saf.pos.gz: gen1.autosomes.saf.pos.gz
	-> Version of fname: gen2.autosomes.saf.idx is:2
	-> Assuming .saf.gz file: gen2.autosomes.saf.gz
	-> Assuming .saf.pos.gz: gen2.autosomes.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:gr_wolf.syria.autosomes.saf.idx fstout:(null) oldout:0 seed:1572536899 bootstrap:0 whichFst:0
	-> Multi SFS is 'still' under development. Please report strange behaviour
	-> nSites: 1930960768
	-> The choice of -nSites will require atleast: 73660.304688 megabyte memory, that is at least: 57.24% of total memory
Bus error

Booking 90Mb of memory for my analysis in my server is not useful either. 

unfoldedSFS/genomes/gen1.autosomes.saf.idx fstout:(null) oldout:0 seed:1572536375 bootstrap:0 whichFst:0
	-> Multi SFS is 'still' under development. Please report strange behaviour
	-> nSites: 1930960768
	-> The choice of -nSites will require atleast: 73660.304688 megabyte memory, that is at least: 57.24% of total memory
/var/spool/slurmd/job27224485/slurm_script: line 19: 39851 Bus error               $RSFS -P 8 $AUT/gen2.saf.idx $AUT/gen1.saf.idx > $
AUT/sfs/gen1.gen2.sfs

I am in touch with the managers of my server, but I am suspicious that the problem is in relationship with the -sites flag. 

I had previously used -sites to call unfolded SFS in neutral sites along all 38 autosomes of a canid species. I am interested in using only neutral sites, so the -sites text file had the length of the chromosomes minus the genic regions. Later these chromosomes were merged successfully using realSFS cat. I attempted to do 2DSFS on the merged genomes of these chromosomes.

What can be happening?

Thank you!

**Comment by ANGSD** [comment]
Hello, ok, so the input file, is something that was generated from realSFS cat?
If so, could you validate it with realSFS print and realSFS check.

You are not using -sites for the actual command that causes the segfault?

**Comment by cdomsar** [comment]
Hi, so I used:
1. -sites to call uSFS sites. I wanted to exclude an area of 10kb around genic sites. The command per genome was:
```

for i in {01..38}
do
	$ANGSD -P 8 -bam $FILE.chr$i.bamlist -anc $ANC/chr$i.edited.fasta -ref $REF/chr$i.fa -out $OUT.chr$i -r chr$i \
		-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 \
		-minMapQ 20 -minQ 20 -minInd 1 -setMinDepth 5 -setMaxDepth 71 -doCounts 1 \
		-GL 1 -doSaf 1 -sites $SITES/chr$i.10kb.neutral_regions.corrected.txt
done
```
2. realSFS cat to merge all chromosomes together. 
$RSFS cat gen1.chr01.saf.idx gen1.chr02.saf.idx [...] -outnames gen1.autosomes.saf.idx
$RSFS cat gen2.chr01.saf.idx gen1.chr02.saf.idx [...] -outnames gen2.autosomes.saf.idx

3. Output of realSFS check:
$RSFS check gen1.autosomes.saf.idx 
	-> ./realSFS check your.saf.idx
	-> This will check that the positions are ordered correctly
	-> Version of fname:gen1.autosomes.saf.idx is:2
	-> Assuming .saf.gz file: gen1.autosomes.saf.gz
	-> Assuming .saf.pos.gz: gen1.autosomes.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:gen1.autosomes.saf.idx fstout:(null) oldout:0 seed:1573147308 bootstrap:0 whichFst:0

with no output. 

4. Output of realSFS print:
	-> Version of fname:gen1.autosomes.saf.idx is:2
	-> Assuming .saf.gz file: gen1.autosomes.saf.gz
	-> Assuming .saf.pos.gz: gen1.autosomes.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:gen1.autosomes.saf.idx fstout:(null) oldout:0 seed:1573147644 bootstrap:0 whichFst:0
	-> Will jump to multisaf printer and will only print intersecting sites between populations
Bus error

Does realSFS support whole genomes?

**Comment by ANGSD** [comment]
Ok, so this looks like a bug in the realSFS cat command. Until I get around to look into that you can generate a single output file from angsd and use that as input. The software should work fine on whole genomes for very large sample sizes. The segfault you observe is due to corrupted input data from the realSFS cat command.

Hopefully this helps.

Best

**Comment by cdomsar** [comment]
Hi, 

I solved the problem by considering how many GB of RAM did realSFS need to run. Actually, for 2DSFS in my whole genomes realSFS needed ca. 190GB of RAM memory, which unless specified in my server, weren't allocated. Normal SFS call with realSFS needs ca. 90-100Gb of RAM. Since the normal specification of my server was 75Gb unless specified, it caused realSFS to crash. After allocating this space, everything worked smoothly.

This might be useful for other users experiencing similar problems. 

Best regards and thanks, 

Carlos

**Comment by ANGSD** [comment]
Ok, im closing this issue, feel free to reopen or submit a new issue.

Best
