### ISSUE TITLE
vcf input: Problem with length of fastafile vs length of chr in BAM header

### ISSUE THREAD

**Issue by noahrose** [ANGSD/angsd#268]
Hi there,

I'm having an issue with using vcf-pl input for -dosaf -- when I try to run the program, I get the following error:
	-> Problem with length of fastafile vs length of chr in BAM header
	-> Chromosome name: 'NC_035107.1' length from BAM header:2147483647 length from fai file:310827022

the relevant header line in the vcf file shows the correct length, so I'm not sure where it's getting the (incorrect) 2147483647 length:
##contig=<ID=NC_035107.1,length=310827022>

Thanks in advance for any thoughts or advice you might have!

**Comment by ANGSD** [comment]
Dear @noahrose , could you supply me with the full commandline.

Best

**Comment by noahrose** [comment]
The command line was:

angsd -anc /tigress/noahr/ref/male_altref_iter3.fna -vcf-pl
WESTAF_PREF.vcf.gz -dosaf 1 -out WESTAF_PREF -nThreads 16 -nInd 40

However, I've switched to just using the bam files rather than trying to
coordinate my analyses with my already-processed vcf, and that's all
working fine

**Comment by cursorially** [comment]
I've encountered the same problem running [this file](https://github.com/ANGSD/angsd/files/3829581/ancmiss10.info.vcf.gz) through the following command:

`angsd -vcf-pl ancmiss10.info.vcf -doSaf 1 -out test -fai melanoplus.fasta.fai -anc melanoplus.fasta -nInd 7`

I get exactly the same incorrect length reported from the BAM header too:

`-> Chromosome name: 'locus.100647' length from BAM header:2147483647 length from fai file:105`

**Comment by ANGSD** [comment]
Hello, what is the length of the chromosome in the fastafile?

Best

**Comment by cursorially** [comment]
Length is as reported in the .fai; 105. All chromosomes are RADtags and are in the region of 105-114 bp. [Fasta attached.](https://github.com/ANGSD/angsd/files/3850023/melanoplus.fasta.gz)

**Comment by deboraycb** [comment]
Hi, I'm also getting the `BAM header:2147483647`. Details (command and files) here https://github.com/ANGSD/angsd/issues/227#issuecomment-550598764.

**Comment by ANGSD** [comment]
Sorry about the delayed response with all these vcf things. Im travelling with very limited net access. Will look into it when I am back.

Sorry about this.

Best

**Comment by zyxplus** [comment]
I met the same vcfreader problem, and I am using angsd version: 0.931 (htslib: 1.9)
I kept only bialleles but it didn't work. 
The length of chr1 in .fai file is 249250621.
I searched for 2147483647 but found that it equals 2^32-1, the length of INT. Something wrong related with it?
the command I used is: angsd -dosaf 1 -fai $hg19_fai -anc $anc -out $input_vcf -nInd 2 -vcf-pl $input_vcf

Another question is whether linkage disequilibrium will affect the result of fst ?

###########################################################

the report of vcfreader is as following:
        -> Problem with length of fastafile vs length of chr in BAM header
        -> Chromosome name: '1' length from BAM header:2147483647 length from fai file:249250621
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PAA=nan PAa=nan Paa=nan
is nan:4
PROBS at: 1     768448
PROBS at: 1     797281
PROBS at: 1     801661
PROBS at: 1     836896
PROBS at: 1     848445
PROBS at: 1     852820
PROBS at: 1     854978
PROBS at: 1     857177
PROBS at: 1     873558
PROBS at: 1     882033
PROBS at: 1     905017
PROBS at: 1     938125
PROBS at: 1     967658
        -> Done reading data waiting for calculations to finish
        -> Done waiting for threads
        -> Output filenames:
                ->"Adygei.vcf.gz.arg"
                ->"Adygei.vcf.gz.saf.gz"
                ->"Adygei.vcf.gz.saf.pos.gz"
                ->"Adygei.vcf.gz.saf.idx"
        -> Fri Dec 27 10:22:47 2019
        -> Arguments and parameters for all analysis are located in .arg file
        -> Total number of sites analyzed: 50
        -> Number of sites retained after filtering: 37
        [ALL done] cpu-time used =  3.67 sec
        [ALL done] walltime used =  3.00 sec

**Comment by deboraycb** [comment]
As a temporary workaround, you can disable the check of length of chromosomes in the vcf and the fasta in the source code.
Go to this line:
https://github.com/ANGSD/angsd/blob/master/abcGetFasta.cpp#L127
And change it to:
if(0 && f->chrLen!=header->target_len[chrId]){

 It worked for me, but down the line I'm still getting the error reported here: https://github.com/ANGSD/angsd/issues/258

**Comment by ANGSD** [comment]
Dear all, I pushed a new version of angsd yesterday that should use the length definitions in the header part of the vcf/bcf. This also means that you do not need to use the -fai when using vcf/bcf.

Sorry about the delay. I am closing this issue, but feel free to reopen if needed.

Best
