### ISSUE TITLE
Segfault11 -doSaf with .vcf input

### ISSUE THREAD

**Issue by cursorially** [ANGSD/angsd#271]
Hi there,

I'm running -doSaf with a pre-pared [.vcf file](https://github.com/ANGSD/angsd/files/3829621/finalmiss10.info.vcf.gz) from FreeBayes, so each site has a GL field, with the following command:

`angsd -vcf-gl finalmiss10.info.vcf.gz -doSaf 1 -out test.f -fai melanoplus.fasta.fai -anc melanoplus.fasta -nInd 58`

The file seems to be reading fine (after applying the quick fix in #227) but get this error:

`-> Reading fasta: melanoplus.fasta`
`Segmentation fault: 11`
 
The .fasta file has worked fine with other inputs (#270) so I'm reasonably sure it's something to do with the .vcf input.

**Comment by ANGSD** [comment]
Dear @cursorially , would you mind sharing the input vcf so I can investigate further.

Thanks for trying the program and reporting possible problems.

Does your vcf contain pl or gl tag?

Best

**Comment by ANGSD** [comment]
Just saw that you had included the vcf file in your original post, could you also supply me with the fastafile, so I can reproduce the problem.

**Comment by cursorially** [comment]
The .vcf file should be included in the original post. [Re-attached here](https://github.com/ANGSD/angsd/files/3850010/finalmiss10.info.vcf.gz). This particular file has a GLs.

**Comment by ANGSD** [comment]
Dear @cursorially sorry for the extended delay. I was just going through the issues for this software and the program does not exist on the most recent version of angsd so I am closing this issue.

Best
