### ISSUE TITLE
failing to open .bam files with -bam command on bam.filelist

### ISSUE THREAD

**Issue by dlema82** [ANGSD/angsd#272]
I have left comments in closed issues 176 and 196, both relating to my issue, but I don't know if I will receive a response as they are closed. So please forgive me for starting a new issue.
I am trying to use angsd to do a variety of analyses, for example here for maf:
`/array/dlema/angsd/angsd -P 8 -bam /array/dlema/bam_mtgenome.filelist -out angsd_mtgenome -GL 1 -doMaf 3 -doMajorMinor 1 -SNP_pval 0.0001 -doGeno 19 -doPost 1 -doDepth -doCounts 1` 
here are the first few rows of my bam_mtgenome.filelist:
`/array/dlema/A34746.mapped.bam

/array/dlema/A52028.mapped.bam

/array/dlema/A52039.mapped.bam

/array/dlema/A52045.mapped.bam`

But I can't run a thing because i keep getting the error:
`-> angsd version: 0.930 (htslib: 1.9) build(Nov  6 2019 21:46:42)
" : No such file or directoryo open file "/array/dlema/A34746.mapped.bam
angsd: multiReader.cpp:380: multiReader::multiReader(int, char**): Assertion `in' failed.
`
I have tried editing the filelist with and without full/path/to/bam/file, I've tried appending each line of the text with \n, I've tried dos2unix fix on the filelist, I've tried calling the filelist with and without a .txt extension, I've checked and rechecked again and again every detail of the files and paths and directories, to make sure they are correctly represented in the filelist. What am I doing wrong? There does not seem to be a solution anywhere for this issue. I'm embarrassed it may be some really silly oversight on my part, but PLEASE since I cannot find the oversight, help me get this running!!!

**Comment by ANGSD** [comment]
Dear @dlema82 , could you try to see if the filelist works for samtools?

samtools mpileup -b /array/dlema/bam_mtgenome.filelist 

And see if that works. If not then try to do ls -lh for the different entries to see if the file exists.

**Comment by dlema82** [comment]
Hello thank you for your suggestions. samtools mpileup worked, and the files exist in my array/dlema/ directory when called by ls -lh.

**Comment by dlema82** [comment]
Hello @ANGSD 
I am looking for a followup. I have tried your suggestions as above (testing the .bam files with samtools mpileup). Since then I have also tried running it without multi-thread parallelization, which still gave me this error. Then I tried to use -i to call a single .bam file in my bam_mtgenome.filelist, and I received a segfault error. At least I know that this means angsd can read the .bam files before it segfault dumps them (it just can't read them from a .filelist with -bam) So then I uninstalled and re-installed angsd and htslib to see if that would help, but I get the same errors:
no such file or directory when I use -bam for my .filelist
segfault when I use -i for a file in my .filelist

Please advise

**Comment by ANGSD** [comment]
Dear @dlema82 sorry for not getting back to you. I assume this has been resolved so I am closing this issue. Feel free to reopen if that is not the case.

**Comment by chenqing-1996** [comment]
> Hello @ANGSD I am looking for a followup. I have tried your suggestions as above (testing the .bam files with samtools mpileup). Since then I have also tried running it without multi-thread parallelization, which still gave me this error. Then I tried to use -i to call a single .bam file in my bam_mtgenome.filelist, and I received a segfault error. At least I know that this means angsd can read the .bam files before it segfault dumps them (it just can't read them from a .filelist with -bam) So then I uninstalled and re-installed angsd and htslib to see if that would help, but I get the same errors: no such file or directory when I use -bam for my .filelist segfault when I use -i for a file in my .filelist
> 
> Please advise

Hi dlema82,
I'm sorry to bother you. I met the same problem as you, how did you solve it?
