### ISSUE TITLE
NaN in fst values

### ISSUE THREAD

**Issue by clairemerot** [ANGSD/angsd#274]
I'm sorry to be asking questions again...
We have been trying the last version of angsd and realSFS to do the fst following the issue
https://github.com/ANGSD/angsd/issues/259
and I am encountering new problems. 

Some positions have NaN in the file .sfs produced by 
 realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1pop2.ml 
 realSFS fst print pop1pop2.fst.idx > pop1pop2.sfs

I guess this is not a big problem as it may be due to position fixed or absent in one of the population. Is it?
But then, when doing the sliding window analyses (realSFS  fst stats2), only one position with NaN and the whole window is NaN (realSFS  fst stats). So obviously the global estimation of fst is also Nan.
Has anybody face this issue too? 

I could problaly work around it by filtering the .sfs for NaN position and then make the ratio of the sum of column 3 over column 4 across all the genome and by sliding windows... But I am concerned that this may reveal other underlying problem. And it also means that the interesting functions of fst stats are not directly usable...?

Also, I kept wondering about whether I should use doMajorMinor or if it is no use for the initial doSAF step. Will this always polarised via the ancestral reference for each population? (I'm now using doSaf bamlistpop1, dosaf bamlistpop2, and then realSFS pop1.saf.idx pop2.saf.ida -fold)

Thanks a lot for your help!!
Claire

**Comment by clairemerot** [comment]
Comparing other populations, we also have negative values for FST. This is very strange because it used to be, with former version of angsd and (-fold) in dosaf, that we had perfectly sensible FST values. Any idea what's going wrong? Is there something I should be careful with when running the new version?
Thanks
Claire

**Comment by nspope** [comment]
Hi,

1. What happens if you use unfolded SFS to calculate Fst? Remember that Fst is symmetric with regard to allele frequency, so the only difference b/w the unfolded/folded calculation is with the estimation of the SFS itself -- which should be a minimal difference with a long sequence. If the Fst are very different b/w folded & unfolded that's a sign that something is broken.

2. Can you send me a small subset of the inputs (say, 10Kb or so) in a region where you are getting NaN Fst and values that are now negative, but that were positive in previous versions of ANGSD. Use [the -r flag](http://www.popgen.dk/angsd/index.php/Input#Arguments). So for example,
```
angsd -r chr:start-stop <arguments that you are using> -doGlf 3 -doSaf 1 -out pop1
```
I need (a) the binary GLF file (.glf.gz) for both pops, (b) the 3 SAF files for both pops, (c) the estimated  folded and unfolded 2d SFS that you are using as a prior when calculating Fst. [Upload here](https://www.dropbox.com/request/mytCVkfNmj2dTcoJAZxI).

**Comment by clairemerot** [comment]
Thanks for your help!
I wanted to re-generate the files for a 10kb region but to output a glf, I need to choose a doMajorMinor option. Would this affect saf? any recommandation? I've ran it with doMAjMinor 1, but I'm very unclear about whether doSaf is affected or not by the doMajorMinor. It should be important because don't we want the spectrum to be polarized towards the same alleles for the two poulations?
Cheers
Claire

**Comment by nspope** [comment]
Yes. Determination of major/minor determines the ordering of the SAF. I assume you have a reference genome that you've mapped to. You can force the major allele to match the reference sequence, which will ensure that the SAF is ordered consistently across separate (per-population) runs of angsd.
```
angsd <options> -ref reference.fa -doMajorMinor 4 <options>
```

**Comment by clairemerot** [comment]
Hello, I have been trying today to reproduce the Nan problem with a smaller region, but it does not appear anymore! (although the negative problem is still here - and when it is not negative, FST values are much lower than what they used to be, I suspect this is because the first column also has negative). I am now exploring whether it may have appeared because I use the sites options in doSaf. 
I'll be in touch hopefully tomorrow to try solving the pb! Thanks a lot

**Comment by tomoosting** [comment]
Hi! I'm having the same issue. I've had estimates for Fst but I took some of the suggestions from the post clairemerot mentioned in the original question.

I haven't been able to backtrack all my changes but things I changed were a lower `-SNP_pval` (1e-2) when doing the initial GL estimates, and didn't use a `-Minmaf`. The argument is that you least distort the SFS. But I'm wondering if by having these parameter settings you get a lot of sites with an fst estimate of 0.0,  and when calculating the average fst you some sort error. Maybe that's way clairemerot doesn't get the error message with a smaller region, not enough zero values to throw the program off(???). 
I've also switched to estimating the SFS `-doSaf` unfolded and only estimating the 2dSFS use the `fold 1` as suggested. I used the -sites option both instances so I don't think that is causing any problems, as far as I can tell.

Maybe this helps with troubleshooting. I'd be curious to hear any solutions. :)

**Comment by nspope** [comment]
Fst is a ratio, and here is calculated by taking the average of both
numerator and denominator across sites, then taking the ratio. Not by
taking the average of the ratio across sites. If a given window is too
small and is over a monomorphic region, then you may end up with division
by 0 ==> NaN. That is expected. However, the numerator and denominator for
a given site should never be NaN (which is evidently happening to
clairemerot), no matter the frequency. Thus the global Fst estimate should
never be NaN (except in the trivial case of an entirely monomorphic
genome), regardless of the filters used.

As far as the SFS, both the -snp_pval and -minmaf filters will certainly
distort the SFS, as they filter on the basis of frequency. This may not
matter overmuch for Fst, which is not greatly influenced by SNPs with a low
global frequency. However, for statistics that *are* highly influenced by
lower frequency alleles -- such as Tajima's D, various estimators of theta,
etc. -- you will get meaningless results if you apply frequency-based
filters.

**Comment by clairemerot** [comment]
I'll come back later on the Nan and negative problem. Nan were only at some lines of the byposition values that are then summed up by windows/or accross the genome. I'm trying to reproduce it and it does not! (for the nan, for the negative it dooes).  Generating files for smaller regions at the moment too.

Just one question in the mean time. When one does not goive a doMajorMinor option for the saf (and then 2d sfs) as describedd here http://popgen.dk/angsd/index.php/2d_SFS_Estimation what is the value taken by defaut (doMajorMinor 1? the ancestral? the ref?)? How are alleles polarised in each population? 
Thanks a lot
Claire

**Comment by nspope** [comment]
Hi Claire, in that example the spectrum is polarized by the ancestral states given by -anc <fasta>.

**Comment by clairemerot** [comment]
Hello,
So I have been trying to reproduce the Nan without success on a subset region - maybe this is a good sign and  there was a problem in my previous command - I'll run again the whole genome to test and be in touch.
However, if you are still willing to look into the problem, negative fst are very very strange. Note that the same pattern is happenning whether we apply no filter and work on a 15kb region or a subset of 5000 polymorphic sites selected via maf filters. So I don't think the pb is in distorted filtered frequencies.

-> In some comparison (LG5_27Mb_B1B1 vs LG5_27Mb_B1B2), there are negative value in the left column (precalculated A) that is summed before making the ratio with the sum of the second column (precalculated B). I never observed that in previous calculation and it makes overall fst much lower than it used to be. We have this coming back in several datasets.
 This is the head of the file output by        realSFS fst print essai_saf_fst/"$pop1"_"$pop2".fold.fst.idx -P $NB_CPU -fold 1 > essai_saf_fst/"$pop1"_"$pop2".fold.bypos.sfs

LG1     80077   0.000000        0.000196
LG1     80078   0.000000        0.000196
LG1     80079   0.000000        0.000194
LG1     80080   0.000000        0.000194
LG1     80081   0.000000        0.000196
LG1     80084   -0.000238       0.181843
LG1     80086   0.000000        0.000193
LG1     80087   -0.000248       0.183825

In other comparisons (AA vs AB, 144 ind vs 860), in the same file, all positions of the second column are negative -> making an overall negative FST. 

LG1     80075   0.000002        -0.001373
LG1     80076   0.000001        -0.001348
LG1     80077   0.000001        -0.001290
LG1     80078   0.000001        -0.001299
LG1     80079   0.000001        -0.001286
LG1     80080   0.000001        -0.001290
LG1     80081   0.000001        -0.001282
LG1     80082   0.000001        -0.001286
LG1     80083   0.000002        -0.001497
LG1     80084   0.004881        -2.099850
LG1     80085   0.000001        -0.001325
LG1     80086   0.000001        -0.001271
LG1     80087   0.004377        -2.475301

And finally, in another comparison (Ab vs BB, 860 vs 442), the 2dsfs cannot be computed because of segmentation fault. Even with the use of -nsites 1000000 to reduce memory usage. 
I'm giving sample size as this might be the problem?

Thanks a lot for your help! and so sorry to take your time for that. 
Claire

**Comment by nspope** [comment]
@clairemerot can you share a small portion of your data-- the outputs I described in [previous comment](https://github.com/ANGSD/angsd/issues/274#issuecomment-560462075) on this issue ... say for a 5-10kb region in a pair of populations with fewer samples. As long as each file is <2gb they can be uploaded to that dropbox link. It is hard to discern what is going on simply from the Fst output. Fst estimators can certainly be negative due to sample size bias. More worrying is if these numbers are radically different from those output by previous versions of angsd (for same sites/samples).

**Comment by clairemerot** [comment]
thanks for your help. Yes I uploaded the files and the code used on the dropbox;please let me know if there is anything else. It is on a 15kb region so small files.

In the meantime, I'll try to re-run with previous angsd version to compare values and with balanced sample sizes. Thanks!!

**Comment by clairemerot** [comment]
To follow-up, I run several trials with angsd 0.923 and angsd 0.931:

So values of FSt obtained with the latest angsd (unfold saf) & unfold saf & fold/notfold realSFS are consistent when sample size are more or less balanced. 
With large sample size, the 2dsfs is not calculated (segmentation fault) and when sample size are imbalanced, we get negative FST values.
below is the summary of the comparison for a 15kb portion of the genome

FST run with older version of angsd (0.923) and the fold option within the saf provide totally different values - never goes into NA or negatives - but I guess this procedure was not right so we shall not stick to it, right?

For now, we are persuing the analyses trying to balance sample size and using the last version of angsd + fold within the realSFS. Any advice is welcomed!

Thanks a lot for the help!!
Claire
                        | angsd0.923 | angsd0.923 | angsd0.931 | angsd0.931
           |sample size | unfold | fold (dosaf) | unfold | fold(realSFS)
AA vs BB | 144 vs 442 | 0.002 | 0.005 | 0.002 | 0.002
AA vs BB | 144 vs 144 | 0.005 | 0.012 | 0.005 | 0.005
  |   |   |   |   |  
AA vs AB | 144 vs 860 | -0.001 | 0.008 | -0.0013 | -0.0013
AA vs AB | 144 vs 144 | 0.004 | 0.009 | 0.004 | 0.004
  |   |   |   |   |  
AB vs BB | 442 vs 860 | NA | 0.0014 | NA | NA
AB vs BB | 144 vs 144 | 0.004 | 0.0098 | 0.004 | 0.004

**Comment by nspope** [comment]
Hi Claire, 

yes, the old approach to folding was incorrect for multi-dimensional SFS, although I am a bit surprised to see Fst in your data greater by a factor of 2. The equivalence b/w unfolded and folded with the latest version is as it should be (as Fst is symmetric with regard to allele frequency).

It is not obvious to me why you'd get a segfault with large sample sizes. I will try to replicate

**Comment by clairemerot** [comment]
Hello, 
I managed to replicate the nan problem. It appears only in the fold version (fold in the realSFS and not saf). 
It appears at very few position in the sfs by position file but when summed, of cours it makes the global fst as well as some sliding windows "nan"
I'm uploading the sample file if you want to take a look. Thanks a lot!

Since FSt is really the same between fold and unfold, I am now running the stats without the fold option.

**Comment by nspope** [comment]
@clairemerot Thank you. I will take a look.

**Comment by ANGSD** [comment]
Both the realSFS part and the fst has been updated within the last weeks, so I am hopefull that this issue has resolved by itself.

I am therefore closing this issue but feel free to reopen or make a new issue. Please supply us with the saffiles and your estimate prior if you reopen or make a new issue.

Best
