### ISSUE TITLE
Segfault with contamination (angsd v0.931)

### ISSUE THREAD

**Issue by jfy133** [ANGSD/angsd#276]
When running the following contamination command (filenames replaced as this isn't my data), using the angsd version v0.931 installed via bioconda:

```
contamination -a <my_file>.doCounts.icnts.gz -h HapMapChrX.gz 2> <my_file>.bam.filtered_rmdup.X.contamination.out

```
I get the following segmentation fault error:
```
        -> angsd version: 0.931 (htslib: 1.9) build(Oct 25 2019 18:02:57)
[bammer_main] 1 samples in 1 input files
        -> Parsing 1 number of samples 
        -> Region lookup 1/1
[shared.cpp.changeChr():281] refid:22
Charnge chr:22

        -> Done reading data waiting for calculations to finish
        -> Done waiting for threads
        -> Output filenames:
                -><my_bam>.doCounts.arg"
                -><my_bam>.doCounts.icnts.gz"
        -> Thu Dec 19 15:52:28 2019
        -> Arguments and parameters for all analysis are located in .arg file
        -> Total number of sites analyzed: 5872
        -> Number of sites retained after filtering: 5839 
        [ALL done] cpu-time used =  0.02 sec
        [ALL done] walltime used =  0.00 sec
.command.sh: line 4: 131975 Segmentation fault      (core dumped) contamination -a <my_bam>.doCounts.icnts.gz -h HapMapChrX.gz 2> <my_bam>.X.contamination.out
```

**Comment by ANGSD** [comment]
Dear @jfy133 could you supply me with a copy of the icnts.gz?

**Comment by jfy133** [comment]
Sorry for the delay, holidays and all. Please find the requested file attached (file name changed, as above).

[my_bam.doCounts.icnts.gz](https://github.com/ANGSD/angsd/files/4014324/my_bam.doCounts.icnts.gz)

**Comment by ANGSD** [comment]
Sorry for the delay. It looks like the bam does not have any data for the marker positions. It might be a very small bam file.

I have updated the code so it doesnt segfault but give a nice informative message.
0531b2f64878dfc4bd076a68a9

Im closing this issue. Feel free to reopen if needed.

**Comment by jfy133** [comment]
Ok thank you very much! A more informtative error message is very helpful. I'll let my colleague know
