### ISSUE TITLE
analysisFunction.h:125:13: error: ‘gzFile’ was not declared in this scope

### ISSUE THREAD

**Issue by lufuhao** [ANGSD/angsd#277]
HTSSRC defined
echo '#define ANGSD_VERSION "0.931"' > version.h
gcc -c  -I/share/program/angsd/v0.931/htslib -O3   fet.c
gcc -MM -I/share/program/angsd/v0.931/htslib -O3   fet.c >fet.d
gcc -c  -I/share/program/angsd/v0.931/htslib -O3   pooled_alloc.c
gcc -MM -I/share/program/angsd/v0.931/htslib -O3   pooled_alloc.c >pooled_alloc.d
gcc -c  -I/share/program/angsd/v0.931/htslib -O3   sample.c
gcc -MM -I/share/program/angsd/v0.931/htslib -O3   sample.c >sample.d
gcc -c  -I/share/program/angsd/v0.931/htslib -O3   kprobaln.c
gcc -MM -I/share/program/angsd/v0.931/htslib -O3   kprobaln.c >kprobaln.d
gcc -c  -I/share/program/angsd/v0.931/htslib -O3   from_samtools.c
gcc -MM -I/share/program/angsd/v0.931/htslib -O3   from_samtools.c >from_samtools.d
gcc -c  -I/share/program/angsd/v0.931/htslib -O3   malloc_wrap.c
gcc -MM -I/share/program/angsd/v0.931/htslib -O3   malloc_wrap.c >malloc_wrap.d
g++ -c  -I/share/program/angsd/v0.931/htslib -O3   makeReadPool.cpp
g++ -MM -I/share/program/angsd/v0.931/htslib -O3   makeReadPool.cpp >makeReadPool.d
g++ -c  -I/share/program/angsd/v0.931/htslib -O3   abcCounts.cpp
In file included from abcCounts.cpp:8:0:
analysisFunction.h:125:13: error: ‘gzFile’ was not declared in this scope
   int tgets(gzFile gz,char**buf,int *l);
             ^
analysisFunction.h:125:23: error: expected primary-expression before ‘char’
   int tgets(gzFile gz,char**buf,int *l);
                       ^
analysisFunction.h:125:33: error: expected primary-expression before ‘int’
   int tgets(gzFile gz,char**buf,int *l);
                                 ^
analysisFunction.h:125:39: error: expression list treated as compound expression in initializer [-fpermissive]
   int tgets(gzFile gz,char**buf,int *l);
                                       ^
make: *** [Makefile:66: abcCounts.o] Error 1

**Comment by ANGSD** [comment]
Dear @lufuhao this issue was resolved in commit d22308aa5a3f3b5a1e1759c5770b5a0c7c95a226 please try to pull the most recent version and see if this resolves the issue.

I am closing this commit but feel free to reopen if needed.
