### ISSUE TITLE
Polarizing SFS with major/minor info (instead of ancestral sequence)

### ISSUE THREAD

**Issue by jordanbemmels** [ANGSD/angsd#278]
Hi, I'm trying to generate an unfolded multidimensional SFS with the SFS polarized according to the major/minor information provided in a sites file, rather than polarized according to an ancestral fasta sequence.

For the first step to generate the SAF files (-doSaf 1) for each population, I thought perhaps I could do this by using the flag -doMajorMinor 3 to use pre-specified major/minor info, and not providing any ancestral sequence (i.e., do not use the -anc flag at all). However, when I do this, I receive the error "Must supply -anc for polarizing the spectrum".

I want to make a multidimensional SFS (4 populations), so I cannot use folding to avoid this issue (because it is not possible to implement folding of the SFS for >2 populations).

How can I use the major/minor info to polarize the SAF and the SFS?

**Comment by Jungal10** [comment]
How can you do an unfolded SFS without providing ancestral sequence? To have derived and reference alleles you need to know the ancestry. Other than that you end up with info for minor/major allele and your frequencies will be toped in 0.5

**Comment by jordanbemmels** [comment]
Hi Jose, thanks for the question. Yes, this would be a little unconventional but I have populations from across two species, so I could assume the most common allele across species (i.e., the major allele calculated across those multiple populations of both species) is the ancestral one. Whether or not it's a good biological assumption is perhaps another matter (better yet if I had a third outgroup species, but I don't).

[[This may be irrelevant, but if it matters, my end goal for this is to generate a multidimensional SFS of observed data to compare to demographic simulations in fastsimcoal2. If you (or anyone reading this) are familiar with fastsimcoal2, that program can also use several independent 2D folded SFSs (which would be easy to generate in ANGSD). However, I was advised that given our interests (demographic model selection) it is preferable to use a single multidimensional SFS. So, this is what I'm trying to generate, but in the absence of a true ancestral sequence it will require some assumptions about which allele is ancestral, like I mentioned above]].

**Comment by nspope** [comment]
@jordanbemmels Three options:

1. Use an arbitrary polarization, estimate the unfolded SFS, and fold it yourself. The difference between this and realSFS w/ folded option is that in the latter case there are fewer parameters that need to be estimated by the EM algorithm (so is both faster and more accurate). However, folding it manually should produce something quite similar, especially if you use hypergeometric projection to smooth it (see comment at end).

2. Use -doFasta 2 to generate an ancestral fasta with the most common base. "Common" here is defined as the sum of depth across samples ... so if average depth is reasonably equivalent across samples, you should get a fasta with the majority-frequency allele for each SNP. Passing this to -anc should polarize as you describe above.

3. Use -doMajorMinor 3 with sites file as you are currently doing, but use -doSaf 5 (I know, I know, it's not documented). This option forces SAF estimation to use the major/minor designations produced by -doMajorMinor and should not require -anc.

A side note: realSFS estimates the SFS by maximum likelihood, treating each SFS bin as a parameter. It is important to realize that when there are many bins in the SFS, the MLE will be "patchy" (as in figure in first link [here](https://github.com/ANGSD/angsd/issues/119#issue-271313433)) Basically, in this case the MLE is overfitting the data. Whether this matters or not depends on the downstream application. With a 4d SFS there are bound to be a lot of bins. To smooth out the patchiness, use hypergeometric projection to reduce the size of the SFS along each axis (if you want to avoid doing so manually, both projection and folding are implemented in the dadi python package).

Nate

**Comment by jordanbemmels** [comment]
Nate, thank you for the several options, this is really helpful! Undocumented option #3 is exactly the functionality I was hoping existed. :)

I had initially also thought of option #1 but got stuck being unsure if conceptually understood how to fold a multidimensional SFS; after thinking about it more today, I think I know what to do.

Option #2 sounds great with ~equal depth, but my samples are quite unequal in depth.

Thanks very much for pointing me in the right direction(s).
Jordan
