### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by alissaseverson** [ANGSD/angsd#279]
I was trying to call variants from the 1000 Genomes LWK low depth data and I kept running into segfault issues. There are 101 individuals in LWK with an average of 6X coverage. For my downstream analysis I need a beagle file, maf file, and tped/tfam. Splitting up by chromosome, I was trying to call variants with the command (with the formatting from Snakemake):

```
angsd -b {input.bamlist} -out {params.prefix} -P 4 -ref {params.ref} -r {wildcards.chr}\
    -GL 1 -doMajorMinor 1 -doMaf 2 -doPlink 2 -doGeno -4 -doPost 2 -doCounts 1 -doGlf 2\
    -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -SNP_pval 1e-6 -minMaf 0.05 -minInd 3 -minMapQ 30 -minQ 20
```

I built angsd v0.931 with htslib v1.8, the system wide available version. I was worried that the segfault was due to too much writing for the four files, so I retried the command without making the tped/tfam and it still crashed. I tried increasing the memory per cpu from 4Gb to 10Gb, and that did not help either. Sometimes it would finish for smaller chromosomes and/or a subset of the data set like only 25 or 15 individuals, but it would reliably segfault for the larger sample sizes and chromosomes.

I saw in another post that users ran the command in a debugger and got the backtrace, so I tried that, but the output was unhelpful to me at least

```
(gdb) run -b bamlist.txt -out LWK.chr1 -ref hg19_nochr.fa -r 1 -GL 1 -doMajorMinor 1 -doMaf 2 -doPlink 2 -doGeno -4 -doPost 2 -doCounts 1 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -SNP_pval 1e-6 -minMaf 0.05 -minInd 3 -minMapQ 30 -minQ 20
Starting program: angsd -b bamlist.txt -out LWK.chr1 -ref hg19_nochr.fa -r 1 -GL 1 -doMajorMinor 1 -doMaf 2 -doPlink 2 -doGeno -4 -doPost 2 -doCounts 1 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -SNP_pval 1e-6 -minMaf 0.05 -minInd 3 -minMapQ 30 -minQ 20
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
	-> angsd version: 0.931-11-gec5dd20 (htslib: 1.8) build(Jan 14 2020 15:35:33)
	-> Reading fasta: hg19_nochr.fa
	-> SNP-filter using a pvalue: 1.000000e-06 correspond to 23.928127 likelihood units
[bammer_main] 101 samples in 101 input files
	-> Parsing 101 number of samples 
	-> Region lookup 1/1

	-> Allocated ~ 10 million nodes to the nodepool, this is not an estimate of the memory usage

	-> Allocated ~ 20 million nodes to the nodepool, this is not an estimate of the memory usage
	-> Printing at chr: 1 pos:5484176 chunknumber 8500 contains 342 sitess
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000000000 in ?? ()
```

I also tried downloading v0.921 and building with htslib v1.6, but that segfaulted too. Ultimately I reverted back to our systemwide installation of angsd, v0.919, built with  htslib v1.5, and the issue has gone away.

**Comment by sagitaninta** [comment]
I would like to know if this issue can be fixed without installing older version of angsd?

I also got segmentation fault issue by running this:

```
angsd -GL 2 \
> -bam bam_list \
> -doCounts 1 \
> -doMajorMinor 1 \
> -setMinDepth 3 \
> -setMaxDepth 10 \
> -doGlf 4 \
> -doPost 2 \
> -doGeno 8 \
> -out angsd_out
        -> angsd version: 0.931-21-g13af014 (htslib: 1.10.2) build(Apr 14 2020 11:29:47)
Segmentation fault (core dumped)
```
The command run just fine if I remove the `-doGeno` argument, but I would like to have all the posterior probabilities of all the possible genotypes as the documentation said it would do.

**Comment by ANGSD** [comment]
Both commands work for me on the most recent version of angsd, so could you try that?

**Comment by sagitaninta** [comment]
Is there a version newer than 0.931-21-g13af014? As you can see from my previous post, the segmentation fault happens in that version.

**Comment by sagitaninta** [comment]
I just want to update that the command is working if I specify `-doMaf`

```
$ angsd -i babirusa_mdup.bam -GL 2 -out test -r 1:10000-1000000 -dopost 2 -dogeno 8 -docounts 1
        -> angsd version: 0.931-21-g13af014 (htslib: 1.10.2) build(Apr 14 2020 11:29:47)
        -> Potential problem: You are required to choose a major/minor estimator (-doMajorMinor)
(base) btx638@gobekli:/data/btx638/genotypeProbability_2020-04-21/babirusa$ angsd -i babirusa_mdup.bam -GL 2 -out test -r 1:10000-1000000 -dopost 2 -domajorminor 1 -dogeno 8 -docounts 1
        -> angsd version: 0.931-21-g13af014 (htslib: 1.10.2) build(Apr 14 2020 11:29:47)
Segmentation fault (core dumped)
$ angsd -i babirusa_mdup.bam -GL 2 -out test -r 1:10000-1000000 -dopost 2 -domajorminor 1 -domaf 1 -dogeno 8 -docounts 1
        -> angsd version: 0.931-21-g13af014 (htslib: 1.10.2) build(Apr 14 2020 11:29:47)
[bammer_main] 1 samples in 1 input files
        -> Parsing 1 number of samples 
        -> Region lookup 1/1
        -> Printing at chr: 1 pos:959099 chunknumber 1800 contains 399 sitess
        -> Done reading data waiting for calculations to finish
        -> Done waiting for threads
        -> Output filenames:
                ->"test.arg"
                ->"test.mafs.gz"
                ->"test.geno.gz"
        -> Thu Apr 23 15:00:49 2020
        -> Arguments and parameters for all analysis are located in .arg file
        -> Total number of sites analyzed: 937032
        -> Number of sites retained after filtering: 931204 
        [ALL done] cpu-time used =  3.63 sec
        [ALL done] walltime used =  4.00 sec
$ 
```

I thought you do not need the frequency known if you want to use -doPost 2 but I think it is just me misunderstanding flat prior

**Comment by ANGSD** [comment]
The part of the code that does the frequency estimation is disjoint from the part that does the post calculation. If -dopost 2 is used then it will not use the prior.

There has been a number of changes in the code since the issue was posted so it is likely that it has been resolved, I am therefore closing this issue.
