### ISSUE TITLE
no output from abbababa

### ISSUE THREAD

**Issue by zyxplus** [ANGSD/angsd#281]
Ran a test to calculate D statistics as followings,
ANGSD -doAbbababa2 1 -bam test.bam.list -sizeFile test.bam.size -doCounts 1 -out test.bam.Angsd.1240k_test -anc $chimpFasta -rf 1240k.regio.test.v1 -useLast 1 -minQ 20 -minMapQ 13 -p 1 -nThreads 1 

the output log is:
       ......
        -> Region lookup 999/1000
        -> Region lookup 1000/1000

        -> Done reading data waiting for calculations to finish
        -> Done waiting for threads
        -> Output filenames:
                ->"test.bam.Angsd.1240k_test.arg"
                ->"test.bam.Angsd.1240k_test.abbababa2"
        -> Sat Jan 25 23:01:45 2020
        -> Arguments and parameters for all analysis are located in .arg file
        -> Total number of sites analyzed: 185109
        -> Number of sites retained after filtering: 1870 
        [ALL done] cpu-time used =  53.75 sec
        [ALL done] walltime used =  54.00 sec

"test.bam.Angsd.1240k_test.abbababa2" only shows one line:
CHR     BLOCKstart      BLOCKend        Numer   Denom   numSites 0000 .... 3333

I checked the region file, bam file header, fasta file, they all name cheomosome as "chr1..23" .
Any clue, please?

**Comment by SamueleSoraggi** [comment]
The error might be the use of -useLast 1 option, because you provide a
fasta file as outgroup and not the last group of individuals in the list of
bam files. Try to set -useLast 0 instead.



lør. 25. jan. 2020 4.08 PM skrev zyxplus <notifications@github.com>:

**Comment by ANGSD** [comment]
Im am closing this issue feel free to reopen if needed.
