### ISSUE TITLE
RealSFS - How to find number of sites

### ISSUE THREAD

**Issue by alisoncl** [ANGSD/angsd#283]
Hello,

I am struggling to understand how to calculate/find the number of sites used by realSFS to generate an unfolded 4d SFS (I need this number as the scaling factor 'L' for dadi/moments). I didn't specify anything for -nsites, so I assume it has used all available sites, but I can't seem to figure out how many "all" is.

How/where can I find this? I was thinking it might be equal to the sum of all entries in the SFS?

Any help very much appreciated!

**Comment by ANGSD** [comment]
It should be the sum of all values in the output.

**Comment by alisoncl** [comment]
Thanks!

**Comment by ANGSD** [comment]
I am closing this issue, feel free to reopen if needed.
