### ISSUE TITLE
Deamination error estimation

### ISSUE THREAD

**Issue by olgadolgova** [ANGSD/angsd#284]
Hello!
I'm trying to estimate the error rate for each nucleotide in some ancient genomes. The files created by command line <angsd -doAncError 1 -anc chimpHg19.fa -ref NA12778.fa -out results -bam bam.filelist> seem to be correct. I put only one path to bam.filelist executing it for each genome separately. But estERROR.R script worked correctly only for 1 genome out of 6, for which I obtained reasonable estimates of deamination and good graphs. For the rest of the genomes appeared the message (see below) and the error rate was the same for all nucleotides and equal to 1e-10. My question is: can I rely on these error estimations despite the graphs  are failed? I do´t really need the graphs, only error estimations.
*********************************************************************************************************
Error in plot.window(xlim = xlim, ylim = ylim, log = "") :
  need finite 'xlim' values
Calls: dotchart -> plot.window
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
Execution halted
*********************************************************************************************************
Thank you!
Olga

**Comment by SamueleSoraggi** [comment]
Hi Olga, 

could you send one of the files that give you the error with the estError.R script?

**Comment by olgadolgova** [comment]
Hi Samuele,
 
Please find attached all the output documents from angsd and R scripts for Neanderthal Altai genome.
 
Thank you,
Olga
  
>Понедельник, 3 февраля 2020, 17:13 +01:00 от Samuele Soraggi <notifications@github.com>:
> 
>Hi Olga,
>could you send one of the files that give you the error with the estError.R script?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Olga Dolgova
 
"C -> A"	"G -> A"	"T -> A"	"A -> C"	"G -> C"	"T -> C"	"A -> G"	"C -> G"	"T -> G"	"A -> T"	"C -> T"	"G -> T"
"ind"	1e-10	1e-10	1e-10	1e-10	1e-10	1e-10	1e-10	1e-10	1e-10	1e-10	1e-10	1e-10
"ind -0.3608 %"

**Comment by SamueleSoraggi** [comment]
Hi Olga,

I meant the file that you use to get such an output. Do you think you could send it to me for testing what happens?

**Comment by olgadolgova** [comment]
Hi Samuele,
Please find attached the file I used with R script.
 
Thanks,
Olga
  
>Вторник, 4 февраля 2020, 9:38 +01:00 от Samuele Soraggi <notifications@github.com>:
> 
>Hi Olga,
>I meant the file that you use to get such an output. Do you think you could send it to me for testing what happens?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Olga Dolgova

**Comment by SamueleSoraggi** [comment]
I think you did not attach it - I cannot find any attachment

**Comment by olgadolgova** [comment]
It was attached, I see it in my «sent» box as a message with attachment. Besides, it was attached along with other files to the very first message. 
Anyway, I attached it again, let’s see if now it works. The name of the file is «results.ancError».
 
Thanks,
Olga 
>Вторник, 4 февраля 2020, 16:17 +01:00 от Samuele Soraggi <notifications@github.com>:
> 
>I think you did not attach it - I cannot find any attachment
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Olga Dolgova

**Comment by SamueleSoraggi** [comment]
Hi Olga, 

forgive me, but I cannot find a way to see the attachment. Could you just send it to samuele.soraggi at gmail.com?

Sorry once more

**Comment by olgadolgova** [comment]
Hi Samuele,
 
how are you doing?
 
Did you received my email with the file in you gmail box?
 
Cheers,
Olga
  
>Среда, 5 февраля 2020, 10:38 +01:00 от Samuele Soraggi <notifications@github.com>:
> 
>Hi Olga,
>forgive me, but I cannot find a way to see the attachment. Could you just send it to samuele.soraggi at gmail.com?
>Sorry once more
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Olga Dolgova

**Comment by SamueleSoraggi** [comment]
Hi Olga

yes I got it. I try to find time today for your problem and report back on
the github issue :)

sorry for the waiting time. Tasks to finish here at work keep cumulating.

fre. 7. feb. 2020 10.50 AM skrev olgadolgova <notifications@github.com>:

**Comment by SamueleSoraggi** [comment]
Hi Olga,

I checked again step by step the estimation of errors. It seems that your data has a very low amount of errors, that goes below the minimum threshold for detecting it (that is, indeed, 1e-10). So I would say that you should consider not using the error estimations that come out of those individuals for which you get 1e-10 in all values.
The low estimate of errors might also be due to a reference genome (`-ref NA12778.fa`) that is not high quality. This would lower the amount of detected errors.

I do not get however the same error in producing the plot - I do not know if this is due to different versions of R that we are using. 

Just as a last curiosity, which rates do you get for the dataset in which you had values different from 1e-10?

**Comment by olgadolgova** [comment]
Hi Samuele,
 
Thank you so much for your reply! Such a relief! :)
The genomes that obtained the higher error rates (due to deamination) were Ust-Ishim (G->A: 0.000331884813554243 and C->T: 0.00036009299888702) and Sumidouro (ancient Native American) (G->A=C->T = 0.02). 
 
Which genome would you use as a reference in my case?
 
Thank you,
Olga
  
>Понедельник, 10 февраля 2020, 12:21 +01:00 от Samuele Soraggi <notifications@github.com>:
> 
>Hi Olga,
>I checked again step by step the estimation of errors. It seems that your data has a very low amount of errors, that goes below the minimum threshold for detecting it (that is, indeed, 1e-10). So I would say that you should consider not using the error estimations that come out of those individuals for which you get 1e-10 in all values.
>The low estimate of errors might also be due to a reference genome (-ref NA12778.fa) that is not high quality. This would lower the amount of detected errors.
>I do not get however the same error in producing the plot - I do not know if this is due to different versions of R that we are using.
>Just as a last curiosity, which rates do you get for the dataset in which you had values different from 1e-10?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Olga Dolgova

**Comment by SamueleSoraggi** [comment]
Ok, those two estimates you showed are reasonable values for ancient genomes. So the reference is probably good and the other files of better quality. Are those also ancient genomes?

**Comment by olgadolgova** [comment]
Yes, they are all ancient. the other ones are Neanderthal Altai, Denisovan, USR1 and SpiritCave.
 
Have a nice day and thanks for resolving my doubts,
Olga
  
>Понедельник, 10 февраля 2020, 13:55 +01:00 от Samuele Soraggi <notifications@github.com>:
> 
>Ok, those two estimates you showed are reasonable values for ancient genomes. So the reference is probably good and the other files of better quality. Are those also ancient genomes?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Olga Dolgova

**Comment by SamueleSoraggi** [comment]
I will close this, but open it again if in need of help :)
