### ISSUE TITLE
thetaStat fails with folded saf

### ISSUE THREAD

**Issue by evochange** [ANGSD/angsd#286]
Hello,

I have been trying to calculate thetas with folded and unfolded SFS, following the commands on the wiki page. I am using angsd version 0.928. The pipeline with the unfolded data worked with no problems:

```
angsd -P 10 -b bams.txt -anc ~/reference/ory_ancestral.fa -out all_indvs_chr2 -dosaf 1 -gl 1 -rf chr2.txt -minMapQ 20 -minQ 20 -doCounts 1 -minInd 50 -setMinDepth 50 -setMaxDepth 300 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 2 -sites ../ct_ga_filter/2.nonctga.sites.txt -ref lepus_ref.fa

/usr/local/src/angsd/misc/realSFS -P 10 all_indvs_chr2.saf.idx > all_indvs_chr2.saf.sfs

angsd -P 10 -bam bams.txt -out all_indvs_chr2_thetas -doThetas 1 -doSaf 1 -pest all_indvs_chr2.saf.sfs -anc ~/reference/ory_ancestral.fa -GL 1 -rf chr2.txt -minMapQ 20 -minQ 20 -doCounts 1 -minInd 50 -setMinDepth 50 -setMaxDepth 300 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 2 -sites ../ct_ga_filter/2.nonctga.sites.txt -ref lepus_ref.fa

/usr/local/src/angsd/misc/thetaStat do_stat all_indvs_chr2_thetas.thetas.idx -win 20000 -step 2000  -outnames all_indvs_chr2_thetas.thetasWindow.gz
```

While trying to do the same analysis with the folded spectra following the wiki page I run into an error in the final step. I used -fold 1 flag while generating the saf file in the first command and while calculating thetas in the third command. The final step with thetaStat do_stat (or even with print) fails.

```
angsd -P 10 -b bams.txt -out all_indvs_chr2_folded -doSaf 1 -fold 1 -gl 1 -rf chr2.txt -minMapQ 20 -minQ 20 -doCounts 1 -minInd 50 -setMinDepth 50 -setMaxDepth 300 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 2 -sites ../ct_ga_filter/2.nonctga.sites.txt -anc lepus_ref.fa -ref lepus_ref.fa

/usr/local/src/angsd/misc/realSFS -P 16 all_indvs_chr2_folded.saf.idx > all_indvs_chr2_folded.saf.sfs

angsd -P 10 -bam bams.txt -out all_indvs_chr2_folded_thetas_EB -doThetas 1 -fold 1 -doSaf 1 -pest all_indvs_chr2_folded.saf.sfs -GL 1 -rf chr2.txt -minMapQ 20 -minQ 20 -doCounts 1 -minInd 50 -setMinDepth 50 -setMaxDepth 300 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 2 -sites ../ct_ga_filter/2.nonctga.sites.txt -anc lepus_ref.fa -ref lepus_ref.fa

/usr/local/src/angsd/misc/thetaStat do_stat all_indvs_chr2_folded_thetas_EB.thetas.idx -win 20000 -step 2000 -outnames all_indvs_chr2_folded_thetas_EB_w20s20.thetasWindow.gz
```

This is the error I run into with thetaStat:

> thetaStat: thetaStat.cpp:50: int isok(char*, char*): Assertion `8==fread(buf,sizeof(char),8,fp)' failed.
> Aborted (core dumped)

Could this be a similar problem to #259? Should I be generating unfolded saf but folded sfs with realSFS? 

Thanks

**Comment by evochange** [comment]
I realized this error was probably due to the third command generating an incomplete output. I corrected the third command and I have no error anymore. I'm closing this issue.

**Comment by madzayasodara** [comment]
Hi I'm having a similar questioning here. I get that to calculate FST, the new is 
1 - BAMs used to generate unfolded SAF (do NOT use -fold option)
2 - unfolded SAF used to generate folded SFS (use -fold in realSFS)
3 - unfolded SAF and folded SFS used to generate per-site numerator/denominator of Fst (use -fold in realSFS fst index)
as described in https://github.com/ANGSD/angsd/issues/259 
I'm also using a reference genome that's NOT the ancestral. No ancestral available. 
How should I go about the thetas calculations, do I fold?
