### ISSUE TITLE
Identify shared regions between closely related individuals

### ISSUE THREAD

**Issue by drkmj** [ANGSD/angsd#289]
Hello,

I have used angsd to identify related individuals using ibs.  I generated the ibs matrix using:

angsd -b all.filelist.mito -nThreads 16 -minMapQ 30 -minQ 20 -GL 2  -doMajorMinor 1 -doMaf 1 -SNP_pval 2e-6 -doIBS 1 -doCounts 1 -doCov 1 -makeMatrix 1 -minMaf 0.05 -doGlf 3 -out all_out

This provided a file all_out.ibsMat which clearly separates out the individuals into 6 "families" when viewed with both hierarchical clustering and a distance-based redundancy analysis. 

What I would like to do is find which sites are most conserved within a family while being distinct from the other 5 families. I was thinking I could use the all_out.ibs.gz file which has chromosome, position, major, and minor allele followed by either a -1,0, or 1 value for each sample. I have looked online and cannot determine the meaning of these designations; however, I think they are the values that I am looking for. 

Any help would be much appreciated!

Thank you,
Kevin

**Comment by nspope** [comment]
Hi Kevin: it is documented [here](http://www.popgen.dk/angsd/index.php/PCA_MDS#sampled_bases_.2Aibs.gz), but the designations are backwards based on [the source code](https://github.com/ANGSD/angsd/blob/4c28453cf67c946deab482b8d39692af32f3faf2/abcIBS.cpp#L237). A "1" means the sampled base is the minor allele, a "0" means it is the major allele, and a "-1" means that either that the site was missing in the individual or that the sampled base is neither the major or minor.

**Comment by drkmj** [comment]
Thank you! This is exactly what I was looking for.
