### ISSUE TITLE
NGSadmix program failing without error?

### ISSUE THREAD

**Issue by devonorourke** [ANGSD/angsd#290]
I have about 200 animal samples I'd like to analyze using NGSadmix. While these individuals can be grouped into two populations based on a phenotype of resistant/susceptible to a disease, the animals will share ancestry between the phenotypic groups.

Because there are different numbers of individuals in my two phenotype groups, I created two separate genotype likelihood `.beagle.gz` files - one for each group - because I wanted to keep the number of missing individuals consistent in terms of the fraction missing (not the raw integer). However, I want to combine these files in NGSadmix to see what kind of admixture exists among all individuals in the study.  

When I run NGSadmix on the individual `beagle.gz` files the program works as expected, producing an output log indicating the interations are progressing:
```
-> Dumping file: path/to/ngsAdmix/pop1Samps.log
-> Dumping file: path/to/ngsAdmix/pop1Samps.filter
Input: lname=path/to/pop1Samps.beagle.gz nPop=3, fname=(null) qname=(null) outfiles=path/to/ngsAdmix/pop1/results
Setup: seed=1 nThreads=22 method=1
Convergence: maxIter=2000 tol=0.000010 tolLike50=0.100000 dymBound=0
Filters: misTol=0.050000 minMaf=0.050000 minLrt=0.000000 minInd=0
Input file has dim: nsites=2236576 nind=80
Input file has dim (AFTER filtering): nsites=2236563 nind=80
iter[start] like is=229835104.095479
```

however, when I run the program on the combined `beagle.gz` file, it generates this bit of output in the log file:

```
-> Dumping file: path/to/ngsAdmix/allSamps.log
-> Dumping file: path/to/ngsAdmix/allSamps.filter
Input: lname=path/to/allSamps.beagle.gz nPop=3, fname=(null) qname=(null) outfiles=path/to/ngsAdmix/allSamps/results
Setup: seed=1 nThreads=12 method=1
Convergence: maxIter=2000 tol=0.000010 tolLike50=0.100000 dymBound=0
Filters: misTol=0.050000 minMaf=0.050000 minLrt=0.000000 minInd=0
ncols=187
```

Then the program just stops. There are not warnings of memory issues, nor are there any warnings of an incorrect file format (I've seen both of these messages already from earlier tests). 

Perhaps it's not advised to manually combine these `.beagle.gz` files from the two populations for reasons I'm not aware of. I filtered the individual populations so that I retained only common SNP sites, and combined the text files so that the headers were relabeled from things like `ind0` and `ind1` to their particular sample names so that there isn't any redundancy in the first line of the combined `beagle.gz` file. The combined file is tab-delimited.

Happy to share data if that helps. Thank you for your response.

I was worried that

**Comment by nspope** [comment]
The dimensions of your beagle input are wrong. There should be 3 "indX" columns per sample. If there aren't, then ngsAdmix exits as you are experiencing (with your input it is reading 187 GL columns--not divisible by 3). Check that you merged the files correctly.

**Comment by devonorourke** [comment]
Oh man, that's embarrassing. I kept 2 columns instead of 3. 
Feel free to delete this issue until I post another boneheaded mistake :)
Thanks for the quick reply!

**Comment by ANGSD** [comment]
Thanks for using the program, I am glad things got resolved. I am closing this issue.

Best
