### ISSUE TITLE
-doMajorMinor4 bias? Sites file ignored

### ISSUE THREAD

**Issue by Jungal10** [ANGSD/angsd#291]
I have been trying to estimate some allele frequencies using angsd. These issues happen repeatedly of different sets of bam files.
settings:
```
 - GL 2
- doCounts 1
- doMajorMinor 4
- doMaf 3
- ref 
- dumpCounts 1
- minMapQ 30
- minQ 20
- SNP_pval 1e-6
- skipTriallelic 1
- nThreads 4
-sites
```
I have two different issues:
1. I use the sites file with 10k sites (sorted and indexed with angsd sites index), but I keep having in my output files millions of sites. So, I assume that angsd is ignoring it for some reason (maybe some of the other parameters conflicts with it (?)). I have tried to use it also with -rf setting, but this also did not work accordingly.

2. When I plot (histogram) the knownEM and unknownEM I have always a rather strong signal at exactly 0.5. This happens consistently with all the different sets of files I try to analyze following the above parameters. I am having a hard time trying to understand it. Maybe you can help me. One hypothesis is that since I am fixing the major allele, the algorithm will calculate frequencies from 0.5 for some cases. Not sure.

Thank you in advance

**Comment by ANGSD** [comment]
Dear @Jungal10 you need to supply the filename as parameter for the -sites argument. With regards to the 0.5 allele frequency it could be a problem of paralogue regions. Since this was posted more than 2 months ago I am closing this issue. But feel free to reopen if needed. Thanks for using the program.

Best
