### ISSUE TITLE
Filtering using -sites

### ISSUE THREAD

**Issue by biopitch** [ANGSD/angsd#293]
Hello, 

I am trying to calculate Dxy per site between two populations. I have found 3 methods to do so using ANGSD output (calcDxy.R, ngsStats, getDxy.pl). I was following [this tutorial](https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md).  

For all methods, it requires for me to call SNPs that are present in both population (either as maf or saf). But I am unable to do this using -sites.

I first create a file with a list of intersecting sites between the two population. 
```
for POP in pop1 pop2
do
echo $POP
angsd -P 5 -b $POP.filelist -out ./$POP \
-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -minMapQ 30 -minQ 20 \
-minInd 1 -setMinDepth 3 -doCounts 1 -GL 2 -doSaf 1 -anc $anc \
-ref $ref
done

realSFS print -P 10 ./pop1.saf.idx ./pop2.saf.idx | cut -f 1-2 >  ./test_intersect.txt
angsd sites ./test_intersect.txt
NSITES=`wc -l ./test_intersect.txt | cut -f 1 -d " "`
echo $NSITES
```
I get 869881095 sites.

Then I try to do SNP calling for each population using the txt file as a site filter. 
```
for POP in pop1 pop2
do
        echo $POP
        angsd -P 5 -b $POP.filelist \
        -anc $anc \
        -ref $ref -out ./$POP \
        -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1  \
        -minMapQ 30 -minQ 20 -minInd 2 -setMinDepth 3 -doCounts 1 \
        -GL 1 -doSaf 1 -doMaf 3 -doMajorMinor 1 \
        -sites ./test_intersect.txt
done
```
The number of SNPs I get are
pop1 817320435
pop2 816852917

Shouldn't I get the same amount of SNPs for pop1 and pop2? Any suggestions or advise is greatly appreciated.

**Comment by nspope** [comment]
`-minInd` differs between first and second runs through angsd -- and is more stringent in the second run. I expect that's the problem.

**Comment by biopitch** [comment]
I have tried rerunning these steps using the same -minInd of 2. I still get differing numbers. 

pop1 769743304
pop2 769742357

```
for POP in pop1 pop2
do
echo $POP
angsd -P 5 -b $POP.filelist -out ./$POP \
-uniqueOnly 2 -remove_bads 1 -only_proper_pairs 1 -minMapQ 30 -minQ 20 \
-minInd 2 -setMinDepth 3 -doCounts 1 -GL 2 -doSaf 1 -anc $anc -ref $ref
done

realSFS print -P 10 ./pop1.saf.idx ./pop2.saf.idx | cut -f 1-2 > ./test_intersect.txt
	angsd sites index ./test_intersect.txt
	NSITES=`wc -l ./test_intersect.txt | cut -f 1 -d " "`
	echo $NSITES
769743692

for POP in pop1 pop2
do
        echo $POP
        angsd -P 10 -b $POP.filelist \
        -anc $anc \
        -ref $ref -out ./F_$POP \
        -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1  \
        -minMapQ 30 -minQ 20 -minInd 2 -setMinDepth 3 -doCounts 1 \
        -GL 1 -doSaf 1 -doMaf 3 -doMajorMinor 1 \
        -sites ./test_intersect.txt
done
```

**Comment by z0on** [comment]
Try running the filtering step (including -minInd) on a total set (ie both pops together), save the sites, and then re-run it on individual pops with -sites (and no further filters) to get the stats you want

Btw -minInd 2 strikes me as very low, I always set it set it to 60-80% of total number of samples to remove spurious stuff

Cheers
Misha

iPhone. Apologies for brevity

**Comment by biopitch** [comment]
Thank you for your suggestion Misha, the number of SNPs now tally between populations. 

I am running this on a small population of 2 for testing purposes. I am under the impression that I should use 100% non-missingness for my purpose of calculating dxy since I need 1 to 1 SNP comparison between population. 

Cheers!
