### ISSUE TITLE
NGSadmix .fopt output site identity

### ISSUE THREAD

**Issue by cursorially** [ANGSD/angsd#295]
Hi there,

I have a q about the output formats for NGSadmix. The [tutorial website](http://www.popgen.dk/software/index.php/NgsAdmixTutorial) states that the .filter file contains all of the sites that have been filtered out, but my .filter files are all empty, despite sites having been filtered out. Here is an example of the relevant lines from the .log file of one of my analyses:

`Input file has dim: nsites=489 nind=37`
`Input file has dim (AFTER filtering): nsites=155 nind=37`

Clearly, many sites are being filtered. The .fopt output does indicate that only those 155 sites retained after filtering were used, but I don't know how to identify which sites those actually are. I need to know which sites those are so I can specify those in another input file for a supervised analysis.

Is there possibly an input issue in my .beagle files?

**Comment by ANGSD** [comment]
Dear @cursorially , you needed to add -printInfo 1 for the filtering values to be printet. This was not clear from the program or from the documentation of the program. I have added both.

Thanks for your input, it is much appreciated.
