### ISSUE TITLE
How to estimate SFS for mtDNA

### ISSUE THREAD

**Issue by einararn** [ANGSD/angsd#297]
Hi Angsd folks

I am trying to estimate the unfolded SFS for mtDNA from whole genome sequences using realSFS. I am getting strange results. First I pulled out the 10 sequences using -doFasta 3 and get an SFS from that

86   8  14   2  12   2  10   7  19     (with 625 fixed differences)

When I run: angsd -ref ref.fa -anc anc.fa -Gl 1 -doSaf 1 -isHap 1

realSFS gives me:

200.96 4.01 0.00 2.00 0.00 5.00 0.00 1.00 1.00 124.48 15849.55

with the invariant sites at the end and an odd-looking spectrum of mostly singletons (124; if this is the reverse)

Skipping the -isHap 1 flag the "diploid" version is

15847.69 16.43 72.20 0.000003 8.45 1.38 9.40 0.98 1.18  0.95 9.03 1.09  0.00 0.01 7.30 0.00 9.40 0.00 14.99 3.06 610.45

with numbers more in line with the fasta sequences.

So how does get unfolded haploid SFS with realsFS?

Thanks
Einar

**Comment by ANGSD** [comment]
You can do this easily on the more recent versions of angsd.
This is documented here:
http://www.popgen.dk/angsd/index.php/SFS_Estimation

I am closing this issue feel free to reopen if needed.
