### ISSUE TITLE
time for analyses depends strongly on "chromosome" number - any way to speed up?

### ISSUE THREAD

**Issue by TeresaPegan** [ANGSD/angsd#299]
Hi,
I am using ANGSD on some low coverage whole-genome sequences non model bird species. I aligned some of my species' data to a warbler non-model reference genome that is only assembled to the "scaffold level," so my resulting data ends up with 150,000 "chromosomes" (each of which is actually a scaffold). The "chromosomes" vary in size from ~2MB to just a few hundred base pairs. I am ultimately using PCAngsd with these data, and I've been making beagle files using code like this:

`./angsd -GL 2 -out MyFileOut -nThreads 24 -doGlf 2 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 -doCounts -minInd 9 -bam bams.txt
`
(adapted from http://www.popgen.dk/software/index.php/PCAngsd) 

When I run this line of code on a list of bams for my data aligned to the 150,000-scaffold warbler reference genome, it takes close to 24 hours.

I recently aligned a different species' data to a Zebra Finch reference genome which has been assembled to the chromosome level (with a few extra scaffolds - total "chromosomes" in this genome = 132). When I tried using ANGSD on these data with the same code pasted above, it took less than an hour. 

These two analyses used the same number of individuals and the data for each individual has roughly the same number of reads. The main difference, as far as I can tell, is that one analysis used data aligned to 150,000 chromosomes and one used data aligned to 132 chromosomes.

I was wondering whether you have any advice for how to optimize ANGSD for use with data aligned to genomes with many thousands of "chromosomes"? Is there a way I could get this to take less time? Thanks!

**Comment by nspope** [comment]
Unfortunately, the way that angsd handles i/o and parallelization isn't
well suited to very fragmented reference genomes (for very very fragmented
genomes, it may actually be faster to run with a single thread)

You could try making a "pseudo-reference" that consists of 20 or so long
synthetic sequences. Where each synthetic sequence is a subset of your
original scaffolds, glued together by long stretches of N's.

Nate

**Comment by TeresaPegan** [comment]
Ok, thanks for the quick response and suggestions!
