### ISSUE TITLE
Newest version breaks vcf-gl

### ISSUE THREAD

**Issue by jpuritz** [ANGSD/angsd#30]

**Comment by jpuritz** [comment]
angsd-new -vcf-GL SNP.TRSMIg95HWEmaf05dsfLibBiasFil.recode.vcf -out ./RS -fai ../reference.fasta.fai -nIND 378 
	-> angsd version: 0.911-3-gf212d58 (htslib: 1.3-35-g26b3085) build(Mar  9 2016 13:17:11)
input_vcf
	-> VCF still beta. Remember that
	   1. indels and sites that are non diallelic are discarded
	   2. will use chrom, pos, ref, alt columns
	   3. GL tags are interpreted as log10 and are scaled to ln
	   4. GP tags are interpreted directly as unscaled post probs (spec says phredscaled...)
	   5. FILTER column is currently NOT used (not sure what concensus is)
*** Error in `angsd-new': realloc(): invalid next size: 0x0000000001af9460 ***

**Comment by jpuritz** [comment]
version 9.10

angsd-new -vcf-GL SNP.TRSMIg95HWEmaf05dsfLibBiasFilND.recode.vcf -out ./RS -fai ../reference.fasta.fai -nIND 372
input_vcf
	-> VCF still beta. Remember that
	   1. indels and sites that are non diallelic are discarded
	   2. will use chrom, pos, ref, alt columns
	   3. GL tags are interpreted as log10 and are scaled to ln
	   4. GP tags are interpreted directly as unscaled post probs (spec says phredscaled...)
	   5. FILTER column is currently NOT used (not sure what concensus is)
	-> Printing at chr: dDocent_Contig_622 pos:20 chunknumber 100 skipping site:128 multiref/multialt (indel)
	-> Printing at chr: dDocent_Contig_1427 pos:12 chunknumber 300 skipping site:115 multiref/multialt (indel)
skipping site:149 multiref/multialt (indel)
skipping site:193 multiref/multialt (indel)
	-> Printing at chr: dDocent_Contig_1832 pos:28 chunknumber 400 skipping site:122 multiref/multialt (indel)
skipping site:89 multiref/multialt (indel)
	-> Printing at chr: dDocent_Contig_2207 pos:13 chunknumber 500 skipping site:199 multiref/multialt (indel)
skipping site:187 multiref/multialt (indel)
skipping site:179 multiref/multialt (indel)
...

**Comment by ANGSD** [comment]
Can you supply me with the SNP.TRSMIg95HWEmaf05dsfLibBiasFil.recode.vcf  file?

**Comment by ANGSD** [comment]
This has been fixed in the most recent version, 42a5e4c
