### ISSUE TITLE
fst calculation 

### ISSUE THREAD

**Issue by sandyplus** [ANGSD/angsd#300]
Dear angsd team:
To calculate Fst between two populations, can I get accurate results if I use only part of my data ? 
For example, I have chromosome 1 to chromosome 12. I want to get the Fst values of chromosome 1 and 2 between two populations. Is it okay to use -sites to filter other chromosomes? 

Best regards.
Sandy

**Comment by z0on** [comment]
Yes! assuming you have enough (100s) high-frequency (-maf 0.05) polymorphisms on these two chromosomes and nothing weird is going on with your creature, like for example huge non-recombining inversions like in cod, or pervasive introgression like in mosquitoes (but in those cases genome-wide Fst makes little sense anyway). 

Best use -rf to restrict angsd to the two chromosomes ( -sites will work, too, but in that case angsd seems to scan the whole genome anyway for some reason, even though other sites are not analyzed, so there’ll be no saving in time).

Misha

**Comment by ANGSD** [comment]
Hi yes, i agree with @z0on as long as you have a reasonable amount of data then it should be fine. Also -rf is much better for these whole chromosome filteres. Wheres -sites is better for specific sites. I am closing this issue, feel free to reopen if needed.
