### ISSUE TITLE
Issue calculating thetas in hapless

### ISSUE THREAD

**Issue by saramiller23** [ANGSD/angsd#302]
I'm trying to calculate SFS and estimate thetas for a set of 20 haploid individuals, but it seems like the global estimate of the SFS is outputting a diploid value not a haploid value. 

When I run these commands: 

/programs/angsd20191002/angsd/angsd -bam test.bamlist -doSaf 1 -isHap 1 -GL 1 -anc mygenome.fasta -P 24 -rf regionslist -out test
/programs/angsd20191002/angsd/misc/realSFS test.saf.idx -P 8 > test.sfs
/programs/angsd20191002/angsd/angsd -bam test.bamlist  -P 8 -doThetas 1 -doSaf 1 -isHap 1 -pest test.sfs -anc mygenome.fasta -GL 1  -out test_thetas

I get the following error at the last step:
-> angsd version: 0.931-4-g10d2f2b (htslib: 1.9-391-gf8512fb) build(Oct  2 2019 20:25:51)
-> Reading fasta: mygenome.fasta
-> File: 'test.sfs' should contain 41 values, but has 21
-> If you are supplying an estimated sfs, make sure your input file is a single line (an estimate for a single region)

Everything works fine when I remove the -isHap 1 flag.

How do specify to estimate the global SFS for haploids?
Thanks!

**Comment by ANGSD** [comment]
Sorry for the confusion, this haploid sfs was updated in one of the more recent versions. Please use this approach here:
http://www.popgen.dk/angsd/index.php/SFS_Estimation

In short you should not use -doThatas in main angsd but do this in realSFS, it makes things much simpler if the users also needed to fold.

I am closing this issue feel free to reopen if needed.
