### ISSUE TITLE
realSFS error: can't compute .ml file

### ISSUE THREAD

**Issue by CIM92** [ANGSD/angsd#303]
Hi there!

I'm trying to get an Fst estimate using ANGSD for a dataset with 2 populations and keep getting this error when running RealSFS to produce an .ml file:

-> Version of fname:ora.saf.idx is:2
[safreader.cpp->persaf_init():117] Problem reading data: ora.saf.idx

I've redone the saf computation 3 times and it didn't solve anything. Also tried to inspect the saf.idx file as suggested above and still get problems opening the same file. It only happens for 1 of the populations,
I have ran the very same pipeline with several other datasets and it always worked out fine.

What am I doing wrong this time and how can I fix it?

My code is:
./misc/realSFS red.saf.idx ora.saf.idx -r scaffold_1 > red.ora.ml

Thanks in advance :)

**Comment by ANGSD** [comment]
Could you try to printout the offending .saf.idx file to see if the file is valid.

realSFS print file.saf.idx

Best

**Comment by CIM92** [comment]
Hi,
Thanks for your reply.

I tried to do that but it still returns a "cannot open file" error.
The file has content, it's of similar size as the one computed for the
other population.

I've been running the same code on the same input files (with slight
variations on the reference genome file) for months and never encountered
this problem before...

Cheers

Cristiana

**Comment by ANGSD** [comment]
Dear Cristina could you try to cat the idx file.

cat -A ora.saf.idx

**Comment by ANGSD** [comment]
Given the lack of reply I am closing this issue.

Best
