### ISSUE TITLE
Installation error version 0.931

### ISSUE THREAD

**Issue by ddenney1** [ANGSD/angsd#304]
The latest version of ANGSD fails to make using a Mac, Ubuntu, and our cluster. This is the output from our cluster.

dd66718@sapelo2-sub2 angsd$ make HTSSRC=../htslib
HTSSRC defined
echo '#define ANGSD_VERSION "0.931-20-ge9d8927"' > version.h
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
cc -c  -I/scratch/dd66718/htslib -O3   pooled_alloc.c
cc -MM -I/scratch/dd66718/htslib -O3   pooled_alloc.c >pooled_alloc.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
cc -c  -I/scratch/dd66718/htslib -O3   from_samtools.c
cc -MM -I/scratch/dd66718/htslib -O3   from_samtools.c >from_samtools.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
cc -c  -I/scratch/dd66718/htslib -O3   malloc_wrap.c
cc -MM -I/scratch/dd66718/htslib -O3   malloc_wrap.c >malloc_wrap.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
cc -c  -I/scratch/dd66718/htslib -O3   fet.c
cc -MM -I/scratch/dd66718/htslib -O3   fet.c >fet.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
cc -c  -I/scratch/dd66718/htslib -O3   sample.c
cc -MM -I/scratch/dd66718/htslib -O3   sample.c >sample.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
cc -c  -I/scratch/dd66718/htslib -O3   kprobaln.c
cc -MM -I/scratch/dd66718/htslib -O3   kprobaln.c >kprobaln.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   makeReadPool.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   makeReadPool.cpp >makeReadPool.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcCounts.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcCounts.cpp >abcCounts.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcPSMC.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcPSMC.cpp >abcPSMC.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcMismatch.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcMismatch.cpp >abcMismatch.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   vcfReader.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   vcfReader.cpp >vcfReader.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcHWE_F.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcHWE_F.cpp >abcHWE_F.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   multiReader.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   multiReader.cpp >multiReader.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcWriteVcf.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcWriteVcf.cpp >abcWriteVcf.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   analysisFunction.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   analysisFunction.cpp >analysisFunction.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcSmartCounts.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcSmartCounts.cpp >abcSmartCounts.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcGL.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcGL.cpp >abcGL.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   shared.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   shared.cpp >shared.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcDstat.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcDstat.cpp >abcDstat.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcFilterSNP.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcFilterSNP.cpp >abcFilterSNP.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   mpileup.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   mpileup.cpp >mpileup.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   pop1_read.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   pop1_read.cpp >pop1_read.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   chisquare.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   chisquare.cpp >chisquare.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcDstat2.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcDstat2.cpp >abcDstat2.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcGetFasta.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcGetFasta.cpp >abcGetFasta.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   mUpPile.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   mUpPile.cpp >mUpPile.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcWriteBcf.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcWriteBcf.cpp >abcWriteBcf.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   cigstat.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   cigstat.cpp >cigstat.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcCovar.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcCovar.cpp >abcCovar.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   printRes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   printRes.cpp >printRes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcRAD.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcRAD.cpp >abcRAD.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   bammer_main.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   bammer_main.cpp >bammer_main.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   beagleReader.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   beagleReader.cpp >beagleReader.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcIBS.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcIBS.cpp >abcIBS.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   soap_likes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   soap_likes.cpp >soap_likes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcTemplate.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcTemplate.cpp >abcTemplate.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcAncError.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcAncError.cpp >abcAncError.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   bfgs.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   bfgs.cpp >bfgs.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   glfReader_text.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   glfReader_text.cpp >glfReader_text.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcAsso.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcAsso.cpp >abcAsso.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcWritePlink.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcWritePlink.cpp >abcWritePlink.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcMajorMinor.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcMajorMinor.cpp >abcMajorMinor.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcScounts.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcScounts.cpp >abcScounts.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcCallGenotypes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcCallGenotypes.cpp >abcCallGenotypes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcFilter.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcFilter.cpp >abcFilter.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   ancestral_likes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   ancestral_likes.cpp >ancestral_likes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   glfReader.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   glfReader.cpp >glfReader.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abc.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abc.cpp >abc.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcSaf.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcSaf.cpp >abcSaf.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcError.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcError.cpp >abcError.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcHaploCall.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcHaploCall.cpp >abcHaploCall.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcSnpTools.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcSnpTools.cpp >abcSnpTools.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcFreq.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcFreq.cpp >abcFreq.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   simple_likes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   simple_likes.cpp >simple_likes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcHWE.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcHWE.cpp >abcHWE.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   prep_sites.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   prep_sites.cpp >prep_sites.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   filterStrandBias.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   filterStrandBias.cpp >filterStrandBias.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcWriteFasta.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcWriteFasta.cpp >abcWriteFasta.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   angsd.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   angsd.cpp >angsd.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   gatk_likes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   gatk_likes.cpp >gatk_likes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   phys_genolike_calc.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   phys_genolike_calc.cpp >phys_genolike_calc.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcHetPlas.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcHetPlas.cpp >abcHetPlas.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   bam_likes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   bam_likes.cpp >bam_likes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   abcAncestry.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   abcAncestry.cpp >abcAncestry.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   phys_likes.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   phys_likes.cpp >phys_likes.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -c  -I/scratch/dd66718/htslib -O3   parseArgs_bambi.cpp
g++ -MM -I/scratch/dd66718/htslib -O3   parseArgs_bambi.cpp >parseArgs_bambi.d
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
g++ -I/scratch/dd66718/htslib -O3  -o angsd *.o /scratch/dd66718/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread -lcurl
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
abcFreq.o: In function `abcFreq::print(funkyPars*)':
abcFreq.cpp:(.text+0x1139): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x1200): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x13b2): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x1474): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x1524): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.o:abcFreq.cpp:(.text+0x1544): more undefined references to `ks_resize2(kstring_t*, unsigned long)' follow
collect2: error: ld returned 1 exit status
make: *** [angsd] Error 1

**Comment by ANGSD** [comment]
Thanks for letting me know. It should be fixed in the most recent commit 172f053e27406b308c6992e535ec824492072d1f . angsd is using the kstring_t of htslib to populate some internal variables using kputs,kputc and kputw and accessing these directly does not work in the newer versions of htslib.
