### ISSUE TITLE
Negative Fst values

### ISSUE THREAD

**Issue by NikoLichi** [ANGSD/angsd#309]
Hi there!
I have being trying to get some Fst values per gene across. 
I followed the advices in the issue #239 and compute the Fst ratio form alphaBhatia and alphaPlusbeta like: 
Ratio = (sum of alphaBhatia in gene)/(sum of alphaPlusbeta in gene)

But I have similar results as the issue #274. Some values in the sum of alphaBhatia are negatives and then convert the ratio into negative.

My question is: is this normal? To have a "normal" Fst behavior, can I convert the negative values to zero "0"? or?

I am doing the following approach to compute the unfolded Fst values, since I am doing the Fst for the sexes within a population, using ANGSD 0.929

Saf for each population
```
angsd -bam $POP1BAMSAMPLES \
-anc ref.fa \
-ref ref.fa \
-out POP1_allBAMMerged_allPos \
-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 \
-minMapQ 20 -minQ 13 -minInd 2 -setMinDepth 2 \
-doCounts 1 -GL 1 -doSaf 1

angsd -bam $POP2BAMSAMPLES \
-anc ref.fa \
-ref ref.fa \
-out POP2_allBAMMerged_allPos \
-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 \
-minMapQ 20 -minQ 13 -minInd 2 -setMinDepth 2 \
-doCounts 1 -GL 1 -doSaf 1

```
Then do the  realSFS to calculate 2dsfs prior

```
realSFS POP1_allBAMMerged_allPos.saf.idx POP2_allBAMMerged_allPos.saf.idx > POP1_POP2_allBAMMerged_allPos.ml
```
Then do the  realSFS index

```
realSFS fst index POP1_allBAMMerged_allPos.saf.idx POP2_allBAMMerged_allPos.saf.idx -sfs  POP1_POP2_allBAMMerged_allPos.ml -fstout POP1_POP2_allBAMMerged_allPos -whichFst 1
```

Print all positions:

```
realSFS fst print POP1_POP2_allBAMMerged_allPos.fst.idx > POP1_POP2_allBAMMerged_allPos.tsv

```
The result looks like: 
NC_013663.1     6543    0.000000        0.000000
NC_013663.1     6544    0.000000        0.000000
NC_013663.1     6545    -0.054963       0.402236
NC_013663.1     6546    -0.000000       0.000043
NC_013663.1     6547    -0.000000       0.000043
NC_013663.1     6548    -0.055619       0.393919
NC_013663.1     6549    -0.000003       0.000194
NC_013663.1     6550    -0.000036       0.002774
NC_013663.1     6551    -0.000002       0.000100
NC_013663.1     6552    -0.000000       0.000000
NC_013663.1     6553    -0.000000       0.000000
NC_013663.1     6554    -0.000000       0.000000
NC_013663.1     6555    -0.000000       0.000000

Thanks a lot for your help!!!
Niko

**Comment by ANGSD** [comment]
If i remember correctly these are method of moments estimators so they can become negative unlike ML estimators. I would just cap them at zero. Hopefully this helps.

Best
