### ISSUE TITLE
Missing genotype values are wrongly coded as 1/1 in bcf

### ISSUE THREAD

**Issue by alxsimon** [ANGSD/angsd#311]
Hi,
Using angsd version: 0.929-19-gb2b41b5 (htslib: 1.9-139-gce7daf7)

When producing bcf with the genotype calling, I noticed that missing genotypes (coded as -1 in .geno.gz) are written as 1/1 in the bcf file instead of ./.
This produces a bcf file without missing data and with some wrong genotypes.

the commands I am using
```
angsd -P {threads} -bam {crams} -ref {ref} -rf {regions} -sites {sites} -out {out} \
-setMinChunkSize {min_chunksize}  -doMajorMinor 3 -doMaf 1 -doCounts 1 \
-dumpCounts 4 -doGlf 2 -GL 2 -doGeno 3 -doPost 1 -doBcf 1 [and some other filtering options]
```
I don't know if the problem comes from the fact that specific commands are required for bcf output ?
angsd gives me this message before calling genotypes.
```
[bcfoutput]     Please add the following parameters
'-gl 1 -dopost 1 -domajorminor 1 -domaf 1 -dobcf 1 --ignore-RG 0 -dogeno 1 -docounts 1'
```
Can I not use other methods for -gl, -dogeno, -domajorminor and -domaf?

Thanks!

**Comment by alxsimon** [comment]
If this is not expected behaviour, I think the problem comes from the abcWriteBcf.cpp, where there is no case for missing genotype l. 179
```
    // .. FORMAT
    assert(geno);
    if(geno){
      int32_t *tmpia = (int*)malloc(bcf_hdr_nsamples(hdr)*2*sizeof(int32_t));
      for(int i=0; i<pars->nInd;i++){
	if(geno->dat[s][i]==0){
	  tmpia[2*i+0] = bcf_gt_unphased(0);
	  tmpia[2*i+1] = bcf_gt_unphased(0);
	}else if(geno->dat[s][i]==1){
	  tmpia[2*i+0] = bcf_gt_unphased(0);
	  tmpia[2*i+1] = bcf_gt_unphased(1);
	}  else{
	  tmpia[2*i+0] = bcf_gt_unphased(1);
	  tmpia[2*i+1] = bcf_gt_unphased(1);
	}
      }
```

**Comment by ANGSD** [comment]
yes, this is clearly a bug that should be fixed. Thanks for bringing this to my attention.

**Comment by alxsimon** [comment]
Happy to be helpful.
Another thing I noticed, is that all my FORMAT/DP for all individuals have the same value. I would expect them to vary from one individual to the other.
I can open another issue about that if needed.

**Comment by ANGSD** [comment]
Thanks for reporting these things, it is much appreciated.
