### ISSUE TITLE
Single sample heterozygosity

### ISSUE THREAD

**Issue by lucasrocmoreira** [ANGSD/angsd#314]
Hi,

I am trying to estimate heterozygosity for each of my samples. I followed the instructions on the website. I first produced a single sample SAF file:

`angsd -gl 2 -dosaf 1 -fold 1 -anc $ref -ref $ref -rf chromosomes.txt -C 50 -minMapQ 30 -minQ 20 -nThreads 16 -i $i -out $name.total`

Then, I estimated the sfs:
```
saf=$name.total.saf.idx
realSFS $saf > $name.total.sfs
```
Finally, I just calculated the ratio between the second value of the resulting sfs and the total number of sites (value 1 + value 2). 

The problem is that my estimate of heterozygosity are orders of magnitude smaller than I expect them to be. I find values between 0.0035-0.005 (realistic estimates should be between 0.01-0.3). Estimates from vcftools using called genotypes show larger values (0.01-0.05).

Is there anything I'm missing here that might explain why I'm getting these estimates?

**Comment by ANGSD** [comment]
Could you try to increase the number of emstep and lower the tolerance in the realSFS
-maxiter 2000 -tole 1e-16

The stopping criteria was based on some analyses i did for much larger sample size so they might be too relaxed for a single sample.

**Comment by nspope** [comment]
Is the denominator of the ratio the same between your vcftools & angsd attempts? That is, is the number of sites (rows in BCF/VCF) the same as the total number of sites from the angsd single-sample SFS?

To put this another way: single-sample heterozygosity of 0.01 - 0.3 might be reasonable if you are only considering segregating sites, but if you're consider all sites (monomorphic + segregating), 0.01 - 0.3 would be extremely high given the per-base mutation rates of most eukaryotes

**Comment by lucasrocmoreira** [comment]
Thanks for the quick response.

I think that makes a lot of sense. I guess most estimates of heterozygosity in the literature are based on segregating sites only, whereas mine considers all sites.

I will try to increase the number of emstep and lower the tolerance to see if I see any difference, though.

**Comment by nspope** [comment]
Yup. 

If you want to restrict the estimate (or any analysis) to segregating sites with angsd, you'd probably want to call SNPs with all your samples, and then use that subset of sites via the `-sites` or `-rf` options.

Alternatively you could estimate the multi-sample SFS using the same options as you use above (e.g. same total number of sites), calculate the number of segregating sites (sum of non-monomorphic SFS bins), and adjust your denominator accordingly

**Comment by TeresaPegan** [comment]
Thanks so much, I sent you the files! 
My beagle file definitely shows numerous likely-heterozygous sites. It's harder for me to understand SAF output, but here is a sliver of it. If we're looking for AFs with the highest likelihoods and the second out of three columns represents an AF of 1 (i.e. heterozygous diploid), I would have thought there are a few heterozygous sites in here, like 2583402 (second row shown) and 2583492, etc?

I really appreciate that you are taking a look!

Thanks,
-Teresa



```
CM027507.1	2583401	0.000000	-0.599958	-0.799979
CM027507.1	2583402	-0.999202	0.000000	-0.999202
CM027507.1	2583407	0.000000	-0.599958	-0.799979
CM027507.1	2583413	0.000000	-0.599958	-0.799979
CM027507.1	2583416	-0.799979	-0.599958	0.000000
CM027507.1	2583420	0.000000	-0.599958	-0.799979
CM027507.1	2583430	0.000000	-0.599958	-0.799979
CM027507.1	2583451	0.000000	-0.599958	-0.799979
CM027507.1	2583457	0.000000	-0.599958	-0.799979
CM027507.1	2583490	0.000000	-0.599958	-0.799979
CM027507.1	2583492	-0.999202	0.000000	-0.999202
CM027507.1	2583514	0.000000	-0.599958	-0.799979
CM027507.1	2583515	-0.999202	0.000000	-0.999202
CM027507.1	2583528	-0.799979	-0.599958	0.000000
CM027507.1	2583533	0.000000	-0.599958	-0.799979
```

**Comment by nspope** [comment]
I see what is going on -- it is not a bug per se but a gap in documentation and definite "gotcha". For some reason, the beagle *input* is expected to be log-transformed. So if you log-transform and then run, e.g.

```
BEAGLE=path/to/my/beagle/input
echo "
beagle <- read.table('${BEAGLE}')
beagle[,-c(1:3)] <- log(beagle[,-c(1:3)])
write.table(beagle, '${BEAGLE}.logged', row.names=F, col.names=F, quote=F)
" | R --slave

angsd -beagle ${BEAGLE}.logged -doSaf 4 <other stuff>
```
you should get the correct SAF.

I'll create an issue to address this -- I think we can just check that the GLs are <= 0 (e.g. log scaled) and print an informative error for the time being.
