### ISSUE TITLE
hg38 ancestral states

### ISSUE THREAD

**Issue by jaavedm** [ANGSD/angsd#318]
I downloaded the ancestral states for hg19 at `http://popgen.dk/software/download/angsd/hg19ancNoChr.fa.gz`. 
Is there the ancestral states for hg38 pre-computed already? Or can you tell me how I can make such a fasta file?

**Comment by ANGSD** [comment]
See this link:
http://ftp.ensembl.org/pub/release-76/fasta/ancestral_alleles/
As suggested by @RAHenriksen

I am closing this issue feel free to reopen if needed.
