### ISSUE TITLE
The name of Haploid calling

### ISSUE THREAD

**Issue by MaoYafei** [ANGSD/angsd#32]
Hi all,

When I do the haploid calling from bam file, the outfile looks like below:
chr     pos     major   ind0    ind1    ind2    ind3
sc0000012       2416    T       T       T       T       N       
sc0000012       2417    G       G       G       G       G       
sc0000012       2418    A       A       A       N       A       
sc0000012       2420    G       G       G       N       G  

the outfile seems like that they cant automatically replace @SM for ind0/1/2/3. So I am wondering whether the index of ind (ind0/1/2/3) should be same as the order of bam.list file. 

For example: I have the bam.list file looks like below:
bar.Adif.bam
bar.Aech.bam
bar.Agem.bam
bar.Asub.bam

In this case, ind0 should be Adif, ind1 should be Aech, ind2 shoud be Agem, ind3 should be Asub,right?

Thanks a lot

Best, 
Yafei

**Comment by ANGSD** [comment]
Hi Yafei, you are right, the order of individuals is the order of the bams. The program does not use any information from the header apart from chromosome name and their lengths. I'm closing this issue, but feel free to reopen or start a new issue. 

Best

**Comment by MaoYafei** [comment]
Thanks so much~
Plus, the major should be the ref genome, right ?

**Comment by aalbrechtsen** [comment]
major is the major allele i.e. the allele that is most common of the sampled alleles

**Comment by MaoYafei** [comment]
Thanks  a lot ~
