### ISSUE TITLE
Query re. -doGeno

### ISSUE THREAD

**Issue by DrLaurenCWhite** [ANGSD/angsd#320]
Hello,
I have a question about the .geno.gz output from -doGeno 2 (I am using -doGeno 18 to also write the posterior probabilities of the genotypes to the file). Are the output genotypes, (0, 1, 2) the counts of alternate or minor alleles. I was assuming the former but when comparing the .geno file to .mafs I ran into some confusion. The call I am using is below.
Thank you for your time.
-Lauren

angsd -P 1 -b My.bamlist -r chr1 -ref MyRef.fa -out MyOut -GL 1 -doGlf 2 -doMajorMinor 1 -doMaf 3 -doGeno 18 -doPost 1 -trim 0 -C 50 -baq 1 -minMapQ 20 -minQ 20 -SNP_pval 1e-6 -minInd 50  -geno_minDepth 3 -doCounts 1

**Comment by ANGSD** [comment]
Sorry for the long delay, the output is the count of the minor. I have updated the wiki accordingly.
http://www.popgen.dk/angsd/index.php/Genotype_calling#Options
