### ISSUE TITLE
dosaf ignoring -sites

### ISSUE THREAD

**Issue by TonyKess** [ANGSD/angsd#322]
Hello,

Using angsd version: 0.933-52-g8623f2f (htslib: 1.5), I am trying to export SFS for a specific genomic region using -dosaf the with the -sites command for a bed file indexed with angsd. When I attempt this, I get the following warning:

Potential problem: The filereading has reached a chromsome: 'chr01', which is not included in your '-sites' file.
	-> Please consider limiting your analysis to the chromsomes of interest 
	-> see 'http://www.popgen.dk/angsd/index.php/Sites' for more information
	-> Program will continue reading this chromosome... 

And then angsd ignores the sites command does this:
Printing at chr: chr01 pos:558657 chunknumber 200 contains 3378 sites

Has anyone encountered this problem before?

**Comment by z0on** [comment]
my understanding is that it does not actually ignore -sites at the output level, but still scans all the contigs in the genome. Consider making a file listing contigs that appear in the sites file
cut -f 1 mysites >mycontigs 
and supplying it as -rf argument

**Comment by TonyKess** [comment]
Thanks! I should have seen the rf option. I'll close this now!
