### ISSUE TITLE
-minIndDepth removed

### ISSUE THREAD

**Issue by aguilar-gomez** [ANGSD/angsd#323]
Why did you remove this option from latest versions of angsd? It was useful

**Comment by nspope** [comment]
It's now `-setMinDepthInd` and `-setMaxDepthInd`

The wiki needs updating. Best to check the command-line help (in this case `angsd -doCounts`) for arguments, as that usually stays more up-to-date.

**Comment by aguilar-gomez** [comment]
The way I was using minIndDepth was in combination with minInd: 
`-minInd 20 -minIndDepth 1`
with the idea that a site should be kept if at least in 20 individuals it had 1x 

However I looked at the new documentation and it seems, it discards individuals, not sites: 
```
-setMinDepthInd [int]
Discard individual if sequencing depth for an individual is below [int]. This filter is only applied to analysis which are based on counts of alleles i.e. analysis that uses [-doCounts](https://www.popgen.dk/angsd/index.php/Alleles_counts)
```

I think it discards the individual if its average depth is below the number set, which I find a lot less useful. Please correct me if I am wrong. I do not think it discards the individual if it has less than the number set at any position, because I set it to 1 and did not lose any individuals. People working with angsd are using low coverage with regions that would have zero coverage. So, is the filter for filtering individuals based on whole genome average depth  (and not useful for filtering sites)? 

Thank you
