### ISSUE TITLE
Error: No header information could be found for BAM/CRAM file

### ISSUE THREAD

**Issue by mgb1985** [ANGSD/angsd#324]
Hi!

I want to generate SFS for plenty of samples listed in bam.list.

I use this script:
```
ref2019='/home/myref.fa'
mapq='30'    # min MapQ
minq='20'    # min Q
while read indv; do
angsd -i $indv -anc $ref2019 -dosaf 1 -GL 2 -fold 1 -minMapQ $mapq -minQ $minq -out $indv
#realSFS $indv\.saf.idx > $indv|.sfs
done < bam.list
```

I get the error:
`No header information could be found for BAM/CRAM file
`

I don't understand what is the issue?
Strangely, when I use the list to generate a population SFS (using -bam option instead of -i), it is working.

What can I do?

Thanks,

Mgb

**Comment by ANGSD** [comment]
So -i is for multiple samples -b is for a file list. -b is short for -bam.

But the sfs code has been updated quite alot recently so either pull the latest version of angsd or wait a few days til im finished updating it.

**Comment by mgb1985** [comment]
> So -i is for multiple samples -b is for a file list. -b is short for -bam. But the sfs code has been updated quite alot recently so either pull the latest version of angsd or wait a few days til im finished updating it.
> […](#)

Thanks for your reply.
I think I misunderstood -i.
How can I do to generate a SFS on each bam listed in my bam.list?

The script I provided above is not OK?

Thanks,

**Comment by ANGSD** [comment]
You can find documentation here:
http://www.popgen.dk/angsd/index.php/SFS_Estimation

I am closing this issue, feel free to reopen if needed.
