### ISSUE TITLE
SFS calculation for 5 populations (realSFS)

### ISSUE THREAD

**Issue by alxsimon** [ANGSD/angsd#325]
Hi, I may have the need to compute 5D SFS using realSFS (for example the method Moments can take up to 5D SFS). In its present state it stops at 4.

I had a look at the code and it seems quite straightforward to implement it and I think I could have a go to do it when I will need it.

However, I wanted to check first with you the reason it was not implemented:
Is there a mathematical limit to doing it? or is it just that there was no use for it at the time?
I imagine the EM algorithm would take quite some time to run but it is fine to produce one spectrum.

Thanks
Alexis

**Comment by alxsimon** [comment]
Thank you for pointing me to the paper and considering pushing this forward.
Let me know if I can do anything to help.

**Comment by nspope** [comment]
@alxsimon the new `nspope_bandedDP` branch should be able to handle an arbitrary number of populations with realSFS (although it might take a very long time ...), folded or unfolded. It'll be merged into master before too long, but you can also clone it separately if you need to use it now.

**Comment by alxsimon** [comment]
Thank you @nspope, I will be trying it as soon as I get my data ready to run and let you know.

**Comment by ANGSD** [comment]
Dear all, the nspope_bandedDP branch is now merged into the master. I am closing this issue.

Best
