### ISSUE TITLE
Check missing rate for each sample

### ISSUE THREAD

**Issue by elizeng** [ANGSD/angsd#326]
Is there an output that calculates how many loci are being considered/not considered as a percentage total loci output?

Currently I can only use the `.geno` output to briefly look at the missingness per locus but would like a summary of this for each sample. Something along the lines of plink's `--missing` function that allows one to see the amount of missing data per sample.

I would like to know the missing rate to assess if the results were an impact of missing data, other issues, or a reflection of true population structure.

Thank you.

**Comment by ANGSD** [comment]
This is not something I have considered. It would definitely be very easy to include. But I think this metric would be quite similar to the standard coverage that is routinely calculated as part of the qc prior to the downstream analyses, so I dont think it is something that is on the high priority list. I will therefore close this issue.
