### ISSUE TITLE
interpretation of thetas output: pairwise, thetaD?

### ISSUE THREAD

**Issue by TeresaPegan** [ANGSD/angsd#327]
Hello,
I am interested in comparing output from ANGSD with output from another program that reports "Tajima's pi", which I think is the estimate of pairwise differences used in calculation of Tajima's D. Upon looking at the list of estimators that ANGSD can give from the page [Thetas,Tajima,Neutrality tests ](http://www.popgen.dk/angsd/index.php/Thetas,Tajima,Neutrality_tests ), I would guess that the equivalent estimator is "Pairwise" or "tP."

However, when discussing Tajima's D, the webpage says this: 

> If you don't have the ancestral states, you can still calculate the Watterson and Tajima theta, which means you can perform the Tajima's D neutrality test statistic. But this requires you to use the folded sfs. The output files will have the same format, but only the thetaW and thetaD, and tajimas D is meaningful.

Watterson's Theta and thetaW seem straightforward, but the other component of Tajima's D is referred to here as "Tajima theta" and then "thetaD". Neither of those estimators are listed in the example output.

Am I right to assume that the estimator I am looking for is "pairwise"? What is "thetaD"?

Thanks!
-Teresa

**Comment by ANGSD** [comment]
ok I can see this is confusing.

We have theta estimators.

1. wattersons theta=thetaW, based on the number of segregating sites
2. pairwise theta=Tp which is also called tajimas theta.

These two estimates can be used for a netrality test called tajimas D.

Hopefully this help. Otherwise write back.

**Comment by TeresaPegan** [comment]
Yes, that helps clarify things, thanks!
