### ISSUE TITLE
Correction and Scaling of Diversity Estimators in Theta Sliding Window Output (pestPG file) 

### ISSUE THREAD

**Issue by Callithrix-omics** [ANGSD/angsd#329]
Hi, 
I have two questions: 

1. Could you please  clarify how theta diversity estimators such as nucleotide diversity and Watterson's Theta are scaled in the pestPG output file after you do a sliding window analysis of out.thetas.idx ? 

On the page http://www.popgen.dk/angsd/index.php/Thetas,Tajima,Neutrality_tests#Example_Output it says 
- Output in the ./thetaStat print thetas.idx are the log scaled per site estimates of the thetas
- Output in the pestPG file are the sum of the per site estimates for a region

Which base of the log scale was used, if you want to convert back to linear values. 

2. Also, looking thru some recent publications I see that some authors correct theta estimators like nucleotide diversity by dividing "the sum of per-site π by the number of variant and invariant sites in a given window." (e.g., https://onlinelibrary.wiley.com/doi/full/10.1111/mec.15401). In the pestPG output file, could you get this correction for nucleotide diversity, for example,  by dividing tP by nSites? 

regards and thank you.

**Comment by clairemerot** [comment]
Maybe, this could help: The theta Watterson or theta Pi per window should be divided by the total number of sites (last column in the full theta output). I followed what is done in : https://www.biorxiv.org/content/10.1101/2020.06.27.175091v1.full.pdf
The values make more sense in my dataset.
Cheers
Claire

**Comment by Callithrix-omics** [comment]
I ended up doing that too. thank you for the suggestion.

**Comment by ANGSD** [comment]
Yes that it definitely a good approach. I would be carefull if you have very varying coverage along the genome. Like capture or radseq data.

**Comment by BelenJM** [comment]
Hi, I calculated some theta and pi estimates out from some capture data, with medium coverage. @ANGSD Can you elaborate more on why varying coverage along the genome could bias these estimates?

**Comment by ekhowell** [comment]
Hi, I just wanted to follow up on the question @Callithrix-omics asked– are the per-site diversity estimates contained in the .thetas.idx/.thetas.gz output scaled using log base 10 or base e? Thanks!

**Comment by nspope** [comment]
Seems to be natural log, [here](https://github.com/ANGSD/angsd/blob/88fd84d8e44f8399bae451774139589d7278b3a9/misc/thetaStat.cpp#L449) is relevant line in source

**Comment by ANGSD** [comment]
Natural log.
