### ISSUE TITLE
incongruence result in ABBA-BABA test

### ISSUE THREAD

**Issue by MaoYafei** [ANGSD/angsd#33]
Hi all,

I am trying to do ABBA-BABA test in two ways:
1. using -doAbbababa directly,
2. using haplotyping to get haplotype and calculate D-value by myself
and, I set the same parameters for these two run but these two got huge different results there. 

I have done ABBA-BABA test using -doAbbababa 1 using bam file as input:

angsd -doAbbababa 1 -blockSize 5000000 -anc Aten.fa -doCounts 1 -minQ 30 -minMapQ 60 -P 24  -setMinDepth 100  -setMaxDepth 1200 -out five_abba_30 -setMinDepth 100 -setMaxDepth 1200  -bam Bam.list #Aten.fa was assembed by myself and should be outgroup
 
Results:

Aech_group_realigned_reads.bam  Adif_group_realigned_reads.bam  Asub_group_realigned_reads.bam  348168  353385  -0.007436359    -0.007436359    0.002436614     -3.051924  

Also, I am trying to do haplotyping and do ABBA-BABA by myself:

/work/student/yafei-mao/angsd_dep/angsd -minQ 30 -doCounts 1 -setMinDepth 100 -setMaxDepth 1200 -minMapQ 60 -dohaplocall 1 -maxMis 0 -out aln_des_30 -bam bam_aln_des.list
less aln_des_30.haplo.gz |cat >aln_des.txt
#here aln_des.txt looks like
#chr     pos     major   ind0    ind1    ind2    ind3
#sc0000012       2474    C       C       C       C       C       
#sc0000012       2477    C       C       C       C       C       
#...
#ind0:  Adif_group_realigned_reads.bam
#ind1:  Aech_group_realigned_reads.bam
#ind2:  Asub_group_realigned_reads.bam
#ind3:  Aten_group_realigned_reads.bam (outgroup)
#python code
infile=open('aln_des.txt','r')
outfile=open('block_file','w')
step=5000000 #'block size'
ABBA=0
BABA=0
mark='sc0000012' #same as first chr in 'aln_des.txt'
n=1
for line in infile:
        if line.strip()[0]=='c': continue
        L=line.strip().split('\t')
        if mark==L[0]:
                if int(L[1])<=int(step*n):
                        if L[6]==L[3]!='N' and L[4]==L[5]!='N' and L[3]!=L[4]:
                                ABBA=ABBA+1
                        elif L[6]==L[4]!='N' and L[3]==L[5]!='N' and L[4]!=L[3]:
                                BABA=BABA+1
                else:
                     	outfile.write(L[0]+'\t'+str(step*(n-1))+'\t'+str(step*n)+'\t'+str(ABBA)+'\t'+str(BABA)+'\n')
                        n=n+1
                        ABBA=0
                        BABA=0
        else:
             	outfile.write(mark+'\t'+str(step*(n-1))+'\t'+str(step*n)+'\t'+str(ABBA)+'\t'+str(BABA)+'\n')
                n=1
                ABBA=0
                BABA=0
                mark=L[0]
                continue
infile.close()
outfile.close()

#here, the block_file looks like:
#sc0000012       0       5000000 1403    756
#sc0000002       0       5000000 1418    775
#sc0000013       0       5000000 1530    832
#sc0000007       0       5000000 1580    1008

cat block_file|awk '{sum+=$4} END {print "Sum = ", sum}'
#Sum = 287075
cat block_file|awk '{sum+=$5} END {print "Sum = ", sum}'
#Sum = 206104
 Results:
Aech_group_realigned_reads.bam  Adif_group_realigned_reads.bam  Asub_group_realigned_reads.bam  206104  287075 0.19

Here, you will find the two results are huge different. I am not sure why these two results are so different. I have a simple idea below:
1. Using bam file to do ABBA-BABA test directly, I used Aten.fa as ref outgoup, which genome has more information (including mate pair), so that I could got more ABBA-BABA pattern. However, calling haplotype I lost lots of mate pair reads in Aten.bam (much missing data).  So that I got low number of ABBA-BABA pattern.

Do you think the second way(haplotyping and do ABBA-BABA) is reasonable? And also, how could I calculate D-value for each of scaffold (-Chr) directly using -doAbbababa?

Thanks a lot~
Yafei

**Comment by MaoYafei** [comment]
I do not know why I cannot make tab in python code here, sorry for that=-=

**Comment by ANGSD** [comment]
faar du issues mailsne fra github?

**Comment by aalbrechtsen** [comment]
Hi Yafel

If you use a large block size then each block with correspond to a single scaffold. You can then calculate the D-stat from the .abbababa files. You can see how the abbababa files are parsed in the R/jackKnife.R file. 

-Anders

**Comment by MaoYafei** [comment]
HI Anders,

Thanks so much, actually, I tried to read R script. Sadly, I am not good at R, but I will try my best to look again. If you do not mind, could briefly introduce what's meaning for each of column in abbababa file?
BTW, do you think the large block size will affect the detecting introgression?

Thanks so much,
Yafei

**Comment by ANGSD** [comment]
Hi Yafei, Please see the documentation for a description of the output.
http://www.popgen.dk/angsd/index.php/Abbababa#Output

**Comment by MaoYafei** [comment]
Thanks a lot ^^
Yafei

**Comment by ANGSD** [comment]
Ok, Im assuming this can be closed now.
