### ISSUE TITLE
bcf output does not show missing data

### ISSUE THREAD

**Issue by rioten** [ANGSD/angsd#332]
Hello, 

Using ANGSD version 0.930, I am trying to create a bcf file from .bam files to find missing data per individual via VCFtools. The main problem sees to be that that neither the .geno.gz nor the vcf* output shows missing data. 

*even though I am using -dobcf 1, the ".bcf" states: 
> ##fileformat=VCFv4.2

I am using the commands below:

> angsd -bam {bamlist} -out {output} -P 10 -ref {ref} \-sites {sites} \
> -dobcf 1 -GL 1 \
> -minMapQ 30 -minQ 30 -minInd 24 -geno_minDepth 2 -uniqueOnly 1 \
> -trim -C -only_proper_pairs 1 -baq 1 \
> -minMaf 0.05 -SNP_pval 1e-6 -postCutoff 0.95 \
> --ignore-RG 0 -dogeno 20 -docounts 1 -doMajorMinor 1 -doMaf 1 -dopost 1

Are there any required commands that I may be missing? Do any of my commands here conflict?

Thanks!

**Comment by ANGSD** [comment]
I am not sure how vcftools infers missing data. If you are looking at the output bcf from angsd the GT will be encoded as ./. But maybe vcftools is using a different tag.

`./angsd -b list.list -r 1: -dobcf 1 -domajorminor 1 -dopost 1 -gl 1 -domaf 1  -dogeno 20
bcftools view -H angsdput.bcf |head -n1
1	13999902	.	A	C	0	PASS	NS=1;AF=7.81206e-06	GT:GL:PL:GP	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	0/0:0,-0.301034,-2.9:0,3,29:0,51.0723,131.145	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0	./.:0,0,0:0,0,0:0,0,0
`
I am therefore closing this issue, but feel free to reopen if needed.

Best
