### ISSUE TITLE
Restrict -doSaf to regions based on depth of coverage

### ISSUE THREAD

**Issue by DeondeJager** [ANGSD/angsd#335]
Hi,

Is there a way to restrict the action of `-doSaf` to regions with different depths of coverage? 

For example, I would like to calculate the single sample SFS and subsequently calculate heterozygosity, in three different categories: low coverage (read depth = 2-10), medium coverage (read depth = 11-20) and high coverage (read depth = 21-30). Then compare the heterozygosity for each of these categories within each sample to determine the effect of read depth on the heterozygosity estimate. This was suggested by a reviewer who suspects the heterozygosity might be pushed up by low coverage regions, because the individuals (African buffalo) had quite high het estimates for a mammal (we had previously just estimated the genome-wide heterozygosity per sample following this procedure: http://www.popgen.dk/angsd/index.php/Heterozygosity).

This is what I tried and thought it would work nicely: I used bedtools to generate merged bed files of low, medium and high coverage regions in each sample and converted this to a region file as recognised by ANGSD as follows: `bedtools genomecov -bg -ibam A_251_14_aln-PE_sorted_dups_marked.bam -g $CHRSIZES | awk '$4 > 1 && $4 < 11' | bedtools merge -i - | sed 's/\t/:/;s/\t/-/' > A_251_14_lowcov.merge.regions`. Here's what the regions file looks like (it is sorted by chr and pos):

Super_Scaffold0:62-411
Super_Scaffold0:637-640
Super_Scaffold0:837-885
Super_Scaffold0:2168-2203
Super_Scaffold0:2213-2476
Super_Scaffold0:2483-2497

The problem is, there are >13 million regions in this regions file, so when I include it in `-doSaf` it takes very, very long to process it. In fact, after doing a run for 24 hrs, I stopped it to check progress and calculated it would take something like 695 real-time hours to complete the analysis. I also tried to include the regions file in the `realSFS` analysis using `-rf`, but it doesn't recognise the command.

Any help and/or advice would be appreciated!

**Comment by ANGSD** [comment]
Hello sorry for the delayed response.
When using -rf the program is using the indexing feature for the sequencing data and this might take long to calculate. My recommendation would be to define the sites of interest using the -sites feature. Then program will loop across all scaffolds but will only output for the sites defined in the -sites. I am closing this issue, but reopen if it is still relevant.

Thanks
