### ISSUE TITLE
Speeding up dosaf, realSFS for joint SFS, FST

### ISSUE THREAD

**Issue by TonyKess** [ANGSD/angsd#337]
Hello,

I was wondering if anyone had suggestions for speeding up calculation for joint SFS and FST? Even restricted to individual chromosomes I am finding that this process times out on a cluster with scheduling limitations (e.g. processes can run for a few days). For reference my dataset is ~150 individuals sequenced at ~3x for any joint SFS comparison. Any tips?

Thanks!

Tony

**Comment by ANGSD** [comment]
Hi Tony, glad you asked.

There is a new branch that will be merged into the master branch that should speed up these things.

Its made together with @nspope and is called nspope_bandedDP

I trust it myself but i havent had time to update the test script which is the reason that it hasnt been pulled into the masterbranch yet.

It implements the heurestic defined here:  https://doi.org/10.1093/bioinformatics/btu725 <https://doi.org/10.1093/bioinformatics/btu725>

Best

**Comment by TonyKess** [comment]
Thanks! Testing it on a chromosome now!
