### ISSUE TITLE
glfReader.cpp error

### ISSUE THREAD

**Issue by cbossu** [ANGSD/angsd#339]
Hello,

I'm trying to use the .glf file for the downstream ngsDist analysis. However, when I run the script to convert the .glf to a format used by ngsDist (using angsd), I run into a glfReader.cpp error. It does not matter if I use the script for a .glf 4 file or and .glf 3 file.

The code I run is: 

angsd -P 16 -glf BUOW.Plate1-3.noSC.rmrelFinal.baq.maf.glf3.glf.gz -fai BUOW.fasta.fai -nInd 167 -doMajorMinor 1 -doPost 1 -doMaf 1 -doGeno 32 -out all_noSC.rmrelFinal_32
	
and it runs fine until the error happens:
       -> angsd version: 0.933 (htslib: 1.9) build(May  6 2020 21:25:11)
	-> Printing at chr: scaffold1|size15271748 pos:4951 chunknumber 100 contains 50 sites
        ...
	-> Printing at chr: scaffold1|size15271748 pos:739951 chunknumber 14800 contains 50 sites
	-> Printing at chr: scaffold1|size15271748 pos:744951 chunknumber 14900 contains 50 sites
	-> Printing at chr: scaffold1|size15271748 pos:749951 chunknumber 15000 contains 50 sites

**[glfReader.cpp:fetch():34] Error reading full chunk: bytesRead:5344 expected:13360 will exit**

This happens at the same place in my genome for my glf4 and glf3 file. Note (the above script is for the glf3 file, there's a slightly different script for the normal text that is in glf 4. Any idea what this means? Is my glf corrupted? I should note, I've been able to use the .glf 4 files (generated separately for each population) to run ngsLD. Although that glf4 file goes directly into the program. Now I'm trying to format the glf data for ngsDist, but angsd is having trouble reading it. Any help would be great. Best,

Ch

**Comment by ANGSD** [comment]
Dear @cbossu I dont think this is still relevant and sorry for the much delayed response time.

With regards to the issue, you should contact @fgvieira he would now what kind of input ngsDist expects. If this issue is still relevant I would need the input file that was used for your analyses. Given that this issue was posted so long ago I am taking the liberty to close the issue, but feel free to reopen.
