### ISSUE TITLE
beagle genotype posteriors as input (-doSaf 4 and -beagle)

### ISSUE THREAD

**Issue by marqueda** [ANGSD/angsd#34]
Dear angsd-developers,

I tried to create an saf file from genotype likelihoods in a beagle file:
angsd -beagle file_BEAGLE.input -doSaf 4 -doGeno 32 -out out -fai file.fai -anc file.fas -underFlowProtect 1 -fold 0

This worked nicely in version 0.610 up to version 0.614, but 0.911 down to version 0.800 ask in addition for -GL and bam files to work on, instead of beagle genotype posteriors. Is -beagle not anymore supported in this context or is this a bug?

Addition: When providing a -glf file (and -nInd) instead of a beagle file as input, angsd produces a segfault. So, likely a bug?

Thank you for your help,
David

**Comment by ANGSD** [comment]
Should be fised in this commit:
4d4642ded2c1599d5eec96cda034b8f0e2b90167

**Comment by marqueda** [comment]
Fantastic, thank you for your fast reply and fix!
Best, David
