### ISSUE TITLE
Does angsd multithread across cores/cpus?

### ISSUE THREAD

**Issue by madzayasodara** [ANGSD/angsd#341]
Using a cluster where each core/cpu has 2 threads, and each node 24 cores/cpus. 
If I designate angsd -nThreads 24, will it multithread across cores/cpus, if I request -c 12 in my slurm submission?
Thxs!
-mdz

**Comment by ANGSD** [comment]
Most analyses is limited by the diskio so in my experience you would not gain anything from specifying nthreads higher than 6.

**Comment by madzayasodara** [comment]
Oh got it!. 
So, if I do -nThreads 6 and request -c 3, it will know how to go across cpus?

**Comment by ANGSD** [comment]
I am not familiar with slurm, so i dont know about submitting parameters.
Sorry.

Den tor. 27. aug. 2020 kl. 21.23 skrev Madza Farias-Virgens <
notifications@github.com>:

**Comment by madzayasodara** [comment]
I get it. I just need to know if angsd multithread across cpus.
If it doesn't It wont help it if I give it 3 cpus, thinking that it will run on the 6 threads. 
And in this case I should just give 2 threads, which is what 1 cpu has (in this specific cluster). 
thxs!

**Comment by madzayasodara** [comment]
Jus to close up this issue. Yes performance increases greatly with using  6 threads, which in the structure of the cluster I use can be done using 3 cpus. ANGSD seems to be multithreading across cpus to compute using the 6 threads, as requested.
