### ISSUE TITLE
PROB in generating SFS

### ISSUE THREAD

**Issue by mlaylwar** [ANGSD/angsd#347]
Hi,

I am trying to generate the site frequency spectrum from bam files. The command runs ok and generates the files. However, I am then getting an error in downstream processes trying to use these files. In the std error output for some sites I receive the following
PROBs at: chrom  position

From looking at a vcf of sites for these samples it seems that this issue is arising at triallelic sites. Is there an argument to filter for maximum number of alleles? Or any other way to deal with the PROBs error.

Thanks,

Megan

**Comment by ANGSD** [comment]
Hello, I am afraid I will need more information to resolve this. I am not certain if this is still relevant. So I will close this issue in the near future.
