### ISSUE TITLE
Sites filter outputs no sites

### ISSUE THREAD

**Issue by druryc** [ANGSD/angsd#348]
Hi,

I am unable to get the -sites filter to work (version: 0.931 (htslib: 1.9)). I have simplified this analysis far as possible just trying to get it to work at all, testing in .bam files that I know contain these sites and with no other filters. I have also tested this with and without a regions file, which does not resolve the final output. Any ideas where i could be going wrong? I do notice that abcFilter says 'sites is still in beta, use at your own risk'. Is there a different version i should be using?

example sites file (tab separated, no header, indexed successfully): sites.txt
chr4	8163563
chr7	9391071
chr9	8270989

code:
`angsd -bam testlist.txt -GL 1 -nThreads 10 -doGlf 2 -doMajorMinor 1 -doMaf 2 -doCounts 1 -dumpCounts 2 -sites sites.txt -out addl` 

output:
	-> Done reading data waiting for calculations to finish
	-> Done waiting for threads
	-> Output filenames:
		->"addl.arg"
		->"addl.pos.gz"
		->"addl.counts.gz"
		->"addl.beagle.gz"
		->"addl.mafs.gz"
	-> Sat Sep 19 19:50:14 2020
	-> Arguments and parameters for all analysis are located in .arg file
	-> Total number of sites analyzed: 3328032
	-> Number of sites retained after filtering: 0 
	[ALL done] cpu-time used =  27.31 sec
	[ALL done] walltime used =  32.00 sec

**Comment by ANGSD** [comment]
how does your sites files look? Did you remember to index it?

angsd sites index sites.txt

**Comment by druryc** [comment]
I followed the format on the wiki and it appears to have been successfully indexed, although see the note about 'use at own' risk below? the chromosomes should be formatted as in the reference, correct (i.e. 'chr1', not '1')? 

My sites file looks as follows (tab separated):

chr4 8163563
chr7 9391071
chr9 8270989

I get the following when i index it:
	-> angsd version: 0.931 (htslib: 1.9) build(Aug 28 2019 05:50:59)
	-> Indexing sites.txt and will add '0' to pos column
	-> Filterfile: sites.txt supplied will generate binary representations... 
	-> Input file has 2 columns, chr pos
	-> Writing chr:'chr4' 
	-> Filtering complete: Observed: 1 different chromosomes from file:sites.txt
	-> Generated files:	
		'sites.txt.bin'
		'sites.txt.idx'
 
and this after running:
	-> Printing at chr: chr4 pos:29088726 chunknumber 6300 contains 380 sites
	-> Done reading data waiting for calculations to finish
	-> Done waiting for threads
	-> Output filenames:
		->"addl.arg"
		->"addl.pos.gz"
		->"addl.counts.gz"
		->"addl.beagle.gz"
		->"addl.mafs.gz"
	-> Mon Sep 21 14:25:22 2020
	-> Arguments and parameters for all analysis are located in .arg file
	-> Total number of sites analyzed: 1409884
	-> Number of sites retained after filtering: 0 
	[ALL done] cpu-time used =  12.32 sec
	[ALL done] walltime used =  13.00 sec

**Comment by ANGSD** [comment]
try to validate if the binary representation looks fine

./angsd sites print sites.txt

**Comment by druryc** [comment]
This is what i get, which looks right as far as i can tell -- testing it on only a single site that i know is in the dataset.

`angsd sites print sites.txt`
	-> angsd version: 0.931 (htslib: 1.9) build(Aug 28 2019 05:50:59)
	-> [prep_sites.cpp] Reading binary representation of 'sites.txt'
	-> [prep_sites.cpp] nChr: 1 loaded from binary filter file

---------------
fp:0x55967aa15d50
bg:0x55967aa1dff0
hasExtra:0 nchr:1
chr:	'chr4'	last:	'8163663'		offs:0

**Comment by ANGSD** [comment]
This is what I get when I run your example, notice that I am also using cat -A to print out the tabs properly in the example below
cat test.txt
chr4	8163563
chr7	9391071
chr9	8270989

cat -A test.txt 
chr4^I8163563$erslev angsd.master]$ .
chr7^I9391071$
chr9^I8270989$
./angsd sites index test.txt
	-> Indexing test.txt and will add '0' to pos column
	-> Filterfile: test.txt supplied will generate binary representations... 
	-> Input file has 2 columns, chr pos
	-> Writing chr:'chr4' 
	-> Writing chr:'chr7' 
	-> Writing chr:'chr9' 
	-> Filtering complete: Observed: 3 different chromosomes from file:test.txt
	-> Generated files:	
		'test.txt.bin'
		'test.txt.idx'
 ./angsd sites print test.txt
	-> [prep_sites.cpp] Reading binary representation of 'test.txt'
	-> [prep_sites.cpp] nChr: 3 loaded from binary filter file
@@	fp:0x151f2d0	qbg:0x151f190	hasExtra:0 nchr:3
@@	chr:	'chr4'	last:	'8163563'		offs:0
@@	chr:	'chr7'	last:	'9391071'		offs:863240192
@@	chr:	'chr9'	last:	'8270989'		offs:1853685760
chr4	8163563
chr7	9391071
chr9	8270989
From this example it looks like it is working and I am therefore assuming it is a malformed file you have used. I am therefore closing this issue, but feel free to reopen if needed.
