### ISSUE TITLE
Fail to open bam.file

### ISSUE THREAD

**Issue by HanXiaoEvo** [ANGSD/angsd#349]
Hi people,

I have checked the previous relevant post but can not find a solution so I am posting again. The error I got: 
[E::hts_open_format] Failed to open file /data4/Han_charr_ddRAD_2020/demographic_analysis/thingvallavatn_DA/SFS_thingva/thingva_PI/ThPI_1.bam
angsd: multiReader.cpp:380: multiReader::multiReader(int, char**): Assertion `in' failed.Aborted (core dumped)

You can see that I provided the path and actually all the files were in the same folder and were used for SNP calling already, so they all exist and not empty.

Some additional info:
1. santools view XXX.bam | head works.
2. samtools index XXX.bam, didn't work, the error is: 
[E::hts_idx_push] Region 1747042382..1747042497 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6samtools index: failed to create index for "ThPI_1.bam": Numerical result out of range

The reference genome is in a draft state and has many scafford.

Hope someone can help me solve it! Thank you very much!

Best regards,
Han

**Comment by ANGSD** [comment]
im not sure what the issue is. I suggest you make an issue regarding the index problem over at samtools. The underlaying engine for reading bam/cram in angsd is htslib. So as soon as your bam/crams work in samtools then they should in angsd.

**Comment by HanXiaoEvo** [comment]
Thanks for your quick reply and will do that!

**Comment by HanXiaoEvo** [comment]
Well I am also wondering to make it work if anything else is needed. In the folder, I only provide the bam.list and the bam files, I assume this should not be a problem.

**Comment by HanXiaoEvo** [comment]
I am wondering does it somehow correlate to the header?

**Comment by HanXiaoEvo** [comment]
Sry that I just found the reason for this and it should be closed. I didn´t notice that the bam list must be ended up with .filelist.
