### ISSUE TITLE
realSFS -sites making very large log files

### ISSUE THREAD

**Issue by silastittes** [ANGSD/angsd#355]
Hello, 

realSFS using the -sites flag appears to be working for me, but the following message is printed many times

	-> Only read nSites: 21761 will therefore prepare next chromosome (or exit)
	-> Done reading data from chromosome will prepare next chromosome

Is there anyway to avoid this? My log files are > 100Gb of these two lines repeated!  

angsd version: 0.931-2-gfd2a527-dirty (htslib: 1.9-353-gefa7aa6-dirty) build(Sep 16 2019 10:44:32)

**Comment by silastittes** [comment]
Not a solution exactly, but I got around the issue using -sites to generate the saf files, then realSFS without the -sites flag.

**Comment by ANGSD** [comment]
I have added a few lines of code such that it does not print this information too many times. I am closing this issue.
