### ISSUE TITLE
feature request: interval/site list/range

### ISSUE THREAD

**Issue by tommycarstensen** [ANGSD/angsd#36]
It would be cool if I could specify a range of sites or a list of sites for ANGSD to call. Thanks.

It owuld be equivalent to --intervals in GATK:
https://www.broadinstitute.org/gatk/guide/tooldocs/org_broadinstitute_gatk_engine_CommandLineGATK.php#--intervals

**Comment by ANGSD** [comment]
That should allready be possible with the -sites argument.  See this:
http://www.popgen.dk/angsd/index.php/Sites

Let me know if this wasnt what you were looking for.

**Comment by tommycarstensen** [comment]
It's exactly what I was looking for. Apologies for the raised ticket/issue. Thanks!

I get this message though:
	-> [abcFilter.cpp] -sites is still beta, use at own risk...
