### ISSUE TITLE
SFS with high variation in coverage across samples

### ISSUE THREAD

**Issue by mrml500** [ANGSD/angsd#360]
Hi, I am attempting to generate SFS files using ANGSD for later use with fastsimcoal2 and dadi. I have large variation in coverage between samples - from 3X to 36X coverage (although most are 6X to 15X). I read [here ](https://www.biorxiv.org/content/10.1101/165928v1.full.pdf) that not accounting for high variation in coverage across samples could bias SFS estimation - and to avoid this by discarding the lowest coverage outliers and down-sampling reads from highest-coverage outliers. How would you go about down-sampling reads from highest-coverage outliers using ANGSD? 
Many thanks,
Mike

**Comment by ANGSD** [comment]
Hello Mike, it would not be my first option to downsample higher coverage data. If the genotype likelihoods are modelled correctly it should solve the issues concerning variation in coverage between samples. There currently is not an option for doing this directly in angsd, but it can ofcourse be done by a first parse of the data and set filters accordingly. I am closing this issue, but feel free to reopen.
