### ISSUE TITLE
[question] Any recommendation on doing indel realignment or not?

### ISSUE THREAD

**Issue by alxsimon** [ANGSD/angsd#362]
Hi, my current pipeline was integrating GATK3 IndelRealigner before working with ANGSD.
As I need to re-map my individuals and that step is time expensive, I am wondering if I should keep it.
Do you have experience and recommendations on either doing this step or not.

It is now not recommended in other calling softwares, because they integrate some king of local realignment during calling (GATK4, Freebayes). From what I understand this is not the case in ANGSD.

I would really appreciate to have the ANGSD community's opinion and experience on this.
Thanks
Alexis

**Comment by TonyKess** [comment]
Does anyone else have thoughts on either of these approaches? Also curious whether it's necessary - the original ANGSD manuscript states indels are internally represented, but not sure whether that means active alignment around indels is occuring.

**Comment by nspope** [comment]
The only option to deal with indels "natively" in ANGSD is to use BAQ, which just calls the relevant parts of htslib (or uses existing BAQ annotations in the bam). I think it's pretty much accepted that some sort of re-scoring (or re-alignment) around indels is a good idea. I'm really not sure how much worse BAQ performs relative to local realignment ala HaplotypeCaller, but I'd assume that BAQ is more sensitive to spurious indels. 

You could always use bcf files output by GATK4 (or whatever) as input into ANGSD, as long as they have genotype likelihood annotations.

**Comment by ANGSD** [comment]
Yes I agree with @nspope and will close this issue.

Best
