### ISSUE TITLE
Many more called sites output .glf file than -sites file

### ISSUE THREAD

**Issue by ghost** [ANGSD/angsd#364]
Hi, 

I am using angsd to creat a .glf and .maf file for further use in ngsRelate. When i use the option -GL 1 I get only sites that were identified through my -sites and -rf file. However, when I switch to -GL 2 I get about 5x the number of sites than are specified in the sites file. The only thing I changed is the calling method of the .glf file. Is there any explanation for this?

Thanks in advance

**Comment by ANGSD** [comment]
I can not replicate this in my example

`
 ./angsd -gl 1 -doglf 2 -b flist -domajorminor 1 -r 1
	-> Total number of sites analyzed: 100164
	-> Number of sites retained after filtering: 100163 
 gunzip -c angsdput.beagle.gz |wc -l
  100164
gunzip -c angsdput.beagle.gz |sed 1d|head -n20 |tail -n5|cut -f1 | tr "_" "\t" >sites
 cat sites
1	13999934
1	13999935
1	13999936
1	13999938
1	13999939
 ./angsd sites index sites
	-> Indexing sites and will add '0' to pos column
	-> Filterfile: sites supplied will generate binary representations... 
	-> Input file has 2 columns, chr pos
	-> Writing chr:'1' 
	-> Filtering complete: Observed: 1 different chromosomes from file:sites
	-> Generated files:	
		'sites.bin'
		'sites.idx'
./angsd sites print sites
	-> [prep_sites.cpp] Reading binary representation of 'sites'
	-> [prep_sites.cpp] nChr: 1 loaded from binary filter file
@@	fp:0x7ff85afc27c0	qbg:0x6000023fc0e0	hasExtra:0 nchr:1
@@	chr:	'1'	last:	'13999939'		offs:0
1	13999934
1	13999935
1	13999936
1	13999938
1	13999939
 ./angsd -gl 1 -doglf 2 -b flist -domajorminor 1 -r 1 -sites sites
	-> angsd version: 0.937-60-g8c44589 (htslib: 1.14-9-ge769401) build(Mar  2 2022 21:57:59)
	-> Number of sites retained after filtering: 5 
 gunzip -c angsdput.beagle.gz |wc -l
       6
`
So from this analyses it does not seem to be a problem anymore and I am therefore closing this issue.
