### ISSUE TITLE
vcfreader problem

### ISSUE THREAD

**Issue by smallfishcui** [ANGSD/angsd#365]
Hi,
I am using angsd 0.933, with the command:
angsd -vcf-gl AU.vcf -doSaf 1 -anc Y17.fasta -P 24 -out AU
Howwever I always get the error message:
angsd: vcfReader.cpp:40: htsstuff* htsstuff_init(char*, char*): Assertion `hs->hts_file' failed.
Then U used 0.932,0.931, same thing happened.
Anyone knows the reason?

Thanks,
Cui

**Comment by ANGSD** [comment]
Hello, I was just testing this in the most recent version, and here the issue seems to have been resolved so I am closing this issue.
