### ISSUE TITLE
issue about 2d sfs

### ISSUE THREAD

**Issue by willright28** [ANGSD/angsd#367]
Hi everyone:
When I tried to do 2dsfs, it failed and reported `realSFS: realSFS_shared.cpp:133: int set_intersect_pos(std::vector<persaf*>&, char*, int, int, char**, filt*): Assertion tsk[i]==tsk[i-1]' failed.`      
But 1dsfs was produced successfully based on the .saf.idx I used.

So could anyone help me with that? Thanks in advance!!!

**Comment by ANGSD** [comment]
Hello, sorry for not getting back to you sooner. I am afraid I will need the saf files for being able to resolve this. Let me know if this is still relevant otherwise I will close the issue in the near future.

**Comment by willright28** [comment]
Thanks for your reply. Please close this issue.



---Original---
From: ***@***.***&gt;
Date: Fri, Feb 25, 2022 04:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ANGSD/angsd] issue about 2d sfs (#367)




 
Hello, sorry for not getting back to you sooner. I am afraid I will need the saf files for being able to resolve this. Let me know if this is still relevant otherwise I will close the issue in the near future.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
