### ISSUE TITLE
Error with abbababa1

### ISSUE THREAD

**Issue by biopitch** [ANGSD/angsd#368]
Hi all, 

I have been trying to run abbababa1 on my files but I have been encountering an error. I first done SNP calling using the following code
```
angsd -doAbbababa 1 -P 5 -bam ./abbababa.filelist -rmTrans 1 -out ./abba \
 -useLast 1 -doCounts 1 -blockSize 50000 -minInd 45 -minIndDepth 3 

```

I then try to carry out the jackknife.R script as follows:

`Rscript jackKnife.R file='./abba.abbababa' indNames='./abbababa.filelist' outfile='./abba_out'`

I got this output

```
Read 56 items
The length 56  of indNames does not match the number of individuals in ./abba.abbababa 
Error in q("n") : unrecognized value of 'save'
Execution halted
```

I'm not sure why this is happening, since I using the same filelist. Any help is appreciated.

**Comment by SamueleSoraggi** [comment]
just a guess: might that be because your list includes the outgroup name
and the R script does not use it?

tor. d. 10. dec. 2020 3.09 AM skrev biopitch <notifications@github.com>:
