### ISSUE TITLE
Make warning: Comparing a pointer to a null character constant

### ISSUE THREAD

**Issue by cryptic0** [ANGSD/angsd#369]
The compilation itself appears to have worked since I am able to run the ``./angsd`` binary. However, the following warning was generated.  Does it have any bearing on the functionality?

``cc -I"/Users/MACUSER/software/htslib" -O3  msHOT2glf.c -O3 -o msHOT2glf -std=gnu99 "/Users/MACUSER/software/htslib/libhts.a" -lz -lm -lbz2 -llzma -lpthread -lcurl  -lz -lm -lbz2 -llzma -lpthread
msHOT2glf.c:497:16: warning: comparing a pointer to a null character constant; did you mean to compare to NULL? [-Wpointer-compare]
    if(tmppch=='\0')
               ^~~~
               (void *)0
1 warning generated.
``

**Comment by ANGSD** [comment]
It is not a warning I have seen, but given that the code has been used for quite some time, I would not be too concerned about this. I am closing this issue.
