### ISSUE TITLE
angsd -rf combined with -sites seems to fail

### ISSUE THREAD

**Issue by tommycarstensen** [ANGSD/angsd#37]
I'm running angsd like this:

$angsd -bam $bam -GL 1 -doMaf 2 -doMajorMinor 1 -doGeno 9 -ref $ref  -sites $sites -doPost 1 -out $out -rf $rf

I get this error message despite my bam being indexed:

[main_samview] random alignment retrieval only works for indexed BAM or CRAM files. (file: 'bamse_og_kylling.bam' )

Is it because I used an older version of tabix to index my file? What's going on?

I just tried to index one of the bam files with samtools 1.3 and it seems to work. Can you somehow make it compatible with index files generated using an older version of samtools?

**Comment by tommycarstensen** [comment]
OK, I indexed all the files with samtools 1.3 and I still get the same error. Very odd. It works fine without the -rf flag it seems, but it's very very slow.

**Comment by ANGSD** [comment]
How does your  $sites file look?
You should index it with angsd sites index yourfile.txt

The -sites is a passive filter, and the -rf is using the index of the seqfiles.

**Comment by tommycarstensen** [comment]
My sites file is tab separated and indexed with `angsd sites index $sites`. Here is the head:

    1	949696
    1	949739
    1	976962
    1	985955
    1	986143
    1	1149118
    1	1167659
    1	1167674
    1	1167851
    1	1167858

Very odd. All of the bam files are indexed and can be randomly accessed by samtools and GATK and other tools. The cat of the -rf file looks like this:

    1

**Comment by ANGSD** [comment]
Ok,sorry for the delayed response.
Could you do one thing.
./angsd sites print $sites. And check that the indexing of the file looks ok.

**Comment by tommycarstensen** [comment]
Thanks Anders. I just noticed that the sites file has duplicates (converted from a VCF with separate records for SNPs and indels). That might be the issues? Below output from `./angsd sites print $sites`
 
	-> angsd version: 0.911-11-g42a5e4c (htslib: 1.3-50-g653f45e) build(Apr  5 2016 14:37:00)
	-> [prep_sites.cpp] Reading binary representation of 'out_split/DMsites0000'
	-> [prep_sites.cpp] nChr: 1 loaded from binary filter file

---------------
fp:0x2666120
bg:0x266e3c0
hasMajMin:0 nchr:1
chr:	'1'	last:	'5937323'		offs:0
------------
1	949696
1	949739
1	976962
1	985955
1	986143
1	1149118
1	1167659
1	1167674
1	1167851
1	1167858
1	1168010
1	1168064
1	1168124
1	1168239
1	1168277
1	1168307
1	1168352
1	1168557
1	1168583
1	2160267
1	2160297
1	2160299
1	2160300
1	2160305
1	2160306
1	2160308
1	2160309
1	2160484
1	2160552
1	2160554
1	2337254
1	2337267
1	2337954
1	2337965
1	2337967
1	2338000
1	2338005
1	2338015
1	2338019
1	2338205
1	2338230
1	2338288
1	2338297
1	2339890
1	2340118
1	2340139
1	2340153
1	2340258
1	2340280
1	2340283
1	2340288
1	2343913
1	2343937
1	2343939
1	2343940
1	3319489
1	3319550
1	3328329
1	3328865
1	3329208
1	3331180
1	3347452
1	5924474
1	5924528
1	5924535
1	5924544
1	5925201
1	5925205
1	5925272
1	5925275
1	5925304
1	5926432
1	5926503
1	5927090
1	5927141
1	5927799
1	5927868
1	5927904
1	5927908
1	5927943
1	5927957
1	5933335
1	5933354
1	5934566
1	5934581
1	5934612
1	5934631
1	5934694
1	5934941
1	5934967
1	5935006
1	5935064
1	5935096
1	5935142
1	5937254
1	5937323

**Comment by ANGSD** [comment]
Ok, maybe im missreading but do we have 2 issues? 1) The -rf doesn't work ? 2) the -sites options doesn't work?

If you positions of interest are spread out across the entire genome, the -sites is to be preferred. Could you do a run like:
$angsd -bam $bam -GL 1 -doMaf 2 -doMajorMinor 1 -doGeno 9 -ref $ref -sites $sites -doPost 1 -out $out 
(that is without the -rf)
The expected behaviour here is that you should only get output from the sites in your $sites file.

**Comment by ANGSD** [comment]
Btw duplicate positions doesnt matter in the 2 column input in the sites file. The only requirements is that it is sorted according to column1.

**Comment by tommycarstensen** [comment]
I have one issue. -rf does not work in combination with -sites. Without -rf it works, but it seems to be incredibly slow. As a comparison GATK ran within a few hours on the same set of sites. We opted to run with -sites and without -rf, so feel free to close this issue. Thanks for your time!

**Comment by ANGSD** [comment]
Yes, the -rf option corresponds to looping over each -r region in samtools. So for each region it would parse the seq index and move the filepointer accordingly. The -sites option pops all reads, but limits the analysis to the sites defined by -sites
