### ISSUE TITLE
angsd sites index: prep_sites.cpp:443: void filt_gen(const char*, int, int): Assertion `posS>0' failed

### ISSUE THREAD

**Issue by HomereAMK** [ANGSD/angsd#370]
Hello,

I'm trying to run this piece  of code
`angsd sites index sorted.2.SCAND_SNPList_MME_SNPs.txt`

I'm getting this error:

> 	-> angsd version: 0.929-19-gb2b41b5 (htslib: 1.9-139-gce7daf7) build(Oct 28 2019 12:49:14)
> 	-> Indexing sorted.2.SCAND_SNPList_MME_SNPs.txt and will add '0' to pos column
> 	-> Filterfile: sorted.2.SCAND_SNPList_MME_SNPs.txt supplied will generate binary representations...
> 	-> Input file has 4 columns, chr pos major minor
> angsd: prep_sites.cpp:443: void filt_gen(const char*, int, int): Assertion `posS>0' failed.
> Aborted
> 

The input file have been sorted:

`head -10 sorted.2.SCAND_SNPList_MME_SNPs.txt`

> scaffold10_1000001	0	1	0.941178
> scaffold10_10000188	3	0	0.333333
> scaffold10_10000203	1	3	0.333333
> scaffold10_1000044	2	0	0.996109
> scaffold10_10000532	2	0	0.333333
> scaffold10_10000613	0	3	0.333333
> scaffold10_10000762	1	0	0.333333
> scaffold10_10000862	0	1	0.333333
> scaffold10_10000867	3	1	0.333333
> scaffold10_1000087	0	1	0.984616

Thanks,
Homère

**Comment by ANGSD** [comment]
I just pushed a new version that gives more information than 'assertion ... failed'. 

So please 

git pull;make clean;make

And try to rerun.

Best

**Comment by HomereAMK** [comment]
Hi again,

Thanks for the quick answer:

did the git pull:
`[hmon@g-12-l0002 angsd]$ git pull
Already up-to-date.`

same log message
`/angsd sites index nt_results/sorted.2.SCAND_SNPList_MME_SNPs.txt
	-> Indexing nt_results/sorted.2.SCAND_SNPList_MME_SNPs.txt and will add '0' to pos column
	-> Filterfile: nt_results/sorted.2.SCAND_SNPList_MME_SNPs.txt supplied will generate binary representations...
	-> Input file has 4 columns, chr pos major minor
angsd: prep_sites.cpp:449: void filt_gen(const char*, int, int): Assertion posS>0' failed.
Aborted`

**Comment by ANGSD** [comment]
Hi Sorry, I hadnt pushed my commit from my local repos to github.

Please try again.

**Comment by HomereAMK** [comment]
Nothing has changed  
git pull

> git pull
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/ANGSD/angsd
   b0d8011..44d4618  master     -> origin/master
Updating b0d8011..44d4618
Fast-forward
 prep_sites.cpp | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

Same log file 

> /home/projects/dp_00007/people/hmon/reads_lib1_jan2021/angsd/angsd sites index nt_results/sorted.2.SCAND_SNPList_MME_SNPs.txt
> 	-> Indexing nt_results/sorted.2.SCAND_SNPList_MME_SNPs.txt and will add '0' to pos column
> 	-> Filterfile: nt_results/sorted.2.SCAND_SNPList_MME_SNPs.txt supplied will generate binary representations...
> 	-> Input file has 4 columns, chr pos major minor
> 	-> Problem surrounding line: 1
> angsd: prep_sites.cpp:453: void filt_gen(const char*, int, int): Assertion `posS>0' failed.
> Aborted
> > 
> 
> > 

`	-> angsd version: 0.933-107-g44d4618 (htslib: 1.11-42-gf39dae7) build(Jan 19 2021 12:25:27)`

**Comment by ANGSD** [comment]
Dear @HomereAMK sorry for not getting back to you.

The program says that there is an issue around line1. And that the program believes that the position is negative or zero but it should be positive. 

Now that I look properly at your input file, I can see that it is malformed.

See this link for more detailed explanation of how it should look:
http://www.popgen.dk/angsd/index.php/Sites

I am closing this issue but feel free to reopen.
