### ISSUE TITLE
The -rf doesn't seem to work with realSFS

### ISSUE THREAD

**Issue by ashotmarg** [ANGSD/angsd#371]
Hi guys,

When I use the realSFS with a region "-r" it works: 
$ ~/bin/angsd/misc/realSFS -fold 1 myFile.saf.idx -r CM018076.1:327342-328020

However, when I have a region file (regionFile.txt) of the same region, provided with "-rf" it doesn't seem to work:
$ cat regionFile.txt
CM018076.1:327342-328020

$ ~/bin/angsd/misc/realSFS -fold 1 myFile.saf.idx -rf regionFile.txt 
        -> Version of fname: myFile.saf.idx is:2
        -> Assuming .saf.gz file: myFile.saf.gz
        -> Assuming .saf.pos.gz: myFile.saf.pos.gz
        -> Problem opening file: '-rf'

I am using ANGSD version 0.933.

Incidentally, someone else seems to have had the same issue, though it was posted somewhere else: https://github.com/mfumagalli/ngsTools/issues/18

Any comments/suggestions would be appreciated,
Ashot

**Comment by nspope** [comment]
iirc, there's no -rf argument for the ./realSFS executable, only -r and
-sites. 'angsd' executable does have -rf, so you could always dump the
*.saf.* files for the regions of interest and then use realSFS.

**Comment by ashotmarg2004** [comment]
OK, thanks a lot for the feedback. Yeah I ended up using actually -sites (as -rf was very slow) with angsd for getting the *.saf.* files and then used reasSFS.
