### ISSUE TITLE
Paralog removal

### ISSUE THREAD

**Issue by emilya21** [ANGSD/angsd#373]
Hi, I am trying to remove paralogs from my data but I am having issues implementing the new -maxHetFreq command. I just cloned the most recent version of Angsd from github last week. I am trying to remove all sites with a max frequency of heterozygotes above .5 using the following command:

angsd -GL 1 -ref ${ref} -anc ${ref} -dosaf 1 -bam ${POP}_list.txt -out ${POP}.500.nofilter.het -nThreads 28 -doHWE -maxHetFreq 0.5

and the error file reads:

**17 argument     0.5 is unknown will exit**

I would appreciate some clarification as there is no documentation about these filters at http://www.popgen.dk/angsd

**Comment by nspope** [comment]
You need to add "1" after -doHWE. So: `./angsd <stuff> -doHWE 1 -maxHetFreq
0.5`

Nate

**Comment by ANGSD** [comment]
For removing paralogs you might want to try this tool:
https://github.com/tplinderoth/ngsParalog

I am closing this issue, but feel free to reopen.
