### ISSUE TITLE
fst nsites output option?

### ISSUE THREAD

**Issue by tvkent** [ANGSD/angsd#38]
The angsd fst function for sliding windows works nicely, but the output doesn't contain a column listing the number of sites within a window used to calculate the average for that window.  It would be useful to have this in the output similar to that in the thetas output. This would allow users to drop windows which contain below some threshold number of sites, i.e. I think there's quite a few windows in my output that have only a handful of sites post-filtering and I'd like to know which ones

**Comment by ANGSD** [comment]
Sure, that will be useful. Ill keep this issue open until i implement it natively. As a workaround you can actually subtract the first two integers in the first parenthesis in the sliding window output, these contains the index of the first and last position for the window

**Comment by tvkent** [comment]
Thanks!

For the workaround, though, if there's any missing sites within that window, the last-first route will over-count the number of actual sites in the window, no? I assume this information is in the joint sfs, though.

**Comment by ANGSD** [comment]
No the difference will be the actual number of sites with data.

The first column in the output hasn't been described on the fst page on the wiki. This is of course an oversight. Im using the same code for the sliding fst analysis as for the neutrality test statistic. So you can  see a description here: http://www.popgen.dk/angsd/index.php/Tajima#.thetas.gz.pestPG

It can be described as:
(indexStart,indexStop)(posStart,posStop)(regStat,regStop)

* The posStart and posStop is the first physical position, and last physical postion of sites included in the analysis.
* The regStat and regStop is the physical region for which the analysis is performed. Therefore the posStat and posStop is always included within the regStart and regStop
* The indexStart and IndexStop is the position within the internal array.

**Comment by ANGSD** [comment]
Ok i was looking for an old issue, and it looks like this one got solved. Ill close it now, feel free to reopen if needed.
