### ISSUE TITLE
How does -dosaf decide which sites to use?

### ISSUE THREAD

**Issue by TeresaPegan** [ANGSD/angsd#382]
Hello! 

I would much appreciate it if someone could explain how -dosaf decides which sites to put into the .saf files it produces?

I would have guessed that it might use either all sites, or only the variable sites (as I think would be output in an ANGSD run of -doGlf), but neither seems to be the case for me. 

In trying to figure this out, I did a comparison where I made a genotype likelihood file and a saf file with the same set of samples. I used no filters for either. I then compared the sites from each. The sites are not the same.

The doGlf command, where one particular chromosome is specified:
```
$ANGSDIR/angsd -b $BAMS -out $OUT -doMaf 1 -doGlf 2 -doMajorMinor 1 -anc $ANC \
-doPost 2 -GL 1 -r CM027513.1
```

Here are the first 10 lines from the mafs file output by the above code, demonstrating the first 9 sites (plus header) of the output:

```
chromo	position	major	minor	anc	knownEM	nInd
CM027513.1	1701	A	C	A	0.000001	6
CM027513.1	1702	A	C	A	0.000001	6
CM027513.1	1703	T	A	T	0.000001	6
CM027513.1	1704	G	A	G	0.000001	6
CM027513.1	1705	G	A	G	0.000001	6
CM027513.1	1706	C	A	C	0.000001	6
CM027513.1	1707	A	C	A	0.000001	6
CM027513.1	1708	A	C	A	0.000001	6
CM027513.1	1709	A	C	A	0.000001	6
```

Next, the dosaf command followed by the "print" command that I used to read the saf output (the latter is where I specified the chromosome). Please note that although the input bam list is coded slightly differently, it is the exact same set of bam files.
```
$ANGSDIR/angsd -b $OUTDIR/$SPEC"_"$POP"_bams" -ref $ANC -anc $ANC -out $OUTDIR/$SPEC"_"$POP"_nofilter" \
-dosaf 1 -GL 1


$ANGSDIR/misc/realSFS print $OUTDIR/$SPEC"_"$POP"_nofilter".saf.idx -r CM027513.1   > $OUTDIR/printed_chr7_nofilter

```

When I examine the output of the "print" step, I can see that the saf starts out with a completely different set of sites. Here are the first 9 lines of the saf output for comparison with the doGlf output above:

```
CM027513.1	5453	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5454	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5455	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5456	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5457	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5458	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5459	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5460	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
CM027513.1	5461	0.000000	-0.087012	-0.182305	-0.287624	-0.405332	-0.538741	-0.692698	-0.874711	-1.097347	-1.384122	-1.787685-2.474965	-6.907755
```

The doGlf code gives me positions 1701-1709 as its first 9 lines, whereas the dosaf code gives me 5453-5461 as its first 9 lines of code. 

Should I expect the sites from doGlf and the sites from dosaf to match? Does the fact that they do not indicate that I have some kind of error somewhere, or does dosaf decide which sites to use differently than doGlf? If the latter, how does dosaf determine which sites to output?

Thanks for any insights into this!
-Teresa

**Comment by z0on** [comment]
Hi Theresa - angsd would use all sites that pass your filters. If you have
-snp_pval and/or -minMaf filters set, then you will get variable sites
only, otherwise you will get everything.
Note that if you are analyzing several populations separately, different
sites would pass the same filters in different populations. If you want to
ensure the sites match between different populations, extract sites from
the maf.gz output (the first two columns) for each population, form the
intersection (for all sites) or union (or variable-only sites), index that
with ' angsd sites index [sites file name] ' command, and rerun your angsd
with ' -sites  [sites file name] ' argument.

It might be tempting to extract the common filter-passing sites by first
running angsd on the whole dataset (rather than on individual populations)
- which is OK if you are going for all sites. If you are after variable
sites, this might lead to bad ascertainment bias if you have unequal-sized
genetic clusters: smaller clusters will look inbred because most variants
will be coming from the larger cluster.

hope this makes sense!
Misha

**Comment by ANGSD** [comment]
Also notice that it only outputs the sites where the ancestral state is well defined. 

Best

**Comment by TeresaPegan** [comment]
Hi, Thanks so much for your response! I think what you said makes sense...but I think something is going on in my code that I'm not understanding. I was expecting to get "everything" (all sites) for both the -doGlf and the -dosaf versions of my code, above, because I did not use any filters or snp_pval or minmaf or anything -- so I was surprised when the sites I got were different. It sounds like this does indicate that something is not working quite like I thought. In the two cases I showed above, I used the same set of 6 samples for each (but it is useful to note that different populations will have different sites passing filters, as you pointed out!) Would you have expected the results of the two analyses I showed above to use the same sites, all of them, given that I put no filters on the data (except where I filtered it to chromosome)? 

Maybe to have better control over what sites go into my .saf files, I should use the -sites option like you describe above. (I agree that doing it on each population separately sounds like the better option).

Thanks,
-Teresa

**Comment by ANGSD** [comment]
Hi Teresa, sorry about the poor documentation.

It ’should’ be the same sites that are included in all analyses. There are however some extra stuff going on with the sample allele frequency analyses.

1) The program fixes the ancestral and loops over the derived. So if the ancestral is a ’N’ for a site then this will not be used in the analyses
2) A site might be discarded if it underflows due to numerical instability. This could happen for a site when ancestral is not among the two segregating allele.

Hopefully this helps.

How big of a difference in number of sites do you observe?

Best

**Comment by z0on** [comment]
Hi Teresa - sorry for my mansplaining in the previous response... Weird
problem indeed! after reading Thorfinn's comments: can you try running the
first command with -doMajorMinor 5 (force the major allele to ancestral
state as in -anc)  instead of 1 (infer it from GL) ? Maybe it is really all
about properly inferred ancestral states.

**Comment by TeresaPegan** [comment]
Thanks for the idea! I tried with -doMajorMinor 5, but I got the same first set of lines:
Code:
```
$ANGSDIR/angsd -b $BAMS -out $OUT -doMaf 1 -doGlf 2 -doMajorMinor 5 -anc $ANC \
-doPost 2 -GL 1 -r CM027513.1
```
First 10 lines:
```
chromo	position	major	minor	anc	knownEM	nInd
CM027513.1	1701	A	C	A	0.000001	6
CM027513.1	1702	A	C	A	0.000001	6
CM027513.1	1703	T	A	T	0.000001	6
CM027513.1	1704	G	A	G	0.000001	6
CM027513.1	1705	G	A	G	0.000001	6
CM027513.1	1706	C	A	C	0.000001	6
CM027513.1	1707	A	C	A	0.000001	6
CM027513.1	1708	A	C	A	0.000001	6
CM027513.1	1709	A	C	A	0.000001	6
```


In response to the question about how big is the difference in number of sites:
On the chromosome I am using in this example, the saf file has 2,483,812 sites and the output of the code I used above with -doMajorMinor 5 is 30,839,468. This is about 40k more sites than when I used -doMajorMinor 1, so it actually gave me more sites rather than fewer.
For the purposes of this exercise, I am running these analyses with no filters (because I'm trying to figure out what, other than filters, determines what's going into the saf), but it's worth noting that the entire chromosome I am using here is 38,260,000 bp long, so the number of sites that -doGlf is giving me seems extremely large. 
Still, without filters on either analysis, -doGlf gives me almost 15x more sites than -dosaf -- is that weird?

In case something is going on with how I am actually counting the sites, this is how I'm doing it:
For the output of the -doGlf code, I use
```
zcat out.mafs.gz | wc -l
```
For the output of the -dosaf code, I first used realSFS print (code in my first post) on the .saf.idx file and then I ran wc -l on the output of that.

Thanks!
-Teresa

**Comment by nspope** [comment]
that's a big difference and evidently isnt due to missing ancestral info. If you make a small subset of your bam files/reference/ancestral -- say first 50kb of CM027513.1 -- and send to me at nspope at utexas dot edu, I can take a quick look

**Comment by TeresaPegan** [comment]
Thank you! I am sending you the files. I did a test run on them, and I get 1342 sites with the -doGlf code. With these 50kb files, I think that I get nothing in the SAF file. It's hard for me to tell exactly what happened because when I tried realSFS print on the saf.idx that was produced, I get what seems to be an infinite loop of the message saying 
```
-> Only read nSites: 0 will therefore prepare next chromosome (or exit)
	-> Done reading data from chromosome will prepare next chromosome
``` 
Just repeated ad infinitum. I submitted this as a job  and forgot about it, and then I killed it after 3 hours upon realizing that it had created a 73 GB stderr file that was filled with this message! 

This is the binary content of the .saf.idx file I was able to make with the 50 kb files:

```
safv3^@^@^@^L^@^@^@^@^@^@^@
```


In the past few days I have come to the startling realization that my data were all mislabeled during sequencing, such that the species designations were all wrong. The data I am talking about here were therefore aligned to a reference genome of a species that is not closely related to their true species. So, perhaps there is something to the idea that this discrepancy is related to the reference "ancestral" genome! 

I still really appreciate the help figuring out what's going on, since understanding what determines which sites get used by the -dosaf command will really help me understand how to interpret my data and analyses.

Thanks!
-Teresa

**Comment by ANGSD** [comment]
Hi Teresa I am not sure if this is still relevant. The output of the saf file should correspond to those sites where the ancestral is not an N.
So in your example it should be

cut -f5 your.mafs|sed 1d |grep -v N |wc -l

I am closing this issue, but feel free to reopen or make a new issue.

Thanks for using the software.

Best
