### ISSUE TITLE
VCF as input for -doAsso

### ISSUE THREAD

**Issue by annaorteu** [ANGSD/angsd#383]
Hi 

I have been trying to run ANGSD using a vcf using this line:

```
~/bin/angsd/angsd -yBin fw.pheno.bin -doAsso 2 -doPost 1 -nThreads 20 -out gwas.test  -doMajorMinor 4 -doMaf 1 -vcf-gl snp.pos.utg000031l_1.vcf.gz -P 20 -model 2 -ref /home/af658/genomes/Hmis/purge_dups/ilHypMisi1.trio.hap2.p_ctg.purge.fa
```
However, I get this error (multiple times, one error for each SNP in the vcf file):
BAD SITE utg000031l_1:119121. return code:-1 while fetching GL tag rec->rid:28

The vcf has been produced with bcftools and contains the PL tag, which I thought was enough to be able to run angsd? 

The line used to get the vcf: 
```
bcftools mpileup --threads 10 -a INFO/AD,AD,DP,DV,DPR,INFO/DPR,DP4,SP -q 10 -Q 20 -r utg000031l_1 -f ~/genomes/Hmis/purge_dups/ilHypMisi1.trio.hap2.p_ctg.purge.fa --ignore-RG -F 1024 *bam | bcftools call --threads 10 -f GQ,GP -O v -v -m -o snp.pos.utg000031l_1.vcf
```

Ideally, what I want to do is use the vcf file as input for STITCH to impute genotypes using linked read information and then use ANGSD for the association. 

I attached the header and a few lines of the vcf file. 

Any help you can provide will be greatly appreciated. 

Thank you
Anna 

[head.snp.pos.utg000031l_1.vcf.gz](https://github.com/ANGSD/angsd/files/6131414/head.snp.pos.utg000031l_1.vcf.gz)

**Comment by ANGSD** [comment]
Change -vcf-gl to vcf-pl, that should help.

**Comment by annaorteu** [comment]
Thank you, that worked!
