### ISSUE TITLE
ANGSD [E::faidx_adjust_position]

### ISSUE THREAD

**Issue by DcornishUCL** [ANGSD/angsd#384]
Hello all, 

I am trying to estimate derived allele frequencies within a sample of ancient individuals and I keep receiving the following error messages.

```
[E::faidx_adjust_position] The sequence "chr1" was not found

[loadChr] Error loading fasta info from chr:'chr1'
        -> Problem with length of fastafile vs length of chr in BAM header
        -> Chromosome name: 'chr1' length from BAM header:249250621 length from fai file:0
Trying to access fasta efter end of chromsome+200:chr1/chr1 pos=72693 ref_len=0
Trying to access fasta efter end of chromsome+200:chr1/chr1 pos=850293 ref_len=0
```

Although it states that chr1 is not found I am able to locate it both within the ancestral state FASTA and indexed FASTA file and this is also in the BAM headers. I also checked the length of chromosome 1 in my BAM headers and the FASTA file and they match. I am using the ancestral state file from ensembl ftp://ftp.ensembl.org/pub/release-75/fasta/ancestral_alleles/homo_sapiens_ancestor_GRCh37_e71.tar.bz2 

Finally, I am using the below commands in ANGSD:

`~/bin/angsd/angsd -b /DIR/list_EMH_chrtags -ref /DIR/hs37d5.fa -anc ~/DIR/homo_sapiens_ancestor_GRCh37_e71/homo_sapiens_ancestor_fullgenome.fa -out /DIR/EMHchrtags_neutrdiff -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -C 50 -baq 1 -skipTriallelic 1 -GL 2 -nThreads 20 -doGlf 4 -doMaf 2 -doMajorMinor 5 -SNP_pval 1e-06 `

Any suggestions on how to troubleshoot or fix this issue would be fantastic. 

Best, 

Dean

**Comment by ANGSD** [comment]
Dear Dean, could you post the fai and the header of your bam. 

cat DIRhomo_sapiens_ancestor_GRCh37_e71/homo_sapiens_ancestor_fullgenome.fa.fai
samtools view -H your.bam |grep -E "^@SQ\t"

**Comment by DcornishUCL** [comment]
Hello, 

Thanks for your quick response. Yes of course. 

Example representative BAM file header:

`@SQ     SN:chr1 LN:249250621
@SQ     SN:chr2 LN:243199373
@SQ     SN:chr3 LN:198022430
@SQ     SN:chr4 LN:191154276
@SQ     SN:chr5 LN:180915260
@SQ     SN:chr6 LN:171115067
@SQ     SN:chr7 LN:159138663
@SQ     SN:chr8 LN:146364022
@SQ     SN:chr9 LN:141213431
@SQ     SN:chr10        LN:135534747
@SQ     SN:chr11        LN:135006516
@SQ     SN:chr12        LN:133851895
@SQ     SN:chr13        LN:115169878
@SQ     SN:chr14        LN:107349540
@SQ     SN:chr15        LN:102531392
@SQ     SN:chr16        LN:90354753
@SQ     SN:chr17        LN:81195210
@SQ     SN:chr18        LN:78077248
@SQ     SN:chr19        LN:59128983
@SQ     SN:chr20        LN:63025520
@SQ     SN:chr21        LN:48129895
@SQ     SN:chr22        LN:51304566
@SQ     SN:chrX LN:155270560
@SQ     SN:chrY LN:59373566
@SQ     SN:chrMT        LN:17569
@SQ     SN:GL000207.1   LN:4262
@SQ     SN:GL000226.1   LN:15008
@SQ     SN:GL000229.1   LN:19913
@SQ     SN:GL000231.1   LN:27386
@SQ     SN:GL000210.1   LN:27682
@SQ     SN:GL000239.1   LN:33824
@SQ     SN:GL000235.1   LN:34474
@SQ     SN:GL000201.1   LN:36148
@SQ     SN:GL000247.1   LN:36422
@SQ     SN:GL000245.1   LN:36651
@SQ     SN:GL000197.1   LN:37175
@SQ     SN:GL000203.1   LN:37498
@SQ     SN:GL000246.1   LN:38154
@SQ     SN:GL000249.1   LN:38502
@SQ     SN:GL000196.1   LN:38914
@SQ     SN:GL000248.1   LN:39786
@SQ     SN:GL000244.1   LN:39929
@SQ     SN:GL000238.1   LN:39939
@SQ     SN:GL000202.1   LN:40103
@SQ     SN:GL000234.1   LN:40531
@SQ     SN:GL000232.1   LN:40652
@SQ     SN:GL000206.1   LN:41001
@SQ     SN:GL000240.1   LN:41933
@SQ     SN:GL000236.1   LN:41934
@SQ     SN:GL000241.1   LN:42152
@SQ     SN:GL000243.1   LN:43341
@SQ     SN:GL000242.1   LN:43523
@SQ     SN:GL000230.1   LN:43691
@SQ     SN:GL000237.1   LN:45867
@SQ     SN:GL000233.1   LN:45941
@SQ     SN:GL000204.1   LN:81310
@SQ     SN:GL000198.1   LN:90085
@SQ     SN:GL000208.1   LN:92689
@SQ     SN:GL000191.1   LN:106433
@SQ     SN:GL000227.1   LN:128374
@SQ     SN:GL000228.1   LN:129120
@SQ     SN:GL000214.1   LN:137718
@SQ     SN:GL000221.1   LN:155397
@SQ     SN:GL000209.1   LN:159169
@SQ     SN:GL000218.1   LN:161147
@SQ     SN:GL000220.1   LN:161802
@SQ     SN:GL000213.1   LN:164239
@SQ     SN:GL000211.1   LN:166566
@SQ     SN:GL000199.1   LN:169874
@SQ     SN:GL000217.1   LN:172149
@SQ     SN:GL000216.1   LN:172294
@SQ     SN:GL000215.1   LN:172545
@SQ     SN:GL000205.1   LN:174588
@SQ     SN:GL000219.1   LN:179198
@SQ     SN:GL000224.1   LN:179693
@SQ     SN:GL000223.1   LN:180455
@SQ     SN:GL000195.1   LN:182896
@SQ     SN:GL000212.1   LN:186858
@SQ     SN:GL000222.1   LN:186861
@SQ     SN:GL000200.1   LN:187035
@SQ     SN:GL000193.1   LN:189789
@SQ     SN:GL000194.1   LN:191469
@SQ     SN:GL000225.1   LN:211173
@SQ     SN:GL000192.1   LN:547496`

Indexed FASTA file:

chr10   135534747       7       100     101
chr11   135006516       136890109       100     101
chr12   133851895       273246698       100     101
chr13   115169878       408437119       100     101
chr14   107349540       524758703       100     101
chr15   102531392       633181746       100     101
chr16   90354753        736738459       100     101
chr17   81195210        827996767       100     101
chr18   78077248        910003937       100     101
chr19   59128983        988861965       100     101
chr1    249250621       1048582244      100     101
chr20   63025520        1300325379      100     101
chr21   48129895        1363981162      100     101
chr22   51304566        1412592363      100     101
chr2    243199373       1464409981      100     101
chr3    198022430       1710041354      100     101
chr4    191154276       1910044015      100     101
chr5    180915260       2103109840      100     101
chr6    171115067       2285834259      100     101
chr7    159138663       2458660483      100     101
chr8    146364022       2619390539      100     101
chr9    141213431       2767218208      100     101
ANCESTOR_for_chromosome:GRCh37:chrMT:1:16569:1  16569   2909843822      100     101
chrX    155270560       2909860563      100     101

Best, 

Dean

**Comment by DcornishUCL** [comment]
Hi everyone, 

Does anybody have any suggestions on fixing this issue? 

Best wishes, 

Dean

**Comment by ANGSD** [comment]
Would it be possible to obtain a subset of your data that makes it possible to replicate this behaviour?

**Comment by DcornishUCL** [comment]
Hi, 

Apologies for the delayed response. I have noticed that my reference genome has header lines in the format:

>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

Could this be the reason why ANGSD is erroring? Because the header of the reference is not identical to the ancestral state. If not let me know and I can share some sample data.

**Comment by silviagenome** [comment]
Hi Dean,

I have the same error. How could you solve it in the end?

Best,
Silvia
