### ISSUE TITLE
VCF with genotype probabilities

### ISSUE THREAD

**Issue by clydeandforth** [ANGSD/angsd#386]
#https://github.com/ANGSD/angsd/issues/313

Hi,

Is it possible to add the vcf-gp feature back into the program?

I'm using Beagle v4.1 to create a vcf file with genotype probability tags. I would like to do an association (` -doAssoc 6`) with the Beagle output. This is what one position in the Beagle vcf looks like:

```
Contig0 1       .       T       A       .       PASS    AR2=0.00;DR2=0.00;AF=0  GT:DS:GP        0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0
     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0     0/0:0:1,0,0
     0/0:0:1,0,0
```

Thanks,

James

**Comment by ANGSD** [comment]
Yes of course.  Ill try to include in the next commit. It shouldnt be too timeconsuming.

**Comment by ANGSD** [comment]
Dear @clydeandforth , I just pushed a new commit which should allow for vcf-gp input. This should close this issue. Sorry for the delay. 9c3ceee5 @e-jorsboe . I am closing this issue. Feel free to reopen. The vcf-gp is not the much used or tested part of the code.
