### ISSUE TITLE
genotypes for low coverage data

### ISSUE THREAD

**Issue by ma-diroma** [ANGSD/angsd#387]
Hi,

I would like to get reliable genotypes for low coverage DNA samples (<1X). I tried genotype calling using both allele frequency and sample allele frequency with SFS as prior following the guidelines here http://www.popgen.dk/angsd/index.php/Genotype_calling (I chose -GL2 , assuming known major and minor (with uncertainty) allele, postcutoff=99% in both cases, while all the other parameters were the same in the examples). I have some doubts:
1) what are the pros and the cons of each one of the two approaches? When should I use one rather than the other?
2) By requiring a pvalue=0.01, the number of called sites is strongly reduced. Since the analysis is based on genotype likelihoods, is it necessary to set also a pvalue?
3) If I use a set of known SNPs as predefined major and minor alleles, and assume known major and minor allele in MAF estimation, I got more called sites although fixing the same thresholds (postcutoff=99%, pval=0.01). Is this expected?

Thanks for your help.
Best wishes,
Maria Angela

**Comment by ANGSD** [comment]
Hi Maria its not possible to obtain genotype call with high precision in general for lowcoverage data. Of course ifyou have a reference panel then you can do imputation and phasing which will drastically improve things.
1) You can see the performance of the genotype calling approaches here: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0037558
2) you dont need to set a pvalue for snpcalling you can also use the allele frequency which might be more useful.
3) It is not something i have considered, but how big of a difference do you observe?

**Comment by ma-diroma** [comment]
Hi, 
thanks for your reply. 
If I understood correctly, the usage of a reference panel with known major and minor alleles, and known allele frequencies as arguments in -doPost1 can be an alternative to SFS (-doPost 3). Is it right?
In my test with -doPost 1, I got these results:
- using a reference panel of SNPs as predefined major and minor alleles, and assuming known major and minor allele in MAF estimation, and fixing genotype posterior probability =99% and SNP pvalue =0.01: 979,114 genomic sites
- without a reference panel of SNPs, determining major and minor allele from GL, -doMaf 3, PP cutoff =99%, pvalue 0.01: 391,490 genomic sites
I expected to observe more sites without the reference SNPs.
However, if I don't need to set a pvalue, I need to repeat the analysis to update these numbers.

BW,
Maria Angela

**Comment by ANGSD** [comment]
From my experience there is limited advantage from using the much more elaborate and complicated -dopost 3. I am closing this issue.
