### ISSUE TITLE
 Genotype likelihoods in haploid chromosomes

### ISSUE THREAD

**Issue by ryhui** [ANGSD/angsd#391]
Hi, 

I'm trying to get genotype likelihoods on chromosome X in both males and females. On the autosomes, I've been using the following command

`angsd -bam bamlist.${sample}.txt -ref ${refgenome} -sites sites/chr${chrom}.1kg.phase3.v5a.sites -doMajorMinor 3 -GL 1 -doPost 1 -r ${chrom} -doVcf 1 -doMaf 1 -checkBamHeaders 0 -out ${sample}.chr${chrom}.angsd `

I do not see an option to specify the ploidy in angsd. However the wiki says that -doPost is based on the allele frequency. So I'm thinking about using the allele dosage as haploid genotype probabilities in males, namely

P(0/.) = P(0/0) + 0.5\*P(0/1)
P(1/.) = P(1/1) + 0.5\*P(0/1)

And transform GP to GL as needed. Is this a sensible thing to do?

Thanks,
Ruoyun

**Comment by nspope** [comment]
For the GATK sequencing model (I think samtools model too), the homozygous GLs in the diploid case are identical to the desired haploid GLs. So, you just need to remove the heterozygous GL and renormalize.

as far as I know, the only native support for haploids in ANGSD is in SAF/SFS calculation, and this is currently just in the nspope_bandedDP branch. But with a little creativity, you can get many statistics of interest from the SFS.

**Comment by ryhui** [comment]
Thanks a lot for the reply! When I tried to follow your suggestion, I noticed that the GP and GL values are not consistent in the output. For example, 

22	16054713	.	C	T	.	PASS	NS=1;RA=C;AF=8e-06	GP:GL	0.999992,8e-06,0:0,-0.301034,-3.6
22	16054740	.	A	G	.	PASS	NS=1;RA=A;AF=8e-06	GP:GL	0.999992,8e-06,0:0,-0.301034,-3.6
22	16055912	.	C	T	.	PASS	NS=1;RA=C;AF=8e-06	GP:GL	0.999992,8e-06,0:0,-0.301034,-1.4
22	16055937	.	C	T	.	PASS	NS=1;RA=C;AF=8e-06	GP:GL	0.999992,8e-06,0:0,-0.301034,-3.6
22	16055942	.	C	T	.	PASS	NS=1;RA=C;AF=8e-06	GP:GL	0.999992,8e-06,0:0,-0.301034,-3.2

It seems to me that the GP values correspond to the allele frequencies, and I should remove and renormalise the GL values. Is that correct?

Ruoyun

**Comment by nspope** [comment]
The GP field is posterior genotype probabilities on natural scale (e.g. summing to 1), while GL are log-likelihoods per genotype. So yeah, if you just want the haploid likelihoods, drop the GPs and renormalize the GL field (drop heterozygous GL and subtract max from remaining values).

IIRC, with `doPost 1` the GPs are calculated using (diploid) HWE frequencies as priors for genotypes, so the GPs are meaningless in the haploid case (you can't just renormalize).

**Comment by ryhui** [comment]
I see, thank you very much!
