### ISSUE TITLE
seg fault on -dov/bcf (not when I remove this argument)

### ISSUE THREAD

**Issue by cistarsa** [ANGSD/angsd#393]
hello, I've been able to run this well without the -dobcf or -dovcf argument, but keep getting a segmentation fault on this:

```
./angsd/angsd -nThreads 10 -nQueueSize 50 -domaf 1 -GL 1 -doMajorMinor 1 -doCounts 1 -doPost 1 -dobcf 1 -anc F_Kansas_60.fasta2 -remove_bads 1 -minMapQ 30 -minQ 20 -minInd 57 -minMaf 0.05 -setMinDepthInd 2 -setMinDepth 110 -setMaxDepth 550 -skipTriallelic 1 -SNP_pval 1e-3 -b plains_pest_bam_noNJ.list -out Results_CM/vcf_all_pctind90_maxdepth_600_genos
```

```
[bammer_main] 64 samples in 64 input files
	-> Parsing 64 number of samples 
Segmentation fault (core dumped)
```

sometimes I see this, too:
```
	-> Allocated ~ 30 million nodes to the nodepool, this is not an estimate of the memory usage
angsd: abcWriteBcf.cpp:180: virtual void abcWriteBcf::print(funkyPars*): Assertion `geno' failed.
Aborted (core dumped)
```

thank you!

**Comment by ANGSD** [comment]
The bcf writing has been somewhat updated so you should try the most recent github version.

The bcf is a wrapper around existing analyses modules in angsd, so from the error message you should include -dogeno
In general here are the required parts for bcf writing


-gl 1 -dopost 1 -domajorminor 1 -domaf 1 -dobcf 1 --ignore-RG 0 -dogeno 1 -docounts 1

I am closing this issue, but feel free to reopen og make a new issue.

Best
