### ISSUE TITLE
Problem with length of fastafile vs length of chr in BAM header

### ISSUE THREAD

**Issue by marcticruz** [ANGSD/angsd#395]
Hi  
[first_step_log.txt](https://github.com/ANGSD/angsd/files/6374250/first_step_log.txt)
[theta_results.txt](https://github.com/ANGSD/angsd/files/6374251/theta_results.txt)

I'm having a problem with using -vcf-gl to process a vcf file as input for the -dosaf command. The input file includes genotype likelihood calculated in bcftools and this vcf file is the filtered output of the genotype likelihood analysis. It sounds like a similar problem to one that was fixed in an update in January 2020, but I am using a version that was updated after January 2020 

I wrote bellow the whole command I'm using.

angsd -vcf-gl ./south_wales_snps_filtered2_test.vcf.recode.vcf -doSaf 1 -anc ./bank_vole_11Jun2018_KbcOz2.fasta -out south_wales_frequency_testfai_-P 20     

 
When I execute the command above I get the message bellow (you can see the whole message I'm getting in the attached file "first_step_log.txt") 

-> angsd version: 0.930 (htslib: 1.9) build(Jun 16 2020 15:49:24)  

-> Problem with length of fastafile vs length of chr in BAM header

-> Chromosome name: 'Scaffold_1001;HRSCAF_1067' length from BAM header:2147483647 length from fai file:1482

Does anybody know why I'm probably getting the message above and what I should do about it?  

Furthermore, when I execute the final steps to calculate theta using the commands bellow     

realSFS south_wales_frequency_test.saf.idx -P 20 > south_wales_likelihood_sfs

realSFS saf2theta south_wales_frequency_test.saf.idx  -sfs south_wales_likelihood_sfs -outname south_wales_theta 

thetaStat print south_wales_theta.thetas.idx 2> /dev/null  

 I get theta values for each site in two scaffolds, although I have more than two scaffolds in my data set. Is there an option to calculate theta values for several scaffolds at once?   

I attached two files. The file "first_step_log.txt" contains the whole message I'm getting when I execute the first step. The file "theta_results.txt" contains the results of the analysis to estimate theta.  

Thanks,     

Marcos

**Comment by ANGSD** [comment]
Dear Marcos sorry for the late reply. What the program tells you is that the reference fasta that was used for aligning the data is not the same as the one that you are supplying to the angsd software.
This could also be the reason for the unexpected output your are observing.

I am closing this issue but feel to reopen if needed.
