### ISSUE TITLE
Issue using realSFS with conda install

### ISSUE THREAD

**Issue by shannonekj** [ANGSD/angsd#396]
Hi all,

I've been having an issue using `realSFS` where I've installed angsd via conda. (Version 0.931)

I use the following commands (with a sorted rf file):
```
angsd -bam random20.global_path.bamlist -out random20 -ref reference_genome.fa -anc reference_genome.fa -rf random20.loci -GL 2 -doSaf 1 -minMapQ 10 -minQ 20
realSFS random20.saf.idx -fold 1 -maxIter 100 > random20.folded.sfs
```

And I get the following error:
```
...
        -> Region lookup 375/376
[shared.cpp.changeChr():281] refid:44
Charnge chr:44
        -> Region lookup 376/376
[shared.cpp.changeChr():281] refid:45
Charnge chr:45

        -> Done reading data waiting for calculations to finish
        -> Done waiting for threads
        -> Output filenames:
                ->"random20.arg"
                ->"random20.saf.gz"
                ->"random20.saf.pos.gz"
                ->"random20.saf.idx"
        -> Sat May  1 10:52:14 2021
        -> Arguments and parameters for all analysis are located in .arg file
        -> Total number of sites analyzed: 16860739
        -> Number of sites retained after filtering: 16667329
        [ALL done] cpu-time used =  403.87 sec
        [ALL done] walltime used =  405.00 sec
realSFS random20.saf.idx -fold 1 -maxIter 100
        -> Version of fname:random20.saf.idx is:2
Problem with chr: , key already exists, saffile needs to be sorted. (sort your -rf that you used for input)
```

Curiously, when I run angsd from a `module load angsd` on another system, the exact same commands work perfectly. I'm looking to automate some steps of my pipeline (including these) so any help would be greatly appreciated! 

Best,
Shannon

**Comment by janawold1** [comment]
Massive upvote as I'm having the same issue, but don'e thave another machine to try it on. :(

**Comment by zactobias44** [comment]
I was experiencing this same issue! It also seems to be related to #385. I was able to resolve this using the singularity container provided by @James-S-Santangelo. If your HPC is set up for Singularity, I'd recommend running angsd and all related tools using James' singularity recipe. https://cloud.sylabs.io/library/james-s-santangelo

If you make the saf files from within the container and also use the realSFS print command from within the container, you can access the data.

**Comment by janawold1** [comment]
Hi @zactobias44 cheers for the singularity recipe. Sadly, I did not make any progress with this. I'll double check to see if our HPC is set up for Singularity, but I don't think it is. Either way, I'll just have to give it a go!

Thanks again!
