### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by denise0593** [ANGSD/angsd#397]
Hi, I'm having this error when trying to install the software on Centos:

HTSSRC not defined, assuming systemwide installation
g++ -c   -O3   vcfReader.cpp
vcfReader.cpp: In member function ‘int vcfReader::parseline(bcf1_t*, htsstuff*, funkyPars*, int&, int)’:
vcfReader.cpp:267:39: error: expected ‘)’ before ‘PRId64’
       fprintf(stderr, "BAD SITE %s:%" PRId64 " return code:%d" "while fetching GP tag rec->rid:%d\n", bcf_seqname(hs->hdr,rec), rec->pos, n,rec->rid);
                                       ^~~~~~
vcfReader.cpp:295:39: error: expected ‘)’ before ‘PRId64’
       fprintf(stderr, "BAD SITE %s:%" PRId64 ". return code:%d while fetching PL tag rec->rid:%d\n", bcf_seqname(hs->hdr,rec), rec->pos, n,rec->rid);
                                       ^~~~~~
make: *** [vcfReader.o] Error 1

**Comment by xieduo7** [comment]
I come across the same issue.

**Comment by sixqa** [comment]
I come across the same issue.

**Comment by ANGSD** [comment]
Could you try to do.

 make clean;make FLAGS="-D__STDC_FORMAT_MACROS__"

**Comment by sixqa** [comment]
I tried, but still reported the same mistake.

**Comment by ANGSD** [comment]
Can you successfully compile htslib?

**Comment by sixqa** [comment]
I successfully compiled htslib, but htslib and angsd are not in the same folder, so I don't know how to use htslib.

**Comment by ANGSD** [comment]
Could you please try to add 

#include <inttypes.h>

to the top of the vcfReader.cpp file.

and let me know if that changes anything.

**Comment by kullrich** [comment]
Hi, for our Centos7 based HPC cluster this made it:
make HTSSRC=../htslib FLAGS="-D__STDC_FORMAT_MACROS"

**Comment by RAWWiberg** [comment]
Hi,

I have a very similar issue. I am trying to install locally on a CentOS7 machine. 
I have added the `#include <inttypes.h>` line to the top of `vcfReads.cpp`,

I then run

```
make HTSSRC=../htslib-1.9 FLAGS="-D__STDC_FORMAT_MACROS"
```

The original error given by @denise0593 does not arise but eventually I get:

```bammer_main.cpp: In function ‘std::map<char*, std::vector<char*>, ltstr> get_lb_rg(bam_hdr_t*)’:
bammer_main.cpp:26:40: error: ‘sam_hdr_count_lines’ was not declared in this scope
   int nrg = sam_hdr_count_lines(h, "RG");
                                        ^
bammer_main.cpp:30:50: error: ‘sam_hdr_line_name’ was not declared in this scope
     const char *rgid = sam_hdr_line_name(h,"RG",i);
                                                  ^
bammer_main.cpp:31:60: error: ‘sam_hdr_find_tag_id’ was not declared in this scope
     if (sam_hdr_find_tag_id(h, "RG", "ID", rgid, "LB", &lib)  < 0){
                                                            ^
make: *** [bammer_main.o] Error 1```

thanks for any advice.

**Comment by kullrich** [comment]
Have you tried to use the latest devtoolset for Centos?

For me this works fine:
```
scl enable devtoolset-9 bash
gcc --version
#gcc (GCC) 9.1.1 20190605 (Red Hat 9.1.1-2)
git clone https://github.com/samtools/htslib.git;
git clone https://github.com/angsd/angsd.git;
cd htslib/
git submodule update --init --recursive
make
cd ../angsd
make HTSSRC=../htslib FLAGS="-D__STDC_FORMAT_MACROS
```

**Comment by RAWWiberg** [comment]
it doesn't look like our server has the latest devtoolset. Is this something that would need to be updated system-wide?

**Comment by kullrich** [comment]
According to this page you would need to do the following two things, which will be system-widem most likely you need to do as `sudo` user:

https://centos.pkgs.org/7/centos-sclo-rh-x86_64/devtoolset-9-9.0-3.el7.x86_64.rpm.html

```
#1. Install CentOS SCLo RH repository:
yum install centos-release-scl-rh
#2. Install devtoolset-9 rpm package:
yum install devtoolset-9
```

**Comment by RAWWiberg** [comment]
*sigh* OK. I'll check in with our IT guy and see what can be done...

**Comment by RAWWiberg** [comment]
Hi again,
I tried installing via `conda`, that worked fine. I then had some issues with the most recent version of `angsd`. The same issues that have been mentioned several times already in other issue reports. Installing the previous version of `angsd` seems to work just fine though.

**Comment by ANGSD** [comment]
At some point in the future, we will make an official conda version, but it hasnt been a priority. Mainly because I am not using conda myself.

I have added an extra include in the offending vcfReader.cpp file which should solve the original comment posted. The other point raised by @RAWWiberg should be solved by using a newer version of htslib. By default the newer version of angsd will pull htslib by itself when typing make.

I am therefore closing this issue, but feel free reopen or make a new issue if needed.
Best
