### ISSUE TITLE
Fst and SFS

### ISSUE THREAD

**Issue by rabiafidan** [ANGSD/angsd#399]
Hello,

As far as I know, Fst is calculated based on allele frequencies and normally we don't need SFS to calculate Fst from a vcf file for example. Why exactly do we need SFS for Fst calculation here? Is it like an intermediate step to convert likelihoods to frequencies? If so, does it matter if I give reference genome with -anc option to calculate the unfolded SFS instead of an ancestral fasta (SFS will only be used for Fst calculation)?

Also I noticed a typo in the wiki page. 3 population real data example's first line says:
#this is with 2pops

Thanks a lot,
Rabia

**Comment by TeresaPegan** [comment]
There is an explanation related to this in #239, hope that helps
