### ISSUE TITLE
ERROR in generating saf file

### ISSUE THREAD

**Issue by sunshichao0916** [ANGSD/angsd#403]
Hi,
    I use the following command to generate the saf file, and there were two errors during operation:
`angsd -F indF2.txt -nInd 90 -bam syn0.bamlist -P 16 -GL 2 -anc Zea_mays.AGPv4.dna.noScaffold.fa -minMapQ 40 -minQ 20 -doSaf 1 -out syn0`

error 1
`[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[multiReader] 90 samples in 90 input files
        -> Reading fasta: Zea_mays.AGPv4.dna.noScaffold.fa
        -> Parsing 90 number of samples 
[E::bgzf_uncompress] Inflate operation failed: progress temporarily not possible, or in() / out() returned an error
[E::bgzf_read] Read block operation failed with error 1 after 49 of 288 bytes
[E::bgzf_read_block] Invalid BGZF header at offset 73342
[E::bgzf_read] Read block operation failed with error 3 after 0 of 4 bytes
[E::bgzf_read_block] Invalid BGZF header at offset 73360
......`

error 2
`
        -> Allocated ~ 1430 million nodes to the nodepool, this is not an estimate of the memory usage
        -> Printing at chr: 3 pos:232526925 chunknumber 264400 contains 2385 sites
        -> Printing at chr: 3 pos:232820232 chunknumber 264500 contains 2716 sites
        -> Printing at chr: 3 pos:233111526 chunknumber 264600 contains 1778 sites
        -> Printing at chr: 3 pos:233604488 chunknumber 264700 contains 4218 sites
        -> Printing at chr: 3 pos:234149751 chunknumber 264800 contains 1144 sites
        -> Printing at chr: 3 pos:234622431 chunknumber 264900 contains 1767 sites
        -> Printing at chr: 3 pos:234980238 chunknumber 265000 contains 1155 sites
        -> Printing at chr: 3 pos:235376887 chunknumber 265100 contains 1948 sites
        -> Printing at chr: 3 pos:235609231 chunknumber 265200 contains 1985 sites
unsorted file detected will exit
`
How can I solve these problems?

Thank you!

**Comment by ANGSD** [comment]
Hello it looks like your input bam file is corrupt. I am closing this issue, but feel free to reopen.
