### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by NathanL0518** [ANGSD/angsd#406]
liang797@NathanPC:~/angsd-wrapper$ ./angsd-wrapper setup dependencies
angsd-wrapper running from /home/liang797/angsd-wrapper
Cloning into 'ngsF'...
remote: Enumerating objects: 274, done.
remote: Total 274 (delta 0), reused 0 (delta 0), pack-reused 274
Receiving objects: 100% (274/274), 94.94 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (152/152), done.
HEAD is now at 807ca72 Removed deprecated -islog and -isfold options from test runs
make -C bgzf bgzip
make[1]: Entering directory '/home/liang797/angsd-wrapper/dependencies/ngsF/bgzf'
gcc -c -Wall -O3  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=1 -I. bgzip.c -o bgzip.o
In file included from bgzip.c:32:
bgzf.h:29:10: fatal error: zlib.h: No such file or directory
   29 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:21: bgzip.o] Error 1
make[1]: Leaving directory '/home/liang797/angsd-wrapper/dependencies/ngsF/bgzf'
make: *** [Makefile:13: bgzip] Error 2

**Comment by ANGSD** [comment]
Hi you would need to have zlib installed.

Best
