### ISSUE TITLE
Use imputed genotype posteriors

### ISSUE THREAD

**Issue by aguilar-gomez** [ANGSD/angsd#409]
Hi,

I have a vcf with imputed genotypes:
 ##INFO=<ID=INFO,Number=A,Type=Float,Description="IMPUTE info quality score for diploid samples">
##INFO=<ID=BUF,Number=A,Type=Integer,Description="Is it a variant site falling within buffer regions? (0=no/1=yes)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Unphased genotypes">
##FORMAT=<ID=DS,Number=1,Type=Float,Description="Genotype dosage">
##FORMAT=<ID=GP,Number=3,Type=Float,Description="Genotype posteriors">
I am trying to run:
angsd -vcf-gp hae.only.bcf -doSaf 4 -P 1 -nInd 27 -out hae.angsd -anc $REF -ref $REF
I get the following error:
	-> Must supply genotype likelihoods (-GL [INT])

Is there a way that I can calculate Saf files from my vcf with genotype posteriors?

Thank you,
Diana

**Comment by ANGSD** [comment]
This should be fixed in the most recent commit.
