### ISSUE TITLE
Filter -minInd not working properly

### ISSUE THREAD

**Issue by fgvieira** [ANGSD/angsd#41]
I've recently noticed that the `-minInd` filter in ANGSD is not working properly. For example, using `-minInd 76` on a test run gives a MAF file:

chromo  position        major   minor   ref     knownEM pK-EM   nInd
chr10   90625430        C       G       C       0.135223        0.000000e+00    76
chr10   90625447        G       A       G       0.031195        1.791576e-10    75
chr10   90625462        C       A       A       0.319601        0.000000e+00    76

best,

**Comment by ANGSD** [comment]
Thanks for reporting this.
