### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by aguilar-gomez** [ANGSD/angsd#417]
I tried to update angsd and I had the following error:
HTSSRC defined: ../htslib
g++ -O3 -o angsd *.o "/home/diana/programs/htslib/libhts.a" -lz -lm -lbz2 -llzma -lpthread -lcurl -lcrypto
abcFreq.o: In function `abcFreq::print(funkyPars*)':
abcFreq.cpp:(.text+0x1f7c): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x20d8): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x2190): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x2279): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.cpp:(.text+0x2295): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
abcFreq.o:abcFreq.cpp:(.text+0x22b5): more undefined references to `ks_resize2(kstring_t*, unsigned long)' follow
collect2: error: ld returned 1 exit status
Makefile:79: recipe for target 'angsd' failed
make: *** [angsd] Error 1

**Comment by isinaltinkaya** [comment]
Hi @aguilar-gomez,

The issue seems to be similar to #304 and should be resolved after the commit  https://github.com/ANGSD/angsd/commit/172f053e27406b308c6992e535ec824492072d1f.

Please feel free to reopen the issue or create a new one if the issue persists.
