### ISSUE TITLE
What angsd calls derived when both major and minor differ from reference?

### ISSUE THREAD

**Issue by mfariasvirgens** [ANGSD/angsd#419]
Hi angsd team, 
What angsd calls derived when both major and minor differ from reference?
Thank you!

**Comment by ANGSD** [comment]
It depends on what you choose as option for -domajorminor, if you choose 1 then it infers the major and minor, with different values of domajorminor you can choose what is appropriate for your study.

 ./angsd -domajorminor
	-> angsd version: 0.935-62-gf1c7e1d-dirty (htslib: 1.14-9-ge769401) build(Feb  8 2022 10:46:03)
	-> ./angsd -domajorminor 
	-> Analysis helpbox/synopsis information:
	-> Wed Feb 23 11:59:55 2022
	-> doMcall=0
-------------------
abcMajorMinor.cpp:
	-doMajorMinor	0
	1: Infer major and minor from GL
	2: Infer major and minor from allele counts
	3: use major and minor from a file (requires -sites file.txt)
	4: Use reference allele as major (requires -ref)
	5: Use ancestral allele as major (requires -anc)
	6: Use EBD for major and minor (requires read data)
	7: Use EBD for minor (Major is ref) (requires -ref and read data, (similar to SAMtools))
	-rmTrans: remove transitions 0
	-skipTriallelic	0

**Comment by ANGSD** [comment]
I am closing this issue, feel free to reopen.
