### ISSUE TITLE
-SNP_pval parameter

### ISSUE THREAD

**Issue by diegodiazd** [ANGSD/angsd#42]
Hi all, 

Just a quick question.  What method is implemented for the **-SNP_pval** parameter? 

I was reading your [paper](http://download.springer.com/static/pdf/27/art%253A10.1186%252Fs12859-014-0356-4.pdf?originUrl=http%3A%2F%2Fbmcbioinformatics.biomedcentral.com%2Farticle%2F10.1186%2Fs12859-014-0356-4&token2=exp=1466436803~acl=%2Fstatic%2Fpdf%2F27%2Fart%25253A10.1186%25252Fs12859-014-0356-4.pdf*~hmac=52580c5f48c8f66bd69909a6380f49b2e20bfa954c6fbbf62636bd787d0e9d6el) (and the wiki) and I think that parameter is related to LRT in SNP discovery, described in the table 1 of the paper, but I am not pretty sure about that.

Thanks in advance

**Comment by ANGSD** [comment]
You are right, the -snp_pval is the LRT test. You can either supply the raw LRT value, or the corresponding pvalue.

**Comment by diegodiazd** [comment]
Thanks ;)
