### ISSUE TITLE
-doSnpStat filters out all sites

### ISSUE THREAD

**Issue by jbruxaux** [ANGSD/angsd#420]
Hi!

I spent quite some time today to understand why I got an empty ANGSD result.
I started from this command line, which worked for some of my populations, but not for others:

angsd -doCounts 1 -setMinDepthInd 5 -GL 2 -out /pfs/stor10/projects/projnb10/snic2019-29-3/ANGSD/ANGSD_by_pop/ANGSD_pop_${nb}_geno -ref $ref -nThreads 24 -doMajorMinor 1 -SNP_pval 1e-6 -doMaf 1 -bam $file -minMapQ 40 -minQ 20 -skipTriallelic 1 -doSnpStat 1 -doHWE 1 

I got, at the end of the ouput:

        -> Total number of sites analyzed: 7507848
        -> Number of sites retained after filtering: 0

To try to find out why, I first looked at my populations files, they all looked similar, and there was no clear relationships between the number of individuals in the population, and the 0 output (I got some results for populations with 10 individuals, and 0 for others).
I tried to remove each filtering parameter one after another, without any success. The populations that failed kept failing.
And I finally tried to remove -doSnpStat 1, and it worked! 

        -> Total number of sites analyzed: 7507848
        -> Number of sites retained after filtering: 71728

I have absolutely no idea why, but I can provide one of the dataset that were problematic if it helps.

**Comment by z0on** [comment]
This annoying problem keeps popping up - it is some weird installation/HTSLIB incompatibility problem. Have a look at this issue, there are solutions: https://github.com/ANGSD/angsd/issues/385

**Comment by ANGSD** [comment]
I am assuming this this was a htslib or conda issue, so I am closing this issue since I have not been able to observe the error. Feel free to reopen though if it is still relevant.
