### ISSUE TITLE
How can I use realSFS.old? (to view contents of .fst.gz files)

### ISSUE THREAD

**Issue by TeresaPegan** [ANGSD/angsd#421]
Hello,
I am troubleshooting some of my data to try to understand why I sometimes get negative Fst values. The formats.pdf document says that *.fst.gz files should contain information about alpha and beta coefficients of the Fst estimate. I believe [alpha is the numerator and beta is the denominator of the Fst estimator](http://www.popgen.dk/angsd/index.php/Fst). It would be useful to see what these values are, for each locus, to better understand what's going on.
![Screen Shot 2021-09-03 at 6 45 46 PM](https://user-images.githubusercontent.com/35701568/132071925-300cee3d-fe40-494d-ab39-a9e8b16a9e88.png)

When I try to print the *.fst.gz file, I get this message:
```

$ANGSDIR/misc/realSFS print Rcale.MB19181.Z021121.which1.fst.gz
	-> Version of fname:Rcale.MB19181.Z021121.which1.fst.gz is:0
	-> Looks like you are trying to use a version of realSFS that is incompatible with the old binary output from ANGSD
	-> Please use realSFS.old instead (or consider redoing the saf files )
	-> Will exit

```

First of all, is this expected? Am I trying to view the file wrong?

Assuming it's not some kind of mistake, I'd like to use realSFS.old to view the data in the *.fst.gz file. I can see there is a script called realSFS.old.cpp in the ANGSD folder, but I do not know how to actually use it. Neither "$ANGSDIR/misc/realSFS.old print" nor "$ANGSDIR/misc/realSFS.old.cpp print" works. The latter command tells me "permission denied."

I'm sorry if this is a silly question, I don't have much experience with C++ scripts outside of using ANGSD.

I'm using angsd version: 0.935 (htslib: 1.11) build(Apr 19 2021 15:46:47)

**Comment by nspope** [comment]
You need to use `realSFS fst print` I think, not `realSFS print`.

**Comment by TeresaPegan** [comment]
Hmm, I tried that and got a segmentation fault, so I was thinking the message above about using realSFS.old was more promising.

```
$ANGSDIR/misc/realSFS fst print Rcale.MB19181.Z021121.which1.fst.gz
	-> Assuming idxname:Rcale.MB19181.Z021121.which1.fst.gz
Segmentation fault (core dumped)
```




I can use `realSFS fst print` for printing out the .fst.idx file. Is that, in fact, what I want? (Despite the fact that the [formats.pdf](https://github.com/ANGSD/angsd/blob/master/doc/formats.pdf) specifically says the A and B are in the .fst.gz file and that the .fst.idx file contains different information?)

I see now that the fst.idx file does contain 4 columns and that it would make sense for them to be chrom/pos/A/B! Maybe this is just another area where the ANGSD documentation is a little hard to understand.

```
VWZN01000909.1	280747	-0.014634	0.109979
```


Thanks!
-Teresa

**Comment by ANGSD** [comment]
Dear Teresa, you can find documentation about how to access the content of the fst files on the wiki:
http://www.popgen.dk/angsd/index.php/Fst#realSFS_fst_print

The idx contains the binary offsets with the .gz file which contains the actual data. The idx file is used for random access of the data.
I am closing this issue, but feel free to reopen og make a new issue if needed.

**Comment by beausoleilmo** [comment]
I just wanted to make sure, if I want to calculate the per site Fst between 2 population, I need to divide the 1st numerical column with the 2nd numerical column in the fst.idx file?

**Comment by ANGSD** [comment]
Yes, if you want the persite estimate of the fst, then it is the ratio.

If you want the regionwise fst then you should either take the sum of the persite ratios (unweighted) or the ratios of the sums (the weighted). If I remember correctly, the weighted is the recommended.

It is always abit tricky with the sliding window approach depending on how the breaks should be defined. I assume that the first site gets skipped due to some bordercase. You can tweak the behavior of the sliding window approach with the -type option.

http://www.popgen.dk/angsd/index.php/Fst#Relative_window_positions.3F
http://www.popgen.dk/angsd/index.php/Fst#realSFS_fst_print

The sliding window approach is a simple wrapper around the persite estimates, so you can always load the persite estimates and setup your own custom regions if you prefer.

**Comment by beausoleilmo** [comment]
Excellent! Thanks for the clarification!
