### ISSUE TITLE
When do I need to calculate folded SAFs?

### ISSUE THREAD

**Issue by madzayasodara** [ANGSD/angsd#425]
Hi ANGSD team, 
I was reading the issues here and I'm still confused about when to use -fold 1.
I wanna confirm that nothing related to `angsd` sould use it, but only calculations involving `realSFS`. 
So, if I need to just call variants, for example, no fold.
Let me know if this is correct.
Thank you, 
-madza

**Comment by nspope** [comment]
Hi Madza, yes that's right, you should only use the -fold argument in `realSFS`, not in `angsd`. I agree, it is confusing, the docs/CL usage strings are in desperate need of updating.
