### ISSUE TITLE
minQ doesn't seem to filter

### ISSUE THREAD

**Issue by mlucenaperez** [ANGSD/angsd#43]
Filtering without setting any minQ: 

/opt/angsd/angsd \
-P 4 \
-b my_bamlist.bamlist \
-ref myref_genome.fa \
-out test_1.qc \
-uniqueOnly 1 \
-remove_bads 1 \
-only_proper_pairs 1 \
-baq 1 \
-C 50 \
-minMapQ 20 \
-minInd 10 \
-doQsDist 1 \
-doDepth 1 \
-doCounts 1 

Result --> test_1.qc.qs:
qscore	counts	perc
0	238923500	0.000933898301529085
1	17250164	0.0010013253183805
2	62039382	0.00124382332915681
3	53694141	0.00145370166712676
4	83444136	0.00177986605398264
5	343915629	0.00312415500752805
6	260831145	0.00414368537311112
7	303137118	0.00532858028562756
8	336742720	0.00664483194885987
9	416247587	0.00827185028114983
10	458819334	0.0100652720112488
11	468760041	0.0118975497324215
12	397065639	0.0134495901380646
13	278482917	0.0145381173159737
14	249902172	0.0155149287806443
15	303371074	0.0167007381746204
16	382181559	0.0181946000543679
17	471625377	0.020038077730437
18	586967965	0.0223324036781378
19	753900165	0.0252792301042365
20	871126635	0.0286842684736026
21	1086066241	0.0329294574894089
22	1451773493	0.0386041140188739
23	2201277526	0.0472084134817796
24	2351913369	0.0564015146235788
25	2832976237	0.0674749824741944
26	4405280569	0.0846942348338333
27	7155142714	0.112662080725103
28	13338473918	0.164799179574778
29	24793478649	0.261711319231608
30	40255135801	0.419059604152834
31	56025276812	0.638049828460714
32	52545623732	0.843438870376227
33	27902958736	0.952505269333159
34	9638182002	0.990178758133951
35	2259030756	0.999008802002094
36	253582723	0.999999999914007
37	22	1

Filtering with minQ = 20:

    
/opt/angsd/angsd \
-P 4 \
-b my_bamlist.bamlist \
-ref myref_genome.fa \
-out test_2.qc \
-uniqueOnly 1 \
-remove_bads 1 \
-only_proper_pairs 1 \
-baq 1 \
-C 50 \
-minMapQ 20 \
-minQ 20 \
-minInd 10 \
-doQsDist 1 \
-doDepth 1 \
-doCounts 1 
    
   
Result --> test_2.qc.qs:

     
qscore	counts	perc
0	232658276	0.000909539560816795
1	17142450	0.000976555171490038
2	61584284	0.00121730887939844
3	52194312	0.00142135402419103
4	81802495	0.00174114752844625
5	342144303	0.00307870484399427
6	259730904	0.00409408042579695
7	302201649	0.00527548845406572
8	335965486	0.00658889069291855
9	415592002	0.00821357980124003
10	458110202	0.0100044868736056
11	468067737	0.0118343213040107
12	396357974	0.0133838181188078
13	277605518	0.0144690715869545
14	249001544	0.0154425024868399
15	302439375	0.0166248398661095
16	381165065	0.018114942482613
17	470470469	0.0199541700016527
18	585502492	0.022243096441694
19	752175545	0.0251836039818445
20	870242210	0.0285856738806503
21	1085098460	0.0328276892248686
22	1451075433	0.0385004318185723
23	2200543571	0.0471030977866015
24	2351279079	0.0562950396235271
25	2832592548	0.0673685979184439
26	4404551408	0.0845874728370706
27	7154630120	0.112557331674808
28	13337770090	0.16469916715344
29	24792360040	0.261620852683309
30	40253999875	0.418987295850053
31	56024030134	0.638004098687814
32	52544597326	0.843418626796779
33	27902517850	0.952498966715449
34	9638071465	0.990177434200513
35	2259010528	0.999008667195284
36	253580791	0.999999999913995
37	22	1

Sorry if I misunderstood something.

**Comment by ANGSD** [comment]
default qscore filter is 13. You can see all default options in the .arg file that is generated at runtime. Let me know if this doesn't help.

**Comment by mlucenaperez** [comment]
Thank you very much for your quick answer. 
I know that the default is 13, therefore, I was expecting that the .qs file starts in 13 in the first test, as it does in your example in the webpage (http://popgen.dk/angsd/index.php/Alleles_counts) and in 20 in the second one, as those are my threshold in each case. However, it seems to filter something, but I still have bases with 0, 1, 2 ... qscore, which is puzzling for me.

**Comment by ANGSD** [comment]
Ok got it. I hadn't added the minQ as filter in the doQsDist. I was thinking that if users wanted the qscore they didn't want any filtering. But I agree this is counter intuitive. the -minQ is implemented in the downstream analysis by setting the bases with qscore<minQ to N, in effect discarding them, so this would not have impacted anything but the doqsdist. Thanks for taking your time to report this. I'm closing this issue, feel free to reopen if needed.

**Comment by mlucenaperez** [comment]
Thank you very much, that is great, but I still have some doubts. The example above have exactly same parameters but the minQ filter, and it's working over the same files. Therefore, if I understood it correctly, the counts should be the same, but this is not the cases. 

default Q filter:
qscore counts perc
0 238923500 0.000933898301529085
1 17250164 0.0010013253183805
...

minQ 20:
qscore counts perc
0 232658276 0.000909539560816795
1 17142450 0.000976555171490038
...

It seems that is filtering some positions. I have checked everything I could think of, but I can't get to an answer.
Any idea?
I am working with angsd version: 0.911-25-g3fbb94f (htslib: 1.3-64-g5285dc0) build(Apr 20 2016 15:29:14).

**Comment by ANGSD** [comment]
yes, something wasn't properly defined in the previous version. I tested on the latest version and here it gave consistent results:

./angsd -i ../smallBam/smallNA12761.mapped.ILLUMINA.bwa.CEU.low_coverage.20111114.bam -docounts 1 -doqsdist 1 -minQ 0 -out q0
./angsd -i ../smallBam/smallNA12761.mapped.ILLUMINA.bwa.CEU.low_coverage.20111114.bam -docounts 1 -doqsdist 1 -minQ 20 -out q20

paste <(tail -n32 q0.qs) q20.qs 
19	63887	qscore	counts
20	76837	20	76837
21	87523	21	87523
22	107979	22	107979
23	124504	23	124504
24	150261	24	150261
25	182710	25	182710
26	215713	26	215713
27	286981	27	286981
28	356611	28	356611
29	482008	29	482008
30	641792	30	641792
31	831939	31	831939
32	975929	32	975929
33	1004887	33	1004887
34	880805	34	880805
35	848191	35	848191
36	766193	36	766193
37	339670	37	339670
38	93653	38	93653
39	27678	39	27678
40	10538	40	10538
41	7040	41	7040
42	3547	42	3547
43	2614	43	2614
44	1164	44	1164
45	240	45	240
46	88	46	88
47	8	47	8
48	0	48	0
49	0	49	0
50	3	50	3

please try the newest version.

**Comment by mlucenaperez** [comment]
Sorry for the delay, I was running some other analysis (quite heavies) and I didn't want to collapse my server. Anyway, I still have the same problem:

The only difference between the test is minQ filter:

Test 4:
/opt/angsd/angsd -b my_bamlist.bamlist -ref myref_genome.fa -out test_4.qc -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 1 -C 50 -minMapQ 20 **-minQ 20** -minInd 10 -doQsDist 1 -doDepth 1 -doCounts 1 

Test 5:
/opt/angsd/angsd -b my_bamlist.bamlist -ref myref_genome.fa -out test_5.qc -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 1 -C 50 -minMapQ 20 -minInd 10 -doQsDist 1 -doDepth 1 -doCounts 1 

tail -n18 test_4.qc >tail_test_4
tail -n18 test_5.qc >tail_test_5

However I get different counts...

paste tail_test_4 tail_test_5
20	870242210	20	871126635
21	1085098460	21	1086066241
22	1451075433	22	1451773493
23	2200543571	23	2201277526
24	2351279079	24	2351913369
25	2832592548	25	2832976237
26	4404551408	26	4405280569
27	7154630120	27	7155142714
28	13337770090	28	13338473918
29	24792360040	29	24793478649
30	40253999875	30	40255135801
31	56024030134	31	56025276812
32	52544597326	32	52545623732
33	27902517850	33	27902958736
34	9638071465	34	9638182002
35	2259010528	35	2259030756
36	253580791	36	253582723
37	22	37	22

Is there anything very obvious that I am misunderstanding?
Any idea?

Thanks in advance. 


PD: the qs file starts where it should ;).

**Comment by ANGSD** [comment]
If you disable the -minInd filter then you should get the same.

**Comment by mlucenaperez** [comment]
Now I get it. Perfect, thank you very much. 

paste tail_test_6 tail_test_7 
20	872857218	20	872857218
21	1088228539	21	1088228539
22	1453975234	22	1453975234
23	2204108211	23	2204108211
24	2354610003	24	2354610003
25	2835526041	25	2835526041
26	4409761678	26	4409761678
27	7161122193	27	7161122193
28	13349012950	28	13349012950
29	24811315496	29	24811315496
30	40280518766	30	40280518766
31	56053569574	31	56053569574
32	52564309911	32	52564309911
33	27909956546	33	27909956546
34	9639996231	34	9639996231
35	2259368112	35	2259368112
36	253615271	36	253615271
37	35	37	35

**Comment by ANGSD** [comment]
super, im closing this issue, feel free to reopen if needed
