### ISSUE TITLE
realSFS Segmentation Fault

### ISSUE THREAD

**Issue by cs-387** [ANGSD/angsd#433]
Hi there,

I am hoping for some help with a line of code I am trying to run using realSFS. The line is:

realSFS $BASDIR/angsdputneac.saf.idx -P 2 -sites $BASDIR/sortedSNPdata.txt > $BASDIR/neac.sfs

A sample of the SNP data I am using in the input file is below.
CM022274.1 100123735
CM022274.1 100151815
CM022274.1 100181445
CM022274.1 100188151
CM022274.1 100245149
CM022274.1 100273549
CM022274.1 100278777
CM022274.1 100290569
CM022274.1 1003606
CM022274.1 100392486

Each time I attempt to run it I get the error message below. The program is generating a neac.sfs output file, but the file is empty. When I tried running the same line with an indexed version of the input file, it did not create this empty neac.sfs file.

-> Version of fname:/mnt/shared/scratch/csmith/data/merged/angsdputneac.saf.idx is:2
/var/spool/slurm/job2177802/slurm_script: line 10:  5517 Segmentation fault      (core dumped) realSFS $BASDIR/angsdputneac.saf.idx -P 2 -sites $BASDIR/sortedSNPdata.txt > $BASDIR/neac.sfs

Please let me know if you have any suggestions on how to correct the issue. Thank you!

**Comment by peuclide** [comment]
I am having a similar issue when running realSFS:

```
realSFS FEM.saf.idx -fold 1 -r R1_17 > FEM_TEST.sfs
	-> Version of fname:FEM.saf.idx is:2
```
I have gone through other comments and tried limiting threads to 1. And this also does not seem to help.

**Comment by ANGSD** [comment]
Dear all, I pushed a new version af the dosaf and associated realSFS program last week. Please try with this more recent version.

If you still investigating the issue, you could try to print out the content of the saf file.
./realSFS print FEM.saf.idx
If that does not work it would mean that your files are corrupt. I am closing this issue, feel free to reopen if needed.
