### ISSUE TITLE
ANGSD 0.933 core dumped

### ISSUE THREAD

**Issue by DcornishUCL** [ANGSD/angsd#436]
Hi,

I am trying to calculate genotype likelihoods and allele frequencies with ANGSD but keep receiving the error: 

"line 51: 155834 Segmentation fault  (core dumped)" 

This error seems to occur at the same genomic position and chunk number and persists if I try running the code on fewer cores or by massively increasing the memory. If it helps, I am using angsd version: 0.933-102-g7d57642 (htslib: 1.11-1-g1814ae3) build(Sep 23 2020 12:15:02) with the following flags: 

~/bin/angsd/angsd \
-b /home/allHG_covm0.5 \
-ref ~/refs/hg19_fix.fa \
-out /home/allHG_covm0.5_GL2  \
-sites /sites/ALL.Allchr.phase3_sites_ANGSD2 \
-uniqueOnly 1 \
-remove_bads 1 \
-only_proper_pairs 1 \
-C 50 \
-baq 1 \
-skipTriallelic 1 \
-trim 3 \
-minInd 3 \
-GL 2 \
-doMajorMinor 1 \
-doMaf 2 \
-minMaf 0.1 \
-nThreads 25

Any help to rectify this issue would be much appreciated. 

Thank you and best wishes, 

Dean

**Comment by fidibidi** [comment]
Was there ever anything you found that fixed this? Similar sitch...

**Comment by DcornishUCL** [comment]
I corrected this by recompiling the latest version of ANGSD. I hope that helps.
