### ISSUE TITLE
VCF PL tag

### ISSUE THREAD

**Issue by tristanpwdennis** [ANGSD/angsd#437]
Hey @ANGSD,
I am fiddling around with VCF output (as input for phasing and imputation in BEAGLE and GLIMPSE). I have question and a potential issue:

- Do the wise people of ANGSD recommend a specific phasing software? I have settled on BEAGLE v4 as it says it accomodates GLs, but would others be suitable (e.g. SHAPEIT or GLIMPSE)

- The documentation says there may be some problems with GL scaling in VCF output, but the page was last modified (I think) in 2015 - is this still a concern?

- I am trying out some imputation in GLIMPSE and apparently it needs the phred-scaled likelihood (PL) tag. The PL tag is specified in ANGSD VCF header, but I can't see it in the FORMAT column (just `GT:DP:AD:GP:GL`). Is there any scope for implementing PL tag in ANGSD VCF output?  I am trying to look through the vcfReader.cpp, but I am getting a bit lost.

Maybe I am missing something, but good to check. Thanks as always for the software.

Tristan

**Comment by Jungal10** [comment]
Not sure if it still helps, but I had success using beagle (v5.2) on the VCF output from angsd (v0.921) before.

**Comment by ANGSD** [comment]
I do not have experience enough to recommend a specific phasing software. The issue with the GL tag is that at the time it was not clear for me how it should be scaled. What we ended up doing was this:
```
##FORMAT=<ID=GL,Number=G,Type=Float,Description="scaled Genotype Likelihoods (loglikeratios to the most likely (in log10))">
```
Angsd should output both PL and GL in the newer versions.

```
./angsd -b list -gl 1 -dopost 1 -domajorminor 1 -domaf 1 -dobcf 1 --ignore-RG 0 -dogeno 1 -docounts 1 -r 1
bcftools view angsdput.bcf -H|head -n1
1	13999902	.	A	C	0	PASS	NS=1;DP=1;AF=7.81206e-06	GT:DP:GL:PL:GP	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	0/0:1:0,-0.301034,-2.9:0,3,29:0,51.0723,131.145	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0	./.:0:0,0,0:0,0,0:0,0,0
```
I am closing this issue, feel free to reopen if needed.
