### ISSUE TITLE
How to transform angsd.sfs in a format SweepFinder2 can use

### ISSUE THREAD

**Issue by mfariasvirgens** [ANGSD/angsd#438]
Hi, 
I'm trying to use a folded sfs output by realSFS in SweepFinder2, which I put in the format bellow. Unfortunately, I don't have a ancestor species assembly, so I'm using self as reference assembly, and that's why my sfs is folded.  

```
1       971466749.403089
2       2574529.722530
3       2369827.648993
4       1763843.071659
5       1426016.534606
6       1160726.869036
7       988399.580437
8       870618.953452
9       786907.410523
10      731642.388835
11      707536.048869
12      343753.349550
13      0.000000
14      0.000000
15      0.000000
16      0.000000
17      0.000000
18      0.000000
19      0.000000
20      0.000000
21      0.000000
22      0.000000
23      0.000000
```
The program seems to run fine, but I wanna make sure I don't have to do any transformations to the angsd sfs because this is the kind of sfs SweepFinder2 itself produces for the same data. 

```
0       9.780822e-01
1       1.041976e-02
2       2.735620e-03
3       1.837831e-03
4       1.402438e-03
5       1.154053e-03
6       9.732948e-04
7       8.188403e-04
8       8.031051e-04
9       7.517067e-04
10      7.057625e-04
11      3.121344e-04
12      2.991976e-07
13      2.991976e-07
14      2.991976e-07
15      2.991976e-07
16      2.991976e-07
17      2.991976e-07
18      2.991976e-07
19      2.991976e-07
20      2.991976e-07
21      2.991976e-07
22      2.991976e-07
```

**Comment by ANGSD** [comment]
I am not sure what the format is for sweepfinder2, maybe this question should be for the sweepfinder authors. In the more recent versions of angsd, there is a possibility of printing out the bin for the flattened output. I will close this issue but feel free to reopen if needed.
