### ISSUE TITLE
Huge log file

### ISSUE THREAD

**Issue by willright28** [ANGSD/angsd#439]
Hi all,
Rrcently when I used angsd it returns a very huge log file(about 4T) and after I rm it the memory in my server does not release at all. Does the angsd will create some temporary file which tends to occupy the memory quickly? Because I can see my server's memory decreasing very fast when the angsd is running, then I confirm my guess by stopping the job and checking memory again.
Have anyone else encounted this problem ever? Where can I find the possible temporary file?

Thanks in advance!

**Comment by TeresaPegan** [comment]
This sometimes happens when ANGSD prints out a repeating message endlessly. I'm sure it's some kind of bug. E.g. https://github.com/ANGSD/angsd/issues/390

**Comment by willright28** [comment]
> This sometimes happens when ANGSD prints out a repeating message endlessly. I'm sure it's some kind of bug. E.g. #390

Thanks for your replying @TeresaPegan.
What about your disk space when you removed the log file? For mine, it was still occupied after the log file was removed, and I cannot find out why.

**Comment by TeresaPegan** [comment]
I've never had that particular problem, so it might not be ANGSD. Two things to check -- did you see whether there is both an output file and an error file? Make sure you've deleted both. Second, I have used an institutional cluster where the storage doesn't always immediately clear when you delete a file (to allow the possibility of undoing an accidental delete), so I'd look into the storage policies of the affected disk.

**Comment by ANGSD** [comment]
I dont think this has to do with very large logfiles but maybe you have allocated to many threads. Can you supply me with the commands you have used together with some of the output from the very large log file if this issue is still relevant.
