### ISSUE TITLE
`msToGlf` pileup output

### ISSUE THREAD

**Issue by MoiColl** [ANGSD/angsd#441]
Dear @ANGSD,

I'm using `angsd` (more specifically, `msToGlf`) in order to simulate Genotype Likelihoods (GLs) from simulated data by `SLiM`. The `msToGlf` output is obtained in `pileup` format by setting the option `-pileup 1`, since I could not find a way to read the `.glf1.gz` file outputted by default or when the option `-pileup 0` was set. 

In order to be consistent and reproducible, I've generated a [gist](https://gist.github.com/MoiColl/0871a351c02b041f6ce5ec3fe16e8c33) with the examples I'm referring to and with some other minor questions. But here is a summary:

My issue is with the interpretation of the resulting file. As I understand, the `pileup` format consists of each row being an SNP and each has 3 initial columns (chromosome, position, and reference bp) and then contains information for each haplotype that appear in the `ms` file (usually 3 rows per haplotype which corresponding to (i) the number of reads, (ii) the bases in each read and (iii) the quality of those bases). However, when I simulate with 30x depth I get "missing" information for an extra haplotype (in my `ms` file I have only 10 haplotypes and I get info corresponding to 11 haplotypes in the `pileup` file) and when I simulate with 1x depth, I can't understand how the information is organized.

When I then call GLs with `angsd` using those `pileup` files, the output for the 30X depth simulation looks fine and seems to vary according to the support each allele has. However, although the output for the 1X `pileup` file has GLs for 5 individuals (as it should be), all the GLs are the same for the 5 simulated individuals, which doesn't seem to be right (based on how the `mpileup` file looks like). Thus, I believe that I'm either not understanding the outputs produced by both `angsd` and `msToGlf` (most probably), or the GLs files are incorrect. In case I interpret the files incorrectly, can you point me to documentation describing the `pileup` format? I can only find the format in which each line corresponds to a single read for a given individual like [here](http://samtools.sourceforge.net/pileup.shtml) or [here](http://www.htslib.org/doc/samtools-mpileup.html).

Thanks for your help and for developing such a cool tool!

Moi

**Comment by ANGSD** [comment]
Dear Moi, Sorry for not getting back to your sooner. I have pushed a new commit that should fix some of the points. In my testrun I indeed had a problem with empty glfs, but not an issue with extra individuals. The previous version did actually not allow for the the joint generation of the glfs and the pileup. Now it can do both. Please let me know if you still encounter problems with the software.

Again I am sorry for the prolonged response time.

**Comment by MoiColl** [comment]
Thanks!
