### ISSUE TITLE
duplicate sites in maf output

### ISSUE THREAD

**Issue by bishopia** [ANGSD/angsd#447]
Hi there,

I'm trying to get a beagle file for PCA, but I'm having some strange issues using ```-rf``` and ```-sites``` with my exon bedfile (which was converted to 1-base and indexed per ANGSD wiki). When I use these parameters my resulting maf.gz and beagle.gz files end up contain many duplicate rows for each site. I'm running the following:

```
singularity exec --no-home -B $PWD:/mnt angsd.sif angsd -b /mnt/exon_bam.list \
  -anc /mnt/$REF \
  -ref /mnt/$REF \
  -out /mnt/PCA_TRIAL6/PCA_SNPs \
  -rf /mnt/bedfiles/aug_exon.angsd.file \
  -sites /mnt/bedfiles/aug_exon.angsd.file \
  -nThreads $THREADS \
  -minMapQ 20 -minInd 16 -minQ 20 -doMaf 1 -minMaf 0.05 -SNP_pval 1e-6 \
  -GL 1 -doGlf 2 -doMajorMinor 1 -rmTriallelic 0 -setMinChunkSize 5000
```

bam list looks like this:
```
head exon_bam.list

/mnt/bam_subsets/S10.exon_region.bam
/mnt/bam_subsets/S11.exon_region.bam
/mnt/bam_subsets/S12.exon_region.bam
/mnt/bam_subsets/S13.exon_region.bam
/mnt/bam_subsets/S14.exon_region.bam
/mnt/bam_subsets/S15.exon_region.bam
/mnt/bam_subsets/S16.exon_region.bam
/mnt/bam_subsets/S17.exon_region.bam
/mnt/bam_subsets/S18.exon_region.bam
/mnt/bam_subsets/S19.exon_region.bam

```

bed file looks like this:
```
head bedfiles/aug_exon.angsd.file

scaffold-1_704926   139394  141973
scaffold-1_704926   142064  143248
scaffold-1_704926   143338  143583
scaffold-1_704926   519031  520676
scaffold-1_704926   520735  520951
scaffold-1_704926   521033  521608
scaffold-1_704926   662747  663124
scaffold-2_695645   1   196
scaffold-2_695645   326 880
scaffold-2_695645   10449   10700
```

When I collapse my output maf file and remove/count duplicate rows, it looks like this:
```
zcat PCA_SNPs.mafs.gz | sort - | uniq -c | head
      1 chromo  position    major   minor   ref anc knownEM pK-EM   nInd
     21 scaffold-1_704926   519151  C   A   C   C   0.068520    3.522127e-11    19
     21 scaffold-1_704926   519157  C   A   C   C   0.069220    8.915091e-14    19
     21 scaffold-1_704926   519270  A   T   A   A   0.083462    3.868919e-10    17
     21 scaffold-1_704926   519407  G   A   G   G   0.482972    0.000000e+00    21
     21 scaffold-1_704926   519618  A   T   T   T   0.454772    0.000000e+00    21
     21 scaffold-1_704926   519696  T   C   T   T   0.374056    0.000000e+00    20
     21 scaffold-1_704926   519813  C   T   C   C   0.101124    0.000000e+00    24
     21 scaffold-1_704926   519939  T   C   T   T   0.218069    0.000000e+00    25
     21 scaffold-1_704926   520206  C   T   T   T   0.372301    0.000000e+00    23
```

I've tried just ```-sites```, just ```-rf```, both ```-sites``` and ```-rf```. I've also tried using BAMs prefiltered to remove reads outside of target regions. I don't know what I'm missing here. All I'd like to do is get likely SNPs for different genomic regions, which i have bedfiles for. Maybe it is easier (if longer) to run whole genome and filter by bedfile after that.

Any help much appreciated

**Comment by ANGSD** [comment]
Are you sure the regions used by -rf are disjoint.
Secondly you can verify the actual sites used by the -sites by doing angsd sites print /mnt/bedfiles/aug_exon.angsd.file

I would limit the input for the -rf to the contigs supplied by the -sites. In details the input for -sites is a passive filter, whereas -rf is active, meaning that it is using the indexing feature.

Best

**Comment by bishopia** [comment]
Thanks for the suggestion. I did indeed find a few regions that overlap, but when I fixed that (made this disjoint via bedtools merge) I still get the same issues, ie many duplicate rows when i use -rf to target exons, and a region lookup count of 195231, 3x the number of intervals in the region file i provide (65077).

**Comment by ANGSD** [comment]
Apart from intervals not being disjoint in the file supplied to rf I can not spot what could be causing it. Could you supply me with the contents of -rf file?

**Comment by bishopia** [comment]
[aug_exon_flattened.angsd.file.zip](https://github.com/ANGSD/angsd/files/7974070/aug_exon_flattened.angsd.file.zip)

**Comment by ANGSD** [comment]
Dear @bishopia did you figure this out?
I would normally use this format for the -rf file
chr:from-to
I am not sure what the behavior is when using space/tab in that file

**Comment by ANGSD** [comment]
I assume this issue has resolved by itself. Feel free to reopen.

**Comment by bishopia** [comment]
I think the sites file format is the issue. when i have it with tabs, like:

scaffold-1_704868	4375	4376
scaffold-1_704868	9446	9447

i get rows for both from and return, like this:

scaffold-1_704868_4375
scaffold-1_704868_4376
scaffold-1_704868_9446
scaffold-1_704868_9447

duplicates are not there when i use the "chr    pos" format. thanks!

**Comment by ANGSD** [comment]
Hello, if i remember this functionality correct you should format your -rf like

chrom:from-to
