### ISSUE TITLE
Creating GLF for 50+ samples, crashing

### ISSUE THREAD

**Issue by fidibidi** [ANGSD/angsd#449]
Hi All. 

I am trying to run the following command on roughly 60 samples

```
angsd -GL 1 -out outputfile -nThreads 4 -doGlf 2 -doMajorMinor 3 -doMaf 2 -SNP_pval 1e-6 -bam BAMLIST -sites 1240K_sites.txt
```

I keep getting a segmentation fault ( core dump ) error, and the software crashes. 

I thought it could be a memory issue, but I just ran it using an instance with 700+ gb ram, and still got the error...

I'm hoping somebody might be able to help me debug this issue!

Thanks

**Extra Info:**

For context, the overall goal is to create a GLF for a reference set, then for a testing set. 

Merge these, and pass along to PCAngsd to do a kinship analysis. 

1. Download the reference set of around ~60 bams, as well as my trio to my instance.
2. Prepare the sites file:
   sed -r 's/^[ ]+//;s/[ ]+/\t/g' v42.4.1240K_haploid.snp  | awk '{print $2,$4}' >1240K_sites.txt
   angsd sites index your.file

3.Run TRIO through angsd
angsd -GL 1 -out CA0346.angsd -nThreads 4 -doGlf 2 -doMajorMinor 1 -doMaf 2 -SNP_pval 1e-6 -bam CA0346.bamslist -sites 1240K_sites.txt

4. Run Reference Set through angsd
angsd -GL 1 -out Ref.angsd -nThreads 4 -doGlf 2 -doMajorMinor 1 -doMaf 2 -SNP_pval 1e-6 -bam Ref.bamslist -sites 1240K_sites.txt

5. Test to see that both files have the same number of lines
wc -l ref_beagle samples_beagle

6. If confirmed same line count, merge the files, column-wise:
unzip
if needed, rename column header for trio samples
cut -d' ' -f 4- samples_beagle >samples_glf
paste -d' ' ref_beagle samples_glf >kinship_glf
gzip

7. Pass to Pcangsd!

**Comment by ANGSD** [comment]
Could you try to use a newer version of angsd, there was a bug that could be causing segfaults that was fixed in this comit:
https://github.com/ANGSD/angsd/commit/7633b530b9b39a06a2f022965b3a135d3bacbc97
