### ISSUE TITLE
-snp_pval is unknown will exit

### ISSUE THREAD

**Issue by alexjvr1** [ANGSD/angsd#450]
Hi, 

When I try to use -snp_pval or -SNP_pval (the two variations of this filter that I could find) I get the error: -snp_pval is unknown will exit. 

Is there an updated command I can use? 

time $angsd -b pop1.bams -checkBamHeaders 1 -minQ 20 -minMapQ 20 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 0 -r LR761675.1 -GL 1 -doSaf 1 -anc REF.fna -ref REF.fna -doCounts 1 -setMinDepth 20 -setMaxDepth 1000 -doMajorMinor 4 -out filtered.out -C 50 -baq 1 -dumpCounts 2 -doDepth 1 -doGlf 2 -minInd 10 -doGeno 4 -doPost 2 -geno_minDepth 2 -snp_pval 1e-6

I've also tried adding -dosnpstat 1 and -doHWE 1, but that doesn't work. 

Thank you
Alex

**Comment by ANGSD** [comment]
Dear Alex, the current method for doing snp discovery in angsd is based on
the estimated allele frequency. You therefore also need to supply -domaf 1.
I agree that this is not clear and I will therefore keep this issue open so
I remember to update either the program or documentation.

Best regards

Den fre. 4. feb. 2022 kl. 15.53 skrev Alexandra J. van Rensburg <
***@***.***>:

**Comment by alexjvr1** [comment]
Thanks so much for the quick reply. That does make sense and I should have noticed that I need -domaf 1. It all works now with no problems. 

All the best
Alex
