### ISSUE TITLE
2D SFS memory usage

### ISSUE THREAD

**Issue by VBieker** [ANGSD/angsd#454]
Hi,

When trying to estimate the 2D SFS between 2 populations for the whole genome,` realSFS ` takes up a lot of memory. I was thinking to do it for each chromosome individually instead. Is there a way to combine the output for each individual chromosome later so that I can calculate the global Fat with `realSFS fst stats`?

Thank you,
Vanessa

**Comment by ANGSD** [comment]
Dear @VBieker I pushed a new version of angsd and realSFS that should use alot less memory. I suggest you try that.
If you have different local estimates of the sfs, you can of course take the average to obtain a new global one. But I would use the entire genome. I am closing this issue, feel free to reopen if needed.
