### ISSUE TITLE
thetaStat input bug

### ISSUE THREAD

**Issue by ArthiiNW** [ANGSD/angsd#458]
Hi there,

I was trying to use thetaStat (angsd v.0.935) with the following command:

`thetaStat do_stat ${outname}.saf.idx -win 50000 -step 1000 -outnames ${outname}.theta.thetasWindow.gz`

The input .saf.idx file was generated by the following command (angsd v.0.935):

`angsd -bam $bamlist -GL 2 -dosaf 1 -anc $ref -ref $ref -doCounts 1 \
     -minQ 20 -minmapq 30 -r HiC_scaffold_1 -setMinDepth $MinDepth -setMaxDepth $MaxDepth \
     -noTrans 0 -minInd $n -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 \
     -nthreads 20 -out ${outname}`

However, it returns the following error:

> thetaStat do_stat ReHo_Modern_ch1.saf.idx -win 50000 -step 1000 -outnames ReHo_Modern_ch1.theta.thetasWindow.gz
	Assuming binfile:ReHo_Modern_ch1.saf.gz and indexfile:ReHo_Modern_ch1.saf.idx
	-> It looks like input files have been generated with an older version of ANGSD. Either use older version of angsd <0.915 or rerun main angsd with later version of angsd >0.917 magicnr:'safv3'

As I am using angsd v0.935 all the way, I wonder if there's a bug in the program? Or, how to fix the error?

**Comment by g-pacheco** [comment]
I am no expert -- far from it, but I guess you are missing a few steps, no?:


#### Population Genetics Estimates:

##### Runs `realSFS`:

```
for query in NorthSea Kattegat BalticSea

do
    realSFS -P 40 -fold 1 /home/projects/dp_00007/people/geopac/Analyses/Turbot/Turbot_Fst/BSG_Turbot--GoodSamples_Ind66_${query}.saf.idx > /home/projects/dp_00007/data/geopac/angsd_Fst/Turbot/BSG_Turbot_Ind66_${query}.sfs
    
done
```

##### Calculates the `thetas` for each site:

```
for query in NorthSea Kattegat BalticSea

do
    realSFS saf2theta /home/projects/dp_00007/people/geopac/Analyses/Turbot/Turbot_Fst/BSG_Turbot--GoodSamples_Ind66_${query}.saf.idx -sfs /home/projects/dp_00007/data/geopac/angsd_Fst/Turbot/BSG_Turbot_Ind66_${query}.sfs -fold 1 -outname /home/projects/dp_00007/data/geopac/angsd_Fst/Turbot/BSG_Turbot_Ind66_${query}_PopGenEstimates
    
done
```

##### Gets summary of `thetas`:

```
for query in NorthSea Kattegat BalticSea

do
    thetaStat print /home/projects/dp_00007/data/geopac/angsd_Fst/Turbot/BSG_Turbot_Ind66_${query}_PopGenEstimates.thetas.idx > /home/projects/dp_00007/data/geopac/angsd_Fst/Turbot/BSG_Turbot_Ind66_${query}_PopGenEstimates.Print

done
```

##### Performs final calculations:

```
for query in NorthSea Kattegat BalticSea
do

    N_IND=`cat /home/projects/dp_00007/people/geopac/Analyses/Turbot/Turbot_Lists/BSG_Turbot--AllSamples_${query}-Fst.list | wc -l`

    Rscript --vanilla --slave /home/projects/dp_00007/apps/Scripts/GetsThetaSummaries.R /home/projects/dp_00007/data/geopac/angsd_Fst/Turbot/BSG_Turbot_Ind66_${query}_PopGenEstimates.Print $N_IND $query
done > /home/projects/dp_00007/people/geopac/Analyses/Turbot/Turbot_Fst/BSG_Turbot_Ind66.PopGenEstimates.txt
```

##### Gets `thetas` per sliding window:

```
for query in NorthSea Kattegat BalticSea
do
    thetaStat do_stat /home/projects/dp_00007/data/geopac/angsd_Fst/Turbot/BSG_Turbot_Ind66_${query}_PopGenEstimates.thetas.idx -win 20000 -step 20000 -outnames /home/projects/dp_00007/people/geopac/Analyses/Turbot/Turbot_Fst/BSG_Turbot_Ind66_20K_${query}_PopGenEstimates-Windows
done
```

**Comment by ANGSD** [comment]
Dear @ArthiiNW , 
Yes you need to estimate a prior using realSFS as suggested by @g-pacheco .

That should fix the problem, so I am closing this issue, but feel free to reopen if needed.

Best

**Comment by squisquater** [comment]
Hi there,

I am having a similar issue and would like to reopen this. I have tried to run the following script several different ways: 
```
#!/bin/bash -l
#SBATCH --job-name=S.CA_SFS
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --time 30:00
#SBATCH --mem=4GB
#SBATCH -p high
#SBATCH -o /home/sophiepq/GrayFoxWGS/GrayFox1/slurmlogs/S.CA_SFS.out
#SBATCH -e /home/sophiepq/GrayFoxWGS/GrayFox1/slurmlogs/S.CA_SFS.err

module load angsd

echo "Generating site allele frequency file using GLs called using samtools (-GL 1)"
angsd -bam ~/GrayFox/angsd/SFS/S.CA_bamlist.txt -doSaf 1 -anc ~/Reference_Genomes/canFam3_withY.fa -GL 1 -P 24 -out ~/GrayFox/angsd/SFS/S.CA_redo

echo "Generating sfs"
realSFS ~/GrayFox/angsd/SFS/S.CA_redo.saf.idx -P 24 > ~/GrayFox/angsd/SFS/S.CA_redo.sfs

echo "Generating thetas"
realSFS saf2theta ~/GrayFox/angsd/SFS/S.CA_redo.saf.idx -sfs ~/GrayFox/angsd/SFS/S.CA_redo.sfs -outname ~/GrayFox/angsd/SFS/S.CA_redo

echo "summarizing theta stats"
thetaStat do_stat ~/GrayFox/angsd/SFS/S.CA_redo.saf.idx

echo "all done"
```

I keep getting the same error on the final step of generating summary thetas (all other files appear to have been generated correctly)

```
thetaStat do_stat /home/sophiepq/GrayFox/angsd/SFS/S.CA_redo.saf.idx
        Assuming binfile:/home/sophiepq/GrayFox/angsd/SFS/S.CA_redo.saf.gz and indexfile:/home/sophiepq/GrayFox/angsd/SFS/S.CA_redo.saf.idx
        -> It looks like input files have been generated with an older version of ANGSD. Either use older version of angsd <0.915 or rerun main angsd with later version of angsd >0.917 magicnr:'safv3'
```
Since this was all done within a shell script where I loaded a specific angsd module "-> angsd version: 0.934 (htslib: 1.11) build(May 11 2021 19:16:02", I don't understand how I am getting this error. 

I have also tried running this by loading the same angsd version/module in an interactive session and I also tried using two different conda environments, but I keep getting the same error. 

conda environments
-angsd version: 0.935 (htslib: 1.14) build(Feb 22 2022 08:41:24)
-angsd version: 0.937 (htslib: 1.15.1) build(Mar  3 2022 00:51:08)


Any ideas what could be causing this or how to troubleshoot?
