### ISSUE TITLE
angsd fst index error output !!!

### ISSUE THREAD

**Issue by Wesley-sx** [ANGSD/angsd#459]
Hi,

I am using angsd to calculate fst. Due to poor quality reference genome, there are many scaffolds with 0 sites to keep from 2 or 3 pops. Something like the following:

>         -> Will now do fst temp dump using a chunk of 0
>         -> Done reading data from chromosome will prepare next chromosome
>         -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect
>         -> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
>         -> Sites to keep[Sc247Nf-1043] from pop0:       0
>         -> Sites to keep[Sc247Nf-1043] from pop1:       0
>         -> There is no data for this chr/scaffold lets skip
>         -> Is in multi sfs, will now read data from chr:Sc247Nf-1000
>         -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect
>         -> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
>         -> Sites to keep[Sc247Nf-1000] from pop0:       26
>         -> Sites to keep[Sc247Nf-1000] from pop1:       26

I would expect no output from `Sc247Nf-1043`. However, using command `realSFS fst print svbd.nor_wild.fold.fst.idx  -r Sc247Nf-1043: | less` , I have the following result:

>   -> args: tole:0.000000 nthreads:4 maxiter:100 nsites:0 start:(null) chr:Sc247Nf-1043 start:-1 stop:-1 fstout:(null) oldout:0 seed:-1 bootstrap:0 resample_chr:0 whichFst:0 fold:0 ref:(null) anc:(null)
> choose:1
> pars->stop:-1 ppos:3427 first:0 last:26
> Sc247Nf-1043    504     0.015601        0.401580
> Sc247Nf-1043    929     0.004172        0.069170
> Sc247Nf-1043    950     0.003287        0.064777
> Sc247Nf-1043    959     0.001515        0.243238
> Sc247Nf-1043    960     0.001868        0.238069
> Sc247Nf-1043    962     0.001680        0.240506
> Sc247Nf-1043    963     0.002484        0.247683
> Sc247Nf-1043    999     -0.004600       0.394339
> Sc247Nf-1043    1057    0.018149        0.400057
> Sc247Nf-1043    1076    0.018484        0.404613
> Sc247Nf-1043    1081    -0.006349       0.442238
> Sc247Nf-1043    1112    -0.007199       0.449839
> Sc247Nf-1043    1136    0.000986        0.390635
> Sc247Nf-1043    1151    -0.000716       0.275244
> Sc247Nf-1043    1154    0.000503        0.269551
> Sc247Nf-1043    1156    -0.000715       0.275317
> Sc247Nf-1043    1187    -0.001118       0.136160
> Sc247Nf-1043    1190    -0.000702       0.132815
> Sc247Nf-1043    3208    0.008366        0.223306
> Sc247Nf-1043    3242    -0.006058       0.390717
> Sc247Nf-1043    3294    0.006249        0.499968
> Sc247Nf-1043    3319    -0.010514       0.500000
> Sc247Nf-1043    3320    -0.010515       0.500000
> Sc247Nf-1043    3354    -0.010523       0.500000
> Sc247Nf-1043    3427    -0.011543       0.500000
> Sc247Nf-1043    3428    -0.011518       0.500000

This is actually the result of` Sc247Nf-1000]`. 

>  -> args: tole:0.000000 nthreads:4 maxiter:100 nsites:0 start:(null) chr:Sc247Nf-1000 start:-1 stop:-1 fstout:(null) oldout:0 seed:-1 bootstrap:0 resample_chr:0 whichFst:0 fold:0 ref:(null) anc:(null)
> choose:1
> pars->stop:-1 ppos:3427 first:0 last:26
> Sc247Nf-1000    504     0.015601        0.401580
> Sc247Nf-1000    929     0.004172        0.069170
> Sc247Nf-1000    950     0.003287        0.064777
> Sc247Nf-1000    959     0.001515        0.243238
> Sc247Nf-1000    960     0.001868        0.238069
> Sc247Nf-1000    962     0.001680        0.240506
> Sc247Nf-1000    963     0.002484        0.247683
> Sc247Nf-1000    999     -0.004600       0.394339
> Sc247Nf-1000    1057    0.018149        0.400057
> Sc247Nf-1000    1076    0.018484        0.404613
> Sc247Nf-1000    1081    -0.006349       0.442238
> Sc247Nf-1000    1112    -0.007199       0.449839
> Sc247Nf-1000    1136    0.000986        0.390635
> Sc247Nf-1000    1151    -0.000716       0.275244
> Sc247Nf-1000    1154    0.000503        0.269551
> Sc247Nf-1000    1156    -0.000715       0.275317
> Sc247Nf-1000    1187    -0.001118       0.136160
> Sc247Nf-1000    1190    -0.000702       0.132815
> Sc247Nf-1000    3208    0.008366        0.223306
> Sc247Nf-1000    3242    -0.006058       0.390717
> Sc247Nf-1000    3294    0.006249        0.499968
> Sc247Nf-1000    3319    -0.010514       0.500000
> Sc247Nf-1000    3320    -0.010515       0.500000
> Sc247Nf-1000    3354    -0.010523       0.500000
> Sc247Nf-1000    3427    -0.011543       0.500000
> Sc247Nf-1000    3428    -0.011518       0.500000

So, I believe there is a small output logic error in the code. Please check and fix this.

Thanks!

Best,
Xin

**Comment by Wesley-sx** [comment]
The version I have tried is 0.931 and 0.935.

**Comment by ANGSD** [comment]
Dear xin, can you supply me with the saf files? Then I can look into it.

**Comment by Wesley-sx** [comment]
Dear angsd,

Please find the attached file and logs.
I generated saf from beagle files.

These scaffolds should be empty. 

> Sc247Nf-1019 
> Sc247Nf-1029


Best,
Xin

[for_angsd_test.tar.gz](https://github.com/ANGSD/angsd/files/8168638/for_angsd_test.tar.gz)

**Comment by ANGSD** [comment]
Dear Xin, thanks for reporting this. There was indeed an error. Your input data helped me resolved it. It is fixed int he most recent commit.
