### ISSUE TITLE
multiSFS with realSFS fails for reasons unknown

### ISSUE THREAD

**Issue by thetrio84** [ANGSD/angsd#46]
Hi there,

I'm encountering an error that I can't seem to work around. I'm trying to make a 2d SFS (joint MAF SFS) from two populations. The two ANGSD commands seem to work without issue, but when I run the realSFS command on the two .saf.idx files I get an error that I don't understand. Any ideas what's happening? This happens regardless of whether I change the way I create my 1d SFS (-GL 1 or -GL 2, folded or unfolded -- although I really do need to keep it folded). Below are the commands that I've run, and the error. Any help you can give would be great -- I'm not even sure what went wrong...

Thanks!

-Alex

angsd -b ../PAon_bamlist -anc ../Reference.fasta -Sites ../Sites_passed_filters.keep -out 2dattempt_paon -GL 2 -minMapQ 1 -minQ 20  -doSaf 1

angsd -b ../PAoff_bamlist -anc ../Reference.fasta -Sites ../Sites_passed_filters.keep -out 2dattempt_paoff -GL 2 -minMapQ 1 -minQ 20  -doSaf 1

realSFS 2dattempt_paoff.saf.idx 2dattempt_paon.saf.idx > 2attempt

-> 1) Will set iter according to chooseChr and start and stop

        -> Sites to keep[EBRARK001_BG118_locus100956] from pop0:        90

        -> Sites to keep[EBRARK001_BG118_locus100956] from pop1:        90

        -> [readdata] lastread:90 posi:4

        -> Comparing positions: 1 with 0 has:16779

        -> Only read nSites: 16779 will therefore prepare next chromosome (or exit)

        -> Done reading data from chromosome will prepare next chromosome

        -> Is in multi sfs, will now read data from chr:EBRARK001_BG118_locus100963

        -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect

        -> 1) Will set iter according to chooseChr and start and stop

        -> Sites to keep[EBRARK001_BG118_locus100963] from pop0:        66

        -> Sites to keep[EBRARK001_BG118_locus100963] from pop1:        66

        -> [readdata] lastread:66 posi:4

        -> Comparing positions: 1 with 0 has:16845

        -> Only read nSites: 16845 will therefore prepare next chromosome (or exit)

        -> Done reading data from chromosome will prepare next chromosome

        -> Is in multi sfs, will now read data from chr:EBRARK001_BG118_locus100965

        -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 

        -> 1) Will set iter according to chooseChr and start and stop

        -> Sites to keep[EBRARK001_BG118_locus100965] from pop0:        90

        -> Sites to keep[EBRARK001_BG118_locus100965] from pop1:        90

        -> [readdata] lastread:90 posi:4

        -> Comparing positions: 1 with 0 has:16935

        -> Only read nSites: 16935 will therefore prepare next chromosome (or exit)

        -> Done reading data from chromosome will prepare next chromosome

        -> Is in multi sfs, will now read data from chr:EBRARK001_BG118_locus10097

        -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 

        -> 1) Will set iter according to chooseChr and start and stop

realSFS: multisafreader.hpp:117: int set_intersect_pos(std::vector<persaf*>&, char*, int, int, char**): Assertion `hit->m>0' failed.

Aborted (core dumped)

**Comment by ANGSD** [comment]
Hi Alex, are you using the latest version?

**Comment by thetrio84** [comment]
Hi there,

I am running angsd version 0.902 with htslib 1.2.1 on a linux cluster.

-Alex

**Comment by ANGSD** [comment]
The 902 is almost a year old, could you try the latest version, just for the realSFS part.

**Comment by thetrio84** [comment]
Well, that feels silly. Indeed, updating ANGSD worked to solve the problem.
I'm still not sure why I was able to make a 2D SFS in the past with the old
version, but wasn't able to this time. Anyway, thanks for your help!

-Alex

**Comment by ANGSD** [comment]
ok glad to hear that I’m closing this issue, feel free to reopen if needed.
