### ISSUE TITLE
realSFS saf2theta size of dimension error

### ISSUE THREAD

**Issue by ArthiiNW** [ANGSD/angsd#461]
Hi there,

It's me again! I was trying to use thetaStat (angsd v.0.935) with the following command:

```
angsd -bam $bamlist -GL 2 -dosaf 1 -anc $ref -ref $ref -doCounts 1 \
     -minQ 20 -minmapq 30 -r HiC_scaffold_1 -setMinDepth $MinDepth -setMaxDepth $MaxDepth \
     -noTrans 0 -minInd $n -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 \
     -nthreads 20 -out ${outname}

realSFS ${outname}.saf.idx -fold 1 -P 20 -tole 1e-8 -bootstrap 100 > ${outname}.sfs 

realSFS saf2theta ${outname}.saf.idx -fold 1 -sfs ${outname}.sfs -P 20 -outname ${outname}

thetaStat print ${outname}.saf.idx > ${outname}.Print

thetaStat do_stat ${outname}.saf.idx -win 50000 -step 1000 -outnames ${outname}.theta.thetasWindow
```

However, at the saf2theta step, it gives the following error:

> -> Version of fname:ReHo_Modern_ch1.saf.idx is:2
	-> Assuming .saf.gz file: ReHo_Modern_ch1.saf.gz
	-> Assuming .saf.pos.gz: ReHo_Modern_ch1.saf.pos.gz
	-> args: tole:0.000000 nthreads:20 maxiter:100 nsites:0 start:ReHo_Modern_ch1.sfs chr:(null) start:-1 stop:-1 fstout:ReHo_Modern_ch1 oldout:0 seed:-1 bootstrap:0 resample_chr:0 whichFst:0 fold:1 ref:(null) anc:(null)
	-> Will read chunks of size: 4096
	-> Reading: ReHo_Modern_ch1.sfs assuming counts (will normalize to probs internally)
	-> Pxroblem with size of dimension of prior 43 vs 1677

Could you help me with this error? Thanks!

**Comment by hhy18** [comment]
I also have the same problem.
My commamd line is "realSFS fst index pop3.saf.idx pop4.saf.idx -sfs pops34.2dsfs -fstout pops34 -whichFst 1", the result have error that "Pxroblem with size of dimension of prior 1023 vs 1089"
Could you help me with this error? Thanks!

**Comment by ANGSD** [comment]
The input for saf2theta and all methods that is an estimate of the (multi)sfs is assuming that the estimate of the sfs is a single line of text. This seems to be causing the issue both @ArthiiNW and @hhy18  observe. I am closing this issue but feel free to reopen if needed.
