### ISSUE TITLE
Make error 1

### ISSUE THREAD

**Issue by MayangStreet** [ANGSD/angsd#465]
Hello.  I've been trying to run angsd in cygwin following this:
git clone --recurse-submodules https://github.com/samtools/htslib.git;
git clone https://github.com/angsd/angsd.git;
cd htslib
make
cd ../angsd
make HTSSRC=../htslib

But I keep running into this error:

HTSSRC not defined; using htslib submodule
Use make HTSSRC=/path/to/htslib to build angsd using a local htslib installation
Use make HTSSRC=systemwide to build angsd using the systemwide htslib installation
git submodule update --init --recursive
make -C /home/NN/angsd/htslib
make[1]: Entering directory '/home/NN/angsd/htslib'
make[1]: Leaving directory '/home/NN/angsd/htslib'
g++ -O3 -o angsd *.o /home/NN/angsd/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread -lcurl -lcrypto
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make: *** [Makefile:114: angsd] Error 1

I'd really appreciate your help. Thanks!

**Comment by ANGSD** [comment]
Compile without cryptolib like:

make CRYPTOLIB=""'


Den ons. 16. mar. 2022 kl. 06.06 skrev MayangStreet <
***@***.***>:

**Comment by isinaltinkaya** [comment]
I am closing this issue. @MayangStreet please feel free to reopen the issue if this is not resolved.
