### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by idiltac** [ANGSD/angsd#470]
Hi. I am trying to run ANGSD on 16 bams with genomic data at 32 × -48× coverage/individual to calculate the maf.Unfortunately, when I run the command, I end up with a segmentation fault every time. Below is my error information and command .
angsd -bam ${bamlist} -ref ${ref} -out ${output} -doGeno 4 -GL 1 -doGlf 4 -doMajorMinor 4 -doMaf 1 -doPost 1 -doPlink 2 -nThreads 5
> 
/tmp/slurmdnode-4//job331380/slurm_script: line 24: 234238 Segmentation fault      ${angsd}/angsd -bam ${bamlist} -ref ${ref} -out ${output} -doGeno 4 -GL 1 -doGlf 4 -doMajorMinor 4 -doMaf 1 -doPost 1 -doPlink 2 -nThreads 5

Why ?
It would be fantastic if you could help me with this! Thank you very much. I am looking forward to hearing from you.Best, İdil.

**Comment by isinaltinkaya** [comment]
Hi,

Could you please specify the version of angsd you are using? If it is not the latest version, could you try using a newer version of angsd? There was a bug that could be causing this issue, and was fixed by the commit https://github.com/ANGSD/angsd/commit/7633b530b9b39a06a2f022965b3a135d3bacbc97

**Comment by idiltac** [comment]
@isinaltinkaya thanks a lot for your answer,  I am attaching the version information below

 /usr/local/sw/angsd/angsd/angsd 
        -> angsd version: 0.934 (htslib: 1.13-23-g3eada2f) build(Sep 21 2021 20:02:32)
        -> /usr/local/sw/angsd/angsd/angsd 
        -> No '-out' argument given, output files will be called 'angsdput'

        -> angsd version: 0.934 (htslib: 1.13-23-g3eada2f) build(Sep 21 2021 20:02:27)

**Comment by isinaltinkaya** [comment]
Could you please try running it with the latest version of angsd?

You can download and build it with the following command:
```
git clone https://github.com/angsd/angsd.git; cd angsd; make;
```

**Comment by isinaltinkaya** [comment]
I am closing the issue; but you are very welcome to reopen it if the issue persists with the latest version.

Best wishes
