### ISSUE TITLE
Ancestral fasta or Reference fasta used for sfs generation with -doMajorMinor 4?

### ISSUE THREAD

**Issue by srachita** [ANGSD/angsd#476]
Hi,

I wanted to generate unfolded sfs for a population of interest and tried various approaches for the same. Some of them included not using -domajorminor at all, using -domajorminor 1 and -domajorminor 4. In order to get sfs with a similar approach as was used to get the sfs, I tried the following command:

**  angsd -bam bamlist -gl 2 -out test -minmapQ 25 -minQ 25 -docounts 1 -anc outgroup.fa -ref reference.fa -P 8 -doHWE 1 -maxHetFreq 0.0001 -setMinDepth 4 -dosaf 1 -doMajorMinor 4 -r Chr1 **

I am forced to use -domajorminor as I want to get rid of all heterozygous sites and therefore need to set -maxHetFreq. I checked the output sfs for a small region of the genome and it does not seem to match the sfs one would generate by counting alleles using a vcf file (excluding the monomorphic bin). Due to this I am unable to understand if anc fasta is being used at all ? I understand that -domajorminor 4 uses ref sequence to assign ref and alt alleles but in case of providing -anc, is the software using anc allele from the anc fasta or the ref allele from ref fasta? Could you please also post if you would recommend using -domajorminor while generating sfs?

**Comment by ANGSD** [comment]
I am not sure what you are trying to do. If you are discarding all the het sites then you wont have a proper sfs. The algorithm polarizes according to a defined ancestral. I hope this helps. I will close the issue, but feel free to reopen if still relevant.
