### ISSUE TITLE
Failing to open .bam files

### ISSUE THREAD

**Issue by mho190** [ANGSD/angsd#477]
Hello,

I am having the same issue as @tristanpwdennis, @dlema82, and @chenqing-1996 had with opening bam files from a list of files. 

angsd -doAbbababa2 0 -bam bamfiletest.txt -sizeFile sizeFile.size.txt -doCounts 1 -out ./Abbababatest.out -useLast 1 -minQ 15 -minMapQ 15 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 0 -minInd 101 -trim 0 -nThreads 60
        -> angsd version: 0.935-53-gf475f10 (htslib: 1.13) build(Dec  2 2021 10:11:27)
        -> angsd -doAbbababa2 0 -bam bamfiletest.txt -sizeFile sizeFile.size.txt -doCounts 1 -out ./Abbababatest.out -useLast 1 -minQ 15 -minMapQ 15 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 0 -minInd 101 -trim 0 -nThreads 60
        -> Inputtype is BAM/CRAM
" : No such file or directoryo open file "/data/mho190/mnova-MT/angsd-no-replciate/189-bamfiles/Mnova16008_FKDL192550623-1a-D701.RG.bam
angsd: multiReader.cpp:192: multiReader::multiReader(argStruct*): Assertion in' failed.
Aborted (core dumped)

I have checked that the file throwing the error exists and is accessible. Any ideas how to troubleshoot the issue? It seems like previous users have solved it somehow. Any help is appreciated!

**Comment by chenqing-1996** [comment]
Hello,
I just change the name of bam file.txt to xxx.filelist,you can try it out.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月10日 04:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | [ANGSD/angsd] Failing to open .bam files (Issue #477) |

Hello,

I am having the same issue as @tristanpwdennis, @dlema82, and @chenqing-1996 had with opening bam files from a list of files.

angsd -doAbbababa2 0 -bam bamfiletest.txt -sizeFile sizeFile.size.txt -doCounts 1 -out ./Abbababatest.out -useLast 1 -minQ 15 -minMapQ 15 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 0 -minInd 101 -trim 0 -nThreads 60
-> angsd version: 0.935-53-gf475f10 (htslib: 1.13) build(Dec 2 2021 10:11:27)
-> angsd -doAbbababa2 0 -bam bamfiletest.txt -sizeFile sizeFile.size.txt -doCounts 1 -out ./Abbababatest.out -useLast 1 -minQ 15 -minMapQ 15 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 0 -minInd 101 -trim 0 -nThreads 60
-> Inputtype is BAM/CRAM
" : No such file or directoryo open file "/data/mho190/mnova-MT/angsd-no-replciate/189-bamfiles/Mnova16008_FKDL192550623-1a-D701.RG.bam
angsd: multiReader.cpp:192: multiReader::multiReader(argStruct*): Assertion in' failed.
Aborted (core dumped)

I have checked that the file throwing the error exists and is accessible. Any ideas how to troubleshoot the issue? It seems like previous users have solved it somehow. Any help is appreciated!

**Comment by mho190** [comment]
Hi @chenqing-1996 , thanks for the idea but it is still not working ...

**Comment by shri1984** [comment]
There are two obvious reasons for this: 
1. bam list file is made in windows and then the text file may carry a few unwanted characters (carriage returns and line-feeds in text files) and then angsd may interpret them as part of the file name. There is a tool called dos2unix to clean up the text files made in windows. 
2. obvious problem with the file path.

**Comment by Jungal10** [comment]
Can you try to not have dashes on the path and files? It sounds weird, but it might be triggering something weird. Underscores should be fine. I usually have them on my bam files using angsd pipelines

**Comment by ANGSD** [comment]
Dear all, I assume this issue has been resolved by formatting the bamlist file properly. Otherwise feel free to reopen.

Best
