### ISSUE TITLE
./realSFS : No such file or directory

### ISSUE THREAD

**Issue by starnoux** [ANGSD/angsd#48]
Hi there,
I am encountering a slight issue with angsd. I have been downloading and installing recentely angsd and htslib. I ran perfectly -dosaf but since I am trying to run ./realSFS, it doesn't find it (it end up being (-bash: ./realSFS: No such file or directory).
Here is the log of the installation of angsd.
>make HTSSRC=../htslib/
HTSSRC defined
make -C misc/ HTSSRC=/Users/stephaniearnoux/Downloads/proj/htslib
HTSSRC defined
/Users/stephaniearnoux/Downloads/proj/htslib/libhts.a
g++ -O3 -c safreader.cpp -I /Users/stephaniearnoux/Downloads/proj/htslib
g++ -O3 -c safstat.cpp -I /Users/stephaniearnoux/Downloads/proj/htslib
g++ -O3 -c realSFS_args.cpp -I /Users/stephaniearnoux/Downloads/proj/htslib
g++ -O3 -c header.cpp -I /Users/stephaniearnoux/Downloads/proj/htslib
g++ -O3 -c fstreader.cpp -I /Users/stephaniearnoux/Downloads/proj/htslib
g++ -O3 -c safcat.cpp -I /Users/stephaniearnoux/Downloads/proj/htslib
g++ -O3 realSFS.cpp -o realSFS  safreader.o realSFS_args.o safstat.o fstreader.o header.o safcat.o ../prep_sites.o ../analysisFunction.o -I /Users/stephaniearnoux/Downloads/proj/htslib /Users/stephaniearnoux/Downloads/proj/htslib/libhts.a -lz -lpthread
>make install
HTSSRC not defined, assuming systemwide installation -lhts
make: Nothing to be done for `install'.

any suggestion?

**Comment by ANGSD** [comment]
Could you try to go to the angsd main directory (not the misc subduer) and do a make clean followed by a make HTSSRC=../htslib

**Comment by starnoux** [comment]
Hi,

Indeed I did so. At first I tried in the main directory and only afterwards I tried in the other one.
And still when I do it in the main directory I get this.
[angsdlog.txt](https://github.com/ANGSD/angsd/files/403331/angsdlog.txt)

**Comment by ANGSD** [comment]
But it doesn't it generate the ./realSFS ?

**Comment by starnoux** [comment]
Not in the main directory only in the ./misc/realSFS .
And I get something like following if I want to use it.

> admins-Mac-mini$ ./misc/realSFS smallSS.saf.idx  > ./smallSS.sfs
> 	-> Version of fname:smallSS.saf.idx is:2
> 	-> Assuming .saf.gz file: smallSS.saf.gz
> 	-> Assuming .saf.pos.gz: smallSS.saf.pos.gz
> 	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:smallSS.saf.idx fstout:(null) oldout:0 seed:1470384596 bootstrap:0
> Assertion failed: (saf[i]->pos!=NULL&&saf[i]->saf!=NULL), function main_opt, file realSFS.cpp, line 1063.
> Abort trap: 6

Question : Is it usable the ./misc/realSFS ??? And is it a problem when the chromosome are named differently than "chr".

**Comment by ANGSD** [comment]
Yes the proper realSFS is located in the misc program. The main angsd is in
the main dir, and some helper programs are in the misc. Can you try
regenerate the smallSS.saf.idx?

**Comment by starnoux** [comment]
It worked like a charm, I used an old one I had generate and it worked fine. Thank you so much for helping me.
I am really sorry that I didn't get the point at first. But in the README and online guidelines, there is written to do ./angsd and then ./realSFS so I didn't get the point that realSFS was in ./misc/realSFS.

Have a good day,
Stéhanie

**Comment by starnoux** [comment]
Just to be sure that I am not mistaken... This is just warnings... I guess it is fine no? The likelihood seems to me unrealistic...
> ------------
> startlik=-76422042.726524
> lik[2]=-3827649.144358 diff=7.259439e+07 alpha:1.000000 sr2:5.755581e-01
> lik[5]=-3316936.115396 diff=5.107130e+05 alpha:1.282846 sr2:9.247020e-04
> lik[8]=-3316047.717742 diff=8.883977e+02 alpha:1.795587 sr2:9.008172e-08
> lik[11]=-3316012.927252 diff=3.479049e+01 alpha:3.887730 sr2:2.118543e-10
> 	-> Breaking EM(sq2) at iter:13, sqrt(sq2):7.957153e-07
> likelihood: -3316012.927252
> ------------
> 	-> Only read nSites: 0 will therefore prepare next chromosome (or exit)
> 
> 	-> NB NB output is no longer log probs of the frequency spectrum!
> 	-> Output is now simply the expected values! 
> 	-> You can convert to the old format simply with log(norm(x))

**Comment by ANGSD** [comment]
I think it looks fine, but look at the estimated parameters

**Comment by ANGSD** [comment]
Ok I'm closing this issue feel free to reopen if needed.
