### ISSUE TITLE
different number of loci for different runs with same script

### ISSUE THREAD

**Issue by shri1984** [ANGSD/angsd#480]
Hi, 
I am using angsd version: 0.935-53-gf475f10 (htslib: 1.12). I used -sites and -rf as some non standard parameters along with other standard parameters. When I run the same script multiple times I end up with a different number of SNPs each time. They are not very off from each other, but they differ. I can not understand why this is happening when all the conditions are the same for these runs. Any thoughts?

Shri

**Comment by ANGSD** [comment]
Dear @shri1984 can you please supply all parameters you have been using? Some analyses performs optimization and will depend on some initial random value. Without knowing which analyses you are doing it is not possible to answer.

Best

**Comment by ANGSD** [comment]
Dear @shri1984 I am closing this issue, feel free to reopen if it is still relevant.
