### ISSUE TITLE
thetaStat error: "It looks like input files have been generated with an older version of ANGSD..."

### ISSUE THREAD

**Issue by squisquater** [ANGSD/angsd#482]
Hi there,

I am having a similar issue to the one described here [https://github.com/ANGSD/angsd/issues/458]. I have tried to run the following script several different ways,

```
#!/bin/bash -l
#SBATCH --job-name=N.CA_SFS_redo
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --time 30:00
#SBATCH --mem=4GB
#SBATCH -p high
#SBATCH -o /home/sophiepq/GrayFoxWGS/GrayFox1/slurmlogs/N.CA_SFS_redo.out
#SBATCH -e /home/sophiepq/GrayFoxWGS/GrayFox1/slurmlogs/N.CA_SFS_redo.err

module load angsd

echo "Generating site allele frequency file using GLs called using samtools (-GL 1)"
angsd -bam ~/GrayFox/angsd/SFS/N.CA_bamlist.txt -doSaf 1 -ref ~/Reference_Genomes/canFam3_withY.fa -anc ~/GrayFox/angsd/SFS/AncestralState/CanVulpAnc.fa -GL 1 -P 24 -out ~/GrayFox/angsd/SFS/N.CA_redo

echo "Generating sfs"
realSFS ~/GrayFox/angsd/SFS/N.CA_redo.saf.idx -P 24 -fold 1 > ~/GrayFox/angsd/SFS/N.CA_redo.sfs

echo "Generating thetas"
realSFS saf2theta ~/GrayFox/angsd/SFS/N.CA_redo.saf.idx -sfs ~/GrayFox/angsd/SFS/N.CA_redo.sfs -fold 1 -outname ~/GrayFox/angsd/SFS/N.CA_redo

echo "summarizing theta stats"
thetaStat do_stat ~/GrayFox/angsd/SFS/N.CA_redo.saf.idx
```

The module load angsd command loads the following version 
```
angsd version: 0.935 (htslib: 1.12) build(Mar 28 2021 01:00:43)
```
All files are generated correctly except the final file summarizing the theta statistics using the thetaStat command. At this step I get an error that reads:
```
It looks like input files have been generated with an older version of ANGSD. 
Either use older version of angsd <0.915 or rerun main angsd with later version of angsd >0.917 magicnr:'safv3'`
```

I don't understand how I am getting this error when the script should be using the same version of angsd loaded at the beginning of the script. 

I also tried this interactively on the computing cluster and using two different conda environments as well and keep getting the same error. 

conda environments:
angsd version: 0.935 (htslib: 1.14) build(Feb 22 2022 08:41:24)
angsd version: 0.937 (htslib: 1.15.1) build(Mar  3 2022 00:51:08)

Any ideas as to what is causing this error?

**Comment by ANGSD** [comment]
Dear @squisquater , it looks like there is a mismatch in versions. I do not think issue #458 relates to the issue you are reporting. Could you validate that the .saf.idx file is parsed correctly using

```realSFS print_header  ~/GrayFox/angsd/SFS/N.CA_redo.saf.idx```

Best

**Comment by ANGSD** [comment]
I assume this one has been resolved, so I am closing the issue.

Best
