### ISSUE TITLE
Is the -SNP_pval option working correctly?

### ISSUE THREAD

**Issue by cbird808** [ANGSD/angsd#487]
The `.arg`  file indicates that the `-SNP_pval 1e-5` threshold I've manually set is being converted to `-SNP_pval 19.511421` by `angsd`.

I just wanted to bring this to your attention because either the *.arg file generation needs to be updated, or the filter is not operating correctly. (or perhaps I've made a mistake in specifying the options and arguments?).

Here are the relevant snippets from the `*.arg`

```
        -> angsd version: 0.937 (htslib: 1.14-9-ge769401) build(Mar 25 2022 10:24:30)
        -> angsd -GL 1 -doGlf 2 -doMajorMinor 1 -doMaf 1 -doSnpStat 1 -doHWE 1 -doGeno 3 -doPost 2 -doCounts 1 -doDepth 1 -doQsDist 1 -doEBD 1 -uniqueOnly 1 -rmTriallelic 0.1 -SNP_pval 1e-5 -minMapQ 50 -minQ 30 -minHWEpval 0.1 -maxHetFreq 0.5 -hetbias_pval 0.05 -sb_pval 0.5 -edge_pval 0.1 -mapQ_pval 0.1 -qscore_pval 0.5 -minInd 41 -setMaxDepth 405 -minMaf 0.0062 -out ./mkBGL/test05 -bam ./fltrBAM/bamNames.txt -nThreads 40
        -> Sun May 15 11:22:38 2022
```

```
Filters:
        -minMaf         0.006200        (Remove sites with MAF below)
        -SNP_pval       19.511421       (Remove sites with a pvalue larger)
        -rmTriallelic   0.100000        (Remove sites with a pvalue lower)
        -forceMaf       0       (Write .mafs file when running -doAsso (by default does not output .mafs file with -doAsso))
        -skipMissing    1       (Set post to 0.33 if missing (do not use freq as prior))
```

And this is in the `*.err` file:

```
-> SNP-filter using a pvalue: 1.000000e-05 correspond to 19.511421 likelihood units
```

**Comment by ANGSD** [comment]
Hello, if I remember correctly the supplied pval gets converted into the corresponding test stat which in 1e-5 should be 19.5.

Best

**Comment by cbird808** [comment]
Thank you for your response.  If everything is working as it should, then this line in the `*.arg` file generated by `angsd` indicates that most good SNPs will be removed (those >19.5):

```
-SNP_pval       19.511421       (Remove sites with a pvalue larger)
```

**Comment by ANGSD** [comment]
Dear @cbird808 , Yes I agree I can see that the message is ver unclear. I have updated the code so it prints out the threshold as pvalue and not as likelihood units.

```
./angsd -gl 1 -domajorminor 1 -b list.list  -r 1  -domaf 1 -snp_pval 12
grep SNP angsdput.arg 
	-SNP_pval	0.000532	(Remove sites with a pvalue larger)
```
86d7256ff3
