### ISSUE TITLE
angsd fst window drops first window

### ISSUE THREAD

**Issue by noahrose** [ANGSD/angsd#49]
When I run a fst sliding window analysis, for instance with a 1000 base window, the first window is from 1000-2000 bases. I just rebuilt angsd yesterday, and I think this may be a new bug in the latest build? Sorry if I am mistaken, and thanks for any help!

Noah

**Comment by noahrose** [comment]
I will also add that I noticed this problem just after angsd started complaining about zlib being the wrong version when it had not done that before. Is it possible that that is somehow related?

**Comment by ANGSD** [comment]
You can define the windows in three different ways in angsd. See this page:

http://popgen.dk/angsd/index.php/Fst#Relative_window_positions.3F

Let me know if it doesnt work or make sense.

**Comment by noahrose** [comment]
Aha, that makes perfect sense, thanks for the pointer!

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed
