### ISSUE TITLE
fst with folded saf

### ISSUE THREAD

**Issue by marce-sarrias** [ANGSD/angsd#502]
Hello,

Has this issue been fixed? 

I'm trying to run the following (see below):

angsd -b pop1.filelist -anc ref.genome.fasta -ref ref.genome.fasta -GL 1 -minMapQ 30 -minQ 20 -uniqueOnly 1 -remove_bads 1 -baq 1 -dosaf 1 -fold 1 -out pop1

but I get this error: 21 argument 	-fold is unknown will exit

Thanks!

Marcela

_Originally posted by @marce-sarrias in https://github.com/ANGSD/angsd/issues/65#issuecomment-1177458727_

**Comment by ANGSD** [comment]
Dear @marce-sarrias the quick answer is that you should not use the -fold option in main angsd anymore but in the realSFS part. I have just pushed a commit that will be much more useful for users.

22e28a6813

```
$ ./angsd -fold 1
	-> The folding has been moved from main angsd to realSFS subfunction.
	-> Remove -fold when doing -dosaf but apply it in realSFS
	-> Will exit
```

I am closing this issue, but feel free to reopen if needed. I was wondering about the usage of the -fold. Is it still listed somewhere in the documentation that it should be used in main angsd?
