### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by williamamarsh** [ANGSD/angsd#503]
Hi,

I am having installation issues using the latest angsd update. The conda version does not support the -sites option, so I am reverting to github installation.

Both github and github installations are unsuccessful on two seperate hpc clusters. The issues are different dependant on installation method.

Is there a known issue with the latest release?

I can provide output as required.

All the best,

William

**Comment by ANGSD** [comment]
Dear William, this does not sound good. Can you show me the compile error?

Best

Den tir. 12. jul. 2022 kl. 17.13 skrev williamamarsh <
***@***.***>:

**Comment by williamamarsh** [comment]
`vcfReader.cpp: In member function 'int vcfReader::parseline(bcf1_t*, htsstuff*, funkyPars*, int&)':
vcfReader.cpp:254:34: warning: control reaches end of non-void function [-Wreturn-type]
  254 |   std::string vcf_format_field = "PL";
      |                                  ^~~~
`

**Comment by williamamarsh** [comment]
`/software/testing/miniconda/miniconda3/bin/x86_64-conda-linux-gnu-c++ -MM -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /software/testing/miniconda/miniconda3/include -I/gpfs/nhmfsa/bulk/share/data/mbl/share/software/testing/angsd.head/htslib -O3 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/software/testing/miniconda/miniconda3/lib -Wl,-rpath-link,/software/testing/miniconda/miniconda3/lib -L/software/testing/miniconda/miniconda3/lib -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /software/testing/miniconda/miniconda3/include vcfReader.cpp >vcfReader.d
/software/testing/miniconda/miniconda3/bin/x86_64-conda-linux-gnu-c++ -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /software/testing/miniconda/miniconda3/include -I/gpfs/nhmfsa/bulk/share/data/mbl/share/software/testing/angsd.head/htslib -O3 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/software/testing/miniconda/miniconda3/lib -Wl,-rpath-link,/software/testing/miniconda/miniconda3/lib -L/software/testing/miniconda/miniconda3/lib -o angsd *.o /gpfs/nhmfsa/bulk/share/data/mbl/share/software/testing/angsd.head/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread -lcurl -lcrypto
/gpfs/nhmfsa/bulk/share/data/mbl/share/software/testing/miniconda/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /gpfs/nhmfsa/bulk/share/data/mbl/share/software/testing/angsd.head/htslib/libhts.a(knetfile.o): in function `socket_wait':
/software/testing/angsd.head/htslib/knetfile.c:71: undefined reference to `__fdelt_chk'
collect2: error: ld returned 1 exit status
make: *** [Makefile:69: angsd] Error 1`

**Comment by ANGSD** [comment]
Hi William, there has been many users that have had issues with the conda version. I suggest you clone the github version and see if that helps.

I did not make the conda release, but it is on our todo list to do this as part of our general releases.

Best

**Comment by ANGSD** [comment]
I am closing this issue, feel free to reopen if the issue persists with the most recent github version.

Best
