### ISSUE TITLE
File list reader needs to check for carriage returns in the file contents.

### ISSUE THREAD

**Issue by daviesrob** [ANGSD/angsd#509]
An issue has been raised in samtools/htslib#1481 about angsd failing to read a BAM file.  It looks like this may be due to a carriage return character on the end of the file name passed to `sam_open()`.  I see that a test for carriage returns was added to the file list reader in #93, although the code seems to have later been moved [here](https://github.com/ANGSD/angsd/blob/d0254fe376/misc/safcat.cpp#L30).  However, that's checking the name of the file list, not the contents.  A similar check needs to be done [after the getline](https://github.com/ANGSD/angsd/blob/d0254fe376/misc/safcat.cpp#L45) as well - or possibly add something to strip out a trailing `\r` if it's present.

Also, it would be good if you could replace the [`assert(in);`](https://github.com/ANGSD/angsd/blob/d0254fe376/multiReader.cpp#L189) after `sam_open()` with something along the lines of `if (in == NULL) { exit(0); }`, please?  `sam_open()` will return NULL if it fails to find the file, and it would be more friendly to not dump core if that happens.

**Comment by ANGSD** [comment]
Thanks for your input, I have just pushed a commit 2f3dd3c1 that properly checks for carriage returns in the filecontents and have updated the check of the return value of sam_open so it conforms with your advice. Thanks for your input it is much appreciated.
