### ISSUE TITLE
realSFS command not found 

### ISSUE THREAD

**Issue by shailij246** [ANGSD/angsd#510]
Hi, I am using the angsd/977fd2fe7c on a cluster. I have been able to run everything so far but not realSFS. it says realSFS command not found. Can you please suggest if this simply needs an upgrade or is something else an issue?
here are the commands I use: 

module load legacy/scg4
module load angsd/977fd2fe7c
realSFS species_het_angsd.saf.id > species.est.ml

it also said realSFS now replaced with -doSaf, is this true? 
If so what commands should I use?

**Comment by TeresaPegan** [comment]
realSFS is inside a file in ANGSD called misc. I am not sure how it works with your cluster, but when I run the program I have to say 

```
angsd/misc/realSFS
```

Hope that's helpful! -Teresa

**Comment by isinaltinkaya** [comment]
Dear @shailij246,

As @TeresaPegan explained, you need to specify the path to realSFS explicitly. 

This is probably easier to do when you have a local installation of angsd instead of using the module, but it is still possible.

Below is a simple illustration of the usage on a cluster system:

```sh
#load the module
$ module load angsd
Module angsd/934 loaded

#find the module path
$ which angsd
/share/apps/angsd-0.934/bin/angsd

#add misc/realSFS
$ /share/apps/angsd-0.934/bin/misc/realSFS 

	-> ---./realSFS------
	-> EXAMPLES FOR ESTIMATING THE (MULTI) SFS:

	-> Estimate the SFS for entire genome??
	-> ./realSFS afile.saf.idx 

	-> 1) Estimate the SFS for entire chromosome 22 ??
	-> ./realSFS afile.saf.idx -r chr22 

	-> 2) Estimate the 2d-SFS for entire chromosome 22 ??
	-> ./realSFS afile1.saf.idx  afile2.saf.idx -r chr22 

	-> 3) Estimate the SFS for the first 500megabases (this will span multiple chromosomes) ??
	-> ./realSFS afile.saf.idx -nSites 500000000 

	-> 4) Estimate the SFS around a gene ??
	-> ./realSFS afile.saf.idx -r chr2:135000000-140000000 

	-> Other options [-P nthreads -tole tolerence_for_breaking_EM -maxIter max_nr_iterations -bootstrap number_of_replications -resample_chr 0/1]

	-> See realSFS print for possible print options
	-> Use realSFS print_header for printing the header
	-> Use realSFS cat for concatenating saf files

	->------------------
	-> NB: Output is now counts of sites instead of log probs!!
	-> NB: You can print data with ./realSFS print afile.saf.idx !!
	-> NB: Higher order SFS's can be estimated by simply supplying multiple .saf.idx files!!
	-> NB: Program uses accelerated EM, to use standard EM supply -m 0 
	-> Other subfunctions saf2theta, cat, check, dadi

```

Please feel free to reopen the issue if this does not resolve it.

Best wishes
