### ISSUE TITLE
bgzf_flush 

### ISSUE THREAD

**Issue by pierrespc** [ANGSD/angsd#516]
Hi,

I'm trying do use the doCounts flag.  It works perfectly in some control cases.
Now that I am trying to scale-up, and that the expected files are quite big (millions of variants for dozens of samples), I encounter some issues: the process finishes without any exit error. However the .pos.gz file is not correctly written and in the log I see errors such as
`[E::bgzf_flush] File write failed (wrong size)`
`[E::bgzf_close] File write failed`

It seems that it is because the folder where temporary files are written is getting full.
I already had such issues with other program (the default temporary folder in the cluster I am using is very limited in size) so I already defined in my ~/.bashrc file the following
`TMPDIR=$MYSCRATCH `(where $MYSCRATCH  points to a folder with unlimited size).
However it seems it is not recognized by angsd.
How does angsd deal with temporary files? Where are they written and how can I change this?

Thanks.

Pierre

**Comment by ANGSD** [comment]
Dear @pierrespc the program does not generate temporary files, everything is kept in memory and in final outputfiles, so you should specifiy a folder that has enough capacity for the full output.

Best
