### ISSUE TITLE
Tajimas D calculation for site windows

### ISSUE THREAD

**Issue by aguilar-gomez** [ANGSD/angsd#519]
Hi,

I am trying to replicate the calculation of Tajimas'D of thetaStat sliding windows using tP and tW. According to the regular formula and the paper is:
 TajimasD=(thetaP-thetaW)/sqrt((var(thetaP-thetaW))))

However when I try it like that I do not get the same number. I saw your C code, and you have this formula
res =  (sumk - (thetaW))/sqrt((e1*segsites) + ((e2*segsites)*(segsites-1))) 

Can you explain this formula?  Is it a special correction or why are you not using the regular formula? It is a different denominator, and I do not understand it. 

I am trying to replicate the calculation because I want to do windows of sites instead or base pairs. 

thank you,
Diana

**Comment by nspope** [comment]
Hmm, what's there matches [Tajima's paper introducing D](https://academic.oup.com/genetics/article/123/3/585/5998755) -- see equation 38. So, not sure I understand the question -- are you worried that the empirical variance of the numerator (like, calculated across a bunch of windows) doesn't match the theoretical variance under neutrality that is given by the equation in Taijma's paper (and used in the calculation here)? I think using the empirical variance would probably make it much less useful as a statistic for measuring local deviations from neutrality.

**Comment by aguilar-gomez** [comment]
I meant in the paper suggested by the angsd Wiki : [Korneliussen2013](http://www.popgen.dk/angsd/index.php/Korneliussen2013)

But it is OK, thank you for your answer. That paper you sent clarifies it.
