### ISSUE TITLE
-doAsso: crash after changing -minHigh -minCount

### ISSUE THREAD

**Issue by marqueda** [ANGSD/angsd#53]
Dear ANGSD developers,

Angsd (newest version) is crashing when I change the -minHigh and -minCount parameters in the following command:
`angsd -yBin FPbin -doAsso 2 -model 1 -cov POP4.PC1v2.eigvect -GL 2 -doPost 1 -out tmp.out -doMajorMinor 1 -SNP_pval 1e-6 -doMaf 2 -bam ../bamlists/POP4.GLA.bfl -r chrIV:1-100000 -minHigh 4 -minCount 2`

The stdout/err looks like this: 
        -> angsd version: 0.913-61-gc5d14e1 (htslib: 1.3.2-78-g0ca17a0) build(Nov  3 2016 12:02:45)
        -> SNP-filter using a pvalue: 1.000000e-06 correspond to 23.928127 likelihood units
        -> Parsing 29 number of samples
        -> Region lookup 1/1
        -> Printing at chr: chrIV pos:34160 chunknumber 100 contains 258 sitesy: 0.000000         post 0.000000 1.000000 0.000000   Ex 1.000000 1.000000     U -0.026912
y: 0.000000       post 0.989759 0.010241 0.000000       Ex 0.010241 0.010241    U -0.026912
y: 0.000000       post 0.989763 0.010237 0.000000       Ex 0.010237 0.010237    U -0.026912
y: 0.000000       post 0.989749 0.010251 0.000000       Ex 0.010251 0.010251    U -0.026912
y: 1.000000       post 0.999669 0.000331 0.000000       Ex 0.000331 0.000331    U -0.026912
y: 1.000000       post 0.989739 0.010261 0.000000       Ex 0.010261 0.010261    U -0.026912
y: 0.000000       post 0.994850 0.005150 0.000000       Ex 0.005150 0.005150    U -0.026912
y: 0.000000       post 0.959972 0.040028 0.000000       Ex 0.040028 0.040028    U -0.026912
y: 0.000000       post 0.999349 0.000651 0.000000       Ex 0.000651 0.000651    U -0.026912
y: 0.000000       post 0.999918 0.000082 0.000000       Ex 0.000082 0.000082    U -0.026912
y: 0.000000       post 0.997374 0.002626 0.000000       Ex 0.002626 0.002626    U -0.026912
y: 0.000000       post 0.033417 0.966583 0.000000       Ex 0.966583 0.966583    U -0.026912
y: 0.000000       post 0.960273 0.039727 0.000000       Ex 0.039727 0.039727    U -0.026912
y: 0.000000       post 0.979596 0.020404 0.000000       Ex 0.020404 0.020404    U -0.026912
y: 0.000000       post 0.923806 0.076194 0.000000       Ex 0.076194 0.076195    U -0.026912
y: 1.000000       post 0.997410 0.002590 0.000000       Ex 0.002590 0.002590    U -0.026912
y: 0.000000       post 0.979713 0.020287 0.000000       Ex 0.020287 0.020287    U -0.026912
y: 0.000000       post 0.960345 0.039655 0.000000       Ex 0.039655 0.039655    U -0.026912
y: 0.000000       post 0.000000 0.160259 0.839741       Ex 1.839741 3.519224    U -0.026912
y: 0.000000       post 0.000000 0.087451 0.912549       Ex 1.912549 3.737647    U -0.026912
y: 0.000000       post 0.960345 0.039655 0.000000       Ex 0.039655 0.039655    U -0.026912
y: 0.000000       post 0.858455 0.141521 0.000025       Ex 0.141570 0.141619    U -0.026912
y: 0.000000       post 0.979751 0.020249 0.000000       Ex 0.020249 0.020249    U -0.026912
y: 0.000000       post 0.000000 0.999988 0.000012       Ex 1.000012 1.000035    U -0.026912
y: 0.000000       post 0.999669 0.000331 0.000000       Ex 0.000331 0.000331    U -0.026912
y: 0.000000       post 0.994844 0.005156 0.000000       Ex 0.005156 0.005156    U -0.026912
y: 1.000000       post 0.979751 0.020249 0.000000       Ex 0.020249 0.020249    U -0.026912
y: 0.000000       post 0.039029 0.960971 0.000000       Ex 0.960971 0.960971    U -0.026912
y: 0.000000       post 0.994836 0.005164 0.000000       Ex 0.005164 0.005164    U -0.026912

It works, if I use a smaller region, e.g. chrIV:1-10000, but not with chrIV:1-100000, and if I use default -minHigh and -minCount values (10 and 10).

Also, I wonder what the cut-off is for a "high credible genotype" for -minHigh.

Thank you for your help with this potential bug.
David

**Comment by aalbrechtsen** [comment]
Hi David


The cut off is 0.9 so is it not very high. 

The test will not work unless there is a certain amount of variability in the posterior probability of the genotypes. This is why the -minHigh and -minCount filters are there. When you reduce then the test will become unreliable and the problem will fail. 

I have updated ANGSD so it does not stop when performing unreliable testing however, I would strong advice against choosing such low filters. 


-Anders

**Comment by marqueda** [comment]
Hi Anders,

Thank you again for the quick answer and your suggestion - I will not use such low filters, but I was not sure what the cut-off was and thus tried different values. What is the unit of the cut-off = 0.9? 90% accuracy, e.g. phred-scaled GQ = 10?

Thanks again & best wishes,
David

**Comment by aalbrechtsen** [comment]
it is a posterior probability of 0.9 which does correspond to a phred-scaled  score of 10

**Comment by marqueda** [comment]
Great, thank you, Anders!
