### ISSUE TITLE
make -rf in realSFS

### ISSUE THREAD

**Issue by ANGSD** [ANGSD/angsd#54]

**Comment by ANGSD** [comment]
This is not clearly defined. Should the analysis be done over each entry in the -rf file, or should a single  estimate be obtained across the region spanned by the -rf

**Comment by z0on** [comment]
Looks like your $POP1.$POP2.unfolded-lr.fst.idx is not recognized as actual file name; try the same command without using $ variables? (Ie use actual file names)

Misha

iPhone. Autocorrections galore.

**Comment by mlucenaperez** [comment]
Thank you Misha, but I think that is not the issue. The command is working smoothly if I do not add -rf.  Actually the "Assuming .fst.gz file: BLA" is right. The rf file that I am using has been previously used with other ANGSD command and works fine.

**Comment by z0on** [comment]
ah yes. It is just that your error message indicates that angsd thinks that “-rf” is not a switch but a file to be opened, suggests some mess-up in the command line to me…
