### ISSUE TITLE
HWE test

### ISSUE THREAD

**Issue by claudiuskerth** [ANGSD/angsd#55]
Hi ANGSD team,

I have trouble making sense of the output from `-HWE_pval`. I am trying to filter out loci with negative F as a way to remove likely paralogs. I have run the following command on BAM files belonging to 36 individuals from two different populations:

>ls split_rf/* | parallel -j 12 "angsd -doSnpStat 1 -HWE_pval 1 -b slim.bamfile.list -sites keep.sites -rf {} -out Results/{/} -doMaf 1 -doMajorMinor 1 -GL 1 -P 2 -only_proper_pairs 0 -minMapQ 5"

The *hwe.gz output of this command looks like this:

>Chromo  Position        Major   Minor   hweFreq Freq    F       LRT     p-value
 Contig_270      20      T       A       0.000009        0.000150        0.666617        -6.624056e-03   1.000000e+00

My questions are:

1. Why are the estimated allele frequencies so low? They are all below 10^-4, while 1/36=0.0278.

2. The F value is always 0.666617. Is something not working here?

3. Why is LRT negative? It's always negative. Shouldn't this statistic be Chi-square distributed and therefore LRT>=0?

4. Why is the p-value always 1? Is something not working here?

thank you so much for your help  

claudius

**Comment by claudiuskerth** [comment]
Continuing from the above, I have also tried `-HWE_pval_F` on the same data with:

>ls split_rf/* | parallel -j 12 "angsd -HWE_pval_F 1 -b slim.bamfile.list -sites keep.sites -rf {} -out Results/{/} -doMaf 1 -doMajorMinor 1 -GL 1 -P 2 -only_proper_pairs 0 -minMapQ 5"

and I get the following output in *hweF.gz files:

>Chromo  Position        Major   Minor   Freq    hweFreq F       LRT     p-value
Contig_17       35      G       A       0.000000        0.000000        0.000000        1.925535e-05    9.964988e-01
Contig_17       36      C       T       0.036406        0.065774        0.999991        5.247851e+00    2.197389e-02
Contig_17       37      G       A       0.112477        0.109179        0.575731        3.006406e+00    8.293601e-02
Contig_17       38      G       A       0.000000        0.000000        0.000000        1.925535e-05    9.964988e-01
Contig_17       39      A       T       0.026889        0.026884        0.000000        -5.766070e-08   1.000000e+00

Here estimated minor allele frequencies are much higher than with `-HWE_pval`.

My questions are:

1.  The lowest reported F value is 0. Why is that? I would have expected some negative F values due to mapping paralogous sequences to the same ref position.

2. The p-values indeed seem to be from a Chi-square distribution with 1 df with the LRT as lower limit. However, there are still some negative LRT values. Are they just floating point errors?

I have produced these results with ANGSD version 0.915-5-ge6e63e5 and I get virtually identical results with version 0.913.

many thanks for your support

claudius

**Comment by ANGSD** [comment]
Dear Claudius, it would seem that the program and the wiki had drifted
somewhat apart.
Sorry for the long responstime

I've updated the snpstat page wiki. It could be more verbose, but at least
it is not directly wrong anymore.

Please try to rerun without the hwe_pval. The *_pval arguments are now used
for filtering purposes, and not for toggling analysis on/off anymore. With
the hwe_pval 1, you were only printing out the sites that had a pvalue of
one. Hopefully Ive updated all the pages on the wiki that had this
extremely misleading information.

**Comment by claudiuskerth** [comment]
Thank you so much for this clarification!

I have just run:

>ls split_rf/* | parallel -j 12 "angsd -b slim.bamfile.list -doSnpStat 1 -doMaf 1 -domajorminor 1 -skipTriallelic 1 -gl 1 -snp_pval 1e-2 -sites keep.sites -only_proper_pairs 0 -minMapQ 5 -minQ 20 -out SnpStat/{/} -rf {}"

... and the output makes much more sense now, i. e. in the *hwe.gz file I find:

1. reasonably high estimates of allele frequencies (with `-snp_pval 1e-2` I don't expect MAF's close to 0)

2. positive and negative F values

3. only positive LRT values

4. a range of p-values

I could not find a wiki page with "snpstat" in its name, but I assume you mean the [SnpFilters](http://popgen.dk/angsd/index.php/SnpFilters) site, right?

I had used `hwe_pval 1` and `hwe_pval_F 1` because of the following sentence on the page [HWE and Inbreeding estimates](http://popgen.dk/angsd/index.php/HWE_and_Inbreeding_estimates):

> By choosing HWE_pval_F 1, no sites will be filtered but the p-value along wight the frequency, and F for the sites will be dumped in .hweF.gz file. 

claudius

**Comment by ANGSD** [comment]
Yes the SnpFilters page on the wiki. The hwe_pval_f is somewhat
different from the std hwe_pval. Let hear what @aalbrechtsen has to
say about this.

Dont hesitate to contact us if you have other questions.

**Comment by ANGSD** [comment]
Ill close this issue, feel free to reopen if needed.
