### ISSUE TITLE
Error message 'Segmentation fault' 

### ISSUE THREAD

**Issue by ThibauldMichel** [ANGSD/angsd#557]
Hello, I try to read a GVCF file with angsd, and get this error message.
I do not think it is related to the indel tag missing, as I got this issue with other errors I had before.
The error message is not clear with the type of issue, so I am not sure how to debug it.
The GVCF file is attached.

```
angsd -vcf-pl GVCF_SNPs_edit.vcf.gz  -domajorminor 1 -domaf 1 -out GVCF_SNPs                                                                                 
        -> angsd version: 0.933 (htslib: 1.9) build(May  6 2020 21:25:11)
        -> VCF still beta. Remember that
           1. indels are are discarded
           2. will use chrom, pos PL columns
           3. GL tags are interpreted as log10 and are scaled to ln (NOT USED)
           4. GP tags are interpreted directly as unscaled post probs (spec says phredscaled...) (NOT USED)
           5. FILTER column is currently NOT used (not sure what concensus is)
           6. -sites does NOT work with vcf input but -r does
           7. vcffilereading is still BETA, please report strange behaviour
        -> No indel tag in vcf/bcf file, will therefore not be able to filter out indels
Segmentation fault (core dumped)
```

[GVCF_SNPs_edit.vcf.gz](https://github.com/ANGSD/angsd/files/10757480/GVCF_SNPs_edit.vcf.gz)

**Comment by isinaltinkaya** [comment]
Hi,

I believe this is due to the use of the deletion notation `*` which is currently not handled in angsd yet.

e.g.
```
ACmerged_contig_4046    45      .       T       C,*,A
```

For a very quick and dirty solution until it is fixed within angsd, I would recommend excluding these sites and try running angsd again.

Best,
Isin

**Comment by ThibauldMichel** [comment]
Thank you Isin, I will give a try as soon as my cluster is available and give feedback.
