### ISSUE TITLE
visualizing the 2D-SFS

### ISSUE THREAD

**Issue by yangwukaidi** [ANGSD/angsd#567]
hi.
How do I visualize the 2D-SFS produced by this software?
According to MFumagalli's tutorial (https://github.com/mfumagalli) . I try to get 2 D-SFS using the following script, 
Rscript $NGSTOOLS/Scripts/plot2DSFS.R Results/LWK.PEL.sfs LWK-PEL 10-10
But I failed, and I got a strange picture. 
As follows
![1680575567157](https://user-images.githubusercontent.com/127917612/229671814-fba48e22-15e6-4d27-a343-a91db5e8f235.png)
How can these problems be solved?
I get 2D-SFS file with only one row in it. Is that correct?
Look forward to your reply!
Thanks!

**Comment by ANGSD** [comment]
Plotting the 2dsfs can be abit tricky and will likely require some tweaking since it is visualized as a heatmap. It should indeed be one row, this is a flattened matrix. If you want to validate correctness of dimension you can convert to a matrix and look at the 1d marginals.
