### ISSUE TITLE
angsd in bioconda

### ISSUE THREAD

**Issue by percyfal** [ANGSD/angsd#57]
Dear angsd developers,

is there a license agreement applicable to angsd that would make it possible to package angsd in the conda package manager?

Conda is being widely used throughout the scientific community, and adding your excellent software to this system would be of great advantage to everyone. It would also greatly improve the visibility and ease of use of your software.

Thank you for your time
Per Unneberg and all of the bioconda community

PS: check us out at https://bioconda.github.io

**Comment by ANGSD** [comment]
Does bioconda require special license? I think most stuff in ANGSD is gnu. But there is also some files with mit license. Let me know if I need to do something.

**Comment by percyfal** [comment]
No special license is needed for bioconda. If it's ok with you then, I'll package angsd with GPLv3 (it is version 3?) and MIT license. Thanks!

**Comment by ANGSD** [comment]
Ok that is super. Thanks for doing it. Let me know if there are issues.

**Comment by percyfal** [comment]
Ok, thanks, the build is up and will hopefully pass before tomorrow. As the current bioconda version of htslib is 1.3.2, I'm currently building 0.910 in wait for a new htslib release that fixes issue #52
