### ISSUE TITLE
without any output

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#58]
Hi @ANGSD 

I want to get the SNPs positions with following command, but after doing filter (`SNP_pvalue, maf, depth, hwe`. et.al), I found no sites were identified as SNPs.  I think I have made some mistakes.  
`angsd -bam bam.list -only_proper_pairs 1 -uniqueOnly 1 -remove_bads 1 -minQ 20 -minMapQ 30 -C 50 -ref reference.fa -nThreads 30 -r 9 -out 9 -doMaf 1 -doMajorMinor 1 -GL 1 -SNP_pval 1 -doCounts 1 -HWE_pval 1 -P 5 -dosnpstat 1`

The version is `angsd version: 0.914`  I need your help.

Thanks.

**Comment by ANGSD** [comment]
Hi this is related to issue #55. You shouldn't set -hwe_pval to 1 in newer versions of angsd. If you want to calculate (without filtering) all the pvals for the different bias estimators you should do -doSnpStat 1, if you then want to filter you should set *_pval. See this page:
http://www.popgen.dk/angsd/index.php/SnpFilters

**Comment by biozzq** [comment]
Many thanks!
