### ISSUE TITLE
-nan in Watterson / Pairwise position calculation.

### ISSUE THREAD

**Issue by jmhallas** [ANGSD/angsd#606]
Hello,

I have an odd error.  I am getting -nan in Watterson / Pairwise calculations for 2 sites. All other populations estimates for theta don't result in any -nan. Also I am getting the same value for watterson estimate for each position.   Can't figure out why this is.  I am filtering sites during -doSaf 1 and doing a folded sfs. Maybe there is something I'm doing during the filtering process that is incorrect, but i am using the same filtering parameters that I used to generate likelihoods.

Out file:
```
HiCscaffold18pilon	61074150	-1.640369	-0.870489	-inf	-inf	-inf
HiCscaffold18pilon	61074155	-nan	-nan	-inf	-inf	-inf
HiCscaffold18pilon	61074158	-1.640369	-0.720385	-inf	-inf	-inf
```

this is the code I am running 
```
angsd -nThreads ${SLURM_CPUS_PER_TASK} -bam ${BAMLISTDIR}/${POP}.list -ref ${REF} -anc ${REF} -out ${OUTDIR}/${POP} \
      -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -C 50 -baq 1 \
      -minMapQ 20 -minQ 20 -minInd ${MININD} -setMaxDepth 400 -doCounts 1 \
      -doMajorMinor 1 -doMaf 1 -minMaf 0.05 -SNP_pval 1e-6 \
      -GL 2 -doSaf 1

realSFS ${OUTDIR}/${POP}.saf.idx -P ${SLURM_CPUS_PER_TASK} -fold 1 > ${OUTDIR}/${POP}.sfs

realSFS saf2theta ${OUTDIR}/${POP}.saf.idx -outname ${POP} -sfs ${OUTDIR}/${POP}.sfs -fold 1

thetaStat do_stat ${OUTDIR}/${POP}.thetas.idx -win 10000 -step 5000  -outnames ${OUTDIR}/${POP}.thetaWindow.gz

thetaStat print ${OUTDIR}/${POP}.thetas.idx > ${OUTDIR}/${POP}.theta_out
```

Has anyone encountered this before? 

Open to all suggestions.

-josh

**Comment by mxt2022202059** [comment]
Hi
 what about the two results "Watterson, pairwise", shouldn't theta values scale around 10^(-3), is there some kind of conversion needed for this?
XunTao Ma

**Comment by jmhallas** [comment]
Column 3 is Watterson and column 4 is Pairwise.  I have still haven't been able to figure out the issue.  I think I'm at the point of just removing the site from calculations, but I would rather figure out the problem.  Does anyone have any thoughts?
