### ISSUE TITLE
FST output

### ISSUE THREAD

**Issue by claudiuskerth** [ANGSD/angsd#61]
Hi ANGSD team,

when running

>realSFS fst print here.fst.idx 2>/dev/null

what is reported in column 3 and column 4 when the `*idx` file was created with `-whichFst 0` or `-whichFst 1`?

many thanks

claudius

**Comment by ANGSD** [comment]
The fst works by calculating per site alphas and betas. The unweighted is the sum of ratios, where as the weighted is the ratio of sums. The whichFst 0 is the reynolds and whichFst 1 is the bhatia.
You can view the R code here:
https://github.com/ANGSD/angsd/blob/master/R/fstFrom2dRHELLER.R

**Comment by claudiuskerth** [comment]
Thanks, the R code is quite clear. So `-whichFst 1` calculates equation 10 from Bhatia2013. I also understand the two global Fst's that `realSFS fst stats *idx` prints out, where the second (weighted, i. e. ratio of averages) should clearly be preferred according to Bhatia2013.

However, I still don't know what is actually reported in columns 3 and 4 of the output from:

> realSFS fst print *fst.idx 2>/dev/null

which reports Fst's for each site. Matteo's [ngsTools tutorial](https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md#population-genetic-differentiation-fst) suggests that when calculating Reynold's Fst, column 3 is *a* and column 4 is *a+b*. When calculating Hudson/Bhatia's Fst with `-whichFst 1`, what is reported in columns 3 and 4? 

many thanks

claudius

**Comment by ANGSD** [comment]
Hi Claudius, the realSFS fst print prints out the alpha and the betas. Not
the fst, so you you should take the ratio between these or the ratio
between of the sums of these if you want to calculate fst for a region. For
the bhatia estimator is of course different alphas and betas but similar
approach.

**Comment by claudiuskerth** [comment]
> so you you should take the ratio between these or the ratio
between of the sums of these if you want to calculate fst for a region

that's exactly what I want to do. So, if I understand you correctly then the output of `realSFS fst print` reports the numerator in the 3rd column and the denominator in the 4th column of either Reynold's or Hudson/Bhatia's formula of Fst.

many thanks for that clarification!

claudius

**Comment by ANGSD** [comment]
Super glad it makes sense  now. Sorry about the lack of proper documentation. Ill close this issue now, feel free to reopen if needed.
