### ISSUE TITLE
-nChr flag for thetaStat

### ISSUE THREAD

**Issue by claudiuskerth** [ANGSD/angsd#62]
Hi ANGSD team,

when running

>thetaStat do_stat out.thetas.gz -nChr 20

what does the number 20 stand for?

many thanks

claudius

**Comment by ANGSD** [comment]
This is number of free categories in your spectrum. This is the same as the chromosome count for all individuals. For diploids it is twice the number of samples. For haploids it is the number of samples.

**Comment by claudiuskerth** [comment]
Aha, related to that: if I had 10 diploid samples, but had to estimate a folded SFS (i. e. 10+1 categories), would I have to specify `-nChr 10`?

many thanks for your support!

claudius

**Comment by ANGSD** [comment]
Yes exactly. But im thinking that this approach might be to cumbersome for
most cases. So i think I will redo this program so users arent confused.
You arent the first one asking.

**Comment by claudiuskerth** [comment]
Great. Thank you for that clarification!

IMHO, it's not confusing, it's just not documented yet. I got confused because in Matteo's [ngsTools tutorial](https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md#nucleotide-diversity) he uses `-nChr 1`, so I first thought this flag was referring to a chromosome/contig number in the reference.

claudius

**Comment by ANGSD** [comment]
Super I'll close this issue. Feel free to reopen if needed.
