### ISSUE TITLE
-argument is unknown will exit

### ISSUE THREAD

**Issue by MboiTui** [ANGSD/angsd#624]
Hello,

I am trying to produce an ancestral.fasta file to be used to build single population SFS.

I am encountering the error `-argument is unknown will exit` for two different arguments, depending on what version of angsd I am using. 

When i use **angsd 0.940-dirty**, built in May 18 2023, with the below command:

`angsd -b outgroup.list -out test -doCounts 1 -snp_pval 0.01 -doMaf 1 -doMajorMinor 1 -rmSNPs 1 -minInd 3 -explode 1 -gl 2`

I get the error: `-rmSNPs is unknown will exit`

Thus i installed the ngsTools version of angsd (angsd version: 0.941-19-g2d1c533 (htslib: 1.18-4-g5098983e) build(May 27 2024 01:06:13).

Switching to this version and running the exact same command, I get the error:

`-explode is unknown will exit`

NOTE: i ran both of these interactively and retyped the command manually a number of time to ensure the error was not the result of hidden characters and/or formatting in the command.

Could you please suggest what I might be doing wrong?

Cheers,
LVB

**Comment by MboiTui** [comment]
I was following the commands on the ANGSD website to produce the ancestral state fasta. Those did not include `-doFasta`. I have now added the `-doFasta` argument and the script is running well, thus I guess the issue was on my end.

**Comment by portiawyh** [comment]
Hello, I am unfortunately having the same issue even after adding -doFasta, specifically, I keep getting the error `-rmSNPs is unknown will exit`.

For your reference, my version of angsd is 0.941-dirty (htslib: 1.14-9-ge769401d) build(Nov 27 2024 11:03:06). I've tried using an older version (0.933 htslib:1.12) but I get the same error. 

The full code I'm trying to run is `angsd -GL 1 -b $filelist -ref $refgenome -doFasta 1 -doCounts 1 -baq 1 -C 50 -P 8 -doMajorMinor 1 -doMaf 1 -rmSNPs 1 -minInd 10 -minQ 20 -minMapQ 30 -uniqueOnly 1 -skipTriallelic 1 -SNP_pval 1e-6 -out $out -setMinDepthInd 10 -explode 1` 

Can you please help me figure out what's wrong? Perhaps something to do with the angsd build I'm using?

Many thanks,
Portia
