### ISSUE TITLE
setting max depth by individual

### ISSUE THREAD

**Issue by lindaboettger** [ANGSD/angsd#63]
Hi ANGSD,

I'm planning to use -doAbbababa with multiple filtering options, and I'd like to filter out very high coverage sites by individual. The coverage of each sample varies widely so I have reservations about filtering on total depth with -setMaxDepth or -setMaxDepthInd, which seems to filter by the same value for every individual.

I'm thinking of filtering the bams prior to using angsd, but I'm curious if there is a better way that I've overlooked.

Many thanks,
Linda

**Comment by ANGSD** [comment]
Hi Linda, if you use the sampling approach you shouldnt need to filter. Ive
put @aalbrechtsen
<https://github.com/ANGSD/angsd/commits/master?author=aalbrechtsen> on this
issue, he might have some clever remarks with regards to the -doabbababa
analysis.

**Comment by aalbrechtsen** [comment]
Hi Linda

ANGSD does not have an option for individual depth filters so you can only use the same filter for each individual or filter based on the total number of reads across samples. My suggestion for you is to make a file with the regions you want to include in the analysis. 

-Anders

**Comment by lindaboettger** [comment]
Hi ANGSD,

Thank you both for the suggestions. 

Most of the papers I've seen that do an abba baba analysis (including Green et al. 2010) filter on coverage to remove variants in paralogous sequences that are collapsed in the reference, so it's probably safer to do this filtering. 

Best,
Linda

**Comment by ANGSD** [comment]
Hi Linda can you state explicitly which kind of filtering you have in mind? Do you propose that there is a possibility to set persample min&max depth for the seq data?

**Comment by lindaboettger** [comment]
Yes, I'm hoping to set a per sample min and max depth for sequence data. I imagine this type of filtering is unnecessary for most analyses, but the read depth for samples I hope to use in the abba baba analysis varies by as much as an order of magnitude.

**Comment by lindaboettger** [comment]
Is it now possible to set different min/max depths for different individuals or is this still best done by only including certain regions in the analysis?
