### ISSUE TITLE
Fst with folded SAF's?

### ISSUE THREAD

**Issue by claudiuskerth** [ANGSD/angsd#65]
Hi Thorfinn,

can `realSFS fst index` take folded SAF files and a folded 2D-SFS as prior and produce correct output?

For more details, please see the discussion on the ngsTools Google forum [to fold or not to fold](https://groups.google.com/d/topic/ngstools-user/9Z4viLJ7NJA/discussion).

many thanks for your support!

claudius

**Comment by ANGSD** [comment]
No, currently the multipop safbased analysis is only properly defined for
the unfolded. It should be relative simple to implement be havent had time.

Im putting @mfumagalli in on this.

Best

**Comment by claudiuskerth** [comment]
Thanks Thorfinn

**Comment by sagw** [comment]
Hi, 
Is this still true? I am able to run realSFS fst index on folded SAFs and SFS, but I am wondering if the numbers it gives me are meaningful, or if I need to use an unfolded SFS to calculate FST even if I don't know the ancestral allele? 
Thanks for your help,
Sarah

**Comment by claudiuskerth** [comment]
Hi Sarah,

I don't think Thorfinn has fixed that yet, but uncertainty in assigning the ancestral and derived state of alleles is not an issue for estimating Fst with ANGSD and realSFS. The only requirement is that the unfolded SAF's for each population refer to the same allele at a locus. That could simply be achieved by supplying the reference sequence to the `-anc` switch when estimating the SAF's for your populations. 

From Matteo Fumagalli's [ngsTools](https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md) tutorial:

>in case an ancestral sequence is not available, analyses on FST, PCA, nucleotide diversity (but not the number of fixed differences) can be carried out using the reference sequence to polarise your data. [...] We also discourage to use the folded site frequency spectrum option to estimate FST/PBS.

Fst from an unfolded 2D SFS and its folded version (i. e. joint minor allele frequency spectrum, not what ANGSD currently does when folding) should be the same.

Please read this [thread](https://groups.google.com/d/topic/ngstools-user/9Z4viLJ7NJA/discussion) on the ngsTools Google forum for reference. 

claudius

**Comment by sagw** [comment]
Hi Claudius,
Thanks for your response, that makes sense. 
Should I also use the unfolded sfs for estimating thetas? or will the folded sfs work for that?
Thanks for your help,
Sarah

**Comment by mfumagalli** [comment]
Dear Sarah,

for estimating thetas it shouldn't matter using the folded spectrum or the
reference as -anc.

Thanks Claudius for addressing her question on FST.

Best

Matteo

**Comment by sagw** [comment]
Ok great thank you. And thanks for making (Matteo) and pointing me towards (Claudius) this tutorial, it is very helpful!
Sarah

**Comment by madzayasodara** [comment]
K, just to check if I got this right:
To calculate Fst using a ref genome (not ancestral) do:
#first calculate per pop saf for each population using a unfolded sfs (cause it doesn't matter if it's folded or not) and the ref genome as your -anc 
> ../angsd -b list1  -anc ref.fa -out pop1 -dosaf 1 -gl 1
> ../angsd -b list2  -anc ref.fa -out pop2 -dosaf 1 -gl 1 

and the rest follows just like it is:

> #calculate the 2dsfs prior
> ../misc/realSFS pop1.saf.idx pop2.saf.idx >pop1.pop2.ml
> #prepare the fst for easy window analysis etc
> ../misc/realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1.pop2.ml -fstout here
> #get the global estimate
> ../misc/realSFS fst stats here.fst.idx 
> -> FST.Unweight:0.069395 Fst.Weight:0.042349
> #below is not tested that much, but seems to work
> ../misc/realSFS fst stats2 here.fst.idx -win 50000 -step 10000 >slidingwindow

the -fold 1 option is supported for Heterozygozity. So, to calculate this using a ref genome (not ancestral) just do as in the website:

> ./angsd -i my.bam -anc ref.fa -dosaf 1 -fold 1
> #followed by the actual estimation
> ./realSFS angsdput.saf.idx >est.ml

the -fold 1 option is also supported for thetas, tajimas'D and other neutrality tests.. So, to calculate this using a ref genome (not ancestral) just do as in the website:

> ./angsd -bam bam.filelist -doSaf 1 -anc chimpHg19.fa -GL 1 -P 24 -out out -fold 1
> ./misc/realSFS out.saf.idx -P 24 > out.sfs
> ./angsd -bam bam.filelist -out out -doThetas 1 -doSaf 1 -pest out.sfs -anc chimpHg19.fa -GL 1 -fold 1
> #Estimate for every Chromosome/scaffold
> ./misc/thetaStat do_stat out.thetas.idx
> #Do a sliding window analysis based on the output from the make_bed command.
> ./misc/thetaStat do_stat out.thetas.idx -win 50000 -step 10000  -outnames theta.thetasWindow.gz

Thanks!

**Comment by claudiuskerth** [comment]
Hi Madza,

for Fst it _does_ matter whether the SFS's are unfolded or folded. They have to be *un*folded. What does not matter for Fst is how the SFS's are polarized, i.e. toward ancestral or arbitrary reference sequence, as long the 2 SFS's are polarized the same way, of course.

Watterson's theta, Tajima's D, Fu & Li's F and D can be calculated from a folded 1D SFS. The Fay's H and Zeng's E values calculated from a *folded* SFS make no sense, since they expect an SFS that contains counts of SNPs with a certain *derived* (i.e. non-ancestral) allele frequency.

claudius

**Comment by claudiuskerth** [comment]
Hi Madza,

for Fst it _does_ matter whether the SFS's are unfolded or folded. They have to be *un*folded. What does not matter for Fst is how the SFS's are polarized, i.e. toward ancestral or arbitrary reference sequence, as long the 2 SFS's are polarized the same way, of course.

Watterson's theta, Tajima's D, Fu & Li's F and D can be calculated from a folded 1D SFS. The Fay's H and Zeng's E values calculated from a *folded* SFS make no sense, since they expect an SFS that contains counts of SNPs with a certain *derived* (i.e. non-ancestral) allele frequency.

claudius

**Comment by madzayasodara** [comment]
Nice! Thank you.
It should not matter for variant calling or PCA either, right?
-madza

**Comment by claudiuskerth** [comment]
Hi Madza,

yes, I think you are right. If you want to use an SFS (usually genome-wide) as empirical prior for posterior genotype probabilities (via posterior SAF probabilities), then it should not matter whether the SFS is folded or not as long as both the SFS and the SAF files are either both folded or both unfolded, of course. They do *not* even need to be polarised the same way *if* they are both folded (but there should be no reason to use different polarisation). Folded SAF files contain likelihoods for the count of the minor allele and a folded SFS gives you the frequency distribution of sites with certain minor allele counts. It should not matter much if you use folded or unfolded SAF files or SFS's, but it may be slightly advantages to use a folded SFS and folded SAF file, since the frequencies in the folded SFS are based on a greater number of sites than in the unfolded SFS and therefore provide a better prior.

Slightly disambiguating the comment on Fst in my previous post: if you calcluated unfolded SAF's, then a 2D-SFS from them and would then fold into a joint minor allele frequency spectrum, you could calculate a correct Fst from that folded 2D spectrum. However, when you estimate a 2D-SFS from two folded SAF files with angsd, you do *not* get a joint minor allele frequency spectrum. So, just to reiterate, estimating Fst with folded SAF's in angsd is nonsensical.

claudius

**Comment by ANGSD** [comment]
Hi I just pushed a commit that can do the folded 2dsfs as part of the realSFS routine this also facilitates the calculation of fst and pbs. Im closing this issue now. 

Best

**Comment by marce-sarrias** [comment]
Hello,

Has this issue been fixed? 

I'm trying to run the following (see below):

angsd -b pop1.filelist -anc ref.genome.fasta -ref ref.genome.fasta -GL 1 -minMapQ 30 -minQ 20 -uniqueOnly 1 -remove_bads 1 -baq 1 -dosaf 1 -fold 1 -out pop1

but I get this error: 21 argument 	-fold is unknown will exit

Thanks!

Marcela

**Comment by ANGSD** [comment]
Dear @marce-sarrias the quick answer is that you should not use the -fold option in main angsd anymore but in the realSFS part. I have just pushed a commit that will be much more useful for users.

22e28a6813

```
$ ./angsd -fold 1
	-> The folding has been moved from main angsd to realSFS subfunction.
	-> Remove -fold when doing -dosaf but apply it in realSFS
	-> Will exit
```
