### ISSUE TITLE
Generate Whole genome SFS by merging SFS from different chromosome

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#66]
Hi @ANGSD 

I want to do summary statistics using `ANGSD`. Before this, I need to estimate of the Site Frequency Spectrum (SFS) at the whole genome level, and I just generated the SFS for each chromosome (with whole genome will use large memory).  In order to get the whole genome SFS, I sum the expected number from different chromosome in each entry. But when I run `-doThetas 1` with this SFS, the results are all nan. I also try to run with only one SFS from one chromosome, it seems ok for the results. 

I hope you can give me some suggestions.

Best

**Comment by biozzq** [comment]
Hi @ANGSD 

I found the first entry (0 copies of the derived allele) causes this problem. When I change this value to a little, it seems ok.  How can I get a right SFS from different chromosome.
![image](https://cloud.githubusercontent.com/assets/15704257/21537227/3446f678-cdc9-11e6-99dc-23d390fbd78c.png)

Best

**Comment by ANGSD** [comment]
To get a proper global ml estimate of the SFS you should merge the saf
files.
./realSFS cat
http://www.popgen.dk/angsd/index.php/RealSFS#Merge_SAF_files
But if you do SFS at the chromosome level i doubt there would be a big
difference.

Im not sure what the issue was with simply summing the categories of the
different subsfs.

**Comment by biozzq** [comment]
Hi @ANGSD 

Many thanks, In order to reduce the memory consumption and running time, I do sfs by chromosome.  

l found there are more than 2.3G sites will be used to do sfs in my data, it will use a large memory. can I just use the intergenic sites to generate sfs (remove selection effect) for genetic statistics and demographic study?

Best
Zhuqing

**Comment by biozzq** [comment]
Hi @ANGSD 

I found when i do sfs after merging the saf files, the categories are some what consistent with simply summing.

Simply summing like following
`2264380204.497612 2433507.985830 1711999.288530 1456137.690873 1197022.862506 974916.717792 847323.974419 676586.260437 616741.717072 569504.078792 539564.003823 587359.326107 41509879.596208`

SFS after merge
`2264379938.40696 2434213.403336 1711308.689572 1456612.186625 1196967.300054 974605.775747 847392.479842 676512.173289 616870.355801 569533.090408 539545.549082 587430.557532 41509818.031754`

But when I run `-doThetas 1` with above two SFSs, the results are all `nan`.  I do not know why. Hope your help.

Best
Zhuqing

**Comment by biozzq** [comment]
Hi @ANGSD 

I found it is difficult for me to figure out this question which pursued me recently.  The version of `angsd` is 0.914. Any suggestion will be appreciate.

Best
Zhuqing

**Comment by ANGSD** [comment]
Is it all entries in the thetas file that are NaN?

**Comment by biozzq** [comment]
Hi @ANGSD 
Yes, all entries in the `thetas.gz` file are `NaN`. If I change the first entry in SFS file to a small one, it will give me seemingly normal results, but I do not know the effect of the SFS on the statistic results.

my command like following
`angsd -bam $bamlist -only_proper_pairs 1 -uniqueOnly 1 -remove_bads 1 -minQ 20 -minMapQ 30 -C 50 -ref $ref -P 8 -r $out -sites $site -out $out -GL 1 -doCounts 1 -doSaf 1 -anc $anc -doThetas 1 -pest $sfs`

Best
Zhuqing

**Comment by biozzq** [comment]
Hi @ANGSD 

I really need your help, I have been here for a long time. Maybe I can remove some regions from the background of the whole genome which will decrease the first entry in SFS.

Best
Zhuqing

**Comment by ANGSD** [comment]
Hi Zhuqing, im not sure how to proceed.

Can you pick a specific position that gives the NaA and then extract the
reads for that position and sent me the data as bam. Then i can reproduce
on my end.

**Comment by biozzq** [comment]
Hi @ANGSD 

Thanks, I have prepared some test files for you. 

Regarding this problem, I attached the whole genome SFS (test1.sfs) which was generated using the genome saf files. When running with this proper SFS, the results are `NaN`. 

Meanwhile, I attached a modified SFS which just changed the first value (test2.sfs), when running with the modified SFS, the results seem normally. 

The reference file is `testref.fa`, the ancestral file is `testanc.fa`. Hope these information can help you to reproduce my problem.
[Debug.tar.gz](https://github.com/ANGSD/angsd/files/691233/Debug.tar.gz)
Best
Zhuqing

**Comment by biozzq** [comment]
Hi @ANGSD 
I hope you will let me know if I do something wrong.
Many thanks.
Best
Zhuqing

**Comment by biozzq** [comment]
Hi @ANGSD 

Sorry for disturbing you once more . I have ran  `-doThetas 1` using SFS generated from random selected whole chromosomes. Hope this method can give me a proper result. 

Anyway, If you have reproduced my problem with above attached test file, I hope I can also run this statistic using the whole genome SFS.

Looking forward to your replay.
Best
Zhuqing

**Comment by ANGSD** [comment]
Sorry for the delay. There was a problem with integer overflow in the
parsing of the prior file. Please try the latest version of angsd. That
should fix the issue.

While i was fixing the bug, i refactored the -doThetas process. So it is
somewhat more simple.
Instead of having to do do

./thetaStat make_bed, angsd will now directly output the binary indexed
files.
There is more information here:

http://www.popgen.dk/angsd/index.php/Thetas,Tajima,Neutrality_tests

**Comment by biozzq** [comment]
Hi @ANGSD 

Thanks for your help. It's ok now when running with the latest version `angsd-master`.  More, you have also updated the library of GLIB. 

Best
zhuqing

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed
