### ISSUE TITLE
Problems with performing ABBA BABA on specific bases with -rf

### ISSUE THREAD

**Issue by lindaboettger** [ANGSD/angsd#68]
Dear ANGSD, 

I am trying to run an abba baba analysis on only specific bases in the genome using the `-rf` argument.

I first tried a small test file using this command with three ordered bases in the `test_abbababa.regions` file:
```
    chr25:31558578
    chr25:31570089
    chr25:31571436
```

The command I ran was:
```
angsd \
    -bam $bamlists/my_bams.bamfilelist \
    -out $outpath/output_test \
    -doAbbababa 1 \
    -remove_bads 1 \
    -rf test_abbababa.regions \
    -useLast 1 \
    -minMapQ 30 \
    -blockSize 1 \
    -minQ 30 \
    -doCounts 1
```

Instead of the 3 lines of output in the `.abbababa` file for the 3 SNPs as expected, I got 762 lines of output. 

Snippets of the resulting `output_test.abbababa` file:
```
chr1    31558329        31558329        0       0       0       0       0       0
chr10   31558329        31558329        0       0       0       0       0       0
chr11   31558329        31558329        0       0       0       0       0       0
chr12   31558329        31558329        0       0       0       0       0       0
chr13   31558329        31558329        0       0       0       0       0       0
chr14   31558329        31558329        0       0       0       0       0       0
chr15   31558329        31558329        0       0       0       0       0       0
...
chr25   31570101        31570101        0       0       0       0       0       0
chr25   31570103        31570103        0       0       0       0       0       0
chr25   31570105        31570105        0       0       0       0       0       0
chr25   31570107        31570107        0       0       0       0       0       0
chr25   31570109        31570109        0       0       0       0       0       0
chr25   31570111        31570111        0       0       0       0       0       0
chr25   31570113        31570113        0       0       0       0       0       0
...
```

As you can see, 1bp SNP regions are printed from many different chromosomes. Also, only 2 of the 3 SNPs specified in the regions file are in this long list.

I verified that the order of the snps matches the order of the chromosomes in the `.fai` file. The `.bam` files and the `.fai` file also have the same order. 

In addition, I tried just a single base with the `-r` command, but this produces 250 lines in the out file, when I would only expect one:
```
angsd \
    -bam $bamlists/my_bams.bamfilelist \
    -out $outpath/output_test \
    -doAbbababa 1 \
    -remove_bads 1 \
    -r chr17:25505162 \
    -useLast 1 \
    -minMapQ 30 \
    -blockSize 1 \
    -minQ 30 \
    -doCounts 1
```

The reason I need single bases is that I would like to check a series of SNPs on a genotyping array in order to determine to what extent array ascertainment bias changes the result.

**Comment by SamueleSoraggi** [comment]
Hej
Have you tried writing the region file as

    chr25:31558578-31558578
    chr25:31570089-31570089
    chr25:31571436-31571436


Den 4. feb. 2017 9.17 PM skrev "lindaboettger" <notifications@github.com>:

**Comment by lindaboettger** [comment]
I just tried submitting ranges of 1bp, as you suggested, but the problem remains. I get 762 1bp regions returned and only 2/3 SNPs that I requested are included. 

Thanks,
Linda

**Comment by aalbrechtsen** [comment]
Hi Linda

The method will output one block for each chromosome as well as blocks where you have data but the output should have only zeros for the blocks you did not specify. 
Regarding the missing block then it might be the case that you don't have data for this site after filtering?

cheers
Anders

**Comment by lindaboettger** [comment]
Hi Anders,

Thanks for your reply. I know the SNPs are not removed by the filtering for two reasons:

1. When I remove the filters, the output is the same:

```
angsd \
    -bam $bamlists/my_bams.bamfilelist \
    -out $outpath/output_test \
    -doAbbababa 1 \
    -rf chr1:31571436-31571436 \
    -useLast 1 \
    -blockSize 1 \
    -doCounts 1

$ wc -l outpath/output_test.abbababa 

228 # (I would expect one line)

$ grep 31571436 outpath/output_test.abbababa 

# (nothing)
```

2. If you examine the sample output in the `.abbababa` file above, you will notice that **every other base is missing**, and this is why the missing SNP is not printed:

```
...
chr1    31571425        31571425        0       0       0       0       0       0
chr1    31571427        31571427        0       0       0       0       0       0
chr1    31571429        31571429        0       0       0       0       0       0
chr1    31571431        31571431        0       0       0       0       0       0
chr1    31571433        31571433        0       0       0       0       0       0
chr1    31571435        31571435        0       0       0       0       0       0 # < snp should be here
chr1    31571437        31571437        0       0       0       0       0       0 
chr1    31571439        31571439        0       0       0       0       0       0
chr1    31571441        31571441        0       0       0       0       0       0
chr1    31571443        31571443        0       0       0       0       0       0
chr1    31571445        31571445        0       0       0       0       0       0
...
```

If I use a block size of 2, then the missing snp appears, but only in column 3, and not in column 2.

```
# command:
angsd \
    -bam $bamlists/my_bams.bamfilelist \
    -out $outpath/output_test \
    -doAbbababa 1 \
    -rf chr1:31571436-31571436 \
    -useLast 1 \
    -blockSize 2 \
    -doCounts 1

# output_test.abbababa
...
chr1    31571431        31571432        0       0       0       0       0       0
chr1    31571433        31571434        0       0       0       0       0       0
chr1    31571435        31571436        0       0       0       0       0       0 # <- my snp in col 3 
chr1    31571437        31571438        0       0       0       0       0       0
chr1    31571439        31571440        0       0       0       0       0       0
...
```

Regardless of the filtering, and even in cases where I can find the SNP, it looks like ANGSD prints out ~250 lines for every single base I specify. Surely this is a bug?

I have found a hack to get it working for my list of 18,000 snp positions. First, I run the abbababa test with `blocksize==2`:

```
angsd \
    -bam $bamlists/my_bams.bamfilelist \
    -out $outpath/output_test \
    -doAbbababa 1 \
    -remove_bads 1 \
    -rf list_of_18k_snps.regions \
    -useLast 1 \
    -minMapQ 30 \
    -blockSize 2 \
    -minQ 30 \
    -doCounts 1
```

The resulting `.abbababa` file is 1.2 Gb, which is non-ideal, but if I grep for the SNPs in my regions file, I find about half:

```
grep -F \
    -f <(perl -pe 's/:/\t/' $regions_fn \
        | perl -pe 's/(\d+)$/$1\t/') \
    $abbababa_fn \
    > $abbababa_fn.found

$ wc -l $abbababa_fn.found

83772 (about half)
```

To get the other half, I have to subtract one from every region position among the missing SNPs:

```
# 1. Get missing SNPs:

# convert from abbababa format to ANGSD region file format:
perl -ne '/^(\w+)\t(\d+)/ && print "$1:$2\n"' \
    $abbababa_fn.found \
    > $abbababa_fn.found.regions

# diff the found and original region files
diff $abbababa_fn.found.regions \
    $regions_fn \
    | grep '^>' | perl -pe 's/> //' \
    > $abbababa_fn.missing.regions

# this is the other half:
wc -l $abbababa_fn.missing.regions 
# (83411)
wc -l $abbababa_fn.found.regions 
# (83772)
wc -l $regions_fn 
# (167183, i.e. 83411+83772)

# 2. Subtract one from region locations:
perl -pe 's/:(\d+)/"\t".($1-1)."\t"/e' \
    $abbababa_fn.missing.regions
    > $abbababa_fn.missing.minus1.regions

# 3. Do a second grep with these shifted snp locations
grep -F \
    -f $abbababa_fn.missing.minus1.regions \
    $abbababa_fn \
    > $abbababa_fn.found.minus1.regions


# 4. remainder are found:
#    (except 2, possibly due to filtering)

wc -l $abbababa_fn.found.minus1.regions
# (83409)
```

Thanks for your prompt replies and your help tracking down this bug.

Best,
Linda

**Comment by aalbrechtsen** [comment]
Hi Linda

The abbababa will print out the results for blocks even if they are not specified in the -rf option. However, they will only contain zeros and therefore will not affect the D statistic. This is because for each region (chromosome or region in the -rf file) the results are printed. This is why you get at least on line for each region in the output even though there is no data (but with only zeroes). In addition for each region all of the reads that overlap that regions is parsed. This is why you get extra blocks around your specified regions. Again it will only print zeros for the none-specified region and thus it will not affect the D-statistic. 

However, there was a bug when choosing a block size of 1 where angsd chose to use a block size of 2. This has been corrected in the newest version here on github.  In addition I have tried to reduce the number of empty blocks getting printed but I have not been able to remove them all (but they will not affect the D-statistic). However, I have added and option "-printEmpty" so that you can specify "-printEmpty 0" if you do not want to print blocks were there are no ABBA or BABA sites. 


best,
Anders

**Comment by lindaboettger** [comment]
Thank you, Anders. Glad this got resolved!

Best,
Linda
