### ISSUE TITLE
realSFS with haploid data

### ISSUE THREAD

**Issue by andrewparkermorgan** [ANGSD/angsd#71]
Hi,

I have calculated a set of `*.saf.idx` files assuming haploid input, using `angsd -doSaf -isHap 1`.  When I try to calculate either 1d or higher-order SFS, `realSFS` dies with the assertion error
```
realSFS: safreader.cpp:301: size_t iter_read(persaf*, void*, size_t, int*): Assertion `ret==length' failed.
```

Inspecting one of the `*.saf.idx` files I see that, despite confirming in the `*.args` file that I used haploid mode, the number of chromosomes is marked as if the individuals (n = 20) are diploid (nChr = 40):
```
(py35) [apm@longleaf-login1 sfs]$ realSFS print_header dom.saf.idx 
	-> Version of fname:dom.saf.idx is:2
	-> Assuming .saf.gz file: dom.saf.gz
	-> Assuming .saf.pos.gz: dom.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:dom.saf.idx fstout:(null) oldout:0 seed:1487732429 bootstrap:0
		Information from index file: nChr:40 nSites:2422
		0	chrY	2422	8	8
```

My questions are:
(1) Is `doSaf` actually using a haploid model?
(2) If so, how can I tell `realSFS` that this is the case?
(3) If the haploid model is not actually supported, is there a rational way to calculate SFS from haploid data?

Thanks,
Andrew Morgan

--
Department of Genetics
University of North Carolina
Chapel Hill NC

**Comment by andrewparkermorgan** [comment]
Sorry -- this was (partly) my fault.  I was using `angsd` as pacakged on Bioconda (0.9.10), and the above-described issue has been fixed between that version and a more recent release (0.9.17).  Putting a fresh version in Bioconda would be excellent if maintainers have time to do so.

I am now able to obtain unfolded haploid SFS, but they appear to be "backwards" -- ie. the zero-frequency bin (all samples fixed for ancestral state) is at the end of the line (for 1d SFS) rather than the beginning.  Is this an intended behavior?

**Comment by ANGSD** [comment]
Dear Andrew, the haploid version is very much in development to the degree that i doubt the current version is working correctly. It is something we will look into at some point but i dont think it will be in the near future.

**Comment by mlaylwar** [comment]
What is the status of the haploid version currently?

**Comment by ANGSD** [comment]
So the haploid should now work in the most recent commit, im closing this issue.
