### ISSUE TITLE
merge .geno files 

### ISSUE THREAD

**Issue by rustaginavin** [ANGSD/angsd#72]
Hi, 

I am trying to get a  PCA plot for the whole genome. It is taking me a lot of time to generate the .geno file for the whole genome. Now I am planning to call chromosome by chromosome and merge the .geno files and then call PCA. 

is there a tool for merging .geno files. 

I have a partial run of the whole genome which could not complete because it ran out of memory. If there a way to extract some data from the corrupted .geno files, that will be great too. 

Thanks, Navin

**Comment by ANGSD** [comment]
Which command did you use for generating the .geno files, and how do they
look?

**Comment by rustaginavin** [comment]
Hi,

attached is my shell script.   Please note that I am using a fairly large
dataset of 185  low coverage whole genome individuals.
I am following the best practices recommendations from the NGStools .

Any way to speed up the process will be much appreciated.

Regards,

navin


ANGSD="/usr/rustagi/temp/angsd/angsd"
INPUT="/usr/rustagi/data/185_SAS-AP/list_185_bams.txt"
REF="/usr/rustagi/data/ref/human/GRCh37/human.g1k.v37.fa"
ngsCovar="/usr/rustagi/temp/ngsPopGen/ngsCovar"
result="chr20_geno"
covariance="cov_all"

$ANGSD -P 4 -b $INPUT -ref $REF -out $result -r 20 -uniqueOnly 1
-remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 -minMapQ 20 -minQ
20 -nind 185  -doCounts 1 -GL 1 -doMajorMinor 1 -doMaf 1 -skipTriallelic 1
-SNP_pval 1e-3 -doGeno 32 -doPost 1
gunzip $result.geno.gz
N_SITES=`zcat $result.mafs.gz | tail -n+2 | wc -l`
$ngsCovar -probfile test.geno -outfile  $covariance  -nind 185  -nsites 5
-call 0 -norm 0

**Comment by rustaginavin** [comment]
Hi,

I apologize,

the previous command  was for chromosome 20. But the run I want to do is
without the -r 20 option. I want whole genome PCA

Regards,

navin

**Comment by ANGSD** [comment]
If it is -dogeno 32, you should be as simple as just catting them together. Maybe @mfumagali has something to add.

**Comment by ANGSD** [comment]
Im closing this issue feel free to reopen if needed.
