### ISSUE TITLE
Segmentation Fault with  -doAbbababa2 

### ISSUE THREAD

**Issue by Xevkin** [ANGSD/angsd#73]
I ran the following command: 

~/bin/angsd/angsd  -doAbbababa2 1 -bam in.bamlist -sizeFile sizeFile.size -doCounts 1 -out out_rmTrans -anc <ancestral.fa> -minQ 20 -minMapQ 30 -nThreads 8 -rmTrans 1 -ref <ref.fa> -rf regions.txt
 
Which gave:

        -> angsd version: 0.917-63-g6522d3e (htslib: 1.3.2-132-g609120d) build(Mar 10 2017 13:15:56)
        -> Reading fasta: <ancestral.fa>
        -> Reading fasta: <ref.fa>
        -> 6 Populations | 30 trees | 10 Individuals | <ancestral.fa> Outgroup
        -> Parsing 9 number of samples 
        -> Region lookup 1/1
Segmentation fault (core dumped)

I initially ran with no regions defined and it gave an identical error> I repeated with 1Mb in the regions.txt file and got the same error.

**Comment by SamueleSoraggi** [comment]
Hi
Could you try to check if it does the same without the rmTrans option?


- Samuele

2017-03-10 16:06 GMT+01:00 Kevin <notifications@github.com>:

**Comment by Xevkin** [comment]
Yes it does.

**Comment by SamueleSoraggi** [comment]
Sorry for the late reply. Did you try to update angsd with the latest version?

I did and it works fine with a setup similar to yours. Let me know if it still does not work.

-Samuele

**Comment by Xevkin** [comment]
What I'm using: angsd version: 0.917-63-g6522d3e (htslib: 1.3.2-132-g609120d)

**Comment by ANGSD** [comment]
Could you try running it through a debugger, then we should be able to
pinpoint exactly which line that causes the seqfault.

in terminal:

cd angsd;
make clean;
make FLAGS="-D__WITH_POOL__ -ggdb"
gdb ./angsd
run -doAbbababa2 1 -bam in.bamlist -sizeFile sizeFile.size -doCounts 1 -out
out_rmTrans -anc <ancestral.fa> -minQ 20 -minMapQ 30 -nThreads 8 -rmTrans 1
-ref <ref.fa> -rf regions.txt

when it crashes, then type bt followed by enter. Then it should tell us
which line.

Thanks for your help weeding  out these bugs, it is appreciated.

Best

**Comment by SamueleSoraggi** [comment]
I think I found out where the bug was and corrected a variable definition. Can you try downloading the latest version of angsd? I updated it.

**Comment by Xevkin** [comment]
Output was:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
        -> angsd version: 0.917-63-g6522d3e (htslib: 1.3.2-132-g609120d) build(Mar 20 2017 13:01:59)
        -> Reading fasta: /bowie/ancestral_fastas/yak_ancestral.fa
        -> Reading fasta: /bowie/goat_CHIR1_0/goat_CHIR1_0.fasta
        -> 6 Populations | 30 trees | 10 Individuals | /bowie/ancestral_fastas/yak_ancestral.fa Outgroup
        -> Parsing 9 number of samples 
        -> Region lookup 1/1
[New Thread 0x7ffff6b61700 (LWP 44482)]
[New Thread 0x7ffff6360700 (LWP 44483)]
[New Thread 0x7ffff5b5f700 (LWP 44484)]
[New Thread 0x7ffff535e700 (LWP 44485)]
[New Thread 0x7ffff4b34700 (LWP 44486)]
[New Thread 0x7fffdffff700 (LWP 44487)]
[New Thread 0x7fffdf7fe700 (LWP 44488)]
[New Thread 0x7fffdeffd700 (LWP 44489)]
[New Thread 0x7fffde7fc700 (LWP 44490)]
[Thread 0x7ffff6360700 (LWP 44483) exited]
[Thread 0x7ffff6b61700 (LWP 44482) exited]
[Thread 0x7fffdffff700 (LWP 44487) exited]
[Thread 0x7fffde7fc700 (LWP 44490) exited]
[Thread 0x7ffff535e700 (LWP 44485) exited]
[Thread 0x7ffff5b5f700 (LWP 44484) exited]
[Thread 0x7fffdeffd700 (LWP 44489) exited]
[Thread 0x7ffff4b34700 (LWP 44486) exited]
[Thread 0x7fffdf7fe700 (LWP 44488) exited]
[New Thread 0x7fffde7fc700 (LWP 45422)]
[New Thread 0x7fffdeffd700 (LWP 45423)]
[New Thread 0x7fffdf7fe700 (LWP 45476)]
[New Thread 0x7fffdffff700 (LWP 45477)]
[New Thread 0x7ffff6a60700 (LWP 45478)]
[New Thread 0x7ffff625f700 (LWP 45479)]
[New Thread 0x7ffff595d700 (LWP 45480)]
[New Thread 0x7ffff4b34700 (LWP 45481)]
[New Thread 0x7fffcde65700 (LWP 45482)]
[New Thread 0x7fffcd664700 (LWP 45483)]
[New Thread 0x7fffcce63700 (LWP 45484)]
*** Error in `/home/kdaly/bin/angsd/angsd': free(): invalid pointer: 0x00007fffd0000078 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffde7fc700 (LWP 45422)]
0x00007ffff6df4c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

**Comment by Xevkin** [comment]
SamueleSoraggi I ran into this issue while compiling, not sure if it has anything to do with the update. 
[angsd_compiler_issue.docx](https://github.com/ANGSD/angsd/files/872144/angsd_compiler_issue.docx)

**Comment by ANGSD** [comment]
The newest version of htslib requires -llzma. Pull the latest version of
angsd where the -llzma is added to the makefile

**Comment by Xevkin** [comment]
Updating angsd resolved the issue - at least the segmentation fault has stopped, it hasn't run to completion yet. Thanks for your help with this!
