### ISSUE TITLE
compilation error for version 0.917

### ISSUE THREAD

**Issue by MichelMoser** [ANGSD/angsd#75]
Hello, 

When i try to compile latest version of angsd, i run into following error: 

```
git clone https://github.com/samtools/htslib.git
git clone https://github.com/ANGSD/angsd.git 
cd htslib;make;cd ../angsd ;make HTSSRC=../htslib
```

last command line terminates due to: 

```
g++ -MM -O3 -D__WITH_POOL__  -I/home/mmoser/htslib shared.cpp >shared.d
g++ -c  -O3 -D__WITH_POOL__  -I/home/mmoser/htslib simple_likes.cpp
g++ -MM -O3 -D__WITH_POOL__  -I/home/mmoser/htslib simple_likes.cpp >simple_likes.d
g++ -c  -O3 -D__WITH_POOL__  -I/home/mmoser/htslib soap_likes.cpp
g++ -MM -O3 -D__WITH_POOL__  -I/home/mmoser/htslib soap_likes.cpp >soap_likes.d
g++ -c  -O3 -D__WITH_POOL__  -I/home/mmoser/htslib vcfReader.cpp
g++ -MM -O3 -D__WITH_POOL__  -I/home/mmoser/htslib vcfReader.cpp >vcfReader.d
g++ -O3 -D__WITH_POOL__  -o angsd *.o -lz -lpthread /home/mmoser/htslib/libhts.a
/home/mmoser/htslib/libhts.a(cram_io.o): In function `lzma_mem_deflate':
/home/mmoser/htslib/cram/cram_io.c:865: undefined reference to `lzma_stream_buffer_bound'
/home/mmoser/htslib/cram/cram_io.c:871: undefined reference to `lzma_easy_buffer_encode'
/home/mmoser/htslib/libhts.a(cram_io.o): In function `cram_compress_by_method':
/home/mmoser/htslib/cram/cram_io.c:1226: undefined reference to `BZ2_bzBuffToBuffCompress'
/home/mmoser/htslib/libhts.a(cram_io.o): In function `cram_uncompress_block':
/home/mmoser/htslib/cram/cram_io.c:1150: undefined reference to `BZ2_bzBuffToBuffDecompress'
/home/mmoser/htslib/libhts.a(cram_io.o): In function `lzma_mem_inflate':
/home/mmoser/htslib/cram/cram_io.c:887: undefined reference to `lzma_easy_decoder_memusage'
/home/mmoser/htslib/cram/cram_io.c:887: undefined reference to `lzma_stream_decoder'
/home/mmoser/htslib/cram/cram_io.c:902: undefined reference to `lzma_code'
/home/mmoser/htslib/cram/cram_io.c:915: undefined reference to `lzma_code'
/home/mmoser/htslib/cram/cram_io.c:924: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
make: *** [angsd] Error 1
```
Could someone help me out?
Thank you, 
Michel

**Comment by ANGSD** [comment]
Dear Michel, it is not something i've seen before. What is your platform?

**Comment by MichelMoser** [comment]
Hello, 

I would like to install it on a cluster with Scientific Linux release 6.8 (Carbon) on it.
Do i miss something for htslib cram extensions?
Thanks, 
Michel

**Comment by ANGSD** [comment]
Can you show me the output from the compilation of the htslib?

**Comment by ANGSD** [comment]
Dear Michel, could you please try the latest version. I've modified the Makefiles to comply with the latests htslib

**Comment by MichelMoser** [comment]
Hello, 
Thank you very much for the fixing this. Works now like a charm!

**Comment by rebzzy** [comment]
Hi - 

I'm getting this same error but with the latest version of htslib and angsd. I'm trying to install on a cluster and am using a local version of htslib that I installed using the xz library:
./configure CPPFLAGS=-I/gscratch/leache/rbharris/bin/xz-5.2.3/include LDFLAGS=-L/gscratch/leache/rbharris/bin/xz-5.2.3//lib

I tried compiling angsd using make HTSSRC=../htslib and then I get the error:

icpc -O3 -D__WITH_POOL__  -o angsd *.o /gscratch/leache/rbharris/bin/temp/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_read':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:281: undefined reference to `curl_easy_pause'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `wait_perform':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:229: undefined reference to `curl_multi_fdset'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:234: undefined reference to `curl_multi_timeout'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:248: undefined reference to `curl_multi_perform'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `process_messages':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:206: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_write':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:326: undefined reference to `curl_easy_pause'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `wait_perform':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:229: undefined reference to `curl_multi_fdset'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:234: undefined reference to `curl_multi_timeout'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:248: undefined reference to `curl_multi_perform'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `process_messages':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:206: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_seek':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:377: undefined reference to `curl_multi_remove_handle'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:385: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:391: undefined reference to `curl_multi_add_handle'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:395: undefined reference to `curl_easy_pause'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `wait_perform':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:229: undefined reference to `curl_multi_fdset'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:234: undefined reference to `curl_multi_timeout'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:248: undefined reference to `curl_multi_perform'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `process_messages':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:206: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_close':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:422: undefined reference to `curl_easy_pause'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `wait_perform':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:229: undefined reference to `curl_multi_fdset'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:234: undefined reference to `curl_multi_timeout'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:248: undefined reference to `curl_multi_perform'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `process_messages':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:206: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_close':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:431: undefined reference to `curl_multi_remove_handle'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:435: undefined reference to `curl_easy_cleanup'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:435: undefined reference to `curl_easy_cleanup'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_open':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:545: undefined reference to `curl_slist_free_all'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:474: undefined reference to `curl_easy_init'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:478: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:487: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:488: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:489: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:491: undefined reference to `curl_slist_append'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:495: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:496: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:498: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:499: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:501: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o):/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:503: more undefined references to `curl_easy_setopt' follow
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_open':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:537: undefined reference to `curl_easy_cleanup'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:538: undefined reference to `curl_slist_free_all'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:507: undefined reference to `curl_multi_add_handle'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:531: undefined reference to `curl_multi_remove_handle'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:521: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:481: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:482: undefined reference to `curl_easy_setopt'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `wait_perform':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:229: undefined reference to `curl_multi_fdset'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:234: undefined reference to `curl_multi_timeout'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:248: undefined reference to `curl_multi_perform'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `process_messages':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:206: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:204: undefined reference to `curl_multi_info_read'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `parse_va_list':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:570: undefined reference to `curl_slist_append'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:577: undefined reference to `curl_slist_append'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:563: undefined reference to `curl_slist_append'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `vhopen_libcurl':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:596: undefined reference to `curl_slist_free_all'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `parse_va_list':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:570: undefined reference to `curl_slist_append'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:577: undefined reference to `curl_slist_append'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:563: undefined reference to `curl_slist_append'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `hfile_plugin_init_libcurl':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:621: undefined reference to `curl_global_init'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:624: undefined reference to `curl_multi_init'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:627: undefined reference to `curl_version_info'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `easy_errno':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:120: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:106: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `hfile_plugin_init_libcurl':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:625: undefined reference to `curl_global_cleanup'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `libcurl_exit':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:189: undefined reference to `curl_multi_cleanup'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:195: undefined reference to `curl_global_cleanup'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_libcurl.o): In function `easy_errno':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:120: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_libcurl.c:106: undefined reference to `curl_easy_getinfo'
/gscratch/leache/rbharris/bin/temp/htslib/libhts.a(hfile_s3.o): In function `s3_sign':
/gscratch/leache/rbharris/bin/temp/htslib/hfile_s3.c:64: undefined reference to `EVP_sha1'
/gscratch/leache/rbharris/bin/temp/htslib/hfile_s3.c:64: undefined reference to `HMAC'
make: *** [angsd] Error 1

**Comment by ANGSD** [comment]
Without more information or even access to to the cluster Im not sure how
to proceed. You might need to contact the admin of the cluster and show him
the compile error.

Best

**Comment by YourePrettyGood** [comment]
Hi,
Apologies for bringing this back up, but maybe this will help others who might get the same problem.

After updating HTSlib to the latest (1.5.5, originally tried with 1.2.1, but that's too old for ANGSD), and trying to install ANGSD 0.919 (commit 03dafc2), I got the same series of errors as @rebzzy above.

The resolution was to add `-lcurl` to the end of every linking recipe in `Makefile` and `misc/Makefile` that also links to HTSlib.  So for commit 03dafc2, that was line 64 of `Makefile`, and lines 70, 73, 76, 89, and 92 of `misc/Makefile`.  Installation worked smoothly thereafter.

Best regards,
Patrick Reilly

**Comment by ANGSD** [comment]
Ok, I've added this in the latest commit. Thanks for your input.

Best
