### ISSUE TITLE
2D folded SFS

### ISSUE THREAD

**Issue by claudiuskerth** [ANGSD/angsd#78]
Many people study systems with currently no good outgroup sequence available to determine ancestral and derived states of alleles and therefore cannot estimate a derived allele frequency spectrum (SFS). They can only estimate minor allele frequency spectra aka folded SFS. However, they can arbitrarily polarise a spectrum with respect to a reference sequence by providing that reference sequence file to the `-anc` switch of ANGSD. From the ngsTools/ANGSD tutorial of Matteo:

> As a note for the general use, in case an ancestral sequence is not available, analyses on FST, PCA, nucleotide diversity (but not the number of fixed differences) can be carried out using the reference sequence to polarise your data. Please be aware that, under this scenario, some quantities (e.g. the unfolded joint site frequency spectrum) will be nonsense.

I would like to analyse folded 2D site frequency spectra, but as [this thread](https://groups.google.com/forum/#!topic/ngstools-user/9Z4viLJ7NJA) on the ngsTools-user forum points out, the 2D-SFS estimated by ANGDS/realSFS from folded SAF's is NOT a *joint minor allele frequency spectrum*, which would - for sample sizes of n and m diploid individuals in the two populations - be the lower triangle (including the diagonal) of a (2n+1) x (2m+1) matrix. An allele is *joint minor* if it has a frequency in the total (i. e. pooled) sample of less than or equal to (2n + 2m)/2. The 2D SFS that ANGSD/realSFS currently prints out is a (n+1) x (m+1) matrix, where each cell corresponds to 4 unfolded frequency classes. This version of the 2D spectrum therefore discards a lot of information about allele frequency divergence between the two populations.

My question is: 

Is it correct to estimate an unfolded 2D SFS using arbitrary polarisation with ANGSD/realSFS and then fold it into a joint minor allele frequency spectrum (e. g. with dadi)?

My comparisons of 1D spectra, folded by ANGSD or folded by dadi, suggest that folding by ANGSD or folding by dadi leads to very similar spectra and I am inclined to think that the differences are due to numerical errors.

![ery_fold_comp](https://cloud.githubusercontent.com/assets/790966/24322911/2cc85314-116d-11e7-84aa-4fb0e480a701.png)
![par_fold_comp](https://cloud.githubusercontent.com/assets/790966/24322912/2ccb425e-116d-11e7-8d54-be6055468ca0.png)

many thanks for your support!

claudius

**Comment by kritikamgarg** [comment]
Hi Claudius,
Have you been able to sort this. 

Thank you

Regards
Kritika

**Comment by ANGSD** [comment]
Hi in the latest commit referenced above I implemented proper folding for the 2dsfs. This should really have been done along time ago. Sorry for the delay.

Best
