### ISSUE TITLE
VCF genotype likelihood input

### ISSUE THREAD

**Issue by ekg** [ANGSD/angsd#8]
As VCF is able to encode genotype likelihoods, is there a way to use these in ANGSD?

Some methods have rather sophisticated methods to calculate these, which might be somewhat context dependent. Also, this would allow working with indels, SVs, and other non-SNP variation.

I'm happy to write a converter to go from VCF to a format that ANGSD can understand. But is there documentation to explain the input format?

**Comment by ANGSD** [comment]
I did basic vcf parsing sometime ago, see the -vcf-gl and -vcf-gp input option. However this will only use diallelic sites, and not the indels etc. The indels are represented internally in angsd, but at the current time no downstream analysis is actually using these. I will need to think about which analysis are well defined for the non-SNPs. See https://github.com/ANGSD/angsd/blob/master/vcfReader.cpp for the vcf reader. 

I don't think the vcf reading is the most used option, so let me know if you find any bugs.
Also I never got around to actually document the internal layout. But i have made a template for users wanting to play around with their own analysis: https://github.com/ANGSD/angsd/blob/master/abcTemplate.cpp

Best

**Comment by ekg** [comment]
@ANGSD as long as VCF input can be used, I think all is well. How do you give VCF input though? It's not obvious at least on the version that I've been working with.

**Comment by ANGSD** [comment]
There is an example on the wiki here:
http://www.popgen.dk/angsd/index.php/Input#VCF_files
./angsd -vcf-gl ../1000g/ref.r1274.vcf -fai fai.fai -nind 181 -domaf 1 -out two

You will also need to supply a fai file and the number of individuals. This should of course not be necessary, but I didn't bother fixing it at the time.

Best

**Comment by ANGSD** [comment]
Let me know if you encounter bugs with the vcf files. It is not something I've tested for all analysis in angsd. Actually only a few. I'm closing the issue. Feel free to reopen.
