### ISSUE TITLE
realSFS Fst problem with size of dimension

### ISSUE THREAD

**Issue by MichelMoser** [ANGSD/angsd#82]
Dear ANGSD, 

I try to estimate Fst along the genome using two populations of 11 samples each (low coverage NGS data). 

I followed provided expamles on page: http://www.popgen.dk/angsd/index.php/Fst
First creating SAF-files: 
```
angsd -b pop_L  -anc /data7/users/mmoser/Peaxi_genome_v1.6.2.scaffolds.fa -out filter_fst_popL -dosaf 1 -gl 1 -nThreads 4 -minMapQ 2 -minQ 20
angsd -b pop_S  -anc /data7/users/mmoser/Peaxi_genome_v1.6.2.scaffolds.fa -out filter_fst_popS -dosaf 1 -gl 1 -nThreads 4 -minMapQ 2 -minQ 20

```
then tried to calculate the 2dsfs prior but due to large number of sites, 
-> nSites: 1120135016
        -> The choice of -nSites will require atleast: 213648.796875 megabyte memory, that is at least: 82.74% of total memory
/opt/sge/default/spool/binfservas15/job_scripts/335976: line 3: 35208 Killed                  /home/mmoser/angsd/misc/realSFS filter_fst_popL.saf.idx filter_fst_popS.saf.idx > filterALL_popL.popS.ml

i had to restrict the number of sites to 10 mio: 

```
realSFS -nSites 10000000 fst_popL.saf.idx fst_popS.saf.idx >popL.popS.ml

```
When i then tried to combine the priors and saf, i get a error having the wrong size of dimensions: 

```
realSFS fst index fst_popL.saf.idx fst_popS.saf.idx -sfs popL.popS.ml -fstout here

STDOUT:

        -> Version of fname:fst_popL.saf.idx is:2
        -> Assuming .saf.gz file: fst_popL.saf.gz
        -> Assuming .saf.pos.gz: fst_popL.saf.pos.gz
        -> Version of fname:fst_popS.saf.idx is:2
        -> Assuming .saf.gz file: fst_popS.saf.gz
        -> Assuming .saf.pos.gz: fst_popS.saf.pos.gz
        -> args: tole:0.000001 nthreads:4 maxiter:100 nsites:10000000 start:popL.popS.ml chr:(null) start:-1 stop:-1 fname:fst_popS.saf.idx fstout:here oldout:0 seed:1496216250 bootstrap:0 whichFst:0
        -> nSites: 10000000
        -> Reading: popL.popS.ml assuming counts (will normalize to probs internally)
problem with size of dimension of prior 529 vs 61364

```

I dont quite get the strucutre of the ml-file as it has the prior-numbers on 116 rows with 529 columns. (116 * 529 = 61364)   

Could you tell me how to avoid this problem or what i am doing wrong?
Thank you, 
michel

**Comment by ANGSD** [comment]
Dear Michel, sorry for the delay i was on a small vacation.

When you specify -nSites, then it will estimate on disjoint blocks across
the genome each containing nSites number of sites. The expected input for
the prior is a single estimate. So you can either just pick a random
estimate (one of the rows of the output). Or you can take the mean across
all the estimates.

I would use a blocksize much larger than 10mio sites.

Best

**Comment by ANGSD** [comment]
im closing this issue feel free to reopen if needed.

**Comment by marce-sarrias** [comment]
Hi there, 

I'm having a similar problem and I can't figure out what's wrong. I'm hoping you can identify the problem.

Basically, I have what I believe are 2 different populations (the whole point of doing these analyses is to actually see if they are different or not): pop1 (n = 10) and pop2 (n =10)

So far, this is what I've done:

1 -> calculate SAF:
(I'm using my reference genome as the ancestral sequence to polarise the alleles)
FILTERS="-minMapQ 30 -minQ 20 -uniqueOnly 1 -remove_bads 1 -baq 1 -only_proper_pairs 1 -trim 0 -C 50 -maxDepth 500 -minInd 10 -setMinDepth 20 -setMaxDepth 100"
$ANGSD -b pop1.bam.list -anc $ANC -ref $REF $FILTERS -GL 1 -doCounts 1 -doSaf 1 -out pop1
$ANGSD -b pop2.bam.list -anc $ANC -ref $REF $FILTERS -GL 1 -doCounts 1 -doSaf 1 -out pop2

2 -> calculate SFS:
$realSFS -bootstrap 100 pop1.saf.idx > pop1.sfs
$realSFS -bootstrap 100 pop2.saf.idx > pop2.sfs

Then I checked the number of values by doing:
awk -F' ' '{print NF; exit}' pop1.sfs
awk -F' ' '{print NF; exit}' pop2.sfs
awk -F' ' '{print NF; exit}' pop1.pop2.sfs

and I get 21 (2N+1), 21, and 441 respectively

3 -> calculate 2d SFS:
$realSFS -bootstrap 100 pop1.saf.idx pop2.saf.idx > pop1.pop2.sfs

now I'm trying to calculate the fst by doing:
$realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1.pop2.sfs -fstout pop1.pop2
$realSFS fst stats pop1.po2.fst.idx

but I get this error:
-> args: tole:0.000000 nthreads:4 maxiter:100 nsites(block):0 start:pop1.pop2.sfs chr:(null) start:-1 stop:-1 fstout:pop1.pop2 oldout:0 seed:-1 bootstrap:0 resample_chr:0 whichFst:0 fold:0 ref:(null) anc:(null)
-> nSites: 100000
-> IMPORTANT: please make sure that your saf files haven't been folded with -fold 1 in -doSaf in angsd
-> [reynoldFst] sfs1:20 sfs2:20 dimspace:441
-> generating offset remapper lookup
-> isSame:1 adjusting foldfactors
-> Reading: pop1.pop2.sfs assuming counts (will normalize to probs internally)
-> Pxroblem with size of dimension of prior 441 vs 44100

Any ideas?

Thank you!

Marcela

**Comment by ANGSD** [comment]
This step is wrong, just do

realSFS pop1.saf.idx pop2.saf.idx >pop1.pop2.sfs

**Comment by marce-sarrias** [comment]
Hi! Thanks for getting back to me so fast!

Could you just briefly explain why is the bootstrap a problem?

**Comment by ANGSD** [comment]
The bootstrap will give you many bootstrapped estimates, for the next part you should only supply a single sfs.

**Comment by marce-sarrias** [comment]
I see.. thank you! I was able to calculate the fst!

**Comment by ANGSD** [comment]
Thats great.

Best
Thorfinn

**Comment by Raksha-95** [comment]
Hi, 

I am also having a similar problem and I am not sure how to solve it. I am trying to calculate now the Thetas.
My steps until now are:

Calculate SAF 
angsd -bam BamFiles.txt -doSaf 1 -out allsites.sfs -anc ReferenceGenome_final.fasta -GL 2 -minMapQ 1 -minQ 20

Calculate SFS
realSFS allsites.sfs.saf.idx -nSites 1500000000 -P 30 > allsites.sfs
*Here I had to use -nSites because my file was too big (I think)

The command I am using now is 
RealSFS saf2theta allsites.sfs.saf.idx -sfs allsites.sfs -outname theta

And the error: 
        -> Version of fname:allsites.sfs.saf.idx is:2
        -> Assuming .saf.gz file: allsites.sfs.saf.gz
        -> Assuming .saf.pos.gz: allsites.sfs.saf.pos.gz
        -> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:allsites.sfs chr:(null) start:-1 stop:-1 fstout:theta oldout:0 seed:1665234516 bootstrap:0 resample_chr:0 whichFst:0 fold:0 ref:(null) anc:(null)
        -> Will read chunks of size: 4096
        -> Reading: allsites.sfs assuming counts (will normalize to probs internally)
        -> Pxroblem with size of dimension of prior 33 vs 66

Do you have any ideas? 

Thanks a lot!
