### ISSUE TITLE
thetaStat: Problem opening file: out.thetas.idx.idx

### ISSUE THREAD

**Issue by ariloytynoja** [ANGSD/angsd#84]
Hi,

I have problems using thetaStat. When I follow the example on the web page, thetaStat gives error:

`$ thetaStat do_stat out.thetas.idx`
`        Assuming binfile:out.thetas.idx.bin and indexfile:out.thetas.idx.idx`
`Problem opening file: out.thetas.idx.idx`

The files that it assumes do not exist:

`$ ls out.*`
`out.arg  out.saf.gz  out.saf.idx  out.saf.pos.gz  out.sfs  out.thetas.gz  out.thetas.idx`

I'm using angsd v. 0.917-126-gb1d9615 (htslib: 1.3.2-220-g84a89da). The full analysis is like this:

`$ angsd -bam bams.txt -doSaf 1 -anc anc.fa.gz  -GL 1 -out out -r LG1:1-100000`
`        -> angsd version: 0.917-126-gb1d9615 (htslib: 1.3.2-220-g84a89da) build(Jun  7 2017 10:06:14)`
`        -> Reading fasta: anc.fa.gz`
`        -> Parsing 20 number of samples `
`        -> Region lookup 1/1`
`        -> Printing at chr: LG1 pos:85259 chunknumber 100 contains 786 sites`
`        -> Done reading data waiting for calculations to finish`
`        -> Done waiting for threads`
`        -> Output filenames:`
`                ->"out.arg"`
`                ->"out.saf.gz"`
`                ->"out.saf.pos.gz"`
`                ->"out.saf.idx"`
`        -> Wed Jun  7 10:22:41 2017`
`        -> Arguments and parameters for all analysis are located in .arg file`
`        [ALL done] cpu-time used =  11.13 sec`
`        [ALL done] walltime used =  12.00 sec`

`$ realSFS out.saf.idx > out.sfs`
`        -> Version of fname:out.saf.idx is:2`
`        -> Assuming .saf.gz file: out.saf.gz`
`        -> Assuming .saf.pos.gz: out.saf.pos.gz`
`        -> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:out.saf.idx fstout:(null) oldout:0 seed:1496820161 bootstrap:0 whichFst:0`
`        -> nSites: 87621`
`        -> The choice of -nSites will require atleast: 14.372646 megabyte memory, that is at least: 0.00% of total memory`
`        -> dim(out.saf.idx):41`
`        -> Dimension of parameter space: 41`
`        -> Done reading data from chromosome will prepare next chromosome`
`        -> Is in multi sfs, will now read data from chr:LG1`
`        -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect `
`        -> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites`
`        -> Will run optimization on nSites: 87621`
`------------`
`startlik=-458956.725126`
`lik[2]=-26533.257990 diff=4.324235e+05 alpha:1.000000 sr2:3.630703e-01`
`lik[5]=-18773.943202 diff=7.759315e+03 alpha:1.218069 sr2:1.496078e-02`
`lik[8]=-18763.416466 diff=1.052674e+01 alpha:1.628811 sr2:1.425708e-07`
`lik[11]=-18763.024886 diff=3.915800e-01 alpha:2.870426 sr2:1.684668e-10`
`lik[14]=-18762.999704 diff=2.518159e-02 alpha:4.000000 sr2:7.312155e-12`
`        -> Breaking EM(sr2) at iter:15, sqrt(sr2):7.086528e-07`
`likelihood: -18762.999704`
`------------`
`        -> Only read nSites: 0 will therefore prepare next chromosome (or exit)`
` `
`        -> NB NB output is no longer log probs of the frequency spectrum!`
`        -> Output is now simply the expected values! `
`        -> You can convert to the old format simply with log(norm(x))`

`$ angsd -bam bams.txt -out out -doThetas 1 -doSaf 1 -pest out.sfs -anc anc.fa.gz -GL 1 -r LG1:1-100000`
`        -> angsd version: 0.917-126-gb1d9615 (htslib: 1.3.2-220-g84a89da) build(Jun  7 2017 10:06:14)`
`        -> Reading fasta: anc.fa.gz`
`        -> Parsing 20 number of samples` 
`        -> Region lookup 1/1`
`        -> Printing at chr: LG1 pos:85259 chunknumber 100 contains 786 sites`
`        -> Done reading data waiting for calculations to finish`
`        -> Done waiting for threads`
`        -> Output filenames:`
`                ->"out.arg"`
`                ->"out.thetas.gz"`
`                ->"out.thetas.idx"`
`        -> Wed Jun  7 10:22:53 2017`
`        -> Arguments and parameters for all analysis are located in .arg file`
`        [ALL done] cpu-time used =  11.03 sec`
`        [ALL done] walltime used =  11.00 sec`

`$ thetaStat do_stat out.thetas.idx`
`        Assuming binfile:out.thetas.idx.bin and indexfile:out.thetas.idx.idx`
`Problem opening file: out.thetas.idx.idx`

`$ ls out.*`
`out.arg  out.saf.gz  out.saf.idx  out.saf.pos.gz  out.sfs  out.thetas.gz  out.thetas.idx`

Any help is appreciated.

Ari

**Comment by ANGSD** [comment]
Are you sure you are running the commands from the same directory where the
generated files are located?

**Comment by ANGSD** [comment]
Could you try printing the first 8bytes as binary to the screen:

Something like:
od -N8 -c ./tajima/outputNew/norm.thetas.idx
0000000   t   h   e   t   a   v   2  \0
0000010

**Comment by ariloytynoja** [comment]
The problem was resolved with recompilation from scratch. This may have been caused by library issues ( liblzma seems to be a new dependency) on the cluster that I work on. 
Sorry for the trouble. I should have been able to do better before reporting the issue here.
