### ISSUE TITLE
Multi SFS problem

### ISSUE THREAD

**Issue by claudiuskerth** [ANGSD/angsd#86]
Hi Thorfinn,

I am still trying to find a way to get proper bootstraps of the SFS with angsd/realSFS. I have managed to do this for 1D SFS's by providing a bootstrapped regions file to `angsd -dosaf 1`. 
However, when I try to estimate a 2D SFS with the bootstrapped SAF files, I get the following error message:

>realSFS SAF/ERY/ERY.unfolded.merged.saf.idx SAF/PAR/PAR.unfolded.merged.saf.idx -P 20  > SFS/2D/EryPar.unfolded.0001.sfs2d
        -> Version of fname:SAF/ERY/ERY.unfolded.merged.saf.idx is:2
        -> Assuming .saf.gz file: SAF/ERY/ERY.unfolded.merged.saf.gz
        -> Assuming .saf.pos.gz: SAF/ERY/ERY.unfolded.merged.saf.pos.gz
        -> Version of fname:SAF/PAR/PAR.unfolded.merged.saf.idx is:2
        -> Assuming .saf.gz file: SAF/PAR/PAR.unfolded.merged.saf.gz
        -> Assuming .saf.pos.gz: SAF/PAR/PAR.unfolded.merged.saf.pos.gz
        -> args: tole:0.000001 nthreads:20 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:SAF/PAR/PAR.unfolded.merged.saf.idx fstout:(null) oldout:0 seed:1498852062 bootstrap:0 whichFst:0
        -> Multi SFS is 'still' under development. Please report strange behaviour
        -> nSites: 1619517
        -> The choice of -nSites will require atleast: 481.881439 megabyte memory, that is at least: 0.50% of total memory
        -> dim(SAF/ERY/ERY.unfolded.merged.saf.idx):37
        -> dim(SAF/PAR/PAR.unfolded.merged.saf.idx):37
        -> Dimension of parameter space: 1369
        -> Done reading data from chromosome will prepare next chromosome
        -> Is in multi sfs, will now read data from chr:Contig_100013
        -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
        -> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
        -> Potential big problem, ordering of positions indicates that sites has not been sorted ? 
        -> chromoname: 'Contig_100013' pos[132]:7 vs pos[132-1]:155
        -> Consider running ./realSFS check your.saf.idx for each pop
        -> Potential big problem, ordering of positions indicates that sites has not been sorted ? 
        -> chromoname: 'Contig_100013' pos[132]:7 vs pos[132-1]:155
        -> Consider running ./realSFS check your.saf.idx for each pop
        -> Sites to keep[Contig_100013] from pop0:      0
        -> Sites to keep[Contig_100013] from pop1:      0
        -> Only read nSites: 0 will therefore prepare next chromosome (or exit)

I have bootstrapped contigs, not sites, and the SAF files therefore contain repetitions of the sites from whole contigs. They are not sorted by position anymore. The following shows an excerpt from one of my SAF files. The contig begins with position 8 and ends with position 156. The end of one bootstrap replicate and the beginning of the next are shown:

Contig_100013   144     0.000000
Contig_100013   145     0.000000
Contig_100013   146     0.000000
Contig_100013   147     0.000000
Contig_100013   148     0.000000
Contig_100013   149     0.000000
Contig_100013   150     0.000000
Contig_100013   151     0.000000
Contig_100013   152     0.000000
Contig_100013   153     0.000000
Contig_100013   154     -1.338288
Contig_100013   155     0.000000
Contig_100013   156     0.000000
Contig_100013   8       0.000000
Contig_100013   9       0.000000
Contig_100013   10      0.000000
Contig_100013   11      0.000000
Contig_100013   12      0.000000
Contig_100013   13      0.000000
Contig_100013   14      0.000000
Contig_100013   15      0.000000
Contig_100013   16      0.000000
Contig_100013   17      0.000000
Contig_100013   18      0.000000
Contig_100013   19      0.000000
Contig_100013   20      -1.703610
Contig_100013   21      0.000000
Contig_100013   22      0.000000

Is the position sorting in SAF files really required for the multi SFS estimation? It did work very nicely with a single SAF file and I think finding overlapping sites between two SAF files should not require the SAF files to be position sorted.

many thanks for your help!

claudius

**Comment by ANGSD** [comment]
Hello Claudius, maybe im misunderstanding.

The bootstrapping in the realSFS works by angsd subsampling sites with replacement. The -sites argument will be used for limiting the sites to be used by the analysis.

Internally the saffiles requires that each contig/chr is grouped together as single entity. This is done to avoid doing cpu intensive compares when finding the intersect between populations. Then we can easily do bucket sort instead of keeping lists of sites with coverage.

Sorry for the delay.

**Comment by claudiuskerth** [comment]
Hi Thorfinn,

first, thank you for taking the time to think about this problem. This is more of a feature request than an issue with `ANGSD/realSFS`.

>The bootstrapping in the realSFS works by angsd subsampling sites with replacement. 

I think there is a problem with this kind of bootstrapping: it leads to overly narrow confidence intervals since it assumes that all sites in the data set are statistically independent, which they are generally not due to tight linkage with adjacent sites. This resampling over also tightly linked sites therefore underestimates uncertainty, but resampling over unlinked blocks of linked sites should provide better estimates of uncertainty. I think this would best be implemented via the `-sites` routine to `realSFS`, so that users can provide custom bootstrapped sites files (i. e. let users define the blocks of sites to resample, in my case these blocks happen to be the contigs of my de novo assembly). However, If presented with a sites file that contains multiple occurrences of the same site (as there should be in a bootstrap resample), `realSFS` only reads each site once (at least when called with `realSFS print`). The same is true for `angsd -dosaf`. All it therefore needs is that `realSFS` accepts multiple occurrences of the same site (in a sites file) for SFS estimation.

Since `realSFS` can't do the job at the moment, I tried a workaround by bootstrapping the SAF file creation with a bootstrapped _regions_ file. This has worked nicely with a single bootstrapped SAF file for 1D SFS estimation, but when trying to estimate a 2D SFS with two bootstrapped SAF files (created with the same bootstrapped regions file), I just get the error printed above from `realSFS`. In my bootstrapped SAF files, contigs (chr) _are_ grouped together, e. g. all positions from Contig_100013 are occurring contiguously in the SAF files but they are not sorted. Repeated positions (due to bootstrapping) are not contiguous in the SAF files because I had to bootstrap a regions file. That is, if Contig_100013 occurs 3 times in the bootstrap resample, its, say, 5 positions would occur like this in the SAF file:

Contig_100013 1
Contig_100013 2
Contig_100013 3
Contig_100013 4
Contig_100013 5
Contig_100013 1
Contig_100013 2
Contig_100013 3
Contig_100013 4
Contig_100013 5
Contig_100013 1
Contig_100013 2
Contig_100013 3
Contig_100013 4
Contig_100013 5

I believe for finding the overlapping sites between two saffiles you are applying the algorithm for finding the intersection between two sorted arrays as described [here](http://www.geeksforgeeks.org/union-and-intersection-of-two-sorted-arrays-2/). I had thought you first create a hash (Perl) / dictionary (Python) of overlapping sites and then look them up while reading the saffiles a second time. This would still require position sorting within each element of a bootstrap repetition as shown in the example above ([1, 2, 3, 4, 5]). Checking for this kind of sorting is probably not trivial. Maybe it would be enough to trust that `angsd` has checked that the sites file was position sorted. 

claudius

**Comment by rwaples** [comment]
Hey Claudius, 
I'm dealing with a related issue - I want to get confidence intervals on 2d SFS estimates generated by realSFS. 

But rather than using a bootstrap, I'm using a jackknife, leaving out one block (a contig in your case) at a time.  Then I use the "Delete-m Jackknife for unequal m" to generate the CIs.

Using a jackknife, rather than a bootstrap might solve the issue if it is related to some contigs appearing multiple times.

Ryan

**Comment by claudiuskerth** [comment]
Many thanks for that tip, Ryan! I'll have a close look into that. 

The reason why I did not consider the _standard_ jackknife so far is that I don't just want to estimate CI's on the 2D SFS but also refit demographic models or more generally use resampled 2D SFS's to carry uncertainty into downstream analyses. Since I have about 40,000 contigs, I thought that would be a computationally intractable task with standard jackknife resamples. However, for any less computationally demanding downstream analyses, like calculating Fst, I reckon already the standard jackknife would be an option. I haven't heard about of that version of jackknife that you mention yet.

many thanks for your help!

claudius

**Comment by claudiuskerth** [comment]
Hi,

this multi SFS problem with bootstrapped SAF files can be solved with the following hack:

1. create bootstrapped SAF files that only contain overlapping sites (make sure you have enough disk space!)
2. in `multisafreader.hpp` (or more recently in `realSFS_shared.cpp`) add `return 0;` at the beginning of the function `set_intersect_pos` to turn off determination of overlapping sites and instead read in all sites
3. recompile and use the new realSFS for optimisation of bootstrapped 2D SFS'

Hope this is useful to other users while we wait for a proper implementation of custom bootstrapping in angsd/realSFS.

claudius

**Comment by z0on** [comment]
very cool! thanks!
(would you post it to the Issues in angsd GitHub page for other users?..)

**Comment by claudiuskerth** [comment]
Hi Misha,

> would you post it to the Issues in angsd GitHub page for other users?

I thought I had just done this. What exactly do you mean?

claudius

**Comment by z0on** [comment]
Ha, I see -  you were responding to another other issue, not the one I opened on the same subject! apologies for confusion

**Comment by ANGSD** [comment]
Ok, I think @nspope solved this problem so im closing this issue, feel free to reopen if needed.

Best
