### ISSUE TITLE
Unable to open file - multireader

### ISSUE THREAD

**Issue by Xevkin** [ANGSD/angsd#87]
Hi, just installed latest version of anfsd (0.919) on a new server. Having an issue runnning it:

[E::hts_open_format] Failed to open file sample.bam

angsd: multiReader.cpp:333: multiReader::multiReader(int, char**): Assertion `in` failed

**Comment by ANGSD** [comment]
Hello, please make sure that the file exists at the specified path?

Best

**Comment by Xevkin** [comment]
Hi, yes I realized that one of the paths in my input list was incorrect. The error threw me a little and didn't think it was an input error. Sorry about that.
