### ISSUE TITLE
Adjust Makefile so that ANGSD compiles on systems with site-wide installed htslib

### ISSUE THREAD

**Issue by mmokrejs** [ANGSD/angsd#9]
Hi,
  I am trying to compile this package but find it very awkward that it contains hardcoded paths to ../htslib . I managed to work around by editing:

<pre>
    sed -e 's@FLAGS=-O3@FLAGS=@' 
        -e 's@HTSLIB = .*@HTSLIB = -lhts@' 
        -e 's@all: htshook angsd misc@all: angsd misc@' -i Makefile
    sed -e 's@HTSLIB = .*@HTSLIB = -lhts@' 
        -e 's@HTSDIR = .*@HTSDIR = /usr/include@' -i misc/Makefile
</pre>

but then I ran into

<pre>
g++ -O3 thetaStat.cpp  -I/usr/include/htslib/htslib  -lz -o thetaStat -lpthread -lhts
thetaStat.cpp:7:28: fatal error: ../htslib/bgzf.h: No such file or directory
 #include "../htslib/bgzf.h"
                            ^
compilation terminated.
Makefile:41: recipe for target 'thetaStat' failed
make[1]: *** [thetaStat] Error 1
make[1]: Leaving directory '/var/tmp/portage/sci-biology/ANGSD-9999/work/ANGSD-9999/misc'
</pre>

The thetaStat.cpp should include just "bgzf.h" and let Makefile to set proper '-I /path'.

I propose you use HTS_LIBDIR and HTS_INCDIR variables in your Makefiles, optionally HTS_SRC if you want to use the path to a local copy of htslib source tree. However, it should be enough for a user to provide $(HTS_LIBDIR) and $(HTS_INCDIR).

Finally, you should allow users to link against a shared library -lhts, instead of hardcoding htslib.a. So, probably a good reason to introduce $(HTS_LIBS) variable .

Just some ideas how to make the package more sysadmin friendly. ;-)

**Comment by ANGSD** [comment]
Sure thats a good idea. The htslib dependency in angsd is quite recent, which is the reason why the makefile isn't super tweaked yet. Im keeping the issue open until I get it solved.
Thanks

**Comment by apeltzer** [comment]
+1, this would be great as I have certain other packages relying on htslib and would like to keep them using one htslib instead of severals.

**Comment by ANGSD** [comment]
Should be fixed now. Users can now specify HTSSRC, otherwise it will assume a systemwide installation of htslib is installed. I'm closing this issue, feel free to reopen.

**Comment by apeltzer** [comment]
Thanks, works fine now!
