### ISSUE TITLE
Issue using "different fst estimator" for small sample sizes

### ISSUE THREAD

**Issue by pandolfa** [ANGSD/angsd#91]
I've been trying to follow the notes on http://www.popgen.dk/angsd/index.php/Fst, notably this:

NB; In the latest github version there is a different fst estimator which should be preferable for small sample sizes. Feel free to try that out with
./realSFS fst index [saf.idx's] -whichFst 1

In trying this out with two populations (n=3 diploids for each), I have the following problem: 
./angsd/misc/realSFS fst index pop1.saf.idx pop2.saf.idx -whichFst 1 -r Scaffold18235 -fstout fstout
	-> Version of fname:pop1.saf.idx is:2
	-> Assuming .saf.gz file: pop1.saf.gz
	-> Assuming .saf.pos.gz: pop1.saf.pos.gz
	-> Version of fname:pop2.saf.idx is:2
	-> Assuming .saf.gz file: pop2.saf.gz
	-> Assuming .saf.pos.gz: pop2.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:Scaffold18235 start:-1 stop:-1 fname:pop2.saf.idx fstout:fstout oldout:0 seed:1500055429 bootstrap:0 whichFst:1
	-> nSites: 100000
	-> You have supplied: 2 populations, that is 1 pairs
	-> You therefore need to supply 1 2dsfs priors instead of:0

Am I using the command line incorrectly?

**Comment by ANGSD** [comment]
hello, you need to precompute the 2dsfs priors.

http://www.popgen.dk/angsd/index.php/Fst#Two_Populations_real_data

**Comment by pandolfa** [comment]
I did do that using this: ./angsd/misc/realSFS pop1.saf.idx pop2.saf.idx >pop1.pop2.ml
I re-ran that (it seemed fine) and tried again but no luck. The following line in the output
-> You therefore need to supply 1 2dsfs priors instead of:0
made me think that I may have to specify this priors file in the command line?

**Comment by ANGSD** [comment]
Dear pandolfa sorry for not getting back to you. Im closing this issue feel free to reopen if needed.
