### ISSUE TITLE
Global SFS with -nSites

### ISSUE THREAD

**Issue by sagw** [ANGSD/angsd#99]
Hi @ANGSD 
My machine doesn't have enough memory to calculate the 2d unfolded global sfs across all sites, so I am using the -nSites option set to 1,000,000,000:

~/angsd/angsd/misc/realSFS -P 20 ~/WGS/saf/NJ_E_un.saf.idx ~/WGS/saf/NJ_U_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NJ_EU_unfull

in issue #69 you say "it should be ok just to do sum of the per entry values. But i would make sure that they look somewhat similar." My question is, what does somewhat similar mean? Looking at the first 6 columns of the output:
921788615.005772   15649120.311716   3328809.175070  0.000000 0.000000 0.000000 
654143285.739458  13663114.839733  0.000000              0.000000 0.000000 491934.041405 

Should I be worried that the values in columns 3 and 6 do not seem to be somewhat similar? If so, do you have any ideas what might be wrong?

Thanks so much,
Sarah

**Comment by ANGSD** [comment]
Hello sagw, the output is the expected values. So before you can compare you would need to normalize so each row in the output sums to one.

Best

**Comment by sagw** [comment]
Hi @ANGSD,
Oh ok, thank you. After normalizing, these values look like this:
9.138259458e-01 5.09971152e-03 2.1590368e-02 1.6826374e-08 3.8456115e-04 0.000000e+00 
8.942052167e-01  3.4370503e-02 8.300427e-13    5.9676733e-12  6.0303443e-13 3.3823574e-03
would you consider those numbers close enough? 
Am I then summing these normalized values in a given column to create the final SFS, or is the normalization just to compare them? 
Thanks for the help,
Sarah

**Comment by ANGSD** [comment]
Hi im closing this issue. Feel free to reopen if needed.
